### ISSUE TITLE
date picker is covered if card description too short

### ISSUE THREAD

**Issue by hacker-h** [nextcloud/deck#2944] opened 2021-04-06 15:52 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
When setting a due date, almost half of the date picker since the panel in which it is contained is too small.
This means to even be able to click the OK button you have to scroll within that small panel.
However: Since the same panel also contains the used space of the card's description it grows dynamically with the description height. A description of at least 6 lines reveals the entire date picker.

**To Reproduce**
1. Go to the URL of your deck service
2. Create a new card
3. Click on your newly created card to modify it
4. Click in the 'Set a due date' field
5. Note that the date picker is covered by almost half of its size
6. Give the card a description of 6 lines
7. Click in the 'Set a due date' field
8. Note that the date picker is no longer covered
9. Remove 3 description lines again
10. Click in the 'Set a due date' field
11. Note that the date picker is now partially covered again

**Expected behavior**
The date picker should be fully visible without any scrolling regardless of the card's description height.

**Screenshots**
3. Click on your newly created card to modify it
![image](https://user-images.githubusercontent.com/27709289/113736285-40069e80-96fd-11eb-8b74-41375e859671.png)

4. Click in the 'Set a due date' field; note that the date picker is covered by almost half of its size
![image](https://user-images.githubusercontent.com/27709289/113736381-56acf580-96fd-11eb-9c92-42cf904c08a3.png)

6. Give the card a description of 6 lines
![image](https://user-images.githubusercontent.com/27709289/113736903-cde28980-96fd-11eb-979b-fe82e41f6f80.png)

7. Click in the 'Set a due date' field again; note that the date picker is no longer covered
![image](https://user-images.githubusercontent.com/27709289/113736983-e2268680-96fd-11eb-9984-94bf42323f27.png)

9. Remove 3 of the description lines and check it again; note that the date picker is now partially covered again
![image](https://user-images.githubusercontent.com/27709289/113737320-37629800-96fe-11eb-9709-205cc3f624a7.png)

**Client details:**
 - OS: Ubuntu 20.04.2 LTS (Focal Fossa)
 - Browser: Mozilla Firefox
 - Version: 86.0 (64-bit)
 - Device: desktop

**Operating system:** Linux 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** pgsql PostgreSQL 13.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit

**PHP version:** 

7.4.16
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 21.0.0 - 21.0.0.18

**Updated from an older Nextcloud/ownCloud or fresh install:**  updated to new image

**Where did you install Nextcloud from:** docker

<details><summary>Signing status</summary>
No errors have been found.

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - calendar: 2.2.0
 - cloud_federation_api: 1.4.0
 - contactsinteraction: 1.2.0
 - cookbook: 0.8.4
 - dashboard: 7.1.0
 - dav: 1.17.1
 - deck: 1.3.1
 - drawio: 1.0.0
 - federatedfilesharing: 1.11.0
 - files: 1.16.0
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - maps: 0.1.8
 - nextcloud_announcements: 1.10.0
 - notes: 4.0.4
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - password_policy: 1.11.0
 - photos: 1.3.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - recommendations: 1.0.0
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - side_menu: 1.23.1
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - unsplash: 1.2.2
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather: 1.7.5
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - admin_audit
 - bruteforcesettings
 - comments
 - encryption
 - federation
 - files_external
 - firstrunwizard
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "/var/www/html/apps",
            "url": "/apps",
            "writable": false
        },
        {
            "path": "/var/www/html/custom_apps",
            "url": "/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "21.0.0.18",
    "overwrite.cli.url": "http://***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 2,
    "maintenance": false,
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Comment by stefan-niedermann** [comment] 2021-04-06 16:13
Duplicate of https://github.com/nextcloud/deck/issues/2830 - please use the :mag: search function before opening new issues.

**Closed by stefan-niedermann** 2021-04-06 16:13 UTC

**Comment by hacker-h** [comment] 2021-04-06 20:23
Sorry, I searched for it but apparently missed it.
