### ISSUE TITLE
deletion confirmation dialog is blocking lists (desktop)

### ISSUE THREAD

**Issue by bgmnt** [nextcloud/deck#3340] opened 2021-09-26 09:10 UTC
when i delete a card, i get a confirmation on the upper right. it stays there for ages and is blocking the lists on the right side of the screen (desktop, 1080p). i can not close it, only undo is possible.
- please shorten the time for showing this message (3 seconds e.g.)
- please add a closing button on the message (a simple x would be enough)

**Comment by stefan-niedermann** [comment] 2021-09-26 10:24
Duplicate of https://github.com/nextcloud/deck/issues/2809#issuecomment-891623836

Please follow https://github.com/nextcloud/nextcloud-dialogs/issues/352

**Closed by stefan-niedermann** 2021-09-26 10:24 UTC
