### ISSUE TITLE
Errors in log & in activity mail

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/deck#1795] opened 2020-05-04 08:11 UTC
**Describe the bug**
Logs and activity mails show errors
[deck.pdf](https://github.com/nextcloud/deck/files/4573458/deck.pdf)

**To Reproduce**
1. NC log

**Screenshots**

**Client details:**
 - OS: Debian 10
 - Browser : NA
 - Version : NC 18.0.4
- Deck : 0.8.2
 - Device: NA

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
[activity] Error: OCP\RichObjectStrings\InvalidObjectExeption: Parameter is undefined at <<closure>>

 0. /var/www/nc/apps/activity/lib/GroupHelper.php line 91
    OC\RichObjectStrings\Validator->validate("Vous avez créé  ... }", {user: {type: "u ... }})
 1. /var/www/nc/apps/activity/lib/Data.php line 258
    OCA\Activity\GroupHelper->addActivity({activity_id: "8 ... "})
 2. /var/www/nc/apps/activity/lib/Controller/APIv2.php line 273
    OCA\Activity\Data->get(OCA\Activity\GroupHelper {}, OCA\Activity\UserSettings {}, "f3nix", -1, 43, "asc", "deck", "", 0)
 3. /var/www/nc/apps/activity/lib/Controller/APIv2.php line 209
    OCA\Activity\Controller\APIv2->get("deck", -1, 50, false, "", 0, "asc")
 4. /var/www/nc/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Activity\Controller\APIv2->getFilter("deck", -1, 50, false, "", 0, "asc")
 5. /var/www/nc/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Activity\Controller\APIv2 {}, "getFilter")
 6. /var/www/nc/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Activity\Controller\APIv2 {}, "getFilter")
 7. /var/www/nc/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("APIv2Controller", "getFilter", OC\AppFramework\ ... {}, {filter: "deck", ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({filter: "deck", ... "})
 9. /var/www/nc/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {filter: "deck", ... "})
10. /var/www/nc/ocs/v1.php line 82
    OC\Route\Router->match("/ocsapp/apps/ac ... k")
11. /var/www/nc/ocs/v2.php line 24
    require_once("/var/www/nc/ocs/v1.php")

GET /ocs/v2.php/apps/activity/api/v2/activity/deck?format=json&limit=50&since=-1&sort=asc
from 188.154.171.120 by f3nix at 2020-05-04T07:56:15+00:00
```

#### Browser log
NA

</details>

**Comment by Nils160988** [comment] 2020-06-15 08:37
I can see the same problem on my instance with version 1.0.2
Duplicate of #1755?

**Comment by juliushaertl** [comment] 2020-06-15 08:44
Ah indeed, yes. Closing as a duplicate of #1755

**Closed** 2020-06-15 08:44 UTC
Labels: bug, feature: activity, need to reproduce
