### ISSUE TITLE
As a user, I want to visualize the content of 1 board into 1 Gantt chart

### ISSUE THREAD

**Issue by RodSeq** [nextcloud/deck#3401] opened 2021-11-02 13:36 UTC
When I visualize a Board with underlying Cards, I would like to press a button to switch the Board's view with Cards displayed into a Gantt Chart.

This would greatly help collaborative works between Nextcloud users  (ps: this feature is already supported in Monday.com cloud platform).

**Comment by stefan-niedermann** [comment] 2021-11-02 13:40
Quoting the maintainer:

> As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
> 
> If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

Closing as duplicate of #134

**Closed by stefan-niedermann** 2021-11-02 13:40 UTC
