### ISSUE TITLE
Share Cards to Talk

### ISSUE THREAD

**Issue by aktivde** [nextcloud/deck#2740] opened 2021-01-19 08:37 UTC
It somehow already works to just copy the link to a card and then paste it into a Chat in talk. But it's not very intuitive and possibly not the best way doing it. Why not having a button to share to talk? Or at least "Copy internal link" like in files?

**Comment by juliushaertl** [comment] 2021-01-19 08:39
Duplicate of #2630

**Closed by juliushaertl** 2021-01-19 08:39 UTC
