### ISSUE TITLE
Members right

### ISSUE THREAD

**Issue by kiki78** [nextcloud/deck#543] opened 2018-07-21 06:52 UTC
When I set shared members right to only read, so uncheck Share, Modify and Manage, this members can edit card.
Is it normal or bug ?

Regards,
Christian

**Comment by juliushaertl** [comment] 2018-07-21 07:22
@kiki78 Thanks for your report. I cannot reproduce this, in case it happens, it is of course a bug. Can you tell me some details, is all card data editable or only something specific? Can you check the browser console for errors while setting the permissions?

When testing this i found that it is possible to use the label/user assignment to change data in the UI but the permission check when saving this is correct.

**Comment by kiki78** [comment] 2018-07-21 07:45
Thank you Julius for your quick response.

So Follow the list of what I can do and not when connect as reader only member.
Can't Do
---------
Add new card
Change Members
Add file to card
Archive or Delete card
Change Date
Change Tags
Change Description
Reorganize cards

Can Do
-------
Add user

As you write, some of can't do appear to work in UI, but are not saved. Sorry for bad report :-(

So the only problem is possible modification of assigned users.

Best Regards,
Christian

**Comment by juliushaertl** [comment] 2018-07-21 09:18
Thanks for the detailed report. I'll have a look into it.

**Comment by juliushaertl** [comment] 2018-07-25 16:56
Fixed with #555

**Closed by juliushaertl** 2018-07-25 16:56 UTC
Labels: 1. to develop, bug, high
