### ISSUE TITLE
WebDAV unavailable after Deck update 1.2.1

### ISSUE THREAD

**Issue by Tachi107** [nextcloud/deck#2589] opened 2020-11-19 17:10 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
After updating the app, it is impossible to use any WebDAV app or service (Files app, Nextcloud Client, DAVx⁵...), nor the Deck app itself (screenshot below)

**To Reproduce**
1. Update Deck app
2. Go to Files app
3. (Optional) check logs

**Screenshots**
![image](https://user-images.githubusercontent.com/34214253/99693308-81b6e580-2a8b-11eb-9578-b8a7f0de91b3.png)

**Client details:**
 - OS: Debian Testing
 - Browser: Chromium 83.0.4103.116
 - Device: Desktop

<details>
<summary>Server details</summary>

**Operating system**: Debian 10

**Web server:** Nginx 1.18

**Database:** PostgreSQL

**PHP version:** php-fpm 7.3.19

**Nextcloud version:** 20.0.1

**Where did you install Nextcloud from:** Official tarball of NC 19, then upgraded to 20 when it came out

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.2
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.0.4
  - integration_github: 0.0.11
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.7.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.1.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.1
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - deck (had to disable it because of the errors)
  - encryption
  - files_external
  - social
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.paoloap.ml",
            "paoloap.ml"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.1.1",
        "overwrite.cli.url": "https:\/\/nextcloud.paoloap.ml",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "PLAIN",
        "music.lastfm_api_key": "32c889efd9cd660aab9f253d67ee97dc",
        "theme": "",
        "loglevel": 0,
        "default_language": "it",
        "default_locale": "it_IT",
        "updater.release.channel": "stable"
    }
}

```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"G872R4nHXrWay4PXIDUz","level":3,"time":"2020-11-19T16:52:23+00:00","remoteAddr":"146.241.159.234","user":"tachi","app":"PHP","method":"GET","url":"/apps/files","message":{"Exception":"Error","Message":"Undefined offset: 3 at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#548","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/OC_Helper.php","line":548,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"Undefined offset: 3","/var/www/nextcloud/lib/private/legacy/OC_Helper.php",548,{"path":"/","rootInfo":{"__class__":"OC\\Files\\FileInfo"},"includeExtStorage":false,"used":969918001,"quota":-3,"mount":{"__class__":"OC\\Files\\Mount\\MountPoint"},"storage":{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"sourceStorage":{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"free":10827509760,"total":11797427761,"relative":8.22,"ownerId":"tachi","ownerDisplayName":"Andrea Pappacoda","owner":{"__class__":"OC\\User\\User"}}]},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":139,"function":"getStorageInfo","class":"OC_Helper","type":"::","args":["/",{"__class__":"OC\\Files\\FileInfo"}]},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":187,"function":"getStorageInfo","class":"OCA\\Files\\Controller\\ViewController","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->","args":["","",null,false]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"index"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"index"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\ViewController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"files.view.index"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/files"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","version":"20.0.1.1","id":"5fb6a2c7ce6c0"}

{"reqId":"SBTxQ9NK10DmO4ZPbYNP","level":4,"time":"2020-11-19T16:52:28+00:00","remoteAddr":"146.241.159.234","user":"tachi","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/tachi/","message":{"Exception":"ArgumentCountError","Message":"Too few arguments to function OCA\\Deck\\DAV\\CalendarPlugin::__construct(), 0 passed in /var/www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php on line 293 and exactly 2 expected","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php","line":293,"function":"__construct","class":"OCA\\Deck\\DAV\\CalendarPlugin","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php","line":159,"function":"loadSabreCalendarPluginsFromInfoXml","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[["OCA\\Deck\\DAV\\CalendarPlugin"]]},{"file":"/var/www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php","line":103,"function":"populate","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":311,"function":"getAppPlugins","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"OCA\\DAV\\{closure}","class":"OCA\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":458,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["beforeMethod:PROPFIND",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":325,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/deck/lib/DAV/CalendarPlugin.php","Line":39,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Linux) mirall/3.0.1-3 (Nextcloud)","version":"20.0.1.1","id":"5fb6a2cc60aaf"}

{"reqId":"bSq9jf6ahEzwHsNJIrVm","level":3,"time":"2020-11-19T16:52:39+00:00","remoteAddr":"146.241.159.234","user":"tachi","app":"no app in context","method":"GET","url":"/ocs/v2.php/search/providers?from=%2Fapps%2Ffiles%2F","message":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve boardService! Class boardService does not exist","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["boardService"]},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":156,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["boardService",true]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":96,"function":"query","class":"OC\\ServerContainer","type":"->","args":["boardService"]},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"array_map","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***",{"name":"stackMapper","__class__":"ReflectionParameter"},{"name":"cardMapper","__class__":"ReflectionParameter"},{"name":"urlGenerator","__class__":"ReflectionParameter"}]]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":109,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Deck\\Search\\DeckProvider","__class__":"ReflectionClass"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Deck\\Search\\DeckProvider"]},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":156,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Deck\\Search\\DeckProvider",true]},{"file":"/var/www/nextcloud/lib/private/Search/SearchComposer.php","line":99,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Deck\\Search\\DeckProvider"]},{"file":"/var/www/nextcloud/lib/private/Search/SearchComposer.php","line":121,"function":"loadLazyProviders","class":"OC\\Search\\SearchComposer","type":"->","args":[]},{"file":"/var/www/nextcloud/core/Controller/UnifiedSearchController.php","line":75,"function":"getProviders","class":"OC\\Search\\SearchComposer","type":"->","args":["files.View.index",[]]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getProviders","class":"OC\\Core\\Controller\\UnifiedSearchController","type":"->","args":["/apps/files/"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\UnifiedSearchController"},"getProviders"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\UnifiedSearchController"},"getProviders"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\UnifiedSearchController","getProviders",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"ocs.core.UnifiedSearch.getProviders"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/search/providers"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","Line":115,"CustomMessage":"Could not load search provider dynamically: Could not resolve boardService! Class boardService does not exist"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","version":"20.0.1.1","id":"5fb6a2d825250"}

{"reqId":"kKZxmh5RPtrUMkqb0N81","level":4,"time":"2020-11-19T16:52:40+00:00","remoteAddr":"146.241.159.234","user":"tachi","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/tachi/","message":{"Exception":"ArgumentCountError","Message":"Too few arguments to function OCA\\Deck\\DAV\\CalendarPlugin::__construct(), 0 passed in /var/www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php on line 293 and exactly 2 expected","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php","line":293,"function":"__construct","class":"OCA\\Deck\\DAV\\CalendarPlugin","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php","line":159,"function":"loadSabreCalendarPluginsFromInfoXml","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[["OCA\\Deck\\DAV\\CalendarPlugin"]]},{"file":"/var/www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php","line":103,"function":"populate","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":311,"function":"getAppPlugins","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"OCA\\DAV\\{closure}","class":"OCA\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":458,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["beforeMethod:PROPFIND",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":325,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/deck/lib/DAV/CalendarPlugin.php","Line":39,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","version":"20.0.1.1","id":"5fb6a2d891617"}

{"reqId":"Pg4g47ezbOglu1eni4xi","level":2,"time":"2020-11-19T16:52:54+00:00","remoteAddr":"146.241.159.234","user":"tachi","app":"no app in context","method":"GET","url":"/apps/deck/","message":"Invalid data provided to provideInitialState by core","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","version":"20.0.1.1","id":"5fb6a2e70ef35"}
```

#### Browser log
```
https://del.dog/onecyveppi.txt
```

</details>

**Comment by juliushaertl** [comment] 2020-11-19 18:25
Hmm, I cannot reproduce that but the following ones seem suspicious:

    "Message": "Too few arguments to function OCA\\Deck\\DAV\\CalendarPlugin::__construct(), 0 passed in /var/www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php on line 293 and exactly 2 expected",
    "Message": "Could not resolve boardService! Class boardService does not exist",

**Comment by Tachi107** [comment] 2020-11-20 15:13
The errors do not persist after upgrading to Nextcloud 20.0.2 (one of the apps updated is in fact WebDAV), but it still could be an issue for people running an older version on the server.

**Comment by juliushaertl** [comment] 2021-04-13 17:21
I'll close this as I cannot reproduce it and it seems this did not happen to anyone else. If you still encounter it with the latest releases feel free to reopen again.

**Closed by juliushaertl** 2021-04-13 17:21 UTC
Labels: 1. to develop, bug

**Comment by Tachi107** [comment] 2021-04-13 17:26
Ok, Nextcloud 20.0.2 is really old and anybody using it should upgrade anyways
