### ISSUE TITLE
Comment field in app. Do you plan to add comment to the cards?

### ISSUE THREAD

**Issue by MercuryOZ** [nextcloud/deck#420] opened 2018-02-16 10:03 UTC
### Steps to reproduce
1. Open your deck
2. Create a task
3. Try to leave comments to the task

### Expected behavior
Comments are really useful in trello. It will be nice to use them here.
Do you plan to add comment field to the cards?

### Actual behavior
There are no comments field in DECK app

### Server configuration

**Operating system**:
windows 10  x64
**Nextcloud version:** (see Nextcloud admin page)
12.05

**Comment by juliushaertl** [comment] 2018-02-16 10:18
Duplicate of #10

**Closed by juliushaertl** 2018-02-16 10:18 UTC
