### ISSUE TITLE
RFE: add "create new board" button to top of board list

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/deck#1674] opened 2020-04-11 05:47 UTC
When a new user encounters a busy Deck for the first time, it is not obvious how they add a new board; when you click Deck from the NC app bar or get sent a link to a board you see a list of boards in the left column - and no way to create a new one.

As per v1 beta for lists and cards, add a "+" button at the top of the board list in the left column to add a new board. This would then be a consistent UX across Deck for adding new X. The existing "Create new board" button at the bottom could remain as a bigger hint for new installs of Deck.

**Comment by jakobroehrl** [comment] 2020-05-12 07:06
Hey @putt1ck 
What do you think about this: https://github.com/nextcloud/deck/pull/1865

**Comment by juliushaertl** [comment] 2020-06-18 10:44
Yep, let's tackle this in #1865 but close this issue as a duplicate of https://github.com/nextcloud/deck/issues/1655

https://github.com/nextcloud/deck/issues/2041 is also related to for a good first use experience.

**Closed by juliushaertl** 2020-06-18 10:44 UTC
Labels: design, enhancement
