### ISSUE TITLE
Deck Calendars not synced 

### ISSUE THREAD

**Issue by Gunnar-GO** [nextcloud/deck#3050] opened 2021-05-03 14:44 UTC
The deck integration works nice for ToDo and Calendar, but the additional behavoir seems incomplete.
It creates and shows in Webview the calendar to the coresponding deck. But synced through DAV it isn't there.

### Steps to reproduce
1. Create Deck
2. Look in Calendar App - works
3. Look in caldav-synced Client - not found

### Expected behaviour
Calendar should be synced.

### Actual behaviour
Calendar isn't there.

### Calendar app
**Calendar app version:** 2.2.1

**CalDAV-clients used:** (Windows 10 Calendar, some other tested without success)
** maybe test direct WebDAV later

**Comment by stefan-niedermann** [comment] 2021-05-03 14:47
Duplicate of #2399

**Closed by stefan-niedermann** 2021-05-03 14:47 UTC

**Comment by Gunnar-GO** [comment] 2021-05-03 15:17
Tested direct the DAV, via CarotDAV, the deck calendar is shown as app-generated--deck--board-2 (decks differs by number).

Maybe an incompability causes the missing sync.

**Comment by juliushaertl** [comment] 2021-05-04 14:36
I do not have any windows client to reproduce but so far others I've tested worked fine (DAVx5 on Android and Thunderbird)
