### ISSUE TITLE
Checklists in decks description do not save changes 

### ISSUE THREAD

**Issue by HL-Kramer** [nextcloud/deck#2071] opened 2020-06-25 15:17 UTC
*Description of the bug*
When using the markdown script do create a checklist in the description of a card it creates the checkboxes but doesn´t save them when marked as checked and neither counts the checked boxes correctly, only the number of overall checkboxes is updated correctly. When writing a checked box directly in the markdown script when opening the editing view of the card description, it works, but not at the viewer mode of the card description.

**To Reproduce**
1. go to decks
2. create a new card or click on an existing one
3. Open card details by clicking on the 3 dots on the card
4. Click on the pencil in the card description
5. Write at least one line with the following markdown script: - [ ] this is just a random item
6. The card gets an additiopnal description in their lower left corner (✓ 0/1)
7. Click the eye-symbol in the card description
8. the look of the card description gets updated
9. try checking the checkbox
10. the counter in the card itself does not switch to ✓ 1/1 -> the error
11. click on the pencil in the card description
12. change the markdown script to - [x] this is just a random item
13. Click the eye-symbol in the card description
14. the counter in the card istelf is updated

**Expected behavior**
The checkbox counter should update simply by checking the box in the description view of the card and not just in the editing mode by adjusting the markdwon script.

**Client details:**
 - OS: Windows 1o Pro
 - Browser Firefox
 - Version 77.0.1
 - Device: desktop

**Comment by juliushaertl** [comment] 2020-06-25 15:22
Thanks for reporting, this is a duplicate of #2061 

Please always check if there is already a ticket describing your issue. :wink:

**Closed by juliushaertl** 2020-06-25 15:22 UTC
