### ISSUE TITLE
Unsharing attachment from files deletes the file

### ISSUE THREAD

**Issue by fenglisch** [nextcloud/deck#2942] opened 2021-04-04 22:49 UTC
**Describe the bug**
If you share a Nextcloud file from one of your folders by attaching it to a card and then unshare it, the file gets deleted.

**To Reproduce**
1. Open card, go to "Attachments", click "Share from Files", choose any file
2. Click "Unshare file"
3. Look in the folder the file is (was) in and then in your deleted files

**Expected behavior**
The previously shared file is not attached to the card anymore, but it is not deleted from my folder.

**Client details:**
 - OS: Windows
 - Browser: Firefox
 - Version: 21.0.0
 - Deck version: 1.3.1
 - Device: Desktop

**Comment by stefan-niedermann** [comment] 2021-04-05 05:54
Duplicate of https://github.com/nextcloud/deck/issues/2877 - please use the 🔍 search function before opening new issues.

**Closed by stefan-niedermann** 2021-04-05 05:54 UTC
