### ISSUE TITLE
Comment indicator is not shown after reload

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/deck#2952] opened 2021-04-08 08:45 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
In #730 the wish for a clear indicator of the state of card comments is formulated. In [this comment of the issue](https://github.com/nextcloud/deck/issues/730#issuecomment-628451511) a screenshot clearly shows an icon in the lower-left corner of a card.

I have the problem that I saw these _once_ in the past when I was notified via mail/notifications (depending on app's settings). There was a small icon on all cards that were commented on. A bit back-and-forth did not change anything here.

When opening the deck app now, no indicator for any sort of comment is present. I do not know if this is due to the fact that the indicator should only show unread comments or all but it seems inconsistent in any case.

**To Reproduce**
Unfortunately, I was not 100% able to reproduce what happened. 

1. Share a board with a user B
2. Add a card by either yourself or user B
3. Set the app to notify you of comments
4. Ask user B to add a comment (currently without explicit @-mention)
5. See the icon at the location
6. Read the comments
7.  and move around in the app
8. Go away, come back later, update the app, ... idk exactly
9. Come back and look for the icon

**Expected behavior**
Depending on what the indicator should show, this is different.
If the indicator icon should show any existing comments, after step 8 the icon should still be present.
If the indicator icon should show **new** comments, after step 6 the icon should immediately disappear.

**Actual behavior**
During step 7 the icon is still present. After some time in step 9 the icon is gone.

**Screenshots**
I marked the missing icon in the screenshot manually here:
![grafik](https://user-images.githubusercontent.com/8202922/113992198-7f470380-9853-11eb-83da-8289d88d01a3.png)

**Client details:**
 - OS: Archlinux
 - Browser Firefox
 - Version 86.0
 - Device: Desktop/notebook

<details>
<summary>Server details</summary>

**Operating system:** Linux 5.11.2-arch1-1 #1 SMP PREEMPT Fri, 26 Feb 2021 18:26:41 +0000 x86_64

**Webserver:** Apache/2.4.46 (Unix) OpenSSL/1.1.1j mod_fcgid/2.3.9 (fpm-fcgi)

**Database:** mysql 10.5.9

**PHP version:** 

7.4.15
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, session, posix, readline, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 21.0.0 - 21.0.0.18

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** docker image

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - announcementcenter: 5.0.0
 - apporder: 0.12.0
 - audioplayer: 3.1.0
 - breezedark: 21.0.6
 - calendar: 2.2.0
 - camerarawpreviews: 0.7.10
 - checksum: 1.1.2
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 3.5.1
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.17.1
 - deck: 1.3.2
 - drawio: 1.0.0
 - event_update_notification: 1.2.0
 - external: 3.8.1
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_accesscontrol: 1.11.0
 - files_downloadactivity: 1.10.0
 - files_external: 1.12.0
 - files_markdown: 2.3.3
 - files_mindmap: 0.0.24
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_texteditor: 2.14.0
 - files_trackdownloads: 1.10.0
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - forms: 2.2.4
 - groupfolders: 9.0.0
 - groupquota: 0.1.5
 - guests: 1.6.2
 - impersonate: 1.8.0
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - nextcloud_announcements: 1.10.0
 - notes: 4.0.4
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - password_policy: 1.11.0
 - photos: 1.3.0
 - polls: 1.8.1
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - quota_warning: 1.10.0
 - recommendations: 1.0.0
 - richdocuments: 4.0.4
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - side_menu: 1.23.1
 - spreed: 11.1.1
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - tasks: 0.13.6
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - twofactor_nextcloud_notification: 3.1.2
 - twofactor_totp: 6.0.0
 - twofactor_u2f: 6.1.0
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - whiteboard: 0.0.3
 - workflowengine: 2.3.0
Disabled:
 - admin_audit
 - bruteforcesettings
 - circles
 - cospend
 - encryption
 - files_linkeditor
 - files_lock
 - mail
 - riotchat
 - sharelisting
 - social
 - sociallogin
 - twofactor_admin
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/srv\/data\/slt-cloud\/cloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/srv\/data\/slt-cloud\/cloud\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "password": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.tanzen-saar.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "21.0.0.18",
    "overwrite.cli.url": "https:\/\/cloud.tanzen-saar.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "app_install_overwrite": [
        "whiteboard",
        "issuetemplate"
    ],
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "force_language": "de",
    "force_locale": "de_DE",
    "loglevel": 2,
    "defaultapp": "apporder"
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
Nothing was logged in the nextcloud logs while reloading.

#### Browser log
```
10:29:00.022 Gewechselt zu https://cloud.tanzen-saar.de/index.php/apps/deck/#/board/2/card/83
10:29:00.552 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src").
10:29:00.552 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). common.js:2:319
10:29:00.552 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). content-fontface.js:50:25
10:29:02.745 JQMIGRATE: Migrate is installed, version 3.3.2 jquery-migrate.min.js:2:708
10:29:03.933 OCA.Comments.View initialized comments-app.js:31:21
10:29:04.153 Notifications permissions granted App.vue:306
10:29:04.340 OCA.Files.Sidebar initialized Sidebar.js:37:10
10:29:04.346 Uncaught TypeError: OCA.Files.DetailTabView is undefined
    <anonymous> https://cloud.tanzen-saar.de/index.php/js/activity/activity-sidebar.js?v=148b475b-0:603
    <anonymous> https://cloud.tanzen-saar.de/index.php/js/activity/activity-sidebar.js?v=148b475b-0:803
activity-sidebar.js:603:24
10:29:04.559 Uncaught TypeError: OCA.Files.DetailTabView is undefined
    <anonymous> versionstabview.js:18
    Webpack 3
versionstabview.js:18:7
10:29:07.919 OCA.Sharing.ShareSearch initialized ShareSearch.js:33:10
10:29:07.920 OCA.Sharing.ExternalLinkActions initialized ExternalLinkActions.js:33:10
10:29:08.047 OCA.Viewer initialized Viewer.js:49:10
10:29:08.054 No OCA.Files app found, viewer is now in standalone mode Viewer.vue:316
10:29:10.573 Please do NOT wait for the DOMContentLoaded before registering your viewer handler Viewer.vue:235
10:29:10.575 The following mime is already registered text/csv 
Object { id: Getter & Setter, group: Getter & Setter, mimes: Getter & Setter, component: Getter & Setter, … }
Viewer.vue:529
10:29:10.581 session heartbeat polling started session-heartbeat.js:97:9
10:29:10.587 Files_PDFViewer initialized for public page 
Object { isPublicPage: null, canDownload: true, isSecureViewerAvailable: false }
public.js:30:9
10:29:10.607 Please do NOT wait for the DOMContentLoaded before registering your viewer handler Viewer.vue:235
10:29:11.193 [DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }
ConsoleLogger.js:42:18
10:29:12.347 XHRGEThttps://cloud.tanzen-saar.de/ocs/v2.php/apps/user_status/api/v1/statuses/undefined
[HTTP/1.1 404 Not Found 224ms]

10:29:12.349 XHRGEThttps://cloud.tanzen-saar.de/ocs/v2.php/apps/user_status/api/v1/statuses/undefined
[HTTP/1.1 404 Not Found 257ms]

10:29:12.460 XHRGEThttps://cloud.tanzen-saar.de/ocs/v2.php/apps/user_status/api/v1/statuses/undefined
[HTTP/1.1 404 Not Found 261ms]

10:29:12.462 XHRGEThttps://cloud.tanzen-saar.de/ocs/v2.php/apps/user_status/api/v1/statuses/undefined
[HTTP/1.1 404 Not Found 312ms]

```

</details>

**Comment by juliushaertl** [comment] 2023-11-11 22:18
Closing as I cannot reproduce this anymore. Iirc we used to only show unread comments, but these days we always just show the number

**Closed by juliushaertl** 2023-11-11 22:18 UTC
Labels: frontend, 1. to develop, feature: comments
