### ISSUE TITLE
Faster / auto refresh of stacks

### ISSUE THREAD

**Issue by bsherwoodofdaptiv** [nextcloud/deck#750] opened 2018-11-29 00:15 UTC
**Is your feature request related to a problem? Please describe.**

When I use two different PC's (ie, my desktop and a conference room PC) changes I make on one (conference room) do not automatically show up on my open copy of the same board on my workstation.

**Describe the solution you'd like**

It would be swell if the app was polling for changes frequently in order to render and changes on screen / in the stacks.

**Describe alternatives you've considered**

Idea 1: Any time something is moved or edits (added / edited / deleted / archived) a 'dirty' value is set in the DB for that board. The web app has a timer that fires every X amount and just looks for the dirty bit. If it is there, it reloads the board.  X should be a configurable value with a minimum and maximum value limit.

Idea 2: 'dirty' value may need to be a 'timestamp' app know when it loaded the board. New timestamp means reload. Holding timestamp in memory in browser is not difficult. Would only have to be on currently render board. Same timer rules required.

**Additional context**

Scenario is not exclusive to me if board is shared and other person can't see updates without switching to another board and back, or reloading the page. Makes it a little tougher on/for collaboration.

**Comment by juliushaertl** [comment] 2018-12-04 12:15
Thanks for your report. This is a duplicate of https://github.com/nextcloud/deck/issues/256

**Closed by juliushaertl** 2018-12-04 12:15 UTC
