### ISSUE TITLE
Possibility of copying Deck boards

### ISSUE THREAD

**Issue by coriname** [nextcloud/deck#1251] opened 2019-09-16 07:27 UTC
Our team would like to have the possibility of copying boards (including stacks and cards). The idea is, to create a template board for recurring projects (with identical tasks) and share it with the team (read + share). Then everyone would have access to this template board and could copy it for working on new projects.

The easiest way is probably to provide an entry in the context menu of the board overview. Furthermore, it would be easiest, to not include any further properties (e.g. due dates, assignments, comments) when copying a board. 

We really appreciate the effort you spent so far. 

Best regards,
Corina

**Comment by juliushaertl** [comment] 2019-09-16 09:20
Duplicate of #119

**Closed by juliushaertl** 2019-09-16 09:20 UTC
