### ISSUE TITLE
Ability to change the location of the Deck default folder

### ISSUE THREAD

**Issue by louim-lbs** [nextcloud/deck#4839] opened 2023-06-22 10:00 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I would like to be able to change the location of the Deck default folder, to have a clearer folder list at root.

**Describe the solution you'd like**
Like in Talk, or Calendar apps.

**Comment by stefan-niedermann** [comment] 2023-06-22 10:26
Please use the 🔍 **search function** before opening new issues.

Closing as duplicate of https://github.com/nextcloud/deck/issues/3176

**Closed by stefan-niedermann** 2023-06-22 10:26 UTC

**Comment by louim-lbs** [comment] 2023-06-22 10:33
Sorry,
I checked but I didn't find. I wrongly checked, then 😅
