### ISSUE TITLE
Can't open card-details on read-only deck

### ISSUE THREAD

**Issue by firlevapz** [nextcloud/deck#2033] opened 2020-06-16 11:25 UTC
**Describe the bug**
If you want to open a card and see the details of a card of a deck, which is shared to you as read-only, then nothing happens and an error in the console shows up. 

**To Reproduce**
1. Go to a deck, where you just have read-only permissions (no edit, no sharing, no managing)
2. Click on any card on the deck
3. Nothing happens (actually the card-details should show up)
4. Error in console appears

**Expected behavior**
Details should be visible (assignee, due-date, description)

**Client details:**
 - OS: Ubuntu 20.04
 - Browser firefox, brave, chromium
 - Version recent versions
 - Device: desktop

<details>
<summary>Server details</summary>

Recent snap installation of nextcloud

</details>

<details>
<summary>Logs</summary>

#### Browser log
Firefox
```
TypeError: "e.scope is undefined"
    ia CardSidebar.vue:1
    bt VueJS
    ia CardSidebar.vue:1
    VueJS 7
        _render
        r
        get
        run
        pn
        rt
        Ke
main.js:62:9
    errorHandler main.js:62
    VueJS 9
        $e
        Ge
        _render
        r
        get
        run
        pn
        rt
        Ke
```

Chromium
```
main.js:62 TypeError: Cannot read property 'option' of undefined
    at CardSidebar.vue?4120:1
    at i.bt [as _l] (vue.esm.js:2639)
    at i.<anonymous> (CardSidebar.vue?4120:1)
    at i.e._render (vue.esm.js:3557)
    at i.r (vue.esm.js:4075)
    at mn.get (vue.esm.js:4488)
    at mn.run (vue.esm.js:4563)
    at pn (vue.esm.js:4319)
    at Array.<anonymous> (vue.esm.js:1989)
    at Ke (vue.esm.js:1915)


n.default.config.errorHandler | @ | main.js:35
-- | -- | --
  | $e | @ | vue.esm.js:8
  | Ge | @ | vue.esm.js:8
  | e._render | @ | vue.esm.js:8
  | r | @ | vue.esm.js:8
  | mn.get | @ | vue.esm.js:8
  | mn.run | @ | vue.esm.js:8
  | pn | @ | vue.esm.js:8
  | (anonymous) | @ | vue.esm.js:8
  | Ke | @ | vue.esm.js:8
  | Promise.then (async) |   |  
  | Ve | @ | vue.esm.js:8
  | rt | @ | vue.esm.js:8
  | (anonymous) | @ | vue.esm.js:8
  | mn.update | @ | vue.esm.js:8
  | pe.notify | @ | vue.esm.js:8
  | set | @ | vue.esm.js:8
  | (anonymous) | @ | deck.js?v=2983bf8c:1339
  | (anonymous) | @ | deck.js?v=2983bf8c:1339
  | Ie.updateRoute | @ | deck.js?v=2983bf8c:1339
  | (anonymous) | @ | deck.js?v=2983bf8c:1339
  | (anonymous) | @ | deck.js?v=2983bf8c:1339
  | r | @ | deck.js?v=2983bf8c:1339
  | r | @ | deck.js?v=2983bf8c:1339
  | ye | @ | deck.js?v=2983bf8c:1339
  | (anonymous) | @ | deck.js?v=2983bf8c:1339
  | r | @ | deck.js?v=2983bf8c:1339
  | (anonymous) | @ | deck.js?v=2983bf8c:1339
  | (anonymous) | @ | deck.js?v=2983bf8c:1339
  | (anonymous) | @ | deck.js?v=2983bf8c:1339
  | m | @ | deck.js?v=2983bf8c:1339

```

</details>

**Comment by juliushaertl** [comment] 2020-06-22 18:34
@jakobroehrl Maybe something small for you :wink:

**Comment by jakobroehrl** [comment] 2020-07-15 12:16
Can't reproduce it on the latest master, I can see the sidebar:
![grafik](https://user-images.githubusercontent.com/24530680/87543893-d2659e80-c6a5-11ea-8c4b-d63d77fcf8e0.png)

**Comment by juliushaertl** [comment] 2020-07-15 14:24
Closing as fixed then since the report doesn't mention a deck version number and we can't reproduce.

**Comment by drunkmen** [comment] 2020-07-18 22:14
I can reproduce this in Deck 1.0.5 if the card is assigned to a user.

**Comment by firlevapz** [comment] 2020-07-18 23:42
Yes, still exists on read-only boards when the card is assigned to a user in version 1.0.5 with following error message in the console:

![image](https://user-images.githubusercontent.com/12501952/87863886-091b0d80-c961-11ea-82f0-6c01eec6ebf7.png)

**Comment by Siruv** [comment] 2020-08-17 11:55
I have exactly the same problem as you.
As the screenshots show, did you find a solution to the problem?
Because it's embarrassing not to see the details of a card that another user has shared with you.

Thank you

Regards,
![Capture d’écran de 2020-08-17 13-47-32](https://user-images.githubusercontent.com/2051135/90393584-576f1980-e091-11ea-906f-3827fc253fe5.png)
![Capture d’écran de 2020-08-17 13-46-56](https://user-images.githubusercontent.com/2051135/90393589-58a04680-e091-11ea-8a5e-bb8c63eff205.png)

**Comment by juliushaertl** [comment] 2020-08-18 20:02
@jakobroehrl Could you reproduce this?

**Comment by jakobroehrl** [comment] 2020-08-19 05:41
Yes, on my setup it only occours if a user is assigned.

**Comment by Siruv** [comment] 2020-08-19 11:49
Hello,

Yes, it suffices for user A to assign a card from his table to user B for example so that user B cannot see the details of the card which has been assigned to him.

Thank you

Regards,

**Closed** 2020-08-21 07:18 UTC
Labels: bug, bug: regression, need to reproduce
