### ISSUE TITLE
Setting due date not possible - date selector cut off

### ISSUE THREAD

**Issue by rtfm98** [nextcloud/deck#4436] opened 2023-02-05 14:44 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
In the edit mode of a card it's not possible to use the due date selector as it is cut-off on the top. Scrolling isn't possible. 

**To Reproduce**
1. Create new card
2. Click on the card to enter edit mode
3. Try to select a due date

**Expected behavior**
The date selector should be displayed completely.

**Screenshots**

![deck_bug_1](https://user-images.githubusercontent.com/15339915/216825817-f41a4595-4d73-4497-a7d7-8095d4ad6d6e.png)
![deck_bug_2](https://user-images.githubusercontent.com/15339915/216825816-3fd89002-d3bb-4ace-8c08-ae7519257fa8.png)

**Client details:**
 - OS: macOS 12.6.3
 - Browser: Firefox 109.0.1 (64-bit)
 - Version: 25.0.3
 - Device: MacBook Pro

<details>
<summary>Server details</summary>

**Operating system**: Debian 11.6

**Web server:** Apache 2.4.54-1~deb11u1

**Database:** MariaDB 10.5.18-0+deb11u1

**PHP version:** PHP 8.1.15

**Nextcloud version:** 25.0.3

**Where did you install Nextcloud from:** nextcloud homepage

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.17.0
  - carnet: 0.24.6
  - checksum: 1.2.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.1.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - drawio: 2.1.0
  - external: 5.0.0
  - externalportal: 1.0.2
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.0.4
  - keeweb: 0.6.10
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - metadata: 0.17.0
  - news: 20.0.1
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - polls: 4.1.2
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - ransomware_protection: 1.14.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.0
  - richdocumentscode: 22.5.802
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - unsplash: 2.1.1
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings: 2.3.0
  - encryption
  - files_markdown: 2.3.6
  - nextcloud_announcements: 1.4.0
  - survey_client: 1.8.0
  - suspicious_login
  - twofactor_totp
  - user_ldap
  - user_status: 1.0.1
  - weather_status: 1.0.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.REMOVED SENSITIVE VALUE.de",
            "cloud.REMOVED.SENSITIVE VALUE.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.REMOVED SENSITIVE VALUE.de",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "htaccess.RewriteBase": "\/",
        "enable_previews": false,
        "app_install_overwrite": [
            "jitsi",
            "drawio"
        ],
        "data-fingerprint": "048162efc148aaaf413c541a6cb6bfc5",
        "has_rebuilt_cache": true
    }
}
```

**Are you using an external user-backend, if yes which one:** No

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
not necessary
```

#### Browser log
```
not necessary
```

</details>

**Comment by aquananu** [comment] 2023-02-06 12:46
same issue being faced since nextcloud updated to snap 25.0.2 and even now in 25.0.3

![image](https://user-images.githubusercontent.com/93096176/216975002-92ae8b2f-1386-4a06-9aab-37a639e7e106.png)

**Comment by reox** [comment] 2023-02-07 10:27
duplicate of #4195

**Closed** 2023-05-03 10:40 UTC
