### ISSUE TITLE
Sidebar toggle not working on screen widths < 1024px

### ISSUE THREAD

**Issue by thxlt** [nextcloud/deck#2444] opened 2020-10-13 21:55 UTC
**Describe the bug**
Navigation sidebar won't open, when clicking the hamburger menu button on screen widths < 1024px. Doing so only toggles an inline style `display:none;` on the sidebar `<div class="app-navigation">`. This works, when the sidebar is initially visible (screen width > 1024px) – but not, when it is initially invisible (screen width < 1024px). Seems like instead the class `app-navigation--close` sould be toggled on the sidebar. This class on the other hand is automatically added on screen widths < 1024px (which then makes the sidebar disappear initially). TL;DR: Inline style on sidebar seems obsolete – might better use the close-class to toggle.

**To Reproduce**
1. Open Deck app in browser
2. Resize screen below 1024px width –> sidebar slides out
3. Click hamburger menu button in top left corner –> sidebar is supposed to slide back in
4. Sidebar stays off-screen

**Expected behavior**
In any screen size, in any sidebar state: Clicking the hamburger menu button makes the sidebar slide out/in.

**Client details:**
 - OS: mac OS
 - Browser: Chrome
 - Version: 85
 - Device: MacBook Pro

<details>
<summary>Server details</summary>
**Nextcloud version:** 19.0.4
**Deck version:** 1.1.1
</details>

**Comment by juliushaertl** [comment] 2020-10-14 09:38
Duplicate of #2148, was fixed with #2440 and will be part of the next maintenance release

**Closed by juliushaertl** 2020-10-14 09:38 UTC
