### ISSUE TITLE
Drag 'n Drop to empty stack not working

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/deck#292] opened 2017-09-01 09:32 UTC
### Steps to reproduce
1.Create a new board
2.Add three stacks (e.g. Todo, In Progress, Completed)
3.Add an item to the ToDo stack
4. Drag 'n Drop the item from ToDo to In Progress

### Expected behaviour
There is a location where the item can be dropped, so it's transferred to the In Progress stack

### Actual behaviour
There should be a place where the item can be dropped onto the In Progress stack, but there isn't.

### Configuration
**Server**
Nextcloud
12.02

Deck
0.2.1

**Client**
Operating System
Ubuntu Desktop 17.04

Browser
Firefox 50.02 (64 bits)

**Comment by juliushaertl** [comment] 2017-09-01 13:22
Duplicate of #235

**Closed by juliushaertl** 2017-09-01 13:22 UTC
