### ISSUE TITLE
Menu of a card is opened inside the box of the card

### ISSUE THREAD

**Issue by NinaNC** [nextcloud/deck#318] opened 2017-10-04 09:51 UTC
When you open the menu in a card, it's opened inside the box of the card.

### Steps to reproduce
1. Create a card in a column
2. Click the menu (the 3 dots inside the card)
3. you need to scroll to see it

### Expected behaviour
The menu should overlap the box

### Actual behaviour
The menu is opened inside the card

<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="https://img11.hostingpics.net/pics/388898deckissue.png" border="0" alt="Hebergeur d'image" /></a>

**Comment by juliushaertl** [comment] 2017-10-04 10:55
Thanks for reporting. This is a duplicate of #311 I'll do a bugfix release at the end of the week.

**Closed** 2017-10-04 11:23 UTC

**Comment by NinaNC** [comment] 2017-10-04 11:48
Oh, sorry, I looked for a similar issue but missed #311 apparently
