### ISSUE TITLE
Ask confirmation before delete stack

### ISSUE THREAD

**Issue by Glosshead** [nextcloud/deck#327] opened 2017-10-12 13:30 UTC
Ask confirmation before delete stack.

Now it's enough just click on delete icon without any confirmation. It is not secured of accidental click.

**Comment by juliushaertl** [comment] 2017-10-13 12:21
This is on the list for 0.3.0 already. Closing as a duplicate of #259

**Closed by juliushaertl** 2017-10-13 12:21 UTC
