### ISSUE TITLE
Duplicate Board

### ISSUE THREAD

**Issue by blackdragon-steven** [nextcloud/deck#1201] opened 2019-08-28 00:11 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to be able to create board, setup all the stacks and tags and then use it as a template for future boards

**Describe the solution you'd like**
On the list of boards, in the ... menu, an option to duplicate the board please :)

**Comment by juliushaertl** [comment] 2019-08-28 11:10
duplicate of #119

**Closed by juliushaertl** 2019-08-28 11:10 UTC
