### ISSUE TITLE
To categorize the dashboards

### ISSUE THREAD

**Issue by Cencirhub5** [nextcloud/deck#6530] opened 2024-11-22 12:45 UTC
In order to categorize the boards, I would like to add the option to add categories that we can add boards into, such as the All boards option.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by juliusknorr** [comment] 2024-11-22 13:13
Duplicate of https://github.com/nextcloud/deck/issues/2006

**Closed by juliusknorr** 2024-11-22 13:13 UTC
