### ISSUE TITLE
"Finishing Cards"

### ISSUE THREAD

**Issue by Tricade** [nextcloud/deck#3270] opened 2021-08-24 16:55 UTC
Hello together,

is there no way to "finish" a card?  Like a Task? That would be a nice feature. So all the "25 Days over..." Messages will be gone.

Greetings,

tricade

**Comment by stefan-niedermann** [comment] 2021-08-24 17:04
Please use the 🔍 search function before opening new issues.

Closing as duplicate of #534

**Closed by stefan-niedermann** 2021-08-24 17:04 UTC
