### ISSUE TITLE
Don't open sidebar/popup editor when drag+drop is done

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/deck#3173] opened 2021-07-07 11:21 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
To be honest, I find it quite annoying that the editor pops up all the time when I move card to another stack or up/down within the same stack. Would it make sense to not open/popover when moving, but only when doing a normal/single click?

**Comment by timkrief** [comment] 2021-09-20 01:25
It seems like a duplicate of #2594

**Comment by juliushaertl** [comment] 2021-10-04 20:25
Yep, closing as a duplicate.

**Closed by juliushaertl** 2021-10-04 20:25 UTC
Labels: bug, frontend, 0. Needs triage, feature: modal
