### ISSUE TITLE
Calendar Integration

### ISSUE THREAD

**Issue by crites3** [nextcloud/deck#2256] opened 2020-09-03 19:49 UTC
Please, support calendar integration as well as begin and stop time!
Thanks

**Comment by stefan-niedermann** [comment] 2020-09-03 19:55
Duplicate of https://github.com/nextcloud/deck/issues/2004

See https://github.com/nextcloud/deck/pull/1545 for implementation.

**Closed by stefan-niedermann** 2020-09-03 19:55 UTC
