### ISSUE TITLE
Option in Board settings to select it as Default view when clickinig on Deck / starting Deck (instead of Upcoming card)s

### ISSUE THREAD

**Issue by Karamelmar** [nextcloud/deck#3004] opened 2021-04-19 09:17 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Not related do a problem or Bug, just an additional feature we would love to see.
When we start Deck, click on the Deck icon in Nextcloud, the upcoming cards view is opened by default.
There is no option to change the default view.

**Describe the solution you'd like**
We would like to be able, to select a "favorite" Board, which will be opened as Default View. A checkbox in the Board Details or in the Boards 3dots menu to set it as "Default" or Favorite" would be great.

**Describe alternatives you've considered**
An alternative would be to be able to set the Boardlist as default view.
Both options, a specific board as default view and/or the Boardlist as overview as default view would be great.

**Additional context**
Our use case is, that we have a Board to coordinate out work. This board is simply the most used one, so it would be nice, to skip the steps to select the right board every time we click on Deck.
We are aware that we can create a Bookmark of a specific board in the browser, but often we switch between nextcloud apps and therefore, this would be a nice addition to this great app. Thanks!

**Comment by stefan-niedermann** [comment] 2021-04-19 09:32
Duplicate of #2840 - please use the :mag: search function before opening new issues.

**Closed by stefan-niedermann** 2021-04-19 09:32 UTC
