### ISSUE TITLE
1.0.0 - UI Problems with Markdown Styling

### ISSUE THREAD

**Issue by fm-sys** [nextcloud/deck#1828] opened 2020-05-08 10:05 UTC
In older versions, links were blue and underlined. 
Now they are formatted just like normal text, so you do not see if there are links in the description of cards... This issue comes up when just pasting a link and when using Markdown Styling.

Also there is another problem related to Markdown Styling:
When using enumerations the numbers are outside of the text box
For illustration the following screenshot:
![2020-05-08 12_40_36-Präsentation1 - PowerPoint](https://user-images.githubusercontent.com/64581222/81398644-ecc15000-9129-11ea-8dc5-09f89b7d2b7e.png)

**Comment by joreiff** [comment] 2020-05-08 11:45
Probably a duplicate of #1808.

**Comment by juliushaertl** [comment] 2020-05-11 05:49
Let's track that in https://github.com/nextcloud/deck/issues/1808

**Closed by juliushaertl** 2020-05-11 05:49 UTC
