### ISSUE TITLE
Limit Number of allowed cards in a Stack

### ISSUE THREAD

**Issue by proserver1** [nextcloud/deck#6635] opened 2024-12-28 14:14 UTC
e.g "Next" must not contain more than 25 (open) cards

**Comment by stefan-niedermann** [comment] 2024-12-28 14:19
Please fill out the issue template next time, it is there for a reason.

Duplicate of https://github.com/nextcloud/deck/issues/2008

**Closed by stefan-niedermann** 2024-12-28 14:19 UTC
