### ISSUE TITLE
Duplicating a board copies its lists, but not the card

### ISSUE THREAD

**Issue by luka-nextcloud** [nextcloud/deck#3679] opened 2022-03-30 12:08 UTC
**Describe the bug**
Duplicating a board copies its lists, but not the card.

**To Reproduce**
No card is cloned when “Clone Board” is used.

**Expected behavior**
Cards should also be cloned when “Clone Board” is used.

**Comment by q-wertz** [comment] 2022-04-10 10:10
I thought this is what is wanted by copying the board. To just get the "frame" of the board. It would be nice if this behavior could also be somehow kept and duplicating the cards is an optional feature. (Cannot really think of a scenario where I want duplicated cards in different boards and then have the same task two times to do :sweat_smile: but apparently there is)

**Comment by juliushaertl** [comment] 2022-05-02 15:49
Closing as a duplicate of https://github.com/nextcloud/deck/issues/2797

**Closed by juliushaertl** 2022-05-02 15:50 UTC
Labels: bug, 3. to review
