### ISSUE TITLE
Unable to drag cards into empty stack

### ISSUE THREAD

**Issue by avkoch** [nextcloud/deck#294] opened 2017-09-07 07:52 UTC
### Steps to reproduce
1. Create new deck
2. Create two stacks
3. Add card to one stack
4. Drag card to empty stack

### Expected behaviour
Card should be placed into another stack

### Actual behaviour
Card stays in its stack. The dotted rectangle appears in the and doesn't appear in the empty stack. Only if I create in empty stack dummy card I can drag in cards from another stacks.

### General server configuration

**Operating system:** FreeBSD svc.ru 10.3-RELEASE-p20 FreeBSD 10.3-RELEASE-p20 #0: Wed Jul 12 03:13:07 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64

**Web server:** Apache/2.4.27 (FreeBSD) PHP/7.1.8 (apache2handler) with nginx 1.12.1 as a reverse-proxy

**Database:** mysql 5.7.19

**PHP version:** 7.1.8
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - pcre
 - Reflection
 - SPL
 - hash
 - session
 - apache2handler
 - standard
 - apcu
 - bz2
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - filter
 - ftp
 - gd
 - mysqlnd
 - iconv
 - json
 - ldap
 - exif
 - mcrypt
 - mysqli
 - openssl
 - PDO
 - posix
 - SimpleXML
 - smbclient
 - tokenizer
 - xml
 - xmlwriter
 - zip
 - zlib
 - pdo_mysql
 - wddx
 - xmlreader
 - xsl
 - libsmbclient
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 12.0

**Where did you install Nextcloud from:**  FreeBSD ports

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)
no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_notifications: 1.0.0
 - audioplayer: 2.1.0
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.2.1
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_external: 1.3.0
 - files_opds: 0.8.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - encryption
 - user_external
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocwhbjvo676b",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "svc.ru",
    ],
    "datadirectory": "\/usr\/local\/www\/nextcloud\/data",
    "overwrite.cli.url": "http:\/\/svc.ru\/nextcloud",
    "dbtype": "mysql",
    "version": "12.0.2.0",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Moscow",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "loglevel": 2,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "theme": ""
}
```
</details>

<details>
        <summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko

**Operating system:** Windows 8.1

### Logs

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
{"reqId":"3IqvdxRTwrW6u82vLAjH","level":3,"time":"2017-09-07T07:49:22+03:00","remoteAddr":"127.0.0.1","user":"14D518F0-7422-4D1E-807B-762F988B0F62","app":"index","method":"POST","url":"\/nextcloud\/index.php\/apps\/deck\/cards","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\NotNullConstraintViolationException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_deck_cards`(`stack_id`,`type`,`order`,`owner`,`created_at`,`last_modified`) VALUES(?,?,?,?,?,?)' with params [20, \\\"plain\\\", 999, \\\"14D518F0-7422-4D1E-807B-762F988B0F62\\\", 1504759762, 1504759762]:\\n\\nSQLSTATE[HY000]: General error: 1364 Field 'title' doesn't have a default value\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(247): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/deck\\\/lib\\\/Db\\\/DeckMapper.php(40): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('INSERT INTO `*P...', Array, NULL, NULL)\\n#4 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(125): OCA\\\\Deck\\\\Db\\\\DeckMapper->execute('INSERT INTO `*P...', Array)\\n#5 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/deck\\\/lib\\\/Db\\\/CardMapper.php(45): OCP\\\\AppFramework\\\\Db\\\\Mapper->insert(Object(OCA\\\\Deck\\\\Db\\\\Card))\\n#6 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/deck\\\/lib\\\/Service\\\/CardService.php(64): OCA\\\\Deck\\\\Db\\\\CardMapper->insert(Object(OCA\\\\Deck\\\\Db\\\\Card))\\n#7 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/deck\\\/lib\\\/Controller\\\/CardController.php(80): OCA\\\\Deck\\\\Service\\\\CardService->create(NULL, 20, 'plain', 999, '14D518F0-7422-4...')\\n#8 [internal function]: OCA\\\\Deck\\\\Controller\\\\CardController->create(NULL, 20, 'plain', 999)\\n#9 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#10 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Deck\\\\Controller\\\\CardController), 'create')\\n#11 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Deck\\\\Controller\\\\CardController), 'create')\\n#12 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Deck\\\\\\\\Contro...', 'create', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#13 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#14 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#15 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/deck\\\/card...')\\n#16 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":113}","userAgent":"Mozilla\/5.0 (Windows NT 6.3; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.2.0"}
```
</details>

**Comment by juliushaertl** [comment] 2017-09-07 11:05
Duplicate of #235

I've just release 0.2.2 which includes the fix for this issue.

**Closed by juliushaertl** 2017-09-07 11:05 UTC
