### ISSUE TITLE
Folders in board list

### ISSUE THREAD

**Issue by togethereveryday** [nextcloud/deck#2819] opened 2021-02-21 11:13 UTC
### The Problem
Having many boards naming and color alone are not enough to provide a user friendly sorting and optical navigation.  Especially if the user uses many boards referring to the same project. They sit there in the very same list with boards referring to other projects. 

### The Solution
Folders for the board list. 
A simple version would be just that. Besides the option to create an new board the user has the option to create a new folder and ideally drag and drop boards inside the folder. The folder can be collapsed if needed. 

### Thinking further
A handy enhancement would be a folder view. Instead of opening a board, when selecting a folder in the board list view the user is presented with all the boards inside the folder similar to an open board view but with firm cards representing the boards inside the selected folder.

**Comment by stefan-niedermann** [comment] 2021-02-21 11:29
Duplicate of #2006 - Please use the :mag: search function before opening new issues.

**Closed by stefan-niedermann** 2021-02-21 11:29 UTC

**Comment by togethereveryday** [comment] 2021-02-21 11:34
> Duplicate of #2006 - Please use the 🔍 search function before opening new issues.

Sorry.
