### ISSUE TITLE
Drag and Drop between Boards

### ISSUE THREAD

**Issue by Emporea** [nextcloud/deck#3478] opened 2021-12-08 18:15 UTC
It would be really usefull if one could drag and drop cards between boards.
This might be possible with a little popup over the mouse where you see different cards in a list or something like that. 

Also it would be nice if its possible to "multi-select" cards to take a certain action like moving, deleting etc...

This should also come with a general possibility to move lists. Because if there is a need to recreate a list inside another boards you lose "archived" data, cause it was not possible to move them.

Of course if its a one time action it's possbile via a database script, but not on a workflow basis.

**Comment by juliushaertl** [comment] 2021-12-16 09:40
Closing as a duplicate of https://github.com/nextcloud/deck/issues/2209

**Closed by juliushaertl** 2021-12-16 09:40 UTC
Labels: enhancement, frontend
