### ISSUE TITLE
The Comment icon doesn't appear after comment the task

### ISSUE THREAD

**Issue by vix95** [nextcloud/deck#1933] opened 2020-05-19 21:50 UTC
The comment icon doesn't appear after comment the task. For instance the attachment icon appears after attach the file. After reload the page, the icon is showing correctly.

Step by step how to simulate it:
1. Create/Open the task
2. Move into Comment section
3. Write some comment and send it (please take a look on below screenshot)
![image](https://user-images.githubusercontent.com/38139321/82381393-6c082b00-9a2a-11ea-9779-8c194da61f5c.png)
4. Reload the page, the icon is showing correctly.
![image](https://user-images.githubusercontent.com/38139321/82381539-ab367c00-9a2a-11ea-99d8-dde27da7c5fb.png)

I think the discussion icon should appear immediately after the comment appears.
I can change the language if something isn't clear. If more details is necessery, please let me know.

**Tested on**
Nextcloud 18.0.4
Opera 68.0.3618.104
OS Windows 10 64-bit

**Comment by juliushaertl** [comment] 2020-05-20 08:31
The question is more why it shows up after reload, as currently the icon should only show up if there are unread comments. But your own comment should already been marked as read since you are the author.

**Comment by jakobroehrl** [comment] 2020-05-20 09:32
Similar to: https://github.com/nextcloud/deck/issues/1886

**Comment by juliushaertl** [comment] 2020-05-25 06:50
Closing as a duplicate of https://github.com/nextcloud/deck/issues/730

**Closed by juliushaertl** 2020-05-25 06:50 UTC
Labels: 0. Needs triage, bug
