### ISSUE TITLE
Marking as done in Dashboard of Upcoming Tasks Where it is not working for Deck Tasks

### ISSUE THREAD

**Issue by Gowtham-eng** [nextcloud/deck#3990] opened 2022-08-20 06:41 UTC
Hi,

I would like to mark my upcoming tasks as done where my tasks are created in Deck Boards.

Solution Needed:
1) I need my Deck cards should be edited in Tasks App where i can mark as complete.
2) After marking my Task as completed it should also reflect in my Deck Cards where there should be some workflows to complete.
3) Once i am moving my Deck Card to completed stage or by giving finished label the due date should delete automatically or should not show in dashboard of due dates.

**Comment by stefan-niedermann** [comment] 2022-08-20 07:28
Duplicate of #534 (`Done` state in Deck in general) and #2399 (Write access over `CalDAV`).

**Closed by stefan-niedermann** 2022-08-20 07:28 UTC
