### ISSUE TITLE
Add Custom Fields to Cards

### ISSUE THREAD

**Issue by GuyInCorner** [nextcloud/deck#3472] opened 2021-12-05 02:44 UTC
I would like the ability to add custom fields in a card.  Kind of like you you can add a custom field to a contact.  This should probably be at the board level.

I tried the custom properties app but that didn't add anything to the deck.  I see no way to add custom fields.

Example fields I would add to some of my boards if I could:

- value of my card
- time I spent on my card
- a version of SW that my card relates to
-

**Comment by stefan-niedermann** [comment] 2021-12-05 07:40
Duplicate of https://github.com/nextcloud/deck/issues/1833

Maybe you want to start a Pull Request 😉🚀?

**Closed by stefan-niedermann** 2021-12-05 07:40 UTC

**Comment by GuyInCorner** [comment] 2021-12-05 15:07
I don't have the knowledge to contribute to this or I would.  Sorry for the duplicate.  Didn't find the other issue.  Will anxiously follow it.

**Comment by KaiBuskirk** [comment] 2022-06-28 20:27
ADVANCED CUSTOM FIELDS / CARDS
i cant work this out if anyone feels this would or could be GREAT!
being able to add to the card basics would be exceptional...
is there a group or person dedicated to this?
tia,
kai
