### ISSUE TITLE
When selecting date in "bigger view" the "OK" button is covered / not visible

### ISSUE THREAD

**Issue by langfingaz** [nextcloud/deck#3218] opened 2021-07-30 12:53 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Thanks for the new "bigger view" for cards. When a card is opened in that view, the selection of a "due date" does not work as expected as the date and time selections are either covered upwards or downwards. Sometimes one cannot press the "OK" button to select a chosen due date.

**To Reproduce**
1. Open Deck in Firefox on a FullHD screen and set (Firefox) scaling to 110%.
2. Open a card in the "bigger view"
3. Click on "set due date"
4. The date and time selections are partially covered by the frame below "Details - Attachments - Comments - Timeline" in such a way that one cannot press the "OK" button. Pressing enter to confirm the selected date doesn't work neither.

**Expected behavior**
The date selection should be one layer above "Details - Attachments - Comments - Timeline" and not covered behind it. One should be able to accept the selected date, e.g. by pressing the "OK" button.

**Video**
I did a short recording of the center of my screen to demonstrate. In that video I first try to select a date and then zoom out/in in 10% steps: [https://cloud.privacy1st.de/s/ncaxywe7cGo46fz](https://cloud.privacy1st.de/s/ncaxywe7cGo46fz)

**Screenshots**

At 110% scaling:
![https://cloud.privacy1st.de/s/S695ANYWTqjFQbP](https://cloud.privacy1st.de/s/S695ANYWTqjFQbP/download)

At 100% scaling:
![https://cloud.privacy1st.de/s/R3jDnT5QnGm6C2Y](https://cloud.privacy1st.de/s/R3jDnT5QnGm6C2Y/download)

**Client details:**
 - OS: ArchLinux
 - Browser: Firefox 90.0.2
 - Device: desktop, 1080p screen

<details>
<summary>Server details</summary>

**Nextcloud version:** 21.0.3
**Deck version:** 1.4.3

</details>

**Comment by stefan-niedermann** [comment] 2021-07-30 13:17
Not sure whether this is a duplicate of #2704 - but at least it is related to it.

**Comment by ananyak19** [comment] 2022-11-27 10:46
Hey is this available? I would like to work on this

**Closed** 2023-05-03 10:40 UTC
Labels: frontend
