### ISSUE TITLE
Self-defined path and name of the directory

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/deck#3931] opened 2022-07-22 08:11 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
If I use many apps on one instance then my main directory in the files is full of folders that are used for the respective apps. With most apps you can define where this folder is located (e.g. in a subdirectory) or what this folder is called.

**Describe the solution you'd like**
That the function will be added to set itself the location and name of the directory of the app.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by stefan-niedermann** [comment] 2022-07-22 08:49
Duplicate of https://github.com/nextcloud/deck/issues/3176

**Closed by stefan-niedermann** 2022-07-22 08:49 UTC
