### ISSUE TITLE
Leaving Shared Boards

### ISSUE THREAD

**Issue by TheACF** [nextcloud/deck#3648] opened 2022-03-17 08:24 UTC
As it is in Filesharing, i want to request it it is (or would be) possible to leave the sharing of a board in deck. this would be really great! thx for your work, great product at all!!!

**Comment by stefan-niedermann** [comment] 2022-03-17 09:07
Please use the 🔍 search function before opening new issues!

Closing as duplicate of https://github.com/nextcloud/deck/issues/955

**Closed by stefan-niedermann** 2022-03-17 09:07 UTC
