### ISSUE TITLE
Startseite

### ISSUE THREAD

**Issue by przybilski** [nextcloud/deck#3652] opened 2022-03-18 10:59 UTC
Hallo,

ist es möglich, dass wenn die App "Deck" in der Nextcloud geöffnet eine Startseite zu hinterlegen?
Also wenn man die App öffnet soll man auf ein vorher definiertes Board kommen. Die Übersicht "Anstehende Karten" soll ausgeblendeet werden. Unsere Nextcloud INstanz wird über IONOS gehostet.

Vielen Dank!

**Comment by stefan-niedermann** [comment] 2022-03-18 11:32
Workaround mit der App `apporder`: https://help.nextcloud.com/t/change-default-application/19083/2?u=stefan-niedermann

**Comment by przybilski** [comment] 2022-03-18 12:49
Hi there,

is it possible to store a start page when the app "deck" is opened in the nextcloud?
Even if you open the app you should come to a previously defined board. The "Upcoming Cards" overview should be hidden. Our Nextcloud instance is hosted via IONOS.

Thanks very much!

**Comment by dodedodo** [comment] 2022-03-18 12:58
Sounds like a duplicate of #2840

**Comment by stefan-niedermann** [comment] 2022-03-18 14:04
It is, I just didn't find it, thanks 🙂 

@przybilski see the workaround [i posted above](https://github.com/nextcloud/deck/issues/3652#issuecomment-1072325315) if you need a solution right now.

Disabling the upcoming cards view is very likely not on the roadmap (@juliushaertl can verify that i guess), so you will have to use some tool like the [`CustomCSS`](https://apps.nextcloud.com/apps/theming_customcss) app if you need to hide it (assuming you *want* to hide it and not only use some board as default board).

**Closed by stefan-niedermann** 2022-03-18 14:04 UTC
