### ISSUE TITLE
Checboxes in decription now require to be bulleted to be functional

### ISSUE THREAD

**Issue by HollowedEmpire** [nextcloud/deck#1967] opened 2020-05-28 15:55 UTC
### Steps to reproduce

1\. Edit the description field of any card

2\. Use markdown syntax to add a checkbox without a bullet point.

3\. Checkbox will be nonfunctional until you add a bullet to it

### Expected behaviour

Previously I could add a checkbox in the description without bullets and they would operate as expected. This seem to change after a recent update, though unsure which update.

### Actual behaviour

All my checkboxes have become non-functional in all my cards, and will only work again by preceding them with a bullet point

## Server configuration detail

**Operating system:** Linux 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l

**Webserver:** Apache/2.4.38 (Raspbian) (fpm-fcgi)

**Database:** mysql 10.3.22

**PHP version:** 

7\.3.14-1\~deb10u1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo*mysql, pdo*pgsql, pdo_sqlite, pgsql, apc, posix, pspell, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, wikidiff2, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 18.0.4 - 18.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** downloaded from website

<details><summary>Signing status</summary>

Array

(

)

</details>

<details><summary>List of activated apps</summary>

\`\`\`

Enabled:

 - accessibility: 1.4.0

 - apporder: 0.10.0

 - bookmarks: 3.0.13

 - bruteforcesettings: 1.6.0

 - calendar: 2.0.3

 - camerarawpreviews: 0.7.3

 - checksum: 0.4.4

 - cloud*federation*api: 1.1.0

 - comments: 1.8.0

 - contacts: 3.3.0

 - cookbook: 0.6.5

 - dav: 1.14.0

 - deck: 1.0.1

 - drawio: 0.9.5

 - external: 3.5.0

 - federatedfilesharing: 1.8.0

 - federation: 1.8.0

 - files: 1.13.1

 - files_automatedtagging: 1.8.3

 - files_fulltextsearch: 1.4.2

 - files_lock: 0.8.1

 - files_pdfviewer: 1.7.0

 - files_rightclick: 0.15.2

 - files_sharing: 1.10.1

 - files_trashbin: 1.8.0

 - files_versions: 1.11.0

 - files_videoplayer: 1.7.0

 - firstrunwizard: 2.7.0

 - fulltextsearch: 1.4.1

 - issuetemplate: 0.6.0

 - logreader: 2.3.0

 - lookup*server*connector: 1.6.0

 - mail: 1.3.5

 - maps: 0.1.6

 - metadata: 0.11.1

 - news: 14.1.11

 - nextbackup: 20.4.0

 - nextcloud_announcements: 1.7.0

 - notifications: 2.6.0

 - oauth2: 1.6.0

 - password_policy: 1.8.0

 - passwords: 2020.5.0

 - privacy: 1.2.0

 - provisioning_api: 1.8.0

 - ransomware_protection: 1.6.1

 - recommendations: 0.6.0

 - serverinfo: 1.8.0

 - settings: 1.0.0

 - sharebymail: 1.8.0

 - spreed: 8.0.9

 - support: 1.1.0

 - survey_client: 1.6.0

 - systemtags: 1.8.0

 - tasks: 0.13.1

 - text: 2.0.0

 - theming: 1.9.0

 - timetracker: 0.0.42

 - twofactor_backupcodes: 1.7.0

 - twofactor_totp: 4.1.3

 - twofactor_u2f: 5.1.0

 - unsplash: 1.1.5

 - updatenotification: 1.8.0

 - viewer: 1.2.0

 - workflowengine: 2.0.0

Disabled:

 - activity

 - admin_audit

 - encryption

 - end*to*end_encryption

 - files_external

 - heartigantheme

 - notes

 - photos

 - pride

 - social

 - user_ldap

\`\`\`

</details>

<details><summary>Configuration (config/config.php)</summary>

\`\`\`

{

    "instanceid": "\***REMOVED SENSITIVE VALUE**\*",
    
    "passwordsalt": "\***REMOVED SENSITIVE VALUE**\*",
    
    "secret": "\***REMOVED SENSITIVE VALUE**\*",
    
    "trusted_domains": [
    
        "paracosm.ddns.net"
    
    ],
    
    "datadirectory": "\***REMOVED SENSITIVE VALUE**\*",
    
    "dbtype": "mysql",
    
    "version": "18.0.4.2",
    
    "overwrite.cli.url": "https:\\/\\/paracosm.ddns.net\\/nextcloud",
    
    "overwriteprotocol": "https",
    
    "dbname": "\***REMOVED SENSITIVE VALUE**\*",
    
    "dbhost": "\***REMOVED SENSITIVE VALUE**\*",
    
    "dbport": "",
    
    "dbtableprefix": "oc_",
    
    "mysql.utf8mb4": true,
    
    "dbuser": "\***REMOVED SENSITIVE VALUE**\*",
    
    "dbpassword": "\***REMOVED SENSITIVE VALUE**\*",
    
    "installed": true,
    
    "maintenance": false,
    
    "twofactor_enforced": "false",
    
    "twofactor*enforced*groups": [
    
        "admin"
    
    ],
    
    "twofactor*enforced*excluded_groups": [],
    
    "mail_smtpmode": "smtp",
    
    "mail_smtpsecure": "ssl",
    
    "mail_sendmailmode": "smtp",
    
    "memcache.local": "\\\\OC\\\\Memcache\\\\APCu",
    
    "theme": "",
    
    "loglevel": 2,
    
    "updater.release.channel": "stable"

}

\`\`\`

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:**  no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0

**Operating system:** Windows 10 and Ubuntu 19

**Comment by stefan-niedermann** [comment] 2020-05-28 17:40
@juliushaertl maybe a regex based search & replace solution might be an option to migrate the old syntax to the new one in an future update?

**Comment by juliushaertl** [comment] 2020-05-29 14:17
Yes, unfortunately the old version was a bit odd in that regards, with using easymde and hopefully soon tiptap as the text app is using it, we are sticking to [CommonMark with the GFM task list item extensio](https://github.github.com/gfm/#task-list-items-extension-).

And indeed a automatic replace would be nice, maybe someone is up for contributing.

**Comment by HollowedEmpire** [comment] 2020-05-29 22:31
Ah, thanks for the information on that. I'll start shifting over to the CommonMark style then for the future and current cards.

**Comment by Nyco** [comment] 2020-06-05 14:05
We have lots of checklists in many boards, and all of them render very badly in the 1.0.x versions.

This makes the upgrade to 1.0.x unbearable: we lose all our checklists, or we have to rewrite them all, board by board, card by card, which would take hours, with all the manual mistakes to fix later.

**Comment by juliushaertl** [comment] 2020-06-14 20:27
Let's actually close this as duplicate of https://github.com/nextcloud/deck/issues/1905 since that was created earlier.

**Closed by juliushaertl** 2020-06-14 20:27 UTC
Labels: 1. to develop, enhancement, good first issue
