### ISSUE TITLE
Long links in cards description are broken by line breaks

### ISSUE THREAD

**Issue by wwwindisch** [nextcloud/deck#127] opened 2017-05-09 13:27 UTC
**Expected behaviour**
Links in the card description are automatically converted to hyperlinks an become clickable.

**Actual behaviour**
A line break is created automatically, if a link is too long for one line. 
Problem: Only the first line is converted to a hyperlink (which then points to an incomplete URL).

**Screenshot**
![grafik](https://cloud.githubusercontent.com/assets/28566230/25853118/e6ac9d2c-34cb-11e7-8e16-5d4a14246655.png)

**Comment by juliushaertl** [comment] 2017-05-09 15:59
@wwwindisch Right, that should not happen.

For fixing, this might be an issue with markdown-it adding breaks and markdown-it-linkify.

**Comment by x9t9** [comment] 2017-05-09 23:53
Can confirm this issue but not as title suggest . 
The problem is not long links, the problem is links that has the parenthesis character `)` .

![2017-05-10_072819](https://cloud.githubusercontent.com/assets/23067248/25876907/bf14c8a2-3552-11e7-92c0-2069257eba72.jpg)

As such - This issue should be labeled as `Upstream` and handled at the [source](https://github.com/markdown-it/markdown-it/issues/) of said library / script  . 
I already allowed myself to open an issue [there](https://github.com/markdown-it/markdown-it/issues/354)

**Comment by moritz31** [comment] 2017-05-10 06:18
@juliushaertl 
maybe markdown-it-link-target is a bit out of date, found [markdown-it-link-attributes](https://yarnpkg.com/en/package/markdown-it-link-attributes) which seems to be a bit newer than that 
However bower can't find it for me

**Comment by wwwindisch** [comment] 2017-05-10 07:35
@x9t9 Thanks for clarifying the issue...and sorry that I didn't investigate it more in detail.

**Comment by pixelipo** [comment] 2017-05-10 08:17
Upstream says that is not a bug :) They basically recommend using "<" and ">" to wrap links - that should always work.

**Comment by wwwindisch** [comment] 2017-05-10 08:29
Thanks! Good to know...works for me. 
From the user's point of view this solution is not really intuitive... Therefore, it should be documented somewhere (maybe together with basic formatting examples like `**bold**`), e.g. on a little "Help"-page in the Deck-Wiki?

**Comment by juliushaertl** [comment] 2017-05-10 09:47
Ok, thanks @x9t9 for investigating. I think we should have some help on the markdown as well as having a link to it somewhere near the description field for users who are not aware of markdown. Anyone wants to take care of that?

**Comment by x9t9** [comment] 2017-05-16 11:27
Closed as this issue is not directly related to card card but from upstrem, which will not fix .
Users will be informed following implementation of #129

**Closed by x9t9** 2017-05-16 11:27 UTC
Labels: 1. to develop, bug, frontend
