### ISSUE TITLE
After moving a card on the same board, a refresh is required

### ISSUE THREAD

**Issue by Poldi1977** [nextcloud/deck#3639] opened 2022-03-12 18:57 UTC
1. Choose a card and click on the three dots
2. Choose "Move card"
3. Choose a list on the same board
4. Click on button "Move card"
5. The card is no longer visible. The card becomes visible only after a refresh (F5).

I know that cards can be moved by drag and drop. However, I have a board with many lists and find it easier to go via the menu.

![Move card](https://user-images.githubusercontent.com/28756918/158031027-bbfd9348-d452-48ec-816b-e376e841badc.gif)

Operating system:
Linux 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64

Web server:
Apache/2.4.41 (Ubuntu) (apache2handler)

Database:
mysql 10.3.34

PHP version:
7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Nextcloud version:
23.0.2 - 23.0.2.1

Deck version:
1.6.1

**Comment by ludij** [comment] 2024-12-29 10:38
I can't reproduce this issue anymore. Seems to be resolved by this commit (https://github.com/nextcloud/deck/commit/22bb8d65e96d5f1bd94aa7af753e91b83ffc66df#diff-3671f52ef3b5e700de764d3450c79270a859f0b993925959b0bbd399e4a36234R121) which is part of this PR (https://github.com/nextcloud/deck/commit/fb236edf8c286d3506806b8f4fc66b286c1f7ee3#diff-3671f52ef3b5e700de764d3450c79270a859f0b993925959b0bbd399e4a36234)

**Closed** 2024-12-30 11:43 UTC
Labels: bug, frontend, 1. to develop
