### ISSUE TITLE
people can't see the details

### ISSUE THREAD

**Issue by tomaswarynyca** [nextcloud/deck#2309] opened 2020-09-17 17:27 UTC
By creating a card and not assigning a person to it, board members can see the details. But by assigning a person, no one can access the details, including the one assigned to them. Members are not allowed to edit, share or manage.

**Comment by juliushaertl** [comment] 2020-09-17 17:40
Please fill out the issue template.

**Comment by tomaswarynyca** [comment] 2020-09-17 18:00
**Describe the bug**
By creating a card and not assigning a person to it, board members can see the details. But by assigning a person, no one can access the details, including the one assigned to them. Members are not allowed to edit, share or manage.

**Client details:**
 - OS: [Linux (Deepin v20)]
 - Browser [Chrome]
 - Version [85.0.4183.102 (64 bits)]
 - Device: [Desktop]

<details>
<summary>Server details</summary>


**Operating system**: Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64

**Web server:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.5.3

**PHP version:** 7.4.10

**Nextcloud version:** 19.0.3 - 19.0.3.1

**Where did you install Nextcloud from:** docker (nextcloud:apache)

**Signing status:** Array()

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
**No errors have been found.**
```

**List of activated apps:**
Enabled:
  - accessibility: 1.5.0
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.0.5
  - encryption: 2.7.0
  - extract: 1.2.4
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - unsplash: 1.1.6
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - activity
  - admin_audit
  - files_antivirus
  - files_external
  - riotchat
  - user_ldap

**Nextcloud configuration:**

{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "19.0.3.1",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 2,
    "maintenance": false,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}


</details>

**Comment by juliushaertl** [comment] 2020-09-28 12:02
Have you shared the board with the edit/share/manage permissions?

**Comment by tomaswarynyca** [comment] 2020-09-30 13:15
No, just share the board with the members and when I assign a task they cannot see the content. If I don't assign it to anyone, they can access it.

**Comment by juliushaertl** [comment] 2020-10-02 20:08
Seems like a duplicate of https://github.com/nextcloud/deck/issues/2033, will be fixed with the next release.

**Closed by juliushaertl** 2020-10-02 20:08 UTC
Labels: needs info
