### ISSUE TITLE
I can not set tag color by hex code on Deck

### ISSUE THREAD

**Issue by cmdntd** [nextcloud/deck#3310] opened 2021-09-09 14:58 UTC
Could you build option to set tag color by hex code?
I try to imitate some color from my old card of trello

**Comment by stefan-niedermann** [comment] 2021-09-09 15:22
1. Press the three dot menu of the board in the left sidebar where you want to adjust the tag colors
  ![grafik](https://user-images.githubusercontent.com/4741199/132714228-1e7f3505-d1a5-4e32-8e06-69ec66ca0ef5.png)
2. In the details view (right sidebar) go to the second tab ("Schlagworte" here, should be "Tags" or "Labels" in english)
  ![grafik](https://user-images.githubusercontent.com/4741199/132714334-baea5f01-2755-4777-8053-207d937a42bd.png)
3. Press the :pen: pen icon next to the tag you want to edit and choose your color after clicking on the color picker
  ![grafik](https://user-images.githubusercontent.com/4741199/132714449-65b01455-30c9-4131-b06a-754ddb3e672c.png)
4. GitHub issues are for *development*, features and bug reports. For support and other questions please use the Nextcloud community forum on https://help.nextcloud.com next time - there is even a [category for the Deck app](https://help.nextcloud.com/c/apps/deck/83) :wink:

**Comment by stefan-niedermann** [comment] 2021-09-09 15:26
I see, you want to enter the hex code directly.

This is not implemented directly by the apps like Deck, but they all use the color picker of the [`@nextcloud/vue-components`](https://github.com/nextcloud/nextcloud-vue) - this is at the moment not yet possible, but there is already an open issue for this topic: https://github.com/nextcloud/nextcloud-vue/issues/1687
I recommend you to upvote there.

(Also duplicate of https://github.com/nextcloud/deck/issues/1911 with the search term `hex`)

**Closed by stefan-niedermann** 2021-09-09 15:26 UTC

**Comment by cmdntd** [comment] 2021-09-09 15:29
Thank you. I wait for next update.
