### ISSUE TITLE
[Feature Request] sub-subtask integration of deck markdown comments

### ISSUE THREAD

**Issue by sroener** [nextcloud/deck#3215] opened 2021-07-26 15:38 UTC
I think it would be useful to parse markdown tasklist from nextcloud decks card comments to sub-subtasks.

As far as I know, cards from Nextcloud deck are now added to the tasks app in read-only mode, with boards represented as task and cards as respective subtasks. I think it would be a useful feature to parse the markdown comments in the cards (which support markdown task; - [ ]) as sub-subtasks. This would be especially useful after implementing the write-mode between the apps, so that these tasks could be ticked off and synchronized with the cards.

**Comment by raimund-schluessler** [comment] 2021-07-26 15:43
Moving to the deck repository as this would need to be implemented here.

**Comment by stefan-niedermann** [comment] 2021-07-26 17:04
Please see https://github.com/nextcloud/deck/issues/2905#issuecomment-819642692

-> Closing as duplicate of https://github.com/nextcloud/server/issues/17375

@sroener sorry for the confusion 😉

**Closed by stefan-niedermann** 2021-07-26 17:04 UTC

**Comment by sroener** [comment] 2021-07-26 17:32
@stefan-niedermann 
Now I'm more confused than before 😉

I guess you would only work on parsing markdown from/to other apps, when it's globally available and then build additional functionality (`- [ ]` -> new sub-subtask) on top of that? 

Would this specific functionality covered in existing plans? (Sorry if I missed that, I only looked in the nextcloud/tasks repository and didn't see any)

**Comment by stefan-niedermann** [comment] 2021-07-26 17:41
Sorry, i'm just the developer of the Deck Android app and not related to the Nextcloud GmbH so i can't tell you anything about their plans... 😕 

But yeah, i guess this should also be part if they implement it :)

**Comment by sroener** [comment] 2021-07-26 17:44
OK, thx. And thx for the android app!

I guess after they worked on the markdown, I'll see whether it's implemented or not.

**Comment by stefan-niedermann** [comment] 2021-07-26 17:47
Yep, i recommend you to just subscribe to the linked issue to get notifications about this topic 👀

**Comment by Dunrar** [comment] 2022-07-08 08:52
I know this should definitely be part of core, but it is much more important to Deck. Any chance that we will see this in Deck only, as there seems to be little to no interest to bring this to core anytime soon?
