### ISSUE TITLE
After canceling sharing the file in the attachment, the source file will be deleted.

### ISSUE THREAD

**Issue by wlzjd** [nextcloud/deck#3281] opened 2021-08-31 10:53 UTC
After canceling sharing the file in the attachment, the source file will be deleted.

Just cancel sharing the original file and it should not be deleted.

**Comment by stefan-niedermann** [comment] 2021-08-31 10:59
Please use the 🔍 search function before opening new issues.

Closing as duplicate of #2877

**Closed by stefan-niedermann** 2021-08-31 10:59 UTC
