### ISSUE TITLE
Gantt Chart

### ISSUE THREAD

**Issue by vix95** [nextcloud/deck#3402] opened 2021-11-02 17:41 UTC
Hi all, is it possible to add the Gantt Chart? I see that the Start Date is not available during creation of the Task, so this id needed to be added as well.

Please take a look on below photo as reference.
![image](https://user-images.githubusercontent.com/38139321/139917402-0b97646a-f1aa-45f5-9d8d-f7810bc16f2a.png)

**Comment by stefan-niedermann** [comment] 2021-11-02 17:45
Quoting the maintainer:

> As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
> 
> If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

Closing as duplicate of #134

**Closed by stefan-niedermann** 2021-11-02 17:45 UTC
