### ISSUE TITLE
API / Apps

### ISSUE THREAD

**Issue by mat-l** [nextcloud/deck#491] opened 2018-06-17 09:36 UTC
Dear all,
How is the status about an API for an mobile App?
Accessing the deck using a separated and optimized app would be great. :)
Best

**Comment by juliushaertl** [comment] 2018-06-18 14:02
A rest API has been started in https://github.com/nextcloud/deck/pull/271 besides that there are no news regarding an API. 

Closing this as a duplicate of #83

**Closed by juliushaertl** 2018-06-18 14:02 UTC
