### ISSUE TITLE
Question on nc 19 release: Calendar-Integration not published?

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/deck#2004] opened 2020-06-09 14:46 UTC
"With this release Nextcloud makes it possible for apps to provide a calendar or address book. This allows Deck to provide calendars with todo’s and deadlines from its boards, making it easier for all team members to keep track of their progress."
- https://nextcloud.com/blog/nextcloud-hub-brings-productivity-to-home-office/

Do I miss something or isn't that functionality published yet?

**Comment by stefan-niedermann** [comment] 2020-06-09 15:05
Might be related to #15

**Comment by shgysk8zer0** [comment] 2020-06-11 01:16
Nextcloud itself now allows for this functionality. That's my understanding.

**Comment by sunjam** [comment] 2020-06-11 14:09
Also confused by this as it sounds like Caldav support, but that seems to not be the case. :+1:

**Comment by juliushaertl** [comment] 2020-06-12 20:15
Yes, the server part was released with Nextcloud 19. The deck integration is currently scheduled for deck 1.1 in #1545 

Apart from that we also need a new calendar release with https://github.com/nextcloud/calendar/pull/1798

So it is coming, just not there yet unfortunately. Closing as duplicate of #15

**Closed by juliushaertl** 2020-06-12 20:15 UTC
Labels: question
