### ISSUE TITLE
Show deck id and card id on card

### ISSUE THREAD

**Issue by chritd** [nextcloud/deck#3288] opened 2021-09-03 00:23 UTC
to make it more usable (like jira) it would be helpful to display the board id and card id in the card and have this as a link to easy be able to copy the link to the card and use it where ever needed.

you usually do not know the (exact) title of the card but in talking with your team its easy to say look at deck X card Y
like board/15/card/195

**Comment by stefan-niedermann** [comment] 2021-09-03 06:34
Please use the 🔍 search function before opening new issues.

Closing as duplicate of https://github.com/nextcloud/deck/issues/2906

**Closed by stefan-niedermann** 2021-09-03 06:34 UTC
