### ISSUE TITLE
Allow creation of cards via API (and/or email)

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/deck#445] opened 2018-03-31 14:45 UTC
It would aid integration (and make for a great work ticket system) if there was a way to add new cards to a board via an API (or by sending an email to the server - but if there was an API we'd build that bit anyway). This would allow non-NC users to create cards and also enable a "quick add" solution that doesn't require a user to log in to NC just to add a card.

**Comment by juliushaertl** [comment] 2018-04-04 10:16
duplicate of #83

**Closed by juliushaertl** 2018-04-04 10:16 UTC
Labels: enhancement
