### ISSUE TITLE
endless load icon on avatar

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#685] opened 2018-11-09 16:30 UTC
**Describe the bug**
When i click on my avatar in a shared board and i have no right to share, edit and manage a popup is displayed and the first line shows the waiting icon forever

**To Reproduce**
1. share a board to user 2 and share without rights (same as in 684)
2. open the board details view
3. click on the avatar of the owner (1), nothing happens
4. click on the avatar of myself (2), popup with endless loading is shown

**Expected behavior**
regarding my avatar (2):
no pop up is displayed 
or a pop up with only "no action is available" is displayed

regarding owners avatar (1):
a pop up with only "no action is available" is displayed

![avatar](https://user-images.githubusercontent.com/34692335/48274683-25547080-e444-11e8-9752-1b4b838a78f4.png)

**Comment by juliushaertl** [comment] 2018-12-04 09:51
Do you have one of the following sharing settings enabled?

- Exclude groups from sharing
- Restrict users to only share with users in their groups

This would cause the contacts menu endpoint of the server to return a 404 if you are not allowed to share with the relevant user.

**Comment by juliushaertl** [comment] 2018-12-04 12:08
Moving out of the current milestone, since this is probably an issue with the servers contacts menu code.

**Comment by cloud2018** [comment] 2018-12-04 19:18
In the meantime i noticed that it seems to be independent of what rights the user has while sharing. It is the same behavior when the user has all rights. Perhaps it's just a corrupt installation in my vm. If you can't reproduce this, please close this issue.


**My Setting:**
![screenshot_2018-12-04 settings - nextcloud](https://user-images.githubusercontent.com/34692335/49466484-803d7580-f800-11e8-88b0-5c9b934a1433.png)

**Browser console:**
```
...
XHRPOSThttp://localhost/nextcloud/index.php/contactsmenu/findOne [HTTP/1.1 200 OK 115ms]
```
and a constant repetition of 
`XHRGEThttp://localhost/nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 138ms]`

**Comment by juliushaertl** [comment] 2018-12-05 13:03
I could reproduce this with different sharing settings, but then the findOne request ended in a 404. I'll try to reproduce this with the server avatars to see if it is a deck only issue.

**Comment by juliushaertl** [comment] 2020-01-25 10:05
Closing as this was fixed in the vue branch and is now merged to master

**Closed by juliushaertl** 2020-01-25 10:05 UTC
Labels: 0. Needs triage, bug
