### ISSUE TITLE
Possibility to close/archive the task after completing

### ISSUE THREAD

**Issue by vix95** [nextcloud/deck#1893] opened 2020-05-14 21:55 UTC
Now if I want to close the task I need to show the details and select archive or delete the card. It will be really nice when I want to close the task, everything what I need to do is click on the icon near the title of the task.

My proposition is something like that.

![image](https://user-images.githubusercontent.com/38139321/81989602-d3466980-963d-11ea-82e0-dc4070714c3a.png)

After select the circle.
![image](https://user-images.githubusercontent.com/38139321/81989662-f40ebf00-963d-11ea-9828-480ab45f6597.png)

And after that the card is archived. Similar solutions is defined in MS Teams. I'm using in at work and it's helpful.

**Comment by juliushaertl** [comment] 2020-05-15 06:46
Duplicate of #534

**Closed by juliushaertl** 2020-05-15 06:46 UTC
