### ISSUE TITLE
Not able to move a Card to another Board

### ISSUE THREAD

**Issue by donty** [nextcloud/deck#5486] opened 2024-01-16 19:01 UTC
Recently upgraded to NC 28.01 and although the really useful Done option is in place and appears to work we are not able to move Cards between boards and lists,

Tried with a card marked as Done, tried with an incomplete card not marked and tried with a new created Test card. Used the three dot move option which usually allows me to select the new Board but as soon as I select the List it drops out of the dialogue box and returns to the original screen.  All cards are at least titled.

Logs

General NC logs even at debug level only error for the Deck app I can see is:

BadRequestException title must be provided and must be not empty
Exception thrown: OCA\Deck\BadRequestException 

Only other log entries are details about /appinfo/app.php being deprecated in one of either Music and Epubviewer

Any ideas are welcome!

NC 28.01
Deck 1.12
22.04 Ubuntu
Apache2
PHP 8.1

Login as admin user into your Nextcloud and access
http://xxxxxxxxxxxxxx/index.php/settings/integrity/failed
No errors have been found.

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.opensure.net"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "mysql.utf8mb4": true,
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "dbindex": 0
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "overwrite.cli.url": "https:\/\/nextcloud.opensure.net",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "enable_previews": true,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "updatechecker": false,
        "simpleSignUpLink.shown": false,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Epub",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007"
        ],
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "stable",
        "default_phone_region": "UK",
        "log_rotate_size": 52428800,
        "allowNightlyUpdates": [
            "passwords"
        ],
        "overwriteprotocol": "https",
        "app_install_overwrite": [
            "files_downloadactivity",
            "ocsms",
            "zimbradrive",
            "radio",
            "files_ebookreader",
            "files_reader",
            "cookbook",
            "music",
            "weather",
            "workflow_script",
            "audioplayer_editor",
            "epubreader",
            "passwords",
            "apporder",
            "integration_whiteboard",
            "whiteboard",
            "appointments",
            "cms_pico",
            "riotchat",
            "impersonate",
            "extract",
            "social",
            "richdocumentscode",
            "libresign",
            "solitaire"
        ],
        "has_rebuilt_cache": true,
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe"
    }
}
```

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client details:**
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by proserver1** [comment] 2024-01-17 08:07
same bug on all installations

NC 28.01
Deck 1.12
22.04 Ubuntu
Apache2
PHP 8.1

No errors in server log

Client: Firefox (current, Ubuntu 22.04)
Client: Chromium (current, Ubuntu 22.04)

**Comment by proserver1** [comment] 2024-01-17 15:41
1.12.1 did not fix it

**Comment by juliushaertl** [comment] 2024-01-18 11:06
Closing as a duplicate of https://github.com/nextcloud/deck/issues/5404

**Closed as not planned by juliushaertl** 2024-01-18 11:06 UTC
