### ISSUE TITLE
Activity app sends no Deck updates

### ISSUE THREAD

**Issue by kunago** [nextcloud/deck#5536] opened 2024-01-31 16:27 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
I have a email notifications set for Deck as well as for other apps. I recently made an upgrade from NC27 to NC28, updated all apps and since then when I receive an email with activities, the Deck activity is missing, is empty. Other apps, such as files app activities are displayed just fine.

**To Reproduce**
1. Make sure you have Deck email notifications allowed in the Activity app
2. Go to Deck, make an update (change a text or anything else)
3. Wait until you receive an email
4. No Deck activity is going to be displayed in the email

**Expected behavior**
The email should be populated with Deck activity

**Screenshots**
Please see https://github.com/nextcloud/activity/issues/1521 as this is a cross-post bug report but Activity app seems to work just fine.

**Client details:**
 - OS: run on docker
 - Browser: any
 - Version: NextCloud 28.0.1, Deck version 1.12.1
 - Device: any

<details>
<summary>Server details</summary>

**Operating system**:
docker.io/nextcloud:28-fpm-alpine

**Web server:**
within the container, using Caddy as a proxy

**Database:**
Postgres

**PHP version:**
within the container

**Nextcloud version:** (see Nextcloud admin page)
28.0.1.1

**Where did you install Nextcloud from:**
docker from the mentioned source above

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.4
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.1
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.1
  - event_update_notification: 2.3.0
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_retention: 1.17.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - group_default_quota: 0.1.8
  - impersonate: 1.15.0
  - keeweb: 0.6.17
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sociallogin: 5.6.3
  - spreed: 18.0.3
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0-dev (installed 28.0.0-dev)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.18.0)
  - files_external: 1.20.0 (installed 1.20.0)
  - files_reminders: 1.1.0 (installed 1.1.0)
  - firstrunwizard: 2.17.0 (installed 2.10.0)
  - nextcloud_announcements: 1.17.0 (installed 1.17.0)
  - recommendations: 2.0.0 (installed 1.0.0)
  - sharebymail: 1.18.0 (installed 1.11.0)
  - support: 1.11.0 (installed 1.4.0)
  - survey_client: 1.16.0 (installed 1.9.0)
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0 (installed 1.18.0)
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - weather_status: 1.8.0 (installed 1.8.0)
```

**Nextcloud configuration:**

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain1",
            "domain2",
            "domain3",
            "domain4"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "https:\/\/cloud.apason.cz",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "cs",
        "default_locale": "cs_CZ",
        "default_phone_region": "CZ",
        "auto_logout": "true",
        "logtimezone": "Europe\/Prague",
        "maintenance": false,
        "loglevel": 0,
        "log_rotate_size": 10485760,
        "app_install_overwrite": [
            "keeweb",
            "files_trackdownloads",
            "apporder",
            "talk_matterbridge",
            "ransomware_protection",
            "files_rightclick",
            "files_downloadactivity"
        ],
        "theme": "",
        "session_keepalive": 86400,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "upgrade.disable-web": true,
        "defaultapp": ""
    }
}
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
no sign of Deck issue, can share as needed but the log is huge
```

#### Browser log
```
I believe this does not apply
```

</details>

**Comment by djaniol** [comment] 2024-02-01 08:26
Issue confirmed on my side. This is actually present since several releases. Would be great to have it fixed.
As workaround can be mentioned person in the deck comment whenever something is modified so the person will receive notification.

**Comment by vlastimilott** [comment] 2024-02-02 10:41
Same here. We have another instance in the nearly same configuration, which works. 
```
sudo -u clients php ./occ activity:send-mails
An unhandled exception has been thrown:
TypeError: OC\Group\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, called in /var/www/myweb.xxx/nextcloud/lib/private/Group/Manager.php on line 374 and defined in /var/www/myweb.xxx/nextcloud/lib/private/Group/Manager.php:391
Stack trace:
#0 /var/www/myweb.xxx/nextcloud/lib/private/Group/Manager.php(374): OC\Group\Manager->getUserIdGroupIds()
#1 /var/www/myweb.xxx/nextcloud/apps/deck/lib/Service/PermissionService.php(234): OC\Group\Manager->isInGroup()
#2 /var/www/myweb.xxx/nextcloud/apps/deck/lib/Service/PermissionService.php(115): OCA\Deck\Service\PermissionService->userCan()
#3 /var/www/myweb.xxx/nextcloud/apps/deck/lib/Service/PermissionService.php(160): OCA\Deck\Service\PermissionService->getPermissions()
#4 /var/www/myweb.xxx/nextcloud/apps/deck/lib/Activity/ActivityManager.php(571): OCA\Deck\Service\PermissionService->checkPermission()
#5 /var/www/myweb.xxx/nextcloud/apps/deck/lib/Activity/DeckProvider.php(131): OCA\Deck\Activity\ActivityManager->canSeeCardActivity()
#6 /var/www/myweb.xxx/nextcloud/apps/activity/lib/MailQueueHandler.php(436): OCA\Deck\Activity\DeckProvider->parse()
#7 /var/www/myweb.xxx/nextcloud/apps/activity/lib/MailQueueHandler.php(333): OCA\Activity\MailQueueHandler->parseEvent()
#8 /var/www/myweb.xxx/nextcloud/apps/activity/lib/MailQueueHandler.php(130): OCA\Activity\MailQueueHandler->sendEmailToUser()
#9 /var/www/myweb.xxx/nextcloud/apps/activity/lib/Command/SendEmails.php(101): OCA\Activity\MailQueueHandler->sendEmails()
#10 /var/www/myweb.xxx/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\Activity\Command\SendEmails->execute()
#11 /var/www/myweb.xxx/nextcloud/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#12 /var/www/myweb.xxx/nextcloud/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
#13 /var/www/myweb.xxx/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#14 /var/www/myweb.xxx/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#15 /var/www/myweb.xxx/nextcloud/lib/private/Console/Application.php(206): Symfony\Component\Console\Application->run()
#16 /var/www/myweb.xxx/nextcloud/console.php(100): OC\Console\Application->run()
#17 /var/www/myweb.xxx/nextcloud/occ(11): require_once('...')

```

**Comment by en-iman** [comment] 2024-02-03 07:10
also i have problem with deck, when deck is enable load all activity get fail, but when i disable deck all activty load without any error.
i get this error when deck is enable:
 DoesNotExistException Did expect one result but found none when executing: query "SELECT * FROM `*PREFIX*deck_boards` WHERE (`id` = :dcValue2) AND (`deleted_at` = :dcValue1) ORDER BY `id` ASC";
Exception thrown: OCP\AppFramework\Db\DoesNotExistException

**Comment by en-iman** [comment] 2024-02-03 10:28
> Hello everyone, also i have problem with deck, when deck is enable load all activity get fail, but when i disable deck all activty load without any error. i get this error when deck is enable and go to activity tab: DoesNotExistException Did expect one result but found none when executing: query "SELECT * FROM `*PREFIX*deck_boards` WHERE (`id` = :dcValue2) AND (`deleted_at` = :dcValue1) ORDER BY `id` ASC"; Exception thrown: OCP\AppFramework\Db\DoesNotExistException

this problem solved with: DELETE FROM oc_activity WHERE app='deck'; in mariadb.

**Comment by kunago** [comment] 2024-02-04 04:49
As [was explained](https://github.com/nextcloud/activity/issues/1521#issuecomment-1925454727), this issue seems to occur because of rich objects set by Deck.

**Comment by PetrHar** [comment] 2024-02-05 14:58
@en-iman Is it safe to clear the tables, will the notifications from the Deck work?

**Comment by kunago** [comment] 2024-02-05 15:27
I am afraid this would not fix anything. As I understand it, oc_activity is for NC activities, but the issue is within oc_activity_mq which is regularly populated with changes and sent in predefined intervals to emails. The table is emptied based on the cron schedule, all records are removed once sent but anything regarding to Deck does not make it to the email. There must be some sanitazition does removes the message as such.

**Comment by en-iman** [comment] 2024-02-05 18:35
> @en-iman Is it safe to clear the tables, will the notifications from the Deck work?

yes now notification work and all past notifications showing but don't forget before enter the script take a backup. have luck my friend.

**Comment by PetrHar** [comment] 2024-02-05 20:06
I don't really want to clean it yet, it seems very low to me so we don't cause more problems. Is there a developer here? Any idea when the patch will be released?

**Comment by caww** [comment] 2024-02-06 13:02
Just run in mysql
DELETE FROM oc_activity WHERE app='deck';
and not changes --- email notifications from deck still not working not working
and still showing same issue in logs

`TypeError
OC\Group\Manager::getUserIdGroupIds(): Argument #1 ($uid) must be of type string, null given, called in /var/www/sera/data/www/mgamontreal.com/lib/private/Group/Manager.php on line 374
/var/www/sera/data/www/mgamontreal.com/lib/private/Group/Manager.php
line 374
OC\Group\Manager->getUserIdGroupIds(
  null
)
/var/www/sera/data/www/mgamontreal.com/apps/deck/lib/Service/PermissionService.php
line 234
OC\Group\Manager->isInGroup(
  null,
  "Sales"
)
/var/www/sera/data/www/mgamontreal.com/apps/deck/lib/Service/PermissionService.php
line 115
OCA\Deck\Service\PermissionService->userCan(
  [
    [
      "OCA\\Deck\\Db\\Acl",
      10
    ],
    [
      "OCA\\Deck\\Db\\Acl",
      11
    ]
  ],
  0,
  null
)
/var/www/sera/data/www/mgamontreal.com/apps/deck/lib/Service/PermissionService.php
line 160
OCA\Deck\Service\PermissionService->getPermissions(
  9,
  null
)
/var/www/sera/data/www/mgamontreal.com/apps/deck/lib/Activity/ActivityManager.php
line 571
OCA\Deck\Service\PermissionService->checkPermission(
  [
    "OCA\\Deck\\Db\\CardMapper"
  ],
  32,
  0
)
/var/www/sera/data/www/mgamontreal.com/apps/deck/lib/Activity/DeckProvider.php
line 131
OCA\Deck\Activity\ActivityManager->canSeeCardActivity(
  32
)
/var/www/sera/data/www/mgamontreal.com/apps/activity/lib/MailQueueHandler.php
line 436
OCA\Deck\Activity\DeckProvider->parse(
  "en",
  [
    "OC\\Activity\\Event"
  ]
)
/var/www/sera/data/www/mgamontreal.com/apps/activity/lib/MailQueueHandler.php
line 333
OCA\Activity\MailQueueHandler->parseEvent(
  "en",
  [
    "OC\\Activity\\Event"
  ]
)
/var/www/sera/data/www/mgamontreal.com/apps/activity/lib/MailQueueHandler.php
line 130
OCA\Activity\MailQueueHandler->sendEmailToUser(
  "JustinH",
  "justin@mgagroupcanada.com",
  "en",
  "America/Toronto",
  1707224400
)
/var/www/sera/data/www/mgamontreal.com/apps/activity/lib/BackgroundJob/EmailNotification.php
line 60
OCA\Activity\MailQueueHandler->sendEmails(
  500,
  1707224400
)
/var/www/sera/data/www/mgamontreal.com/lib/private/BackgroundJob/Job.php
line 54
OCA\Activity\BackgroundJob\EmailNotification->run(
  null
)
/var/www/sera/data/www/mgamontreal.com/lib/private/BackgroundJob/TimedJob.php
line 60
OC\BackgroundJob\Job->execute(
  [
    "OC\\BackgroundJob\\JobList"
  ],
  [
    "OC\\Log"
  ]
)
/var/www/sera/data/www/mgamontreal.com/cron.php
line 152
OC\BackgroundJob\TimedJob->execute(
  [
    "OC\\BackgroundJob\\JobList"
  ],
  [
    "OC\\Log"
  ]
)`

**Comment by joshtrichards** [comment] 2024-02-19 23:18
Duplicate of #5499

**Closed by joshtrichards** 2024-02-19 23:18 UTC

**Comment by MichaelPerlbach** [comment] 2024-03-13 15:54
Still no email notifications with Deck 1.12.2 in Nextcloud 28.0.3.

**Comment by caww** [comment] 2024-03-13 16:13
confirming that no email notifications working for deck latest 1.12.2 in Nextcloud 28.0.3 for me too
