### ISSUE TITLE
card titles should be updated when changed via android app

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/deck#3174] opened 2021-07-07 12:58 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
card titles should be automatically updated in browser when changed via android app

**To Reproduce**
1. have board open in browser
2. change card title on android app

**Expected behavior**
The title should update immediately in the browser. 
At the moment you have to refresh the desktop browser page to see the changes.

**Screenshots**
can provide if needed

**Client details:**
 - OS: Linux Mint
 - Browser Firefox
 - Version  89.0.2
 - Device: desktop

Android device:
Android 8.0.0
Deck Android Appp 1.18.3

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 20.0.4

**Deck Server App version:** 1.2.7

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by stefan-niedermann** [comment] 2021-07-07 13:54
Duplicate of #256

**Closed by stefan-niedermann** 2021-07-07 13:54 UTC
