### ISSUE TITLE
Comments: Don't notify author himself

### ISSUE THREAD

**Issue by pschopen** [nextcloud/deck#5437] opened 2024-01-08 14:00 UTC
If I repliy to a comment that I was mentioned in, I receive a notification that I mentioned myself.

I think there should be an exception for notifications if somebody mentions himself (also generally, but especially if it's a reply to a comment where this person was mentioned)

**Comment by joshtrichards** [comment] 2024-10-01 18:44
Duplicate of #2672

**Closed by joshtrichards** 2024-10-01 18:44 UTC
Labels: feature: comments
