### ISSUE TITLE
Description : View / Edit icons need to stay in fixed place

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/deck#1908] opened 2020-05-16 15:16 UTC
**Is your feature request related to a problem? Please describe.**
When editing a description, the View icon shift to left because the Attachment icon shows up :
- in view mode : two icons are present : Pencil (_2_) and Info __1__
- in edit mode : three icons : Eye __2__, Staple __3__ and Info __1__

This is not convenient ans lead to unwanted pressing on attachment in place to leaving edition mode...

**Describe the solution you'd like**
Putting the attachment icon on left : staple __3__, eye/pencil __2__, info  __1__

**Describe alternatives you've considered**
NA

**Additional context**
NA
![ksnip_20200516-171209](https://user-images.githubusercontent.com/47881838/82123219-76ab9180-9798-11ea-8a1e-38b47bdcd2d7.png)
![ksnip_20200516-171057](https://user-images.githubusercontent.com/47881838/82123221-77442800-9798-11ea-860e-ad37f76f1405.png)

**Comment by juliushaertl** [comment] 2020-05-18 14:56
Duplicate of https://github.com/nextcloud/deck/issues/1812

**Closed by juliushaertl** 2020-05-18 14:56 UTC
