### ISSUE TITLE
Movements of cards not logged right in timeline

### ISSUE THREAD

**Issue by crohrandt** [nextcloud/deck#1265] opened 2019-09-27 10:03 UTC
**Describe the bug**
If a card is moved from one stack to another the timeline shows the source stack's name also as the stack that the card was moved to.

**Steps to reproduce the behavior**:
1. Move a card from one stack to another
2. Have a look in the timeline of that card

**Expected behavior**
The source stack and sink stack of the moved card should be correct and not both show the source stack's name

**Screenshots**
![Auswahl_010](https://user-images.githubusercontent.com/33962713/65761049-5e5e0800-e11e-11e9-948f-eb1ab2987094.png)
The screenshot was taken after moving the card from stack "FREITAG" to stack "DONNERSTAG" and back again.

**Client details:**
 Firefox 69.0 (64-Bit)

**Server details**
Nextcloud 16.0.4
Deck 0.6.6

**Comment by putt1ck** [comment] 2019-09-27 10:38
Duplicate of https://github.com/nextcloud/deck/issues/1169

**Closed by putt1ck** 2019-09-27 10:38 UTC
