### ISSUE TITLE
Markdown list with formatting rendering duplicate text

### ISSUE THREAD

**Issue by hectorjsmith** [nextcloud/deck#2753] opened 2021-01-25 19:43 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
When rendering a markdown list in a card description, duplicate text is shown if the list item includes formatted text.

I observed this issue with bold formatting, but it appears to affect all markdown formatting (e.g italics and links)

**To Reproduce**
1. Edit the description of a card and include the following markdown:
```markdown
- [ ] **Step 1:** Do something
- [ ] **Step 2:** Do another thing
```
2. Render the preview of the card description.

**Expected behavior**
The rendered markdown should show the Checkbox, followed by "Step 1" in bold, followed by "Do something" without formatting.

**Actual behavior**
The rendered description shows "Step 1" twice, once in bold, and once in raw markdown.

**Screenshots**
In edit mode:
![image](https://user-images.githubusercontent.com/9355321/105755092-be4b0580-5f42-11eb-94fd-30f218c75bb7.png)

In preview mode:
![image](https://user-images.githubusercontent.com/9355321/105755166-d6228980-5f42-11eb-8a32-7f4889a039ea.png)

**Client details:**
 - OS: Linux Mint
 - Browser Firefox
 - Version: 84.0.2 (64-bit)
 - Device: Desktop

<details>
<summary>Server details</summary>

**Operating system:** Linux 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 5.7.32

**PHP version:** 7.4.13

**Nextcloud version:** 20.0.4 - 20.0.4.0

**Deck version:** 1.2.3

</details>

**Comment by reox** [comment] 2021-01-27 10:46
duplicate of #2138

**Closed** 2021-01-27 11:02 UTC
