### ISSUE TITLE
Improving attachment of NC files

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/deck#2036] opened 2020-06-17 11:03 UTC
**Is your feature request related to a problem? Please describe.**
Nextcloud is the solution for collaboration with files and ideas. Usually users are creating, uploading and storing documents immediately in the folders of Nextcloud.

Deck allows to track the changes in the projects/activities, as well as attach documents created within the project.

Currently, it is not so clear for a user the process of attaching the document to a certain task (card).
I cannot do this from the tab **Attachments**, but in **Details**.
 
From **Details** of the card you have to click **Add to a project**, afterwards you are selecting **Link to a file** and choosing the file in the tree of NC. When done I see instead of the file name the name of the card with unclear button with 4 squares and tidy icon of the attached file. This brings certain confusion at a user.

**Describe the solution you'd like**
Attachment of files should be done under the tab Attachments with the options to upload from NC tree or from your desktop. Attached files should be shown under Attachments in the form of the list and/or thumbnails.

**Link to a file** should be taken out from the Details section, optionally replaced with the link to the folder.

**Additional context**
Project management is something not clear in NC. It should be well elaborated in order to understand what is a project. Currently it is not clear, how to create and understand them.

**Comment by stefan-niedermann** [comment] 2020-06-17 12:26
@ostasevych could you please have a look at [this issue](https://github.com/nextcloud/deck/issues/564)? I think what you are requesting might be already covered by it.

**Comment by juliushaertl** [comment] 2020-06-17 14:16
Yes, let's close that as a duplicate of #564

**Comment by juliushaertl** [comment] 2020-06-17 14:17
Regarding the enhancements of the projects feature you might want to also checkout https://github.com/nextcloud/server/issues/21359

**Closed by juliushaertl** 2020-06-17 14:16 UTC

**Comment by ostasevych** [comment] 2020-06-17 19:20
to some extent this is the same, however I raised another issue with taking away attachment from the projects, especially in Decks to get rid of any  confusions.

**Comment by juliushaertl** [comment] 2020-06-18 19:30
No, this is not about taking away projects. This is a different feature as it works across multiple apps, e.g. with nextcloud talk.
