### ISSUE TITLE
Is it possible to share with user only card, not all deck?

### ISSUE THREAD

**Issue by drmnk** [nextcloud/deck#868] opened 2019-01-30 05:54 UTC
Hello, thank you for great app for nextcloud! 

I stuck that I can't find some functionality: ist it possible to share with user only card, not all deck?

For example, I want to have a deck "Sales" with tasks that I five to my three colleagues, working in sales.
But I don't want they see all tasks of each other in deck, because sometimes it's secret or just don't needed.

But if I share deck with every colleague or team, they all will see all cards.

Can I make this somehow?

**Comment by juliushaertl** [comment] 2019-01-30 08:10
@drmnk There is no way to to that right now. However maybe we could somehow allow to also assign users that are not part of the board and once those access deck, they can only see the cards they were assigned to. So this is actually a duplicate of https://github.com/nextcloud/deck/issues/663

**Closed by juliushaertl** 2019-01-30 08:10 UTC
