### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by rad-li** [nextcloud/deck#2565] opened 2020-11-16 18:31 UTC
The execution time is displayed incorrectly. This happens if the local time differs from UTC. In all other cases, there is no error. In my case, the difference is -3 hours in the web interface and +3 hours in the app. I think the error is in the server side.

    Nextcloud: 20.0.1
    Nextcloud Deck: 1.2.0
![Снимок экрана_2020-11-16_20-38-08](https://user-images.githubusercontent.com/74559754/99292731-ad02c000-2852-11eb-9480-e05c908406b8.png)
![Снимок экрана_2020-11-16_20-38-33](https://user-images.githubusercontent.com/74559754/99292734-ae33ed00-2852-11eb-8977-8bcf5262aa04.png)

**Comment by trev-dev** [comment] 2020-11-19 00:34
Duplicate of https://github.com/nextcloud/deck/issues/2276 - but it's good to see I'm not the only one here.

**Comment by juliushaertl** [comment] 2020-11-19 18:31
Yep, let's continue to track this in #2276

**Closed by juliushaertl** 2020-11-19 18:31 UTC
