### ISSUE TITLE
Cards' date picker overflow not visible

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/deck#4441] opened 2023-02-09 15:24 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
![2023-02-09_16-17](https://user-images.githubusercontent.com/33763786/217854500-eb309299-ebe9-42d0-bc3b-d1b4fa548d23.png)

**To Reproduce**
1. Make sure you use the "bigger card view"
2. Open a card
3. Click on the date picker
4. See that the date picker's overflow is hidden

**Expected behavior**
Overflow should be visible

**Screenshots**
See above.

### Server configuration

**Operating system**: Linux 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 10.3.37

**PHP version:** 8.1.15

**Nextcloud version:** 25.0.3 - 25.0.3.2

**Where did you install Nextcloud from:** Web installer

**Signing status:**
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
 - activity: 2.17.0
 - announcementcenter: 6.4.0
 - bruteforcesettings: 2.5.0
 - calendar: 4.2.3
 - circles: 25.0.0
 - cloud_federation_api: 1.8.0
 - comments: 1.15.0
 - contacts: 5.1.0
 - contactsinteraction: 1.6.0
 - dashboard: 7.5.0
 - dav: 1.24.0
 - deck: 1.8.3
 - external: 5.0.0
 - federatedfilesharing: 1.15.0
 - federation: 1.15.0
 - files: 1.20.1
 - files_accesscontrol: 1.15.1
 - files_automatedtagging: 1.15.0
 - files_external: 1.17.0
 - files_linkeditor: 1.1.13
 - files_lock: 24.0.1
 - files_pdfviewer: 2.6.0
 - files_readmemd: 1.2.2
 - files_rightclick: 1.4.0
 - files_sharing: 1.17.0
 - files_trashbin: 1.15.0
 - files_versions: 1.18.0
 - firstrunwizard: 2.14.0
 - flow_notifications: 1.5.0
 - groupfolders: 13.1.1
 - guests: 2.3.0
 - impersonate: 1.11.0
 - jitsi: 0.16.2
 - logreader: 2.10.0
 - lookup_server_connector: 1.13.0
 - metadata: 0.17.0
 - nextcloud_announcements: 1.14.0
 - notes: 4.6.0
 - notifications: 2.13.1
 - oauth2: 1.13.0
 - occweb: 0.1.0
 - password_policy: 1.15.0
 - passwords: 2023.1.23
 - phonetrack: 0.7.4
 - photos: 2.0.1
 - privacy: 1.9.0
 - provisioning_api: 1.15.0
 - quota_warning: 1.15.0
 - recommendations: 1.4.0
 - related_resources: 1.0.3
 - richdocuments: 7.1.0
 - richdocumentscode: 22.5.802
 - serverinfo: 1.15.0
 - settings: 1.7.0
 - sharebymail: 1.15.0
 - spreed: 15.0.3
 - support: 1.8.0
 - survey_client: 1.13.0
 - systemtags: 1.15.0
 - text: 3.6.0
 - theming: 2.0.1
 - theming_customcss: 1.12.0
 - twofactor_backupcodes: 1.14.0
 - twofactor_email: 2.7.1
 - twofactor_nextcloud_notification: 3.5.0
 - twofactor_totp: 7.0.0
 - updatenotification: 1.15.0
 - user_status: 1.5.0
 - viewer: 1.9.0
 - weather_status: 1.5.0
 - welcome: 1.0.8
 - workflowengine: 2.7.0
Disabled:
 - admin_audit
 - apporder: 0.15.0
 - duplicatefinder: 0.0.15
 - encryption
 - extract: 1.3.5
 - files_zip: 1.1.2
 - suspicious_login
 - user_ldap
 - video_converter: 1.0.5
```

**Nextcloud configuration:**

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.mydomain.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "25.0.3.2",
    "updatechecker": true,
    "overwrite.cli.url": "https:\/\/nextcloud.mydomain.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "default_language": "fr",
    "default_locale": "fr_FR",
    "knowledgebaseenabled": false,
    "default_phone_region": "ISO3166-2",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "occweb",
        "files_readmemd",
        "impersonate",
        "apporder"
    ]
}
```

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Firefox 110

**Operating system:** GNU/Linux Ubuntu 20.04 LTS

### Logs
Can be provided if necessary

#### Browser log
Can be provided if necessary

</details>

**Comment by reox** [comment] 2023-02-10 09:01
Duplicate of #4195

**Comment by Jerome-Herbinet** [comment] 2023-02-10 09:03
OK @reox thx I close it.

**Closed** 2023-02-10 09:03 UTC
