### ISSUE TITLE
Toggle checkbox deletes card description. 

### ISSUE THREAD

**Issue by santifa** [nextcloud/deck#2592] opened 2020-11-20 09:46 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Current Version 1.2.1

If a descriptions contains checkboxes, the toggeling of a checkbox (checked -> unchecked or otherwise)
deletes the entire description of a card. 

**To Reproduce**
1. Go to some card
2. Click on some checkbox
3. See your description going away for ever

**Expected behavior**
It should toggle the checkbox.

**Screenshots**
Nothing to see here

**Client details:**
 - OS: Arch Linux
 - Browser Firefox 82
 - Device: Desktop

<details>
<summary>Server details</summary>

Server details
**Operating system**: Debian 9

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 19.0.4

**Where did you install Nextcloud from:** from source

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors here.

**List of activated apps:** 

  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - apporder: 0.11.0
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - cms_pico: 1.0.10
  - comments: 1.9.0
  - contacts: 3.4.2
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.2.1
  - drawio: 0.9.7
  - event_update_notification: 1.0.2
  - external: 3.6.0
  - extract: 1.2.5
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.2
  - files_external: 1.10.0
  - files_fulltextsearch: 1.4.3
  - files_fulltextsearch_tesseract: 1.4.2
  - files_markdown: 2.3.1
  - files_pdfviewer: 1.8.0
  - files_retention: 1.8.2
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - fulltextsearch: 1.4.2
  - fulltextsearch_elasticsearch: 1.5.2
  - groupfolders: 7.1.1
  - ldap_write_support: 1.1.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - metadata: 0.12.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - passwords: 2020.11.0
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - richdocuments: 3.7.9
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - socialsharing_email: 2.1.0
  - spreed: 9.0.6
  - support: 1.2.1
  - systemtags: 1.9.0
  - tasks: 0.13.6
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflow_pdf_converter: 1.4.0
  - workflowengine: 2.1.0
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "trusted_domains": [
            "192.168.1.50",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "onlyoffice": {
            "verify_peer_off": true
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "skeletondirectory": "",
        "app_install_overwrite": [
            "ocr"
        ]
    }
}

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
- jQuery is deprecated

b) The network log
- Nothing to show 
c) ...
```

</details>

**Comment by stefan-niedermann** [comment] 2020-11-20 10:47
Duplicate of https://github.com/nextcloud/deck/issues/2580 and https://github.com/nextcloud/deck/issues/2591

[A fix](https://github.com/nextcloud/deck/pull/2584) is already in the pipeline.

You should be able to [restore the description content from the timeline tab](https://github.com/nextcloud/deck/issues/2580#issuecomment-730319105).

**Closed by stefan-niedermann** 2020-11-20 10:47 UTC
