### ISSUE TITLE
Shared Folder via Link - OCA\Deck\NoPermissionException

### ISSUE THREAD

**Issue by ternes3** [nextcloud/deck#3296] opened 2021-09-05 10:34 UTC
If you share a folder via Link and grant permissions to edit and upload then you will get a error cousing in no access to this folder.

Deck Version 1.5.1 

```{"reqId":"e9OipibhfAdDMRRE76VR","level":4,"time":"2021-09-05T10:25:16+00:00","remoteAddr":"XXX.34.XXX.30","user":"--","app":"webdav","method":"PROPFIND","url":"/public.php/webdav/","message":"Must be logged in to get the group limit","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0","version":"22.1.1.2","exception":{"Exception":"OCA\\Deck\\NoPermissionException","Message":"Must be logged in to get the group limit","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/deck/lib/DAV/CalendarPlugin.php","line":44,"function":"get","class":"OCA\\Deck\\Service\\ConfigService","type":"->","args":["calendar"]},{"function":"__construct","class":"OCA\\Deck\\DAV\\CalendarPlugin","type":"->","args":[{"__class__":"OCA\\Deck\\DAV\\DeckCalendarBackend"},{"__class__":"OCA\\Deck\\Service\\ConfigService"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[[{"__class__":"OCA\\Deck\\DAV\\DeckCalendarBackend"},{"__class__":"OCA\\Deck\\Service\\ConfigService"}]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Deck\\DAV\\CalendarPlugin","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"/var/www/html/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"/var/www/html/apps/dav/lib/AppInfo/PluginManager.php","line":256,"function":"query","class":"OC\\ServerContainer","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"/var/www/html/apps/dav/lib/AppInfo/PluginManager.php","line":316,"function":"createClass","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":["*** sensitive parameter replaced ***"]},{"function":"OCA\\DAV\\AppInfo\\{closure}","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/dav/lib/AppInfo/PluginManager.php","line":321,"function":"array_map","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/apps/dav/lib/AppInfo/PluginManager.php","line":168,"function":"loadSabreCalendarPluginsFromInfoXml","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[["*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/apps/dav/lib/AppInfo/PluginManager.php","line":106,"function":"populate","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/ServerFactory.php","line":221,"function":"getAppPlugins","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\ServerFactory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":456,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["beforeMethod:PROPFIND",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v1/publicwebdav.php","line":113,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/public.php","line":80,"args":["/var/www/html/apps/dav/appinfo/v1/publicwebdav.php"],"function":"require_once"}],"File":"/var/www/html/custom_apps/deck/lib/Service/ConfigService.php","Line":89,"CustomMessage":"--"},"id":"61349c5a86f5d"}```

**Comment by sovereigndigitool** [comment] 2021-09-05 10:45
Duplicate of https://github.com/nextcloud/deck/issues/3292

**Closed** 2021-09-05 19:02 UTC
