### ISSUE TITLE
Error in Migration file 'Version1000Date20200308073933.php'

### ISSUE THREAD

**Issue by pielonet** [nextcloud/deck#2016] opened 2020-06-11 09:33 UTC
Hi,

It looks like there's an error in the Migration file (https://github.com/nextcloud/deck/blob/3302eab85762cb1463811db7966aa3ce41d0899f/lib/Migration/Version1000Date20200308073933.php#L42) : an index on "participant" column gets created.

```php
		// Defaults to TYPE_USER = 0
		$table->addColumn('type', 'integer', [
			'notnull' => true,
			'default' => 0
		]);
		$table->addIndex(['participant'], 'deck_assigned_users_idx_t');
```

Should be :

```php
		// Defaults to TYPE_USER = 0
		$table->addColumn('type', 'integer', [
			'notnull' => true,
			'default' => 0
		]);
		$table->addIndex(['type'], 'deck_assigned_users_idx_t');
```

since there is already an index on column participant.
Moreover the "t" at the end of the index name clearly indicates that it was meant for column "type".

**Comment by juliushaertl** [comment] 2020-06-14 19:01
Yes, that is indeed the wrong column for the index, so we need a new migration to remove the wrongly set one and add a proper one.

**Comment by juliushaertl** [comment] 2020-06-16 11:20
Duplicate of https://github.com/nextcloud/deck/issues/1884

**Closed by juliushaertl** 2020-06-16 11:20 UTC
Labels: 1. to develop, bug, good first issue
