### ISSUE TITLE
Real time sync of board

### ISSUE THREAD

**Issue by Chaleuri** [nextcloud/deck#3484] opened 2021-12-13 14:05 UTC
A feature that allows to sync board changes in real time between sessions would be great for collaborative editing purposes. 

I mean, if i move, rename a card or do anything to it, it would show up to the other person in real time.

Now the page needs to be reloaded to see the changes that someone else did and it only saves the latest change.

**Comment by stefan-niedermann** [comment] 2021-12-13 14:08
Duplicate of https://github.com/nextcloud/deck/issues/256

**Closed** 2021-12-13 14:08 UTC
