### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by PommensundBier** [nextcloud/deck#5989] opened 2024-06-11 06:28 UTC
Hey there, it would be very nice if it would be possible to dublicate a Board with all the cards. An empty Board isnt very useful to me. I have to Build all the cards with there tasks in it again and again. Copy function would be Great 👍

**Comment by niclasheinz** [comment] 2024-06-13 15:16
duplicate of #2797

**Closed** 2024-06-13 15:18 UTC
