### ISSUE TITLE
wasted space with due-date display and long text

### ISSUE THREAD

**Issue by DragonDev1906** [nextcloud/deck#2063] opened 2020-06-23 13:38 UTC
**Is your feature request related to a problem? Please describe.**
I have some cards with longer text and a 1366x768 screen. Unfortunately having a due-date on a card with long text results in a lot of space being wasted and the card getting unnecessary long (see screenshot)

**Describe the solution you'd like**
It would probably best change it so that the text can be displayed below the due-date as well (just the first line being shorter than the rest). (Additionally the same could be applied to the 3 dots showing the dropdown. That way the text has a tiny bit more space.)

**Describe alternatives you've considered**
Alternatively the due-date could be moved to the bottom of the card, but then there would always  be an empty line at the bottom

**Additional context**
![2020-06-23_15:31:12](https://user-images.githubusercontent.com/8270201/85409698-6ab8a980-b566-11ea-82f5-4cbe2fd3d579.png)
![2020-06-23_15:36:12](https://user-images.githubusercontent.com/8270201/85410219-1bbf4400-b567-11ea-8ec9-27d2fe1f257f.png)

**Comment by juliushaertl** [comment] 2020-06-23 15:09
Closing as a duplicate of #1672, but let me move your screenshots over there to make this a bit clearer in the original issue.

**Closed by juliushaertl** 2020-06-23 15:09 UTC
