### ISSUE TITLE
Change the day on which the week starts

### ISSUE THREAD

**Issue by fm-sys** [nextcloud/deck#1829] opened 2020-05-08 10:18 UTC
In Europe the week traditionally starts on Monday. It would be nice if there is an option where the beginning of the week could be set. Currently, the weeks in the due date calendar start on Sunday. This is quite confusing for most Europeans...

Or does this option even exist already and I just missed it?

Thanks for your help!

**Comment by pierremoreau** [comment] 2020-05-08 10:57
You can change the locale in your settings, but currently the locale is not being used by the calendar.
This is a duplicate of #1506.

**Comment by juliushaertl** [comment] 2020-05-11 05:53
Closing as duplicate of #1506

**Closed by juliushaertl** 2020-05-11 05:53 UTC
