### ISSUE TITLE
wrap title of card when editing

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/deck#1572] opened 2020-03-04 21:28 UTC
**To Reproduce**

1. make a new card
1. enter a really long title for a card (100 characters seems to be max)
2. when you reach the end of the line, the text is not wrapped, so you dont see the beginning of the title any more

**Expected behavior**
text should wrap while editing so you can see everything at once
(it is wrapping in view mode already)
(having a different view for edit/view is confusing)

Related to https://github.com/nextcloud/deck/issues/865

**details:**
Nextcloud 18.0
Deck 0.8.0

**Comment by juliushaertl** [comment] 2020-03-07 08:20
Closing as duplicate of #865

**Closed by juliushaertl** 2020-03-07 08:20 UTC
