### ISSUE TITLE
Hyperlinks in checklists don't markup properly

### ISSUE THREAD

**Issue by clarkhenry** [nextcloud/deck#3278] opened 2021-08-29 04:46 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
The markup doesn't properly work for links in checklists.

**To Reproduce**
1. Create a new card
2. In the description, create a checklist with a hyperlink, for example:
> - [ ] [link](https://example.com)

3. Go to the "View description" view. Hyperlink is not marked up properly. There is still a hyperlink, but the text is wrong.

**Expected behavior**
Display the hyperlink the same way as if it were not within the checklist.

**Screenshots**
![edit-description](https://user-images.githubusercontent.com/42017055/131238690-4741b546-60de-4e13-81bb-46f2f687bcf1.png)
![view-description](https://user-images.githubusercontent.com/42017055/131238693-26b6406f-a161-45a4-8c63-0cd1f584c9e1.png)

**Client details:**
- Nextcloud version 21.0.4
- Nextcloud Deck version 1.4.3
- Firefox browser, version 91.0.2

**Comment by stefan-niedermann** [comment] 2021-08-30 09:09
Closing as duplicate of #2640
Rrelated to #2109

**Closed by stefan-niedermann** 2021-08-30 09:09 UTC
