### ISSUE TITLE
Feature Request: Subtasks

### ISSUE THREAD

**Issue by githubkoma** [nextcloud/deck#264] opened 2017-07-18 12:24 UTC
Dear juliushaertl and others,
thanks for this wonderful app!

Subtasks would be really great, especially if there content would be display on the task directly (and can be collapsed). This is an example picture according to kanbanflow.com:

![image pasted at 2017-7-18 14-08](https://user-images.githubusercontent.com/5107805/28316753-5d518184-6bc4-11e7-8419-50cfbc0121cf.png)

**Comment by pixelipo** [comment] 2017-07-18 14:39
Thanks for your input!

We plan to support Github-style checkboxes in card description - see #53

I don't think we'll display them as prominently as in your screen shot, but a count (e.g. 5/11) would be nice.

**Comment by juliushaertl** [comment] 2017-07-27 07:01
Yep, basically a duplicate of #53

**Closed by juliushaertl** 2017-07-27 07:01 UTC
