### ISSUE TITLE
Automatically tag task based on stack

### ISSUE THREAD

**Issue by modzilla99** [nextcloud/deck#4858] opened 2023-06-27 06:32 UTC
Hey there,

thanks for bringing us Nextcloud deck. I really like it and use it a lot! One feature I would like to see, though, is tagging a task based on the stack it is in.

For example if I put a task into the hypothetical "In progress" stack I would like Deck to automatically add the tag "doing" and remove the automatically set tag from the stack it was in before ( - "in progress").

Thank you!

**Comment by putt1ck** [comment] 2023-06-27 07:08
I think that's a duplicate of https://github.com/nextcloud/deck/issues/1722

**Closed by putt1ck** 2023-06-27 07:08 UTC
