### ISSUE TITLE
Bigger card view: due calendar is cut off

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/deck#2830] opened 2021-02-26 08:23 UTC
![image](https://user-images.githubusercontent.com/24530680/109274924-56732d80-7814-11eb-9648-4eef43a717f6.png)

**Comment by aproposnix** [comment] 2021-02-28 15:55
Would this issue include improved scaling based on screen size, or should another issue be created for that?

**Comment by reox** [comment] 2021-03-05 18:48
duplicate of #2704 ;)

**Closed** 2021-04-14 16:12 UTC
Labels: 1. to develop, bug
