### ISSUE TITLE
Embedding image directly into description/comments with copy/paste

### ISSUE THREAD

**Issue by brunodegoyrans** [nextcloud/deck#3943] opened 2022-07-29 09:31 UTC
Hello

To embed an image into the card description, you have to save your image on your disk, click on the menu "file attachement", search and select you file on your disk (omg, where is it?), upload. Then you have to go back to the description, click on the button, and select the file. Very standard but time-consuming.

**Feature idea**: with GITHUB or GITLAB, the above actions takes only 2 clicks or CTRL-C/CTRL-V. Would be a great feature to have this with deck.

Moreover, it should be even greater if we could do that into comments also. But this is related to #2143

**Comment by stefan-niedermann** [comment] 2022-07-30 07:17
Duplicate of https://github.com/nextcloud/deck/issues/533

Please use the 🔍 **search function** before opening new issues.

**Closed by stefan-niedermann** 2022-07-30 07:17 UTC
