### ISSUE TITLE
Checklist changes not saved in modal view

### ISSUE THREAD

**Issue by wiertz** [nextcloud/deck#2481] opened 2020-10-27 11:35 UTC
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
In the modal view of a card, changing the status of a checkbox in the card description is not saved. After closing the modal, the status is returned to the previous state. Disabling the modal view and doing the same in the sidebar works fine.

**To Reproduce**
1. Activate modal card view
2. Click on a card that contains a checkbox in the description (or create one)
3. Click on the checkbox to change its state
4. Close the modal and reopen the card

**Expected behavior**
State should be saved on closing the modal.

**Client details:**
 - OS: OSX
 - Browser: Tested on Chrome and Safari
 - Version: latest
 - Device: MacBook Pro

<details>
<summary>Server details</summary>

**Operating system**:
Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64

**Web server:**
Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:**
mysql 10.4.14

**PHP version:**
7.3.22-1+ubuntu18.04.1+deb.sury.org+1

**Nextcloud version:** (see Nextcloud admin page)
19.0.4 - 19.0.4.2

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by jakobroehrl** [comment] 2020-10-28 08:33
duplicate of https://github.com/nextcloud/deck/issues/2351

**Closed by jakobroehrl** 2020-10-28 08:33 UTC
