### ISSUE TITLE
0.1.3 renamed to deck instead decks

### ISSUE THREAD

**Issue by dirigit** [nextcloud/deck#110] opened 2017-05-01 17:36 UTC
App update lost everything becuase of  renaming (directory changed from decks to deck, maybe db tables as well).

Now it's not possible to save new deck for me.

**Comment by juliushaertl** [comment] 2017-05-01 17:45
How have you installed the app update? There should be no change in directory/database table names.

**Comment by dirigit** [comment] 2017-05-02 04:43
I have been logged in yesterday, got message "update available" and updated it from apps management.

After encountering unworkable status I tried files from backup (directory "decks", message "update available" again) and manually uploaded new files. I saw the app two times than. Performing activation caused deletion of "decks".

In backup created when upgrading Nextcloud to 11.0.3 there is a directory "decks". In /apps/  I have "deck" now.

I'm sorry but, it's back to stage 0 for me.

**Comment by dirigit** [comment] 2017-05-02 05:09
Ooops, double checked it again, my error:

Directory in backup is "deck" as well. Must be another reason for not working.

**Comment by juliushaertl** [comment] 2017-05-02 07:09
So we can close this? :wink:

**Comment by juliushaertl** [comment] 2017-05-02 07:10
Ah renaming is not working, so you are missing the edit button in the left sidebar, right?

**Comment by dirigit** [comment] 2017-05-02 12:38
Sorry, doesn't work. No reason to close ... ;-)

1. I don't see previous created decks and stacks.
2. I see +-Button, use it to create a new deck, change app, come back to "Deck" -> no deck.
3. After "creation" of new deck, creating a stack is impossible. Otherwise: Goto 2.

**Comment by juliushaertl** [comment] 2017-05-02 13:02
@dirigit would it be possible to create a test account on your instance for me so i can see directly what is going wrong there?

**Comment by juliushaertl** [comment] 2017-05-02 14:14
It would also great if you could check the browser log/network tab if there is anything failing, as well as the nextcloud log.

**Comment by dirigit** [comment] 2017-05-02 14:30
Tested it now with new user in group everybody:
works, even after logout and re-login

admin account:
does not work

it's almost a test site only, an account wouldn't be a real problem. Must be admin than.

I can't see anything related in logs.

**Comment by juliushaertl** [comment] 2017-05-02 15:17
Hmm can you check the content of oc_deck_boards if the old boards are in there and what owner is assigned to them? It should be the uid of your admin account.

**Comment by dirigit** [comment] 2017-05-02 17:33
Checked it:

In #_deck_boards there are old and new decks as well.
#_deck_boards.owner is correct in each case.

In #_deck_stacks there are old and new stacks as well. IDs are correct.

**Comment by juliushaertl** [comment] 2017-05-04 06:43
@dirigit Can you mail me the test account data to the email in my github profile? Then I can take a look. Quite hard to debug, because I cannot reproduce and no errors :wink:

**Comment by juliushaertl** [comment] 2017-05-04 12:13
Fixed with #118

**Closed** 2017-05-04 12:17 UTC
Labels: 0. Needs triage, bug
