### ISSUE TITLE
Server error when accessing Nextcloud Deck on browser "cold" start

### ISSUE THREAD

**Issue by reind33r** [nextcloud/deck#3248] opened 2021-08-11 13:53 UTC
Hello!

In a new browser session, when accessing the Nextcloud instance for the first time with the Deck app, there is a server error. If I reload the page, without doing anything else, it shows up normally.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open a web browser ("cold" start, but your Nextcloud instance should "remember" you from a previous session)
2. Access /apps/deck

### Expected behaviour
The Deck app should show up normally.

### Actual behaviour
A server error happens. (I reproduced it with Firefox and the new Microsoft Edge, it's not browser-related)

It doesn't happen with other apps, such as dashboard, files or notes.

### Server configuration

**Operating system:** Debian

**Web server:** nginx

**Database:** mariadb  Ver 15.1 Distrib 10.6.3-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** PHP 7.4.22

**Nextcloud version:** Hostux Cloud 22.1.0 (but it has been happening through different updates)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Docker

**Signing status:** No errors have been found.

**List of activated apps:**
<details>
<summary>List of activated apps</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.1
  - circles: 22.1.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - deck: 1.5.0
  - drawio: 1.0.1
  - extract: 1.3.2
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - news: 16.0.1
  - nextcloud_announcements: 1.11.0
  - notes: 4.1.1
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - onlyoffice: 7.1.2
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.1
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - socialsharing_email: 2.2.0
  - spreed: 12.0.1
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.11.0
  - text: 3.3.0
  - theming: 1.12.0
  - theming_customcss: 1.9.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - user_external: 2.0.0
  - user_status: 1.1.1
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Nextcloud configuration:</summary>

```
{
    "system": {
        "default_phone_region": "FR",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.hostux.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.1.0.1",
        "overwrite.cli.url": "https:\/\/cloud.hostux.fr",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "imap.hostux.fr",
                    993,
                    "ssl",
                    "hostux.fr"
                ]
            }
        ],
        "maintenance": false,
        "loglevel": 0,
        "theme": "",
        "onlyoffice": {
            "DocumentServerUrl": "\/ds-vpath\/",
            "DocumentServerInternalUrl": "http:\/\/hostux_cloud_onlyoffice",
            "StorageUrl": "http:\/\/hostux_nginx",
            "allow_local_remote_servers": "true"
        },
        "allow_local_remote_servers": "true",
        "app_install_overwrite": [
            "user_external",
            "richdocuments",
            "drawio",
            "onlyoffice",
            "quicknotes",
            "socialsharing_email",
            "bruteforcesettings"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP through External user authentication (nextcloud/user_external)

### Client configuration
**Browser:** Firefox, reproduced with Microsoft Edge

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
IP_ADDRESS_REMOVED - - [11/Aug/2021:13:20:25 +0000] "GET /apps/deck HTTP/1.1" 500 4731 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{
  "reqId": "9YsqHFaDQKgbBIMUVWnr",
  "level": 3,
  "time": "2021-08-11T13:20:25+00:00",
  "remoteAddr": "__MY_IP_REDACTED__",
  "user": "__MY_USERNAME_REDACTED__",
  "app": "index",
  "method": "GET",
  "url": "/apps/deck",
  "message": "Argument 1 passed to OC\\Group\\Manager::getUserIdGroupIds() must be of the type string, null given, called in /var/www/html/lib/private/Group/Manager.php on line 316",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0",
  "version": "22.1.0.1",
  "exception": {
    "Exception": "Exception",
    "Message": "Argument 1 passed to OC\\Group\\Manager::getUserIdGroupIds() must be of the type string, null given, called in /var/www/html/lib/private/Group/Manager.php on line 316",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/lib/private/AppFramework/App.php",
        "line": 156,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Deck\\Controller\\PageController"
          },
          "index"
        ]
      },
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 301,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Deck\\Controller\\PageController",
          "index",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "_route": "deck.page.index"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/base.php",
        "line": 1000,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/apps/deck"
        ]
      },
      {
        "file": "/var/www/html/index.php",
        "line": 36,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
    "Line": 158,
    "Previous": {
      "Exception": "TypeError",
      "Message": "Argument 1 passed to OC\\Group\\Manager::getUserIdGroupIds() must be of the type string, null given, called in /var/www/html/lib/private/Group/Manager.php on line 316",
      "Code": 0,
      "Trace": [
        {
          "file": "/var/www/html/lib/private/Group/Manager.php",
          "line": 316,
          "function": "getUserIdGroupIds",
          "class": "OC\\Group\\Manager",
          "type": "->",
          "args": [
            null
          ]
        },
        {
          "file": "/var/www/html/lib/private/Group/Manager.php",
          "line": 305,
          "function": "isInGroup",
          "class": "OC\\Group\\Manager",
          "type": "->",
          "args": [
            null,
            "admin"
          ]
        },
        {
          "file": "/var/www/html/custom_apps/deck/lib/Service/ConfigService.php",
          "line": 62,
          "function": "isAdmin",
          "class": "OC\\Group\\Manager",
          "type": "->",
          "args": [
            null
          ]
        },
        {
          "file": "/var/www/html/custom_apps/deck/lib/Controller/PageController.php",
          "line": 70,
          "function": "getAll",
          "class": "OCA\\Deck\\Service\\ConfigService",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 217,
          "function": "index",
          "class": "OCA\\Deck\\Controller\\PageController",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 126,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            {
              "__class__": "OCA\\Deck\\Controller\\PageController"
            },
            "index"
          ]
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/App.php",
          "line": 156,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            {
              "__class__": "OCA\\Deck\\Controller\\PageController"
            },
            "index"
          ]
        },
        {
          "file": "/var/www/html/lib/private/Route/Router.php",
          "line": 301,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::",
          "args": [
            "OCA\\Deck\\Controller\\PageController",
            "index",
            {
              "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
            },
            {
              "_route": "deck.page.index"
            }
          ]
        },
        {
          "file": "/var/www/html/lib/base.php",
          "line": 1000,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->",
          "args": [
            "/apps/deck"
          ]
        },
        {
          "file": "/var/www/html/index.php",
          "line": 36,
          "function": "handleRequest",
          "class": "OC",
          "type": "::",
          "args": []
        }
      ],
      "File": "/var/www/html/lib/private/Group/Manager.php",
      "Line": 333
    },
    "CustomMessage": "--"
  },
  "id": "6113cec292fea"
}
```
</details>

PS: this is my first bug report, I tried to do things "the right way" and follow the template but let me know if I should do something differently ;)

**Comment by neerro** [comment] 2021-08-11 16:47
Confirming this issue!
The same situation for me. When I tried to get "cold" (non cached) access to the instance, I've got the error.
`Internar server error`
When I disabled Server Deck app everything is works fine.

It was happened after the Nextcloud have been updated from 21.0.3 to 22.1.0
Deck app version 1.5.0

**Comment by juliushaertl** [comment] 2021-08-19 15:43
I could reproduce the issue by deleting the session cookies manually. 

Some findings though this needs further thinking on if that can be fixed easily in deck or if a server fix would be more suitable.

Deck stated the dav type in info.xml which leads to it being loaded with the filesystem type apps for registering its sabre plugins early in base.php where right before the user session would be set up. 

https://github.com/nextcloud/server/blob/b78f3a57d1d05fb5f81ec8361139b64a3e54d7b0/lib/base.php#L989-L990

Now as far as I see filesystem apps should not be needed for the handleLogin call so it might be an option to just drop the filesystem typed app loading as that is kind of duplicate with later on code anyways in https://github.com/nextcloud/server/blob/b78f3a57d1d05fb5f81ec8361139b64a3e54d7b0/lib/base.php#L996-L997

The ConfigService (which pulls in IUserSession early) is injected in the sharing listener which then basically adds the not setup user session to the container, so an option could also be to not assign it in the constructor https://github.com/nextcloud/deck/blob/b26caaa6e5828cdf50302947467ff770a23200e4/lib/Service/ConfigService.php#L53 but rather at the time it is actually needed in the ConfigService methods.

**Comment by juliushaertl** [comment] 2021-08-19 16:13
Did a bit of a rework of the base.php part in https://github.com/nextcloud/server/pull/28521 though I'll still see to get a fix for deck itself, since the base.php change is probably more a technical dept change rather than a bugfix.

**Closed** 2021-08-20 16:01 UTC
