### ISSUE TITLE
Comments don't keep Shift+Enter line return once saved

### ISSUE THREAD

**Issue by Firerazer** [nextcloud/deck#2066] opened 2020-06-24 15:48 UTC
**Describe the bug**
The tool allow Shift+Enter line return to allow users to have clearer messages, but once the comment is saved, the message is posted without the line breaks.

**To Reproduce**
1. Go to 'Comments' into any card from any deck
2. Enter a message with line breaks
3. Send the message
4. See your beautiful test message without line breaks

**Expected behavior**
The line break/return should stay in the comment as entered by the user.

**Screenshots**
https://nextcloud.red-circuit.org/s/mTfzHDYWWXogooR

**Client details:**
 - OS: Win10
 - Browser Chrome
 - Version last version
 - Device: desktop

Note: I am not a programmer nor a developer, so I cannot provide any detailed information about the server. If this is really needed because anyone else can reproduce, then I will ask my overwhelmed dev to provide me the requested details
-- Nextcloud version: 19.0.0
-- All apps up to date

**Comment by Scumi** [comment] 2020-11-16 11:48
I have two Nextcloud instances with NC 20, both with Deck 1.2.0-beta1. 
I also tried to store comments with line breaks. Here are my observations:
- The comments are not visible at all in the Browser after submitting. I just see the name of the submitter and nothing else. 
- The comments however do show up on the timeline (although unformatted without line breaks).
- When I open the card in the [https://github.com/stefan-niedermann/nextcloud-deck](Nextcloud Deck Android app), they show up correctly formatted with line breaks in its comment view.

Comments without any line breaks are stored and displayed correctly all the times.

**Comment by juliushaertl** [comment] 2020-11-19 08:11
Seems to be a regression of the vue-richtext bump #2510 

I can reproduce this with a newline in https://juliushaertl-vue-richtext.netlify.app/link.html

**Comment by juliushaertl** [comment] 2020-11-19 10:48
Fix proposed in the library at https://github.com/juliushaertl/vue-richtext/pull/286#issuecomment-730288103

**Comment by juliushaertl** [comment] 2021-06-17 14:05
This is actually working as expected now with the latest releases as the library update has been merged already :)

**Closed by juliushaertl** 2021-06-17 14:05 UTC
Labels: 2. developing, bug, feature: comments

**Comment by ronau** [comment] 2023-11-25 20:03
Hi there!
What do you mean by "works as expected"? Comments are not supposed to contain line breaks?

Because I also noticed this behaviour and I find it quite annoying. From my point of view, it definitely should be possible to use line breaks in the comments.

However, on NC 27.1.4 and with the latest version of Deck (v1.11.1), line breaks are still not shown properly.

Actually, they are sent properly to the backend (with "\n" for the line breaks) and they are retrieved from the API properly as well. It's just that they are not converted to proper HTML line breaks when rendering them to the page's HTML.

I'd love to see this fixed. Any idea what needs to be changed here?

<img width="912" alt="SCR-20231125-sauk" src="https://github.com/nextcloud/deck/assets/5237327/83adce3b-8523-4f18-a5da-be9cfdca78a0">
<img width="909" alt="SCR-20231125-sbag" src="https://github.com/nextcloud/deck/assets/5237327/01f4f117-9fbd-4757-a996-01d490a047b0">
<img width="1445" alt="SCR-20231125-seno" src="https://github.com/nextcloud/deck/assets/5237327/7372cdc9-7f45-4b1d-839b-86a78e014c58">
<img width="1439" alt="SCR-20231125-sexh" src="https://github.com/nextcloud/deck/assets/5237327/beee191c-baa4-4fe8-8df2-c5f16c931de2">
<img width="1440" alt="SCR-20231125-sfdj" src="https://github.com/nextcloud/deck/assets/5237327/2c15e356-9f57-4b32-961f-da1e5c361881">
