### ISSUE TITLE
attachments from Nextcloud account's own file directory

### ISSUE THREAD

**Issue by osm-frasch** [nextcloud/deck#2572] opened 2020-11-17 14:25 UTC
A) 
It would be great if you can not only upload attachments from your own operating system but also **attach them directly from your Nextcloud account's own file directory**.  In fact, I find this very important!

B) 
Another useful addition would be to **display photos as file attachments** in the respective cards **as clickable thumbnails**. 

Both features would be especially useful for project management within Nextcloud. 
![Screenshot_20201117_150429](https://user-images.githubusercontent.com/63851138/99402265-7035d800-28e9-11eb-81f3-5f30fb97efd8.png)

**Comment by stefan-niedermann** [comment] 2020-11-17 14:30
Please use the search function before opening new issues.

Closing as duplicate of https://github.com/nextcloud/deck/issues/564 and https://github.com/nextcloud/deck/issues/972 (depending on https://github.com/nextcloud/deck/issues/2273).

**Closed by stefan-niedermann** 2020-11-17 14:30 UTC

**Comment by osm-frasch** [comment] 2020-11-17 14:44
Ups, sorry
