### ISSUE TITLE
Card title is not saved if field is left via mouse click

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#1958] opened 2020-05-25 17:20 UTC
**Describe the bug**
Deck v1.0.1

If you click the card's title and change it, but then just click outside the title, it does not save the change. You need to either click on the arrow or press enter.

file renames in nextcloud work if you click somewhere else to leave the field.

**To Reproduce**
1. Click at a title
2. edit the title
3. click somewhere else
4. title is not saved

**Expected behavior**

The behaviour should IMO be the same as when renaming files, i.e. the title should be saved if clicked away.

**Comment by juliushaertl** [comment] 2020-06-03 10:37
Duplicate of https://github.com/nextcloud/deck/issues/1927

**Closed by juliushaertl** 2020-06-03 10:37 UTC

**Comment by reox** [comment] 2020-06-03 11:22
@jancborchardt looks like it wasn't another issue after all :sweat_smile:
