### ISSUE TITLE
Update from 1.11.1 to 1.11.2 not possible

### ISSUE THREAD

**Issue by bcutter** [nextcloud/deck#5335] opened 2023-11-29 21:19 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Update to latest 1.11.2 fails

**To Reproduce**
1. Install 1.11.1
2. Try updating to 1.11.2
3. See short error message (nothing in logs)

**Expected behavior**
Update is successful

**Screenshots**
![grafik](https://github.com/nextcloud/deck/assets/13799156/d14afc35-8884-482c-a536-d7755974bf93)

**Client details:**
 - OS: Windows
 - Browser: Firefox
 - Version: latest
 - Device: Desktop

<details>
<summary>Server details</summary>

**Operating system**: Raspberry Pi OS

**Web server:** nginx

**Database:** MariaDB

**PHP version:** 8.2.13

**Nextcloud version:** 27.1.4

**Where did you install Nextcloud from:** bare metal

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** No

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

Holy moly, never seen an issue template asking for SO many details. Horrible :-)

**Comment by bcutter** [comment] 2023-11-29 21:28
Ah, well... I think I found the root cause. Same in nextloud.log when trying to install another app (e. g. Issue Template):

`OCP\Http\Client\LocalServerException: No DNS record found for github.com`

Strange - and pretty sure not related to this app (Deck) at all.

**Comment by juliushaertl** [comment] 2023-11-29 21:32
Yes that looks like an error fetching the archive unrealted to deck itself. You may want to check your servers connectivtity to github to download the relase package from there.

> Holy moly, never seen an issue template asking for SO many details. Horrible :-)

Well, it helps a lot to have as much information as possible to be able to reproduce and figure out issues. I don't think there is anything irrelevant  in there.

Let me close this then since it is not a deck issue. For help with debugging best check back at help.nextcloud.com

**Closed by juliushaertl** 2023-11-29 21:32 UTC
