### ISSUE TITLE
New feature idea: Reminder date linked to notification

### ISSUE THREAD

**Issue by albertgr95** [nextcloud/deck#6615] opened 2024-12-18 11:09 UTC
**Is your feature request related to a problem? Please describe.**
I use cards for long term planning of tasks and with external partners. With this approach, the date that could be put in a card could be the start date, a reminder date, and the due date. This would avoid the current limitation of having just a due date, and with, it just one notification via email.

**Describe the solution you'd like**
I would like to be able to put a reminder date (the start one could be assumed to be the date in which the card is created, although it would also be good to have a specific field) linked to notifications via email. This would be a good feature for automation of project management, saving a lot of time in reminder emails, especially with boards shared with other users who may not be using the decks regularly.

**Describe alternatives you've considered**
I could use calendar tasks on other apps, but the kanban view is very useful if users get familiar with it, and is a good tool to centralise all the tasks and their owners. Another alternative that I currently use is creating several cards for one single task, but this duplicity is not very comfortable and could be avoided.

**Additional context**
Here an example of how it could look like:
![Image](https://github.com/user-attachments/assets/6dc694b6-84af-4495-b211-2b40daecb978)

**Comment by stefan-niedermann** [comment] 2024-12-18 11:51
Closing as duplicate of https://github.com/nextcloud/deck/issues/1549

**Closed by stefan-niedermann** 2024-12-18 11:51 UTC
