### ISSUE TITLE
Board still on start page although deleted

### ISSUE THREAD

**Issue by aktivde** [nextcloud/deck#1885] opened 2020-05-14 07:40 UTC
I deleted a board that was shared with a group. For all the group members the board got deleted and it doesn't appear in my sidebar either. However, on the main page of deck (in my account) it remains active. I can click on it and add new cards and whatever I like. On the other hand – as it doesn't appear in the sidebar anymore – there is no option to delete it again or change its name or colour.

I tried to reproduce the bug with another shared board, however that disappeared instantly. I don't know if they were different somehow.

**Comment by jakobroehrl** [comment] 2020-05-14 07:44
Duplicate of https://github.com/nextcloud/deck/issues/1806

**Closed by jakobroehrl** 2020-05-14 07:44 UTC
