### ISSUE TITLE
Mobile view of Deck not working

### ISSUE THREAD

**Issue by evs-cp** [nextcloud/deck#610] opened 2018-09-06 08:10 UTC
**Description of the problem**
When using docker in mobile view, the cards aren't clickable anymore. If tapped/clicked, they wont react and nothing happens. Happens to be one of the newest versions, was upgraded only one or two weeks ago.

**To Reproduce**
1. Go to 'Deck'
2. resize your browser to fit on a normal phone screen, cards should now be in a row
3. Now click on any given card, and nothing should happen

**Expected behavior**
Normally, the card should open, so i can see what is writen in the card

**Client details:**
* Google Pixel, current Chrome
* Arch Linux, current Firefox

**Operating system**:

**Web server:**
nginx 1.13.9
**PHP version:**
7.1.17
**Nextcloud version:** (see Nextcloud admin page)
13.x (no admin)
**Where did you install Nextcloud from:**
official docker example

When our admin arrives, maybe he can give some more information

**Comment by laurentiu2** [comment] 2018-09-07 07:59
Can confirm that. NC 13.0.6, Chrome on Android. Didn't notice before..

**Comment by juliushaertl** [comment] 2018-10-09 12:57
Closing as a duplicate of #575

**Closed by juliushaertl** 2018-10-09 12:57 UTC
