### ISSUE TITLE
Boards are not showing up after upgrade

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/deck#115] opened 2017-05-02 08:27 UTC
### Steps to reproduce
1.Upgrade to latest Deck

### Expected behaviour
All of my existing kanbans should be available and work as usual 

### Actual behaviour
All Kanbans are gone

### Server configuration
**Operating system**: Linux server-us05.server.plus 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 10.1.22

**PHP version:** 5.6.30
Modules loaded: Core, date, ereg, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, memcache, exif, mcrypt, mysqlnd, mysql, mysqli, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, SimpleXML, soap, sockets, sqlite3, tokenizer, xml, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, mhash, ionCube Loader, Zend Guard Loader, Zend OPcache

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors have been found.
```

**List of activated apps:**

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - activitylog: 0.0.1
 - admin_audit: 1.1.0
 - admin_notifications: 1.0.0
 - announcementcenter: 3.0.0
 - calendar: 1.5.2
 - comments: 1.1.0
 - contacts: 1.5.3
 - dav: 1.1.1
 - deck: 0.1.3
 - external: 1
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_accesscontrol: 1.1.2
 - files_automatedtagging: 1.1.1
 - files_downloadactivity: 1.0.1
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notes: 2.2.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - rainloop: 4.28.1
 - richdocuments: 1.1.25
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - spreed: 1.2.0
 - systemtags: 1.1.3
 - tasks: 0.9.5
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - encryption
 - files_external
 - files_markdown
 - files_retention
 - survey_client
 - user_external
 - user_ldap
 - user_saml
```
</details>

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

**Comment by juliushaertl** [comment] 2017-05-02 08:33
Are there any entries in your logfiles (nextcloud/browser)? Can you check manually if those boards sill exist in the mysql table oc_deck_boards ?

**Comment by aproposnix** [comment] 2017-05-02 09:40
I haven't been able to check (too busy at the moment).... however, what I found was that if I manually enter in the Deck # in the URL it will appear - so apparently they are still in the DB.

**Comment by juliushaertl** [comment] 2017-05-02 09:43
@aproposnix Ok, so there might be an issue with the javascript part. Would be great if you could check the browser console for errors if you have some time.

**Comment by aproposnix** [comment] 2017-05-02 09:51
![selection_012](https://cloud.githubusercontent.com/assets/6204273/25613132/6c89f4e8-2f2d-11e7-998a-4f872db12237.png)

Yeah, I see some error there.  See attached screen. I get this when I click on the deck link in the menu.

**Comment by juliushaertl** [comment] 2017-05-02 10:44
Might be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1336076

@aproposnix Would it be possible to get a test account on your instance to find the issue? I cannot reproduce this on my setups.

**Comment by aproposnix** [comment] 2017-05-02 13:44
Just for Clarification - this isn't just about Firefox - the same behavior can be seen in Chrome. 

I'm not sure how giving you a test account on the server will be useful. I mean, it requires an upgrade with existing decks (which I already did).  PM me for the credentials if you really need it.

**Comment by juliushaertl** [comment] 2017-05-02 14:09
Ok, it seems there is something wrong on the backend side. Then a test account won't help much. Any errors in your nextcloud log.

**Comment by aproposnix** [comment] 2017-05-03 09:43
Yeah, I'm getting tons of errors: 

![selection_014](https://cloud.githubusercontent.com/assets/6204273/25655564/9656b75c-2ff5-11e7-850d-c981ab8fb16b.png)

**Comment by Aesculapius** [comment] 2017-05-03 10:21
Same problem over here, all boards have disappeared!

![image](https://cloud.githubusercontent.com/assets/617061/25656815/0db94d0a-2ffb-11e7-983a-2c5065dfced8.png)

**Comment by aproposnix** [comment] 2017-05-04 05:15
based on issue #118 I downloaded and installed https://bitgrid.net/~jus/deck_0.1.3.1-fix-a6b6842.tar.gz
This did not fix the issue.  I still do not see the kanbans.

**Comment by juliushaertl** [comment] 2017-05-04 06:03
@aproposnix Anything new in the logs?

**Comment by aproposnix** [comment] 2017-05-04 08:51
@juliushaertl 

Yeah, it seems the errors aren't as many this time and they are different: 

![selection_016](https://cloud.githubusercontent.com/assets/6204273/25696445/81f0003a-30b7-11e7-801b-d42c932d98bd.png)

**Comment by juliushaertl** [comment] 2017-05-04 09:31
@aproposnix Thanks for the logs. Here is another test build: https://bitgrid.net/~jus/deck_0.1.3.1-fix-860cbab.tar.gz

**Comment by aproposnix** [comment] 2017-05-04 09:45
@juliushaertl With this version, I still do not see the kanbans BUT now when I manually open the board, I can move the cards from one column to another (could not do that in the previous build). 

![selection_017](https://cloud.githubusercontent.com/assets/6204273/25698419/0d8aeec8-30bf-11e7-92f6-bd10777425b7.png)

**Comment by juliushaertl** [comment] 2017-05-04 10:12
@aproposnix And another fix added. Group sharing was broken due to wrong documentation in Nextcloud. https://bitgrid.net/~jus/deck_0.1.3.1-fix-12ebffb.tar.gz

**Comment by aproposnix** [comment] 2017-05-04 10:44
You are making progress :) I can now see ALL kanbans (including previously deleted kanbans!). I cannot delete any of them now (clicking on the trash icon doesn't do anything). 

![selection_019](https://cloud.githubusercontent.com/assets/6204273/25700247/1a7dcc7e-30c7-11e7-9dd0-cf949248720d.png)




![selection_018](https://cloud.githubusercontent.com/assets/6204273/25700266/3650c5d2-30c7-11e7-9108-d679d1f6d722.png)

**Comment by juliushaertl** [comment] 2017-05-04 10:48
@aproposnix Deleting is a different issue which has already been solved in #113 

So with the latest patch the error should not occur anymore. Looks like it worked from the timestamps of your logfile. 

@Aesculapius @dirigit Mind testing https://bitgrid.net/~jus/deck_0.1.3.1-fix-12ebffb.tar.gz as well? Would be great to have your feedback as well.

**Comment by dirigit** [comment] 2017-05-04 11:43
Hi,

performed a short test of fix-12ebffb:

Decks are visible and creatable, stacks as well.

Deletion of stacks works.

Deletion of decks does not work.

thank you so far ;)

**Comment by juliushaertl** [comment] 2017-05-04 12:12
Fixed with #118

**Closed by juliushaertl** 2017-05-04 12:12 UTC
Labels: 0. Needs triage, bug

**Comment by juliushaertl** [comment] 2017-05-04 12:20
Thanks everyone for reporting and helping to fix it. :+1:

**Comment by Aesculapius** [comment] 2017-05-04 17:05
Unfortunately don't have time atm to test but I trust the other guys with their conclusions and will wait for the next version update. Thanks.

**Comment by JSoko** [comment] 2017-05-04 17:12
1.4 works here as it should :-)

First loading after upate to 1.4 showed an error and no decks. 1st reload fixed that.
![deck1 4](https://cloud.githubusercontent.com/assets/5583290/25715930/91527f1c-30fd-11e7-9d79-c816d82d69cb.jpg)
