### ISSUE TITLE
share via public link

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/deck#3581] opened 2022-02-09 09:54 UTC
Add the function to share boards and cards via public link.

**Comment by stefan-niedermann** [comment] 2022-02-09 09:58
Please use the 🔍  search function before opening new issues. "[public link](https://github.com/nextcloud/deck/issues?q=is%3Aissue+is%3Aopen+public+link)" had only four results. Closing as duplicate of https://github.com/nextcloud/deck/issues/14

**Closed by stefan-niedermann** 2022-02-09 09:58 UTC
