### ISSUE TITLE
Priority tag missing

### ISSUE THREAD

**Issue by vantino** [nextcloud/deck#2908] opened 2021-03-23 11:31 UTC
We like it and we use it regularily.

However, we're missing kind of a priority tag. We simulate it by defining PRIO HIgh, PRIO Medium, PRIO Low keywords. But that's only a workaround. We'ld prefer a new and separate item defined in the deck details.

THanks

**Comment by stefan-niedermann** [comment] 2021-03-23 11:38
Duplicate of https://github.com/nextcloud/deck/issues/421#issuecomment-368842848

I don't see the benefit of splitting them into a separate field. After all you can already easily filter for them.

I therefore propose to close this in favor of [user defined fields](https://github.com/nextcloud/deck/issues/1833) which will also cover this use case.

**Closed** 2021-04-08 07:44 UTC
