### ISSUE TITLE
Adding a markdown (link, etc.) feature to the comments block

### ISSUE THREAD

**Issue by neerro** [nextcloud/deck#2905] opened 2021-03-22 09:34 UTC
Please add a possibility to use a full markdown features in comments block as link, etc.

![pic](https://user-images.githubusercontent.com/75830569/111969122-f6b62c80-8b0a-11eb-9e53-ac3bfe219934.jpg)

**Comment by stefan-niedermann** [comment] 2021-03-24 12:49
I am not entirely sure, but i think the comments section is reused from the nextcloud core packages, so fixing this would require to fix this in the nextcloud core. There is already [an open issue](https://github.com/nextcloud/server/issues/17375) which tracks this feature request.

But let's wait for @jakobroehrl or @juliushaertl to approve that this must be fixed over there before closing.

**Comment by juliushaertl** [comment] 2021-04-14 16:16
Yep, I would only do this globally so whenever this becomes available in server we should make sure this then applies to all apps that provide comments so closing as a duplicate of https://github.com/nextcloud/deck/issues/2143#issuecomment-676662256

**Closed by juliushaertl** 2021-04-14 16:16 UTC
