### ISSUE TITLE
Activity notifications too verbose and HTML tags are displayed to users

### ISSUE THREAD

**Issue by lars-becker** [nextcloud/deck#1984] opened 2020-06-04 21:32 UTC
Activity notifications in the activity app are too verbose. Changes in long descriptions lead to very long activity notifications. Also they are quite unreadable since HTML tags aren't rendered and are displayed as is to users.

1. Chance the description of one actitivy
2. go to the activities app
3. changes to descriptions are long and not rendered correctly

**Screenshots**
Tried to upload one, but wasn't possible.

**Nextcloud version:** 19 and Deck 1.0.2

**Comment by juliushaertl** [comment] 2020-06-05 08:40
Yes, we need to find a proper way to display those a bit less extensive and without any HTML annotations, since that is no longer supported by the activity app. 

Closing as a duplicate of https://github.com/nextcloud/deck/issues/1557, but I adjusted the title there to actually cover the verbosity as well.

**Closed by juliushaertl** 2020-06-05 08:40 UTC
