### ISSUE TITLE
limit Deck to groups did not list all groups

### ISSUE THREAD

**Issue by admtkr** [nextcloud/deck#5169] opened 2023-09-29 13:39 UTC
I'm using nextcloud 27.0.2 and added Deck version 1.11.0
If i want to limit the app access to some user gropus, i just see a list of 5 groups in the pull-down list, but i have 11 groups at all.
Just type in a group not listed at the pull-down list is not accepted.

**Comment by joshtrichards** [comment] 2024-10-02 15:21
Duplicate of nextcloud/server#39322 and/or nextcloud/server#46634

**Closed by joshtrichards** 2024-10-02 15:21 UTC
Labels: bug
