### ISSUE TITLE
Integration of Deck in the Nextcloud notification system

### ISSUE THREAD

**Issue by HonkXL** [nextcloud/deck#574] opened 2018-08-07 09:33 UTC
**Is your feature request related to a problem? Please describe.**
When a other user creates a new deck and share this deck with me, I get a notification inside Nextcloud, but it is not shown in the activity stream. The creation or change of cards is not viewable in the stream. 

**Describe the solution you'd like**
I would prefer that Deck puts all changes of decks and cards to the activity stream. So the user can decide to get notifications by stream or by mails sent over the notification system of Nextcloud. This would improve collaborative work on Decks very much.

**Describe alternatives you've considered**
Maybe an own notification system in Deck, but it is better to use the integrated one

**Additional context**
none.

**Comment by juliushaertl** [comment] 2018-08-18 08:47
Duplicate of #211

**Closed by juliushaertl** 2018-08-18 08:47 UTC
