### ISSUE TITLE
Add two more icon to describing the context of the task

### ISSUE THREAD

**Issue by vix95** [nextcloud/deck#1932] opened 2020-05-19 21:37 UTC
I'm not sure that the feature request is already created, I didn't catch it. I have a problem to identify the task that it contains the description. I think it would be nice if the information will be shown as attachments is. I mean, something like that on below screenshot.

![image](https://user-images.githubusercontent.com/38139321/82380385-a96bb900-9a28-11ea-9ec6-6433f9a56776.png)

The order at the developer's discretion, can by any. Anyway I've noticed a bug related with the discussion icon. I've created another issue for that.

Why I really need this? Because as I earlier mentioned, I have a problem to identify the task with context. I wouldn't click every tasks/notes to check that contains some new discussion or contains description.

I think the description (note) icon should be a little separated from other because the icon doesn't have quantity - it's only TRUE (contains) or FALSE (not contains). Hope that it's clear what I think.

**Comment by juliushaertl** [comment] 2020-05-20 08:33
duplicate of https://github.com/nextcloud/deck/issues/1873

**Closed by juliushaertl** 2020-05-20 08:33 UTC
