### ISSUE TITLE
cannot append files to cards [nextcloud 21]

### ISSUE THREAD

**Issue by t1nux** [nextcloud/deck#2856] opened 2021-03-05 10:01 UTC
**Describe the bug**
Attaching a file to a card does not work.

**To Reproduce**
1. select a card
2. click "Upload new files"
3. select file and click ok
4. no file is uploaded and the following message is shown

`fclose(): supplied resource is not a valid stream resource`

**Expected behavior**
- no error message
- file is actually uploaded

**Screenshots**
![image](https://user-images.githubusercontent.com/4058407/110099172-4a054c80-7da1-11eb-8d46-092f25dbdc14.png)

**log**
```
{"reqId":"XuQTV8hz674zLaLPBDNo","level":3,"time":"2021-03-05T09:24:26+00:00","remoteAddr":"134.147.20.210","user":"tinux","app":"deck","method":"POST","url":"/apps/deck/cards/1685/attachment","message":{"Exception":"Exception","Message":"fclose(): supplied resource is not a valid stream resource","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/share/webapps/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":159,"Previous":{"Exception":"TypeError","Message":"fclose(): supplied resource is not a valid stream resource","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/apps/deck/lib/Service/FilesAppService.php","line":187,"function":"fclose"},{"file":"/usr/share/webapps/nextcloud/apps/deck/lib/Service/AttachmentService.php","line":199,"function":"create","class":"OCA\\Deck\\Service\\FilesAppService","type":"->"},{"file":"/usr/share/webapps/nextcloud/apps/deck/lib/Controller/AttachmentController.php","line":71,"function":"create","class":"OCA\\Deck\\Service\\AttachmentService","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"create","class":"OCA\\Deck\\Controller\\AttachmentController","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/share/webapps/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/share/webapps/nextcloud/apps/deck/lib/Service/FilesAppService.php","Line":187},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0","version":"21.0.0.18"}
```

**details:**
 - OS: arch linux kernel 5.11.2
 - webserver: nginx 1.18.0
 - php: 8.0.3
 - NC-Version: 21
 - Deck-Version: 1.3.0

**Comment by juliushaertl** [comment] 2021-03-05 12:37
I cannot reproduce that, but maybe the resource got already closed somewhere in the server filesystem code. are you using a regular filesystem or s3 as a primary storage maybe? Could you share the output of occ config:list ?

**Comment by t1nux** [comment] 2021-03-05 13:15
@juliushaertl Thanks for looking into this.

 I am using a normal filesystem, BTRFS to be exact. The output you asked for is [here](https://github.com/t1nux/pastbin/blob/master/nc_config).

**Comment by juliushaertl** [comment] 2021-03-05 13:33
Possible fix is in https://github.com/nextcloud/deck/pull/2857 Testing is very welcome :)

**Comment by t1nux** [comment] 2021-03-05 17:19
That's it, I just commented out `fclose($content);` and it's working again. Thank you!

**Closed** 2021-03-08 09:25 UTC
