### ISSUE TITLE
Sharing boards with other users

### ISSUE THREAD

**Issue by lepidas** [nextcloud/deck#29] opened 2017-02-03 10:31 UTC
As an option is available but not working though. It can find my NC members but when I press on a member name it's not sharing anything. NC server 11

**Comment by juliushaertl** [comment] 2017-02-03 12:02
Are there any errors in the server/browser log when you try add a new member?

**Comment by lepidas** [comment] 2017-02-03 16:13
NC server errors:
`Error	index	Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_deck_board_acl`(`board_id`,`type`,`participant`,`permission_edit`,`permission_share`,`permission_manage`) VALUES(?,?,?,?,?,?)' with params [1, "user", "anastasia", null, null, null]: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'user' for column 'type' at row 1`

`Debug	deck	DeckMapper SQL: INSERT INTO `*PREFIX*deck_board_acl`(`board_id`,`type`,`participant`,`permission_edit`,`permission_share`,`permission_manage`) VALUES(?,?,?,?,?,?) with 1|user|anastasia|||`

`Debug	deck	DeckMapper SQL: SELECT id, title, owner, color, archived FROM `*PREFIX*deck_boards` WHERE `id` = ? with 1`

**Comment by juliushaertl** [comment] 2017-02-03 17:40
Ah found the mistake. Fix is in #33. Thanks for reporting @lepidas, would be great if you could test if the fix works for you.

**Comment by lepidas** [comment] 2017-02-05 10:16
Well sort of working. I changed the 2 files, now it's available to "share" boards with other users but its problem with permissions (share/edit/manage) tickable, it's not persistent, I check "Manage" for example, refresh page and then its unchecked. And one more is if I share a board to X user then not possible to remove X user from the share.
Logs:
When I press the bin to remove a user from a share
`DeckMapper SQL: SELECT id, title, owner, color, archived FROM `*PREFIX*deck_boards` WHERE `id` = ? with 21`

When I check a permission to the shared user through the tick boxes
`DeckMapper SQL: SELECT id, title, owner, color, archived FROM `*PREFIX*deck_boards` WHERE `id` = ? with 21`

**Comment by lepidas** [comment] 2017-02-05 10:47
and this is from the browser log when I check the permissions boxes
`Possibly unhandled rejection: Error updating ACL [object Object]  angular.min.js:122:8
	f/< https://nextcloud.georgios-voulgarakis.info/apps/deck/js/vendor/angular/angular.min.js:122:8
	uf/this.$get</< https://nextcloud.georgios-voulgarakis.info/apps/deck/js/vendor/angular/angular.min.js:94:42
	g https://nextcloud.georgios-voulgarakis.info/apps/deck/js/vendor/angular/angular.min.js:133:147
	Hf/this.$get</m.prototype.$eval https://nextcloud.georgios-voulgarakis.info/apps/deck/js/vendor/angular/angular.min.js:147:309
	Hf/this.$get</m.prototype.$digest https://nextcloud.georgios-voulgarakis.info/apps/deck/js/vendor/angular/angular.min.js:144:412
	Hf/this.$get</m.prototype.$apply https://nextcloud.georgios-voulgarakis.info/apps/deck/js/vendor/angular/angular.min.js:148:76
	l https://nextcloud.georgios-voulgarakis.info/apps/deck/js/vendor/angular/angular.min.js:101:87
	rg/</t.onload https://nextcloud.georgios-voulgarakis.info/apps/deck/js/vendor/angular/angular.min.js:106:489`

**Comment by juliushaertl** [comment] 2017-02-06 09:19
@lepidas Ok, I've added another commit here: https://github.com/juliushaertl/deck/pull/33/commits/f604f2f7799b028bbfa874afe818b374e0723a29 There were some leftovers.

**Comment by lepidas** [comment] 2017-02-06 14:01
Still is not working.The logs have been changed to
`DeckMapper SQL: SELECT id, title, owner, color, archived FROMPREFIXdeck_boardsWHEREid= ? with 21`
Can someone confirm that is working? maybe is something with my setup

**Comment by juliushaertl** [comment] 2017-02-06 14:10
Those SQL log messages are fine, they just query for the board to check if you are the owner. I've removed the debug messages in https://github.com/juliushaertl/deck/pull/38.

Are there any error messages in the logfiles except for the "DeckMapper SQL" debugging output? What database backend are you using.

**Comment by lepidas** [comment] 2017-02-06 14:55
it's using mysql , no other logs except debugging.

**Comment by juliushaertl** [comment] 2017-02-06 23:37
Moving to 0.1.2, can you verify that the issue still existis in 0.1.1? 

Can you check the network tab of your browsers dev tools if there are details about the failing request after clicking the checkbox?

**Comment by lepidas** [comment] 2017-02-07 17:34
This is from browser dev tools when I check any box
{"status":403,"message":"Permission denied"}

**Comment by joergmschulz** [comment] 2017-02-09 07:47
sharing seems to work with USERS, but not with GROUPS, at lease when the groups come from LDAP.

**Comment by juliushaertl** [comment] 2017-02-10 09:47
@lepidas Can you fill out the issue template I've recently added to the repo and post it here, so I may have some more information to reproduce the bug. That would be awesome.

@joergmschulz I cannot reproduce an issue here with LDAP, can you open a seperate issue for that?

**Comment by juliushaertl** [comment] 2017-05-01 06:50
The sharing part has quite some fixes in the next release. Please test and feel free to reopen if the issue still exists.

**Closed by juliushaertl** 2017-05-01 06:50 UTC
Labels: bug
