### ISSUE TITLE
Duplicate/copy cards

### ISSUE THREAD

**Issue by the-cloud** [nextcloud/deck#3150] opened 2021-06-24 21:09 UTC
**Hello!**

I'm in a high hurry and need of a feature to duplicate or copy single cards (I guess option to mark multiple would be nice, or whole columns of them, to copy). In my eyes duplicate would create exact clone of marked card below of selected one. Copy feature would ask where to copy selected card, and create exact copy in that space.

I'm working seasonal job where a lot of things are repetitive (kind of) and I would like to organise my team using Deck. Manualy rewriting almost the same cards will lose me some time in place where agility and speed is realy important.

**Comment by stefan-niedermann** [comment] 2021-06-24 21:11
Duplicate of #1813

Please use the :mag: search function before opening new issues :slightly_smiling_face:.

**Closed by stefan-niedermann** 2021-06-24 21:11 UTC

**Comment by the-cloud** [comment] 2021-06-24 21:14
I did search. I found topic about cloning boards, but I see I missed what I was looking for. Thank you for poiting me to the correct place, and sorry for creating this issue then.
