### ISSUE TITLE
Calendar picker doesn't work since 1.9.1

### ISSUE THREAD

**Issue by lars-becker** [nextcloud/deck#4669] opened 2023-05-11 13:59 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Since version 1.9.1 the calendar picker doesn't work anymore. A click on the calendar icon doesn't show the picker.

**To Reproduce**
1. Go to the deck app
2. open or create a card
3. click on the calendar icon
4. nothing happens

**Expected behavior**
The calendar picker pops up and can be used to pick a date.

**Screenshots**
![image](https://github.com/nextcloud/deck/assets/8607154/5ef4aa07-2d9c-4149-99ec-2ab950b15620)

**Client details:**
 - Browser: tested with current Firefox (113.0) and current Chromium (113.0.5672.92).
 - Device: desktop

**Nextcloud version:** NC 26.0.1

**Comment by stefan-niedermann** [comment] 2023-05-11 17:42
Duplicate of https://github.com/nextcloud/deck/issues/4663

**Closed by stefan-niedermann** 2023-05-11 17:42 UTC
