### ISSUE TITLE
Duplicate of assigned users

### ISSUE THREAD

**Issue by Ngri88** [nextcloud/deck#720] opened 2018-11-19 15:22 UTC
After upgrading to version 0.5.0, the Deck began to freeze. After the user is assigned to the card, nothing visually happens, but after a while the designated user appears on card in the number of several copies. In this case, any ability to manage the assigned users or remove the user from the card is lost.

**Client details:**
 - OS: Win 7
 - Browser: Any

![bug](https://user-images.githubusercontent.com/42353585/48716237-8ab41880-ec1f-11e8-85c1-e76af784554b.jpg)

NC 14.0.3
Deck 0.5.0

**Comment by putt1ck** [comment] 2018-11-20 09:06
Is this a duplicate of #710 ?

**Comment by putt1ck** [comment] 2018-11-20 09:31
My overly long description at fault! Will close this as a duplicate of #710

**Closed by putt1ck** 2018-11-20 09:31 UTC
