### ISSUE TITLE
Card dialog UI/UX improvements

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/deck#2423] opened 2020-10-11 12:09 UTC
- [x] Do not open the dialog automatically upon card creation, only upon click;
- [ ] If the card is not focus, sometimes opening the dialog requires a double click. I think it should open at first click;
- [x] Shoudln't the cursor be a pointer on the cards? 
- [ ] The content of the modal should have some ~ 12px padding on all 4 sides;

UPDATE:
- [x] When compact mode is toggled, a click on any point of the card should open the sidebar / dialog, we shouldn't allow to rename the card by clicking the title.

**Comment by juliushaertl** [comment] 2020-10-12 05:55
>  If the card is not focus, sometimes opening the dialog requires a double click. I think tt should open at first click;

Never seen that so far, is there anything in the console log?

**Comment by ma12-co** [comment] 2020-10-13 07:25
This happened in Firefox on windows. I can't reproduce again in gnu Linux. I'll check again when I'm back on win

**Comment by ma12-co** [comment] 2020-10-13 07:29
Added 1 more remark @juliushaertl

**Comment by juliushaertl** [comment] 2020-10-13 07:44
Makes sense :+1:

**Comment by drfuture** [comment] 2020-11-23 14:30
Hi,
why "Do not open the dialog automatically.." ?
before modal dialogs (this is a great new feature) i was able to create a new card, hit enter, enter the details like "tags, user..., description".

Normaly i have a filter to "my" Cards active. If i create a new card i now click on +, add the title, enter, remove filter, search the new card, klick on card, add details, enter.

Would be nice to have a more efficient way back 👍

**Comment by FabianUntermoser** [comment] 2021-02-12 22:07
Another improvement would be to add the ability to resize the modal window.
In my opinion, the window is way to small when youre working with limited screen real estate.

![image](https://user-images.githubusercontent.com/13196058/107827319-d1edcd00-6d86-11eb-8da2-594dac63c127.png)

Maybe tweaking some media queries to make the modal window bigger in small windows would do the deal here, as resizing might be overkill.

**Comment by jancborchardt** [comment] 2022-01-13 13:08
Since some of the points in here are fixed already, I will close this issue in favor of https://github.com/nextcloud/deck/issues/2702 which has more specification and mockups for a modal redesign. :)

**Closed by jancborchardt** 2022-01-13 13:08 UTC
Labels: bug, design, 1. to develop
