### ISSUE TITLE
Collapse left sidebar after selecting a board

### ISSUE THREAD

**Issue by cmdntd** [nextcloud/deck#3280] opened 2021-08-31 00:42 UTC
**Expected behavior**
1. Menu not hide automatically after choose board
    * Click on menu
  It should be hide after click on
  ![9LjqAr7fCf](https://user-images.githubusercontent.com/1112881/131525699-082a43b2-26b8-45aa-9aa4-7fe40c958bd0.png)
<details>
<summary>Click to expand additional issue which has been marked as duplicate</summary>
2. Serious error when scroll to other list
  * Scroll down to 'next lists'
  I can not slide to other lists on responsive mobile, and it makes app stand by on my own
  ![mZngWq3roB](https://user-images.githubusercontent.com/1112881/131526818-5e8b8c0b-7a13-421e-9435-122cbb1f8f4a.png)
</details>

**Client details:**
Android 11
Chrome
Deck 1.5.0
Nextcloud 22.1.1
Samsung phone

**Server**
Google compute
Ubuntu 20.04
PHP 7.4
MySQL

**Comment by stefan-niedermann** [comment] 2021-08-31 08:03
Please fill out the complete issue template. It is there for a reason.

**Comment by cmdntd** [comment] 2021-08-31 15:10
Hi, I updated my bug description

**Comment by stefan-niedermann** [comment] 2021-08-31 15:14
Thank you for the clarification.

Your first issue is not considered to be a bug because it is the currently supposed behavior. Allow me to rename this issue to make it more obvious what you want.
Your second issue is a duplicate of https://github.com/nextcloud/deck/issues/1960

**Comment by cmdntd** [comment] 2021-08-31 15:23
Thank you very much

**Closed** 2024-09-09 18:21 UTC
Labels: enhancement, frontend, 0. Needs triage
