### ISSUE TITLE
Cannot enter comments in Deck 0.5.0 / NC 13.0.7

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#704] opened 2018-11-15 16:09 UTC
Just updated Deck to 0.5.0 and ran some tests. Creating a new comment in the timeline seems to be impossible.

***Steps to reproduce:***
- Click on an existing or new card
- Click on "Zeitachse" (Timeline)
- Enter new comment and click the arrow to the right.

***What should happen:***
- Comment is created and shown in the list

***What actually happens:***
- Error message appears: "Absenden des Kommentars ist fehlgeschlagen."
- The arrow becomes an infinitely spinning circle

***Nextcloud Versions:***

- 13.0.7 (does not work as described above)
- 14.0.3 (No problems)

***Excerpt rom the log (level 0):***

{"reqId":"W@2S7tyt5AevJM@z@BbqTgAAAA8","level":"error","time":"2018-11-15T15:38:23+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"no app in context","method":"GET","url":"\/index.php\/apps\/deck\/cards\/126","message":"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"W@2S8trXQZtHh6-honcJcQAAABE","level":"error","time":"2018-11-15T15:38:26+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"no app in context","method":"GET","url":"\/index.php\/apps\/deck\/2\/cards\/deleted","message":"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"W@2S8trXQZtHh6-honcJcgAAABM","level":"error","time":"2018-11-15T15:38:26+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"no app in context","method":"GET","url":"\/index.php\/apps\/deck\/2\/stacks\/deleted","message":"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"W@2S8trXQZtHh6-honcJcwAAABU","level":"error","time":"2018-11-15T15:38:26+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"no app in context","method":"GET","url":"\/ocs\/v2.php\/apps\/activity\/api\/v2\/activity\/filter?format=json&object_type=deck_card&object_id=126&limit=50&since=0","message":"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"W@2S8trXQZtHh6-honcJdAAAABc","level":"error","time":"2018-11-15T15:38:26+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"no app in context","method":"GET","url":"\/ocs\/v2.php\/apps\/activity\/api\/v2\/activity\/filter?format=json&object_type=deck_card&object_id=126&limit=50&since=-1&sort=asc","message":"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"W@2S8trXQZtHh6-honcJdQAAAA8","level":"error","time":"2018-11-15T15:38:26+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"no app in context","method":"GET","url":"\/index.php\/apps\/deck\/%7B%7Bactivity.icon%7D%7D","message":"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"W@2S8trXQZtHh6-honcJdgAAABk","level":0,"time":"2018-11-15T15:38:27+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"webdav","method":"REPORT","url":"\/remote.php\/dav\/comments\/deckCard\/126\/","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"Entity type \\\"deckCard\\\" not found.\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): OCA\\\\DAV\\\\Comments\\\\RootCollection->getChild('deckCard')\\n#1 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(71): Sabre\\\\DAV\\\\Tree->getNodeForPath('comments\\\/deckCa...')\\n#2 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/FilesReportPlugin.php(171): Sabre\\\\DAV\\\\Tree->getNodeForPath('comments\\\/deckCa...')\\n#3 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\FilesReportPlugin->onReport('{http:\\\/\\\/ownclou...', Array, 'comments\\\/deckCa...')\\n#4 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(722): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#6 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#8 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#9 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Server.php(293): Sabre\\\\DAV\\\\Server->exec()\\n#11 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#12 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/remote.php(164): require_once('\\\/www\\\/htdocs\\\/w01...')\\n#13 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Comments\\\/RootCollection.php\",\"Line\":150}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"W@2S89rXQZtHh6-honcJdwAAABs","level":"error","time":"2018-11-15T15:38:27+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"no app in context","method":"GET","url":"\/index.php\/apps\/files\/","message":"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"W@2S9wcpKbENaJic5KW7wwAAAA8","level":0,"time":"2018-11-15T15:38:31+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"webdav","method":"POST","url":"\/remote.php\/dav\/comments\/deckCard\/126\/","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"Entity type \\\"deckCard\\\" not found.\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): OCA\\\\DAV\\\\Comments\\\\RootCollection->getChild('deckCard')\\n#1 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(71): Sabre\\\\DAV\\\\Tree->getNodeForPath('comments\\\/deckCa...')\\n#2 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Comments\\\/CommentsPlugin.php(111): Sabre\\\\DAV\\\\Tree->getNodeForPath('comments\\\/deckCa...')\\n#3 [internal function]: OCA\\\\DAV\\\\Comments\\\\CommentsPlugin->httpPost(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:POST', Array)\\n#6 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Server.php(293): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#9 \\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/remote.php(164): require_once('\\\/www\\\/htdocs\\\/w01...')\\n#10 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/[anonymized]\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Comments\\\/RootCollection.php\",\"Line\":150}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}

**Comment by juliushaertl** [comment] 2018-11-15 16:22
This one looks strange but I cannot reproduce this on 13. Is there any difference in configuration between the 13 and 14 servers, you have tested this on?

**"Entity type "deckCard" not found.**
```
{"reqId":"W@2S8trXQZtHh6-honcJdgAAABk","level":0,"time":"2018-11-15T15:38:27+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"webdav","method":"REPORT","url":"/remote.php/dav/comments/deckCard/126/","message":"Exception: {"Exception":"Sabre\\DAV\\Exception\\NotFound","Message":"Entity type \"deckCard\" not found.\"","Code":0,"Trace":"#0 \/www\/htdocs\/[anonymized]\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(76): OCA\\DAV\\Comments\\RootCollection->getChild('deckCard')\n#1 \/www\/htdocs\/[anonymized]\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(71): Sabre\\DAV\\Tree->getNodeForPath('comments\/deckCa...')\n#2 \/www\/htdocs\/[anonymized]\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/FilesReportPlugin.php(171): Sabre\\DAV\\Tree->getNodeForPath('comments\/deckCa...')\n#3 [internal function]: OCA\\DAV\\Connector\\Sabre\\FilesReportPlugin->onReport('{http:\/\/ownclou...', Array, 'comments\/deckCa...')\n#4 \/www\/htdocs\/[anonymized]\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/www\/htdocs\/[anonymized]\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(722): Sabre\\Event\\EventEmitter->emit('report', Array)\n#6 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/www\/htdocs\/[anonymized]\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#8 \/www\/htdocs\/[anonymized]\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#9 \/www\/htdocs\/[anonymized]\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#10 \/www\/htdocs\/[anonymized]\/cloud\/apps\/dav\/lib\/Server.php(293): Sabre\\DAV\\Server->exec()\n#11 \/www\/htdocs\/[anonymized]\/cloud\/apps\/dav\/appinfo\/v2\/remote.php(35): OCA\\DAV\\Server->exec()\n#12 \/www\/htdocs\/[anonymized]\/cloud\/remote.php(164): require_once('\/www\/htdocs\/w01...')\n#13 {main}","File":"\/www\/htdocs\/[anonymized]\/cloud\/apps\/dav\/lib\/Comments\/RootCollection.php","Line":150}","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0","version":"13.0.7.2"}
```

**Comment by bpcurse** [comment] 2018-11-15 16:48
@juliushaertl Thank you for your fast reply and your work!

Yes, i'm afraid these are completely different servers and setups with many differences in apps and user count. The 14.0.3 is a relatively new self administered physical server, with almost no users at the moment. The 13.0.7 is a pretty long running shared hosting server with 100+ users. Will try to deliver detailed configuration and a test with another browser later, probably tomorrow.

I am thinking about a server update from 13.0.7 to 14.0.3, but this version still isn't tagged as 'production'. I assume this could solve the problem, but maybe others might run into this as well.

**Comment by bpcurse** [comment] 2018-11-15 17:01
@juliushaertl 
The cards actually seem to be created. One just has to reload the page.
Same behaviour when deleting or assigning a card to oneself via 3 dot menu. Nothing seems to happen, but the card is deleted anyway, which can only be seen after a page reload.

**Curiously, archiving the card via 3-dot menu works immediately...**

**Comment by bpcurse** [comment] 2018-11-16 17:44
The same happens using Chromium instead of Firefox.

Here are the configuration details:

**13.0.7 shared hosting server**

Operating system: Linux 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64
Webserver: Apache (fpm-fcgi)
Database: mysql 5.7.21
PHP version:
7.1.19-nmm1 Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dom, hash, filter, ftp, gettext, SPL, iconv, json, mbstring, posix, Reflection, session, standard, shmop, SimpleXML, soap, exif, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, cgi-fcgi, propro, raphf, http, mysqlnd, PDO, curl, dba, fileinfo, gd, gender, gmp, htscanner, imagick, imap, interbase, intl, ldap, mailparse, mcrypt, mongodb, mysqli, OAuth, odbc, pdo_dblib, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, pspell, recode, SourceGuardian, sqlite3, tidy, xsl, ionCube Loader
Nextcloud version: 13.0.7 - 13.0.7.2


**14.0.3 physical server**

Operating system: Linux 4.14.68-1-MANJARO #1 SMP PREEMPT Wed Sep 5 19:07:05 UTC 2018 x86_64
Webserver: nginx/1.14.0 (fpm-fcgi)
Database: mysql 10.1.35
PHP version:
7.2.9 Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, Phar, curl, exif, ftp, gd, iconv, imap, intl, pdo_mysql, pdo_pgsql, pgsql, zip, apcu, igbinary, imagick, mongodb, redis, Zend OPcache
Nextcloud version: 14.0.3 - 14.0.3.0

**Comment by juliushaertl** [comment] 2018-11-17 09:51
Probably related to https://github.com/nextcloud/deck/issues/707

**Comment by juliushaertl** [comment] 2018-11-17 09:54
@bpcurse Just to make sure, is the comments app enabled on both instances?

**Comment by bpcurse** [comment] 2018-11-17 15:53
@juliushaertl Comments app is enabled on both instances. Version 1.3.0 (on 13.0.7) and version 1.4.0 on (on 14.0.3).

**Comment by ashgoodman** [comment] 2018-11-19 09:15
Same issue
Comments enabled
Nextcloud 13 via snap
Console gives the following message

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

That message appears when a card is clicked on

Also, getting message that remote.php cannot be found

**Comment by juliushaertl** [comment] 2018-11-19 10:33
@bpcurse Any change you can apply [this patch](https://gist.github.com/juliushaertl/ee0791e1b337a35e8397241bf10acf17) to the deck app and check if the two log message appears in the log when browsing https://yournextcloud/remote.php/dav/comments (with debug mode enabled on your instance you can just open this in the browser)

**Comment by juliushaertl** [comment] 2018-11-19 10:33
Same for @ashgoodman as well :wink: Maybe we can track down the issue then a bit.

**Comment by ashgoodman** [comment] 2018-11-19 13:00
Applied the patch

I dont get the error logs when navigating to .../remote.php/dav/comments  in the browser, but still cant post a comment and still getting same error in console when I click on a card

**Comment by bpcurse** [comment] 2018-11-19 23:09
@juliushaertl 

- Applied the patch in /apps/deck/lib/AppInfo/Application.php like this
```
public function registerCommentsEntity() {
                \OC::$server->getLogger()->error('Adding comments event listener');
		$this->getContainer()->getServer()->getEventDispatcher()->addListener(CommentsEntityEvent::EVENT_ENTITY, function(CommentsEntityEvent $event) {
			$event->addEntityCollection('deckCard', function($name) {
			\OC::$server->getLogger()->error('Registering comments entity');
				/** @var CardMapper */
				$service = $this->getContainer()->query(CardMapper::class);
				try {
					$service->find((int) $name);
				} catch (\InvalidArgumentException $e) {
					return false;
				}
				return true;
			});
		});
		$this->registerCommentsEventHandler();
	}
```

- Set debug mode and log level 0 in config.php
```<
?php
$CONFIG = array (
    'debug' => true,
    'loglevel' => 0,
    ... configuration goes here ...
);
```
- Tried to comment on a card. Did not work, as expected
- Got this result at https://myinstanceURI/remote.php/dav/comments

![mycloudinstance_remote php_dav_comments](https://user-images.githubusercontent.com/29312856/48739719-1ac08500-ec55-11e8-961f-19ab35307749.png)

- This is in the nextcloud.log
```
{"reqId":"W-NAhmGogYR4OThTFTuvjgAAAA8","level":0,"time":"2018-11-19T23:00:22+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"webdav","method":"POST","url":"\/remote.php\/dav\/comments\/deckCard\/419\/","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"Entity type \\\"deckCard\\\" not found.\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): OCA\\\\DAV\\\\Comments\\\\RootCollection->getChild('deckCard')\\n#1 \\\/www\\\/htdocs\\\[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(71): Sabre\\\\DAV\\\\Tree->getNodeForPath('comments\\\/deckCa...')\\n#2 \\\/www\\\/htdocs\\\[anonymized]\\\/cloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/BirthdayCalendar\\\/EnablePlugin.php(118): Sabre\\\\DAV\\\\Tree->getNodeForPath('comments\\\/deckCa...')\\n#3 [internal function]: OCA\\\\DAV\\\\CalDAV\\\\BirthdayCalendar\\\\EnablePlugin->httpPost(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/www\\\/htdocs\\\[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/www\\\/htdocs\\\[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:POST', Array)\\n#6 \\\/www\\\/htdocs\\\[anonymized]\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/www\\\/htdocs\\\[anonymized]\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Server.php(293): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/www\\\/htdocs\\\[anonymized]\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#9 \\\/www\\\/htdocs\\\[anonymized]\\\/cloud\\\/remote.php(164): require_once('\\\/www\\\/htdocs\\\/w01...')\\n#10 {main}\",\"File\":\"\\\/www\\\/htdocs\\\[anonymized]\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Comments\\\/RootCollection.php\",\"Line\":150}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"W-NAiR3Kw6KPKrOzMs1F2AAAAA8","level":3,"time":"2018-11-19T23:00:25+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"no app in context","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"Adding comments event listener","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}
{"reqId":"W-NAiR3Kw6KPKrOzMs1F2AAAAA8","level":"error","time":"2018-11-19T23:00:25+00:00","remoteAddr":"[anonymized]","user":"[anonymized]","app":"no app in context","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"13.0.7.2"}

```

**Comment by ashgoodman** [comment] 2018-11-20 07:59
Disabled Deck, copied Application.phpin full from https://github.com/nextcloud/deck/blob/master/lib/AppInfo/Application.php over my installs copy

Re enabled deck

Comments work!!

**Comment by ashgoodman** [comment] 2018-11-20 08:15
However the notification email does not contain the name of the person who commented nor the content of the comment email just says:

```
Today at 4:06 PM
has commented on 
```

**Comment by putt1ck** [comment] 2018-11-20 08:22
> However the notification email does not contain the name of the person who commented nor the content of the comment email just says:
> 
> ```
> Today at 4:06 PM
> has commented on 
> ```

I think this is a separate bug, as we also see this behaviour in NC14.03.

**Comment by juliushaertl** [comment] 2018-11-20 08:35
@ashgoodman Yes, please open a separate issue for the email notification. :wink: 

Glad it worked. I assue there has been something wrong during update then or opcache is somehow not up to date :disappointed: 

@bpcurse Maybe you can also try replacing the files manually with the ones from the release package and restart the webserver?

**Comment by putt1ck** [comment] 2018-11-20 08:39
New issue created https://github.com/nextcloud/deck/issues/721

**Comment by bpcurse** [comment] 2018-11-20 21:37
@ashgoodman Nice and simple trick! :thumbsup:
I didn't even copy Application.php. Only deactivated deck, switched to files, switch back to apps and reactivated it. That's all, it works. Weird bits and bytes :monkey_face:
(And removed the logger patch from Application.php)

@juliushaertl Should we close this now as the bug is extremely easy to handle? Maybe it's not even deck's fault?

Thank you for the support!

**Comment by juliushaertl** [comment] 2018-11-20 22:21
Yes, let's close it since it is pretty hard to reproduce and we don't have any hints why this might have failed.

**Closed by juliushaertl** 2018-11-20 22:21 UTC
Labels: bug, needs info

**Comment by anojht** [comment] 2018-12-16 23:19
Hello I am also having this issue without any messages in the logs. When I attempt to post a comment in the Timeline section I get, `Posting the comment failed`

NC - 14.0.4
Deck - 0.5.1

I get a HTTP 404 error when attempting to post a comment:
`core.js?v=9b50fb98-31:5729 POST https://{server_url}/remote.php/dav/comments/deckCard/50/ 404`

**Comment by juliushaertl** [comment] 2018-12-20 07:05
@blizzz Do you have any idea why the comments entity type is not available until the users have disabled and enabled the deck app again?

This is how we register the entity: https://github.com/nextcloud/deck/blob/master/lib/AppInfo/Application.php#L128-L148

**Comment by blizzz** [comment] 2018-12-20 10:53
@juliushaertl there's no logic that kicks in when the app is enabled. Perhaps we have a hidden race condition somewhere.

**Comment by rasos** [comment] 2019-03-26 08:07
Same issue here with NC 13.0.5: comments are not stored, however disabling / enabling Deck as recommended in this issue does not help either. Nothing suspicious in Logfile. Comments work in other apps (Files). 
How could I further debug this?
