### ISSUE TITLE
Request grouping Decks and time frame

### ISSUE THREAD

**Issue by the-luap** [nextcloud/deck#6451] opened 2024-10-28 19:19 UTC
Hi Team,

I would first thank you for the great deck functions and I would request two enhancements for the nextcloud deck. One request would be to be able to group decks on the left menu side to have like a hierarchy to apply one upper deck level to a nextcloud group that can than share multiple different decks below it.

Second request is, that currently the deck only has a single completion date but I would like to have a time frame for specific task to see a deck topic on the calendar for 3 days for example.

Best Regards,
Paul

**Comment by trautjon** [comment] 2024-10-29 14:45
Thanks Paul, I actually wanted to create a issue for that as well!
Would very much appropriate especially the second feature with a starting and end date, rather than just an end date. 
A good example of this would be how MS Planner has it integrated.

**Comment by XueSheng-GIT** [comment] 2024-11-02 06:00
Probably related: https://github.com/nextcloud/deck/issues/6358

**Comment by stefan-niedermann** [comment] 2024-11-02 11:26
Closing as duplicate of https://github.com/nextcloud/deck/issues/2006 and #6358 - @the-luap please search for existing issues next time before opening new ones and open max one issue per topic.

**Closed by stefan-niedermann** 2024-11-02 11:26 UTC
