### ISSUE TITLE
Markdown parsing error when use checkbox and bold formatation

### ISSUE THREAD

**Issue by marvinjuette** [nextcloud/deck#3834] opened 2022-05-22 17:23 UTC
**Describe the bug**
I created a card and gave it a description. I wanted to have a checkbox with bold text. So I used the following markdown formatting: 
`- [ ] **Social Links:**`

The result was:
![grafik](https://user-images.githubusercontent.com/46931628/169707311-1ba8ac42-955b-4560-876d-a20c77a3607a.png)

It looks like the stuff is displayed correctly but for some reason after the "interpreted" version the raw version is beeing displayed. This should not be.

**To Reproduce**
1. Go to Deck
2. Create a Card and give it a description like this: `- [ ] **Example**`
3. Open the card an view it's description.

**Expected behavior**
The raw markdown should not be displayed. (Like it is in the android deck app).

**Screenshots**
![grafik](https://user-images.githubusercontent.com/46931628/169707311-1ba8ac42-955b-4560-876d-a20c77a3607a.png)

**Client details:**
 - OS: Windows 10
 - Browser Mozilla Firefox 100.0.2
 - Version 100.0.2 (64-Bit)
 - Device: Desktop
<details>
<summary>Server details</summary>

**Operating system**: Ubuntu-Server

**Web server:** Nginx Proxy Manager (as reverse Proxy)

**Database:** PostgreSQL

**PHP version:** 8.0

**Nextcloud version:** 24

**Where did you install Nextcloud from:** Official Docker image (`image: nextcloud`)
</details>

**Comment by marvinjuette** [comment] 2022-05-22 17:25
The same behaviour appers also in Googl Chrome (Version: 101.0.4951.67 (64-Bit)).

**Comment by a-mair** [comment] 2022-05-23 08:44
that's also true for other styling (strike though, italics)

**Comment by stefan-niedermann** [comment] 2022-05-23 08:46
Please use the 🔍 search function before opening new issues.

Closing as duplicate of #2109

**Closed by stefan-niedermann** 2022-05-23 08:46 UTC
