### ISSUE TITLE
Feature request for Gantt style needs

### ISSUE THREAD

**Issue by lgnch** [nextcloud/deck#3272] opened 2021-08-25 09:11 UTC
Customer has requested if Deck can do the following:

•	The ability to have a date range instead of just due date.  This would enable building firms to schedule in blocks of days for builders and sub-contractors on jobs
•	The date ranges then filter through to the calendar
•	If the above is possible, would deck also be able to assign colours to blocks, i.e. Red for construction, Brown for Plumber and so on
•	This aligns more with Gantt Chart format which builders are familiar with

Are these features doable?

**Comment by stefan-niedermann** [comment] 2021-08-25 10:26
> As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
> 
> If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

([source](https://github.com/nextcloud/deck/issues/134#issuecomment-448910458))

**Comment by juliushaertl** [comment] 2021-09-10 16:22
Closing as a duplicate of #134

**Closed by juliushaertl** 2021-09-10 16:22 UTC
