### ISSUE TITLE
color picker with HTML color codes

### ISSUE THREAD

**Issue by JustAnotherTill** [nextcloud/deck#3883] opened 2022-06-27 22:04 UTC
Hey there!

First of all: Thank you very much for your great App! I use it more and more often and for me it's great how structured I can deal with my tasks as a result. But... ;-)

I really would like to define the colors for tags in Deck as HTML color code, to ensure a consistent appearance across different apps in Nextcloud.

For reference I would recommend the color picker in calendar.

See also #1911, #2893, #3310

**Comment by juliushaertl** [comment] 2022-07-04 15:51
As mentioned in #1911 this is something that the vue components should implement, follow up discussion shall be happening at https://github.com/nextcloud/nextcloud-vue/issues/1687, so I'm closing this as a duplicate of the linked ones.

**Closed by juliushaertl** 2022-07-04 15:51 UTC
