### ISSUE TITLE
Auto close sidebar after board is opened

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/deck#568] opened 2018-08-04 15:11 UTC
**Is your feature request related to a problem? Please describe.**
Probably many users have more stacks in a board than fit their screen width.
The sidebar consumes some of the valuable space and has to be manually collapsed for a better overview.

**Describe the solution you'd like**
Once a board is accessed the left sidebar should automatically collapse if there are more boards than fit the screen width.

**Describe alternatives you've considered**
Consider customization options for this behaviour in "settings".

**Comment by juliushaertl** [comment] 2018-08-18 08:49
Duplicate of https://github.com/nextcloud/deck/issues/117

**Closed by juliushaertl** 2018-08-18 08:49 UTC
