### ISSUE TITLE
Epics

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/deck#1940] opened 2020-05-21 19:54 UTC
Any chance we can get something akin to Epics used for say DevOps? Kind of like, meta/parent/child Decks with I guess coloured visualisation of children's progress?

**Comment by juliushaertl** [comment] 2020-06-14 19:10
There are currently no plans to implement that. Closing as a duplicate of https://github.com/nextcloud/deck/issues/272

**Closed by juliushaertl** 2020-06-14 19:10 UTC
