### ISSUE TITLE
Web UI and mobile app : When a card is moved, non-existent tags must be removed (or at least hidden) from the card

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/deck#5597] opened 2024-02-15 16:02 UTC
Hi,

When a card is moved from one table to another, if a label does not exist in the new table, it must be removed from the card.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

**To Reproduce**
1. In board A, create a card and apply a tag to it (a tag that exists in board A, but not in board B)
2. Move card from board A to board B 
3. See that the tag is still visible in the moved card in board B and can't obviously be removed because it doesn't exist in board B

**Expected behavior**
The tag should be removed OR should at lease not appear, so if we move it back to board A, it will appear again.

**Screenshots**

**Client details:**
 - Desktop OS: Ubuntu 22.04 LTS 
 - Browser Mozilla Firefox 123
 - Nextcloud 27.1.6
 - Deck 1.11.4

<details>
<summary>Server details</summary>

**Operating system**: Linux 5.14.0-362.18.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 24 23:11:18 UTC 2024 x86_64

**Web server:** nginx/1.25.3 (fpm-fcgi)

**Database:** mysql 10.6.16

**PHP version:** 8.2.15

**Nextcloud version:** 27.1.6

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
 - activity: 2.19.0
 - admin_audit: 1.17.0
 - announcementcenter: 6.7.0
 - appointments: 1.15.5
 - assistant: 1.0.2
 - bbb: 2.5.0
 - bookmarks: 13.1.3
 - bruteforcesettings: 2.7.0
 - calendar: 4.6.4
 - call_summary_bot: 1.0.1
 - circles: 27.0.1
 - cloud_federation_api: 1.10.0
 - collectives: 2.9.2
 - comments: 1.17.0
 - contacts: 5.5.1
 - contactsinteraction: 1.8.0
 - dashboard: 7.7.0
 - dav: 1.27.0
 - deck: 1.11.4
 - external: 5.2.1
 - federatedfilesharing: 1.17.0
 - federation: 1.17.0
 - files: 1.22.0
 - files_automatedtagging: 1.17.0
 - files_downloadactivity: 1.16.0
 - files_fulltextsearch: 27.0.1
 - files_lock: 27.0.4
 - files_markdown: 2.4.1
 - files_pdfviewer: 2.8.0
 - files_reminders: 1.0.0
 - files_rightclick: 1.6.0
 - files_sharing: 1.19.0
 - files_texteditor: 2.15.1
 - files_trashbin: 1.17.0
 - files_versions: 1.20.0
 - firstrunwizard: 2.16.0
 - flow_notifications: 1.7.0
 - forms: 3.4.5
 - fulltextsearch: 27.0.3
 - fulltextsearch_elasticsearch: 27.0.5
 - groupfolders: 15.3.4
 - guests: 2.5.1
 - impersonate: 1.14.0
 - integration_openai: 1.1.5
 - integration_openproject: 2.6.0
 - logreader: 2.12.0
 - lookup_server_connector: 1.15.0
 - mail: 3.5.6
 - memegen: 1.0.7
 - news: 24.0.0
 - nextcloud_announcements: 1.16.0
 - notes: 4.9.2
 - notifications: 2.15.0
 - notify_push: 0.6.9
 - oauth2: 1.15.2
 - onlyoffice: 8.2.4
 - photos: 2.3.0
 - polls: 5.4.3
 - privacy: 1.11.0
 - provisioning_api: 1.17.0
 - qownnotesapi: 23.12.0
 - recommendations: 1.6.0
 - related_resources: 1.2.0
 - richdocuments: 8.2.4
 - secrets: 1.5.2
 - serverinfo: 1.17.0
 - settings: 1.9.0
 - sharebymail: 1.17.0
 - side_menu: 3.11.7
 - snappymail: 2.34.2
 - spreed: 17.1.5
 - support: 1.10.0
 - survey_client: 1.15.0
 - systemtags: 1.17.0
 - tasks: 0.15.0
 - text: 3.8.0
 - theming: 2.2.0
 - theming_customcss: 1.15.0
 - twofactor_backupcodes: 1.16.0
 - updatenotification: 1.17.0
 - user_ldap: 1.17.0
 - user_saml: 5.2.6
 - user_status: 1.7.0
 - viewer: 2.1.0
 - weather_status: 1.7.0
 - workflowengine: 2.9.0
```

**Nextcloud configuration:**

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.mydomain.com"
    ],
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.mydomain.com",
    "dbtype": "mysql",
    "version": "27.1.6.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "filelocking.enabled": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "password": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 0,
        "timeout": 0
    },
    "log_type": "file",
    "logtimezone": "Europe\/Paris",
    "logfile": "\/var\/log\/nextcloud\/cloud.mydomain.com\/nextcloud.log",
    "loglevel": 1,
    "debug": true,
    "default_phone_region": "FR",
    "default_language": "fr",
    "default_locale": "fr_FR",
    "log_rotate_size": 104857600,
    "session_keepalive": true,
    "simpleSignUpLink.shown": false,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpauthtype": "PLAIN",
    "trashbin_retention_obligation": "auto,60",
    "versions_retention_obligation": "auto,60",
    "activity_expire_days": 40,
    "activity_use_cached_mountpoints": true,
    "installed": true,
    "appstore.experimental.enabled": true,
    "maintenance": false,
    "theme": "",
    "mysql.utf8mb4": true,
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "groupfolders",
        "files_downloadactivity",
        "external",
        "files_texteditor",
        "user_saml",
        "flow_notifications",
        "onlyoffice",
        "impersonate",
        "richdocuments",
        "spreedme",
        "piwik",
        "accessibility",
        "apporder",
        "bbb"
    ],
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_sendmailmode": "smtp",
    "defaultapp": "files"
}
```

**Are you using an external user-backend, if yes which one:** LDAP

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Can be provided if necessary
```

#### Browser log
```
Can be provided if necessary
```

</details>

**Comment by q-wertz** [comment] 2024-03-13 12:52
Can confirm for NC 28.0.3 and Deck 1.12.2

**Comment by stefan-niedermann** [comment] 2024-03-13 13:10
Basically duplicate of https://github.com/nextcloud/deck/issues/1832 - at least it depends on it.

**Closed** 2024-05-24 12:38 UTC
Labels: bug, design, client: 💻 desktop, client: 🤖🍏 mobile, ux
