### ISSUE TITLE
[feature request]: being able to share boards, lists and cards with other nextcloud instances

### ISSUE THREAD

**Issue by Rik44444** [nextcloud/deck#2274] opened 2020-09-08 07:02 UTC
Hi, many thanks for developing this, so v useful to have in Nextcloud: makes it usable as a primary work platform.
This is a feature request for being able to share boards, lists and cards with other Nextcloud instances. 
The use case is as follows: I work on many different projects, several with their own Nextcloud instances. We all use NC Deck for our ToDo lists. However, i would like to be able to see all my ToDo's in 1 screen. So it would be useful if we could share boards, lists and cards across these instances, so that I could view the ToDo's from all my projects in 1 screen.

**Comment by stefan-niedermann** [comment] 2020-09-08 07:11
Duplicate of https://github.com/nextcloud/deck/issues/789

**Closed by stefan-niedermann** 2020-09-08 07:11 UTC
