### ISSUE TITLE
keine Beschreibung möglich | no description possible

### ISSUE THREAD

**Issue by ThomasKujawa** [nextcloud/deck#1999] opened 2020-06-08 11:38 UTC
### Steps to reproduce
öffne Deck - öffne Board - öffne Karte | open deck - open board - open card | https://share.vidyard.com/watch/mSqjhbY4NMaKdeeq1TrmPH?

### Expected behaviour
Beschreibung lässt sich einfügen | Description can be inserted

### Actual behaviour
Beschreibungsfeld ist 'schreibgeschützt' | Description field is 'read-only'

## Server configuration detail

**Operating system:** Linux 4.15.0-101-generic #102~16.04.1-Ubuntu SMP Mon May 11 11:38:16 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.28

**PHP version:** 

7.4.5
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, propro, raphf, iconv, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, fileinfo, ftp, gd, gender, gettext, gmp, htscanner, http, imagick, imap, intl, json, ldap, mailparse, exif, mongodb, mysqli, OAuth, odbc, pdo_dblib, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, shmop, SimpleXML, soap, SourceGuardian, sqlite3, sysvsem, sysvshm, tidy, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 18.0.5 - 18.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - announcementcenter: 3.7.0
 - bookmarks: 3.1.1
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dav: 1.14.0
 - deck: 1.0.2
 - documentserver_community: 0.1.5
 - drawio: 0.9.5
 - encryption: 2.6.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_automatedtagging: 1.8.3
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - forms: 1.1.1
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - news: 14.1.11
 - nextcloud_announcements: 1.7.0
 - notes: 3.5.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocsms: 2.1.7
 - onlyoffice: 4.2.0
 - password_policy: 1.8.0
 - passwords: 2020.5.0
 - polls: 1.4.3
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - registration: 0.4.7
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.9
 - support: 1.1.1
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.13.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - files_external
 - photos
 - recommendations
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "familienfreun.de",
        "www.familienfreun.de",
        "familienfreun.de.w0174798.kasserver.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/familienfreun.de",
    "dbtype": "mysql",
    "version": "18.0.5.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "default_language": "de",
    "tempdirectory": "\/www\/htdocs\/w0174798\/cloud\/tmp",
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "app_install_overwrite": [
        "calendar"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Chrome 83.0.4103.97

**Operating system:** win10

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by juliushaertl** [comment] 2020-06-12 20:12
Duplicate of https://github.com/nextcloud/deck/issues/1979

Fix in https://github.com/nextcloud/deck/pull/2021

**Closed by juliushaertl** 2020-06-12 20:12 UTC
