### ISSUE TITLE
Check Boxes in Description Disappear when making change. 

### ISSUE THREAD

**Issue by negativzeroe** [nextcloud/deck#2603] opened 2020-11-21 20:29 UTC
**Describe the bug**
Check Boxes in Description Disappear when making change. 
OR
Checking one box unchecks another and vice-versa.

**To Reproduce**
1. Go to Deck
2. Click on any card
3. Scroll down to Description
4. Make list in Markdown (using - [ ] )
5. Go to preview and check the box

**Expected behavior**
Box checks or unchecks

**Screenshots**

**Client details:**
Ubuntu 20.04
Firefox, Epiphany
83.0; 3.36.4

Desktop

**Operating system**: Debian Buster

**Web server:** Docker: Linuxserver/nextcloud

Postresql

**PHP version:**

20.0.2

**Where did you install Nextcloud from:** Docker Hub

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Enabled:
  - accessibility: 1.6.0
  - admin_audit: 1.10.0
  - apporder: 0.11.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.1
  - deck: 1.2.1
  - event_update_notification: 1.1.0
  - external: 3.7.1
  - extract: 1.2.5
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.1
  - files_automatedtagging: 1.10.0
  - files_fulltextsearch: 2.0.0
  - files_fulltextsearch_tesseract: 1.4.2
  - files_markdown: 2.3.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.1.1
  - guests: 1.6.1
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - metadata: 0.12.0
  - news: 15.0.6
  - nextbackup: 20.9.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - ocr: 6.0.57
  - onlyoffice: 6.1.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - previewgenerator: 3.0.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quota_warning: 1.9.1
  - rainloop: 7.0.3
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - side_menu: 1.20.1
  - spreed: 10.0.3
  - systemtags: 1.10.0
  - talk_matterbridge: 1.19.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_email: 1.0.1
  - twofactor_nextcloud_notification: 3.0.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - uploaddetails: 0.1.3
  - user_status: 1.0.1
  - video_converter: 0.1.5
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflow_script: 1.5.0
  - workflowengine: 2.2.0
Disabled:
  - activity
  - encryption
  - files_external
  - files_trackdownloads
  - ransomware_protection
  - recommendations
  - support
  - survey_client
  - user_ldap

```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.fontaineclan.net"
        ],
        "dbtype": "pgsql",
        "version": "20.0.2.2",
        "overwrite.cli.url": "https:\/\/cloud.fontaineclan.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": false,
        "installed": true,
        "maintenance": false,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 0,
        "app_install_overwrite": [
            "files_texteditor",
            "dropit",
            "uploaddetails",
            "sharerenamer",
            "twofactor_email",
            "files_fulltextsearch_tesseract",
            "ocr",
            "emlviewer"
        ],
        "mail_smtpsecure": "tls",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Image",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Font",
            "OC\\Preview\\MP3",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "has_rebuilt_cache": true,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
…)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
A whole bunch of this boostrap stuff:


{"reqId":"vUU1pdms4UPZ9TW11T1A","level":0,"time":"2020-11-21T20:27:53+00:00","remoteAddr":"172.20.0.14","user":"zeroe@mydomain.tld","app":"uploaddetails","method":"GET","url":"/apps/logreader/poll?lastReqId=YmiRvDJD4FvmGsPO5oAV","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"20.0.2.2"}
{"reqId":"vUU1pdms4UPZ9TW11T1A","level":0,"time":"2020-11-21T20:27:53+00:00","remoteAddr":"172.20.0.14","user":"zeroe@mydomain.tld","app":"video_converter","method":"GET","url":"/apps/logreader/poll?lastReqId=YmiRvDJD4FvmGsPO5oAV","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"20.0.2.2"}



```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...

```

</details>

**Comment by stefan-niedermann** [comment] 2020-11-21 21:10
Duplicate of https://github.com/nextcloud/deck/issues/2580, https://github.com/nextcloud/deck/issues/2591, #2595 and #2592 

[A fix](https://github.com/nextcloud/deck/pull/2584) is already in the pipeline.

You should be able to [restore the description content from the timeline tab](https://github.com/nextcloud/deck/issues/2580#issuecomment-730319105).

Please use the search function next time before open a new issue, thank you 🙂.

**Closed by stefan-niedermann** 2020-11-21 21:10 UTC

**Comment by negativzeroe** [comment] 2020-11-21 21:48
Sorry forgot to remove the is:open when I searched.
