### ISSUE TITLE
Deck card description is empty after saving it

### ISSUE THREAD

**Issue by ernieballslinky** [nextcloud/deck#2881] opened 2021-03-12 08:29 UTC
We are using Deck 1.2.5 and when we add both a due date and a description only the due date is commited (the description disappear). There is no error entry in the nextcloud logging system.

This is a blocking issue for our users.

**Comment by stefan-niedermann** [comment] 2021-03-12 08:44
Maybe a duplicate of https://github.com/nextcloud/deck/issues/2705

Please fill out the complete issue template, it is there for a reason.

**Comment by marcodegroot** [comment] 2021-03-20 15:26
Isn't this linked to #2789? It looks like the patch (#2793 ) failed to get to the 1.3 branch.

**Comment by szimszon** [comment] 2021-03-22 08:41
I have the same problem with NC21 and Deck 1.3.1... ;(

**Comment by juliushaertl** [comment] 2021-04-08 07:47
Should indeed be fixed with 1.3.2 by #2793 At least I cannot reproduce it anymore

**Closed by juliushaertl** 2021-04-08 07:47 UTC
