### ISSUE TITLE
A card with the deadline in past though moved to "Done" still keeps notifying about the deadline

### ISSUE THREAD

**Issue by piiskop** [nextcloud/deck#2576] opened 2020-11-18 09:15 UTC
### Steps to reproduce
1 Create a card and set a deadline for it!
2 Wait until the deadline passes!
3 Move the card to "Done"!
4 See that the notification with bell icon won't disappear!

### Expected behaviour
If the card is in "Done" then the action is done and there's no point to still notifiy about the deadline.

### Actual behaviour
If the card is in "Done" then notification is still be shown.

## Server configuration detail

**Operating system:** Linux 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** mysql 10.1.47

**PHP version:** 

7.2.24-0ubuntu0.18.04.7
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, imap, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 19.0.4 - 19.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
    [maps] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/Controller/RoutingController.php] => Array
                        (
                            [expected] => a76dc79838a1e32aceb8d4ec917062bbe8dfad71191e02f6b52520d222f15469d7475967645e1062b7e645cfa11adbb8c14b9b1e32fc6799217d28aa9e89a8f2
                            [current] => 5cbb4f7111ae93b0e9bdb9daf880acada819956940030a1b7eb3fa5d4125352e2f8e09f6c79b43c7683e8a4ba4db677bdf81194a4048609a68b1967d6db94e20
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.1
 - admin_audit: 1.9.0
 - audioplayer: 2.12.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.0.4
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - deck: 1.2.0
 - drawio: 0.9.7
 - drop_account: 0.2.1
 - emlviewer: 0.0.18
 - external: 3.6.0
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_automatedtagging: 1.9.0
 - files_external: 1.10.0
 - files_external_gdrive: 0.4.0
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_texteditor: 2.14.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - forms: 2.0.4
 - gpxmotion: 0.0.11
 - issuetemplate: 0.7.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - mail: 1.4.1
 - maps: 0.1.6
 - metadata: 0.12.0
 - nextcloud_announcements: 1.8.0
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - onlyoffice: 2.1.2
 - password_policy: 1.9.1
 - photos: 1.1.0
 - polls: 1.5.7
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - recommendations: 0.7.0
 - registration: 0.5.0
 - richdocuments: 3.7.9
 - scanner: 0.1.9
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - spreed: 9.0.6
 - support: 1.2.1
 - survey_client: 1.7.0
 - systemtags: 1.9.0
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - weather: 1.7.3
 - wopi: 3.5.6
 - workflowengine: 2.1.0
Disabled:
 - dicomviewer
 - encryption
 - ojsxc
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.tennis24.ee"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "19.0.4.2",
    "overwrite.cli.url": "https:\/\/test.tennis24.ee\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "app_install_overwrite": [
        "onlyoffice",
        "dashboard",
        "files_external_gdrive",
        "dicomviewer"
    ],
    "tempdirectory": "\/projektid\/nextcloud\/data",
    "overwriteprotocol": "https",
    "mysql.utf8mb4": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "has_rebuilt_cache": true
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by stefan-niedermann** [comment] 2020-11-18 09:48
Closing as duplicate of [#534 Mark card as done](https://github.com/nextcloud/deck/issues/534) - it isn't explicitly mentioned in the description, but has been discussed in the comments ([1](https://github.com/nextcloud/deck/issues/534#issuecomment-576752760), [2](https://github.com/nextcloud/deck/issues/534#issuecomment-582651776), [3](https://github.com/nextcloud/deck/issues/534#issuecomment-590005049)) and confirmed multiple times by @juliushaertl ([1](https://github.com/nextcloud/deck/issues/534#issuecomment-590113570), [2](https://github.com/nextcloud/deck/issues/534#issuecomment-647407232)).

**Closed by stefan-niedermann** 2020-11-18 09:48 UTC
