### ISSUE TITLE
Card details pop out / panel - Don't show on card single click

### ISSUE THREAD

**Issue by bsherwoodofdaptiv** [nextcloud/deck#2445] opened 2020-10-13 23:50 UTC
FEATURE request

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When clicking on a card, the card details panel automatically opens. I may just be trying to edit the card's title or move it somewhere else but have not started a DRAG action.

Oddly, the meatballs (ellipsis) menu has a "Card details" selection that does not work to open the pop out panel, but does work to close it again.

**Describe the solution you'd like**
I would love it if the details panel did not pop out automatically. Two solutions could be: Double click on the card to get the details panel. Or perhaps a icon (same gear icon in meatball menu?) on the card that opened the panel and reducing opening a menu to get at an option not related to the other menu actions

**Describe alternatives you've considered**
No other alternatives have been considered. (outside of going back to Trello... seriously who wants to do that?)

**Additional context**

**Comment by juliushaertl** [comment] 2020-10-15 12:03
I'm not sure if I get the issue correctly. Clicking on the title should not trigger the sidebar and dragging shouldn't as well. If they do that seems to be a bug but I cannot reproduce that. 

Other than that double click is not really an option imo since it is not really discoverable and a very uncommon pattern in web apps. I also don't see the need for another icon. With 1.1.2 we have a different cursor on the card depending if you hover the title or main card body so that indicates which action will be taken.

**Comment by hansimausisteffiwurstbrot** [comment] 2020-10-16 21:27
I think it appeared in our case with the last Update (to 1.1.2).

**Comment by juliushaertl** [comment] 2020-11-02 21:06
Any errors in the javascript console when the first click doesn't work?

**Comment by bsherwoodofdaptiv** [comment] 2020-11-09 17:46
It would appear that I have failed to communicate the 'feature request' correctly.

I do not want to see the 'details' card by default if I click on a card. I do not assign cards, since I am the only user. I do not add tags to my cards. I don't set due dates on my cards. All of those are great features when just the card title isn't enough. But not everyone needs those features. Ideally there should be either a toggleable persistent setting that lets you turn it off, or be something that you trigger the opening of with some sort of action (double click, icon, etc).

So, the panel does open. I do not want it to open. On a narrow screen or window, it takes up too much space. So, this is a 'feature request'.

(my new annoyance is the 'up coming cards' page opening when I go into DECK via the menu bar icon, instead of it persisting where I was last time. It is dependent on spending time putting dates on all of the cards, which I don't do. But that is a different feature request.)

**Comment by grossherr** [comment] 2020-11-17 11:17
I can confirm clicking »Card details« works for closing, but not for opening the panel.

Deck 1,2
Nextcloud 20.0.1

![2020-11-17_18-08](https://user-images.githubusercontent.com/32869105/99383375-59e74680-2900-11eb-8992-a5fbdba80942.png)
![2020-11-17_18-09](https://user-images.githubusercontent.com/32869105/99383380-5b187380-2900-11eb-805e-5cd05d0ab342.png)

**Comment by Dopeelf** [comment] 2021-04-16 14:51
I would also like a setting so that the details sidebar doesn't pop out when you click on a card or move it. I have the same use case as the original poster.


![01 Before dragging](https://user-images.githubusercontent.com/1270455/115042050-6b467600-9ed3-11eb-9bd9-b32e8d1b9e9f.png)
![02 After dragging](https://user-images.githubusercontent.com/1270455/115042055-6bdf0c80-9ed3-11eb-8daf-33d9c2f4aa5d.png)

**Comment by alexanderdd** [comment] 2021-07-06 12:01
related: https://github.com/nextcloud/deck/issues/1794

I think that the current situation (one click to open sidebar) is fine, but it should be easier to close the sidebar, like in the linked post. I think doubleclick is unituitive.

**Comment by bsherwoodofdaptiv** [comment] 2021-07-06 17:38
I'll agree with @alexanderdd  - Single clicking in any blank space should close the details box again. In doing so I am signaling intent to not interact with the pop-out / fly-out any more.

@Dopeelf  makes an interesting workaround. Having to block undesired actions is less than ideal, but if the only way to stop the dike from leaking is to put your finger in it, well....

This would make this the second element in a NextCloud application I would be having to override in the browser. Not something I really want to do. But, definitely an option. Great point @Dopeelf

**Comment by juliushaertl** [comment] 2022-08-09 06:41
This should be fixed by https://github.com/nextcloud/deck/pull/3916

**Closed by juliushaertl** 2022-08-09 06:41 UTC
Labels: enhancement, needs info
