### ISSUE TITLE
Blank Board details under Safari

### ISSUE THREAD

**Issue by EtiennePasteur** [nextcloud/deck#71] opened 2017-03-16 10:04 UTC
### Steps to reproduce

1. Open Safari Web Browser
2. Go to Deck app
3. Open a Board Details

![deck-issue-safari](https://cloud.githubusercontent.com/assets/11411695/23991038/3e7380fc-0a38-11e7-894e-f568f46aa827.jpeg)

### Expected behaviour
The board details should be visible (like under chrome or firefox)

### Actual behaviour
The board details is not visible, the panel is blank.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:**Apache

**Database:** MySQL

**PHP version:**7

**Server version:** 11.0.2 (stable)

**Deck version:** 0.1.1

**Updated from an older installed version or fresh install:** Updated

**Signing status:** 

```
No errors have been found.
```

**List of activated apps:**

```
  - activity: 2.4.1
  - admin_notifications: 1.0.0
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - calendar: 1.5.1
  - comments: 1.1.0
  - dav: 1.1.1
  - deck: 0.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - rainloop: 4.27.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc1fgv54ghl5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "207.154.204.96",
            "focus.sh",
            "cloud.focus.sh"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/207.154.204.96\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "mail_from_address": "etienne",
        "mail_smtpmode": "php",
        "mail_domain": "focus.sh",
        "theme": "",
        "loglevel": 2
    }
}
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:**

### Client configuration
**Browser:** Safari Version 10.0.3 (12602.4.8)

**Operating system:** MacOS 10.12.3 (16D32)

#### Web server error log
```
Nothing special
```

#### Log file (data/nextcloud.log)

```
Nothing special
```

#### Browser log

```
Nothing special
```

**Comment by juliushaertl** [comment] 2017-03-16 10:50
Thanks for reporting. This is a duplicate of https://github.com/nextcloud/deck/issues/49 and has already been fixed. Fix will be in the 0.1.2 coming soon.

**Closed by juliushaertl** 2017-03-16 10:50 UTC
