### ISSUE TITLE
Feature Request: Allow Setting Deck Card Tag Colors via Hex Codes

### ISSUE THREAD

**Issue by adshrest** [nextcloud/deck#5370] opened 2023-12-09 04:59 UTC
Description:
Currently, the Deck app provides a color-spectrum widget for setting tag colors, which is a point-and-click method. However, for users who prefer a more precise and alternative approach, it would be beneficial to allow the setting of tag colors via hex codes. This feature would offer a second method for setting tag colors, enabling users to input hex codes directly.

Proposal:
Introduce an input field in the tag color-setting widget that allows users to enter hex codes for the desired tag color. This input field should also support copying and pasting hex codes, facilitating consistency in tag colors across different cards.

Benefits:
Precision: Users can precisely set tag colors using hex codes, ensuring accuracy in color selection.
Consistency: The ability to copy and paste hex codes allows users to maintain consistent tag colors across multiple cards.

Attachment:
![NextCloud_Deck_Hex_Code_Input](https://github.com/nextcloud/deck/assets/30552592/661457ba-c1ba-4a38-a155-5a5b07de621b)

Offer of Assistance:
If the development team is open to this enhancement but currently occupied with other tasks, we would be willing to provide assistance in implementing this feature.

Thank you for considering this feature request!

**Comment by juliushaertl** [comment] 2023-12-09 08:57
This needs to be provided by the color picker in the component library, so closing as a duplicate of https://github.com/nextcloud-libraries/nextcloud-vue/issues/1687

**Closed** 2023-12-09 08:57 UTC
