### ISSUE TITLE
 Overlay error when assigning a tag to a Card

### ISSUE THREAD

**Issue by kevinelsenbach** [nextcloud/deck#4638] opened 2023-05-02 13:21 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

1. Go to Nextcloud Deck.
2. Check that you have a minimum of 6 Tags in your Nextcloud Deck
3. Open your Board
4. Open a Card
5. Select the Tag on the Deatails
6. You should see an Overlay Error

I hope that this get fixed soon. We can't see our Tags without 

![image](https://user-images.githubusercontent.com/132363278/235677023-8680fd10-b92e-4bef-8bfb-c3ac5036f1b9.png)
![image](https://user-images.githubusercontent.com/132363278/235677084-5a48321b-048a-48a0-b96e-9da1c23f35a9.png)

 - OS: Windows
 - Browser Chrome
 - Device: Terra Notebook

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

--> No errors have been found.
```

**List of activated apps:**
Nextcloud Deck

**Comment by juliushaertl** [comment] 2023-05-03 10:48
Duplicate of #4484

**Closed by juliushaertl** 2023-05-03 10:48 UTC
