### ISSUE TITLE
Auto refresh and warning if someone changed anything

### ISSUE THREAD

**Issue by master-m1000** [nextcloud/deck#591] opened 2018-08-18 21:09 UTC
My team and I have been using Deck for several days. In this short time we noticed a few things:

1. If you work together at the same time on a board, you ever have to refresh the site, to see what the others have changed.
2. If you want to edit something, but you didn't refresh the page before, you maybe overwrite something.

**My suggested solution:**
An auto refresh or an info bar at the top of the page, that something had changed would solve the first problem. If something would get overwritten, a dialog would be a good way to warn the user for loosing data.

Thanks

**Comment by juliushaertl** [comment] 2018-10-09 13:03
Thanks for your report. This is actually a duplicate of https://github.com/nextcloud/deck/issues/256

**Closed by juliushaertl** 2018-10-09 13:03 UTC
