### ISSUE TITLE
Title of Card is not displayed

### ISSUE THREAD

**Issue by fm-sys** [nextcloud/deck#2005] opened 2020-06-09 14:58 UTC
**Expected behavior**
Normaly, the title is also displayed in the right bar, but currently it's just blank...

**Screenshots**
![2020-06-09 16_43_31-VirtualBoxVM](https://user-images.githubusercontent.com/64581222/84163874-3c20d600-aa72-11ea-8654-3de247931661.png)

**Client details:**
-  OS: Windows 10
-  Browser: Firefox
-  Browser Version: 77.0.1 (64-Bit)
-  Device: Desktop
- Nextcloud Deck Version: 1.0.2

#### Browser log
```
nothing special, only some warnings...
```

**Comment by stefan-niedermann** [comment] 2020-06-09 15:04
Duplicate of https://github.com/nextcloud/deck/issues/1980

**Closed by stefan-niedermann** 2020-06-09 15:04 UTC
