### ISSUE TITLE
Real-time push updates

### ISSUE THREAD

**Issue by Nyco** [nextcloud/deck#2781] opened 2021-02-05 11:17 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Deck allows collaborative editing, but not in real-time: this sometimes leads to editing conflicts

**Describe the solution you'd like**
When I open a card, update the card's fields in real-time push, when someone else is editing it at the same time

**Describe alternatives you've considered**
Lock the card?

**Additional context**
Is it technically feasible?

**Comment by stefan-niedermann** [comment] 2021-02-05 15:13
Please use the search function before opening new issues.

Duplicate of https://github.com/nextcloud/deck/issues/256

**Closed by stefan-niedermann** 2021-02-05 15:13 UTC
