### ISSUE TITLE
Description fails to load while editing

### ISSUE THREAD

**Issue by ampoz** [nextcloud/deck#1917] opened 2020-05-17 18:41 UTC
**Describe the bug**
When in edit mode, clicking on another card sometimes the description of the old card stays.

**To Reproduce**
Edit a card with a empty description, write in a description, wait for it to save, click on a second card, then on a third card; the description of the second card now keeps showing even though we are on the third card.
Clicking on a fourth card updates the description correctly to that fourth cards' description, but then clicking on a fifth card shows the fourth card's description. Clicking on a sixth and seventh card, etc, usually keeps showing the fourth card description, but sometimes it "loops" again and updates the description to the x'th card and then keeps showing the x'th card description when changing cards again. Haven't found what causes the description to sometimes be carried over for 2+ cards and sometimes only for 1 card. If we exit edit mode (click on the "View description" icon), then the description updates and correctly shows the current cards' description and then clicking on card always shows the correct description (thus this issue only applies while in edit mode, when in view mode everything loads as expected).

**Expected behavior**
Expectation is to be able to stay in "edit mode" and switch cards and edit the newly selected card so we can easily edit many cards in a row. Or, changing cards should automatically switch to view mode (but staying in edit mode seems preferable to us).

**Client details:**
 - Browser: Firefox 75
 - OS: Windows, Linux

<details>
<summary>Server details</summary>

**Nextcloud version:** 18.0.4

</details>

<details>
<summary>Logs</summary>

#### Browser log
```
Insert your browser log here, this could for example include:

Throughout all of this, sometimes we also get this error (uncertain if related) after clicking on a card. Like the description above, this only happens while switching cards in edit mode, but it doesn't happen on every card switch (haven't noticed a pattern):
TypeError: "e is null"
    De codemirror.js:681
    splitLines codemirror.js:6460
    setValue codemirror.js:6114
    ni codemirror.js:3942
    value easymde.js:2488
    value VueEasyMDE.common.js:2773
    VueJS 4

```

</details>

**Comment by stefan-niedermann** [comment] 2020-05-17 18:45
Might be a duplicate of https://github.com/nextcloud/deck/issues/1910

Have you tried to do a hard refresh with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd>?

**Comment by ampoz** [comment] 2020-05-17 18:53
I have tried a hard refresh and issue stays the same. Might be related to #1910; I hadn't noticed before, but on the first card we edit we get the same issue (description goes blank, no cursor), but then switching back to view mode and then to edit, the description shows up and is editable. Every other card after that has normal behavior when going from view mode to edit mode; it is only the first card after a refresh / going into the deck app for which this happens.

**Comment by reox** [comment] 2020-05-18 08:54
I noticed that too: When I have the details open of an existing card, and create a new card - sometimes the old description would be still visible with the new title in the details. But I can not reproduce this on purpose.

**Comment by juliushaertl** [comment] 2020-05-18 11:13
```
Throughout all of this, sometimes we also get this error (uncertain if related) after clicking on a card. Like the description above, this only happens while switching cards in edit mode, but it doesn't happen on every card switch (haven't noticed a pattern):
TypeError: "e is null"
    De codemirror.js:681
    splitLines codemirror.js:6460
    setValue codemirror.js:6114
    ni codemirror.js:3942
    value easymde.js:2488
    value VueEasyMDE.common.js:2773
    VueJS 4

``` 

Seems interesting, but let's close this as a duplicate of #1910 and continue over there.

**Closed by juliushaertl** 2020-05-18 11:13 UTC
