### ISSUE TITLE
recurrent boards

### ISSUE THREAD

**Issue by mihai-satmarean** [nextcloud/deck#1738] opened 2020-04-21 09:07 UTC
**Is your feature request related to a problem? Please describe.**
Hi, very nice app, we are exercising to use it with our modern kids.
In the context of Coronavirus, our kids are forced in homeschooling for more than 2 months now.
We would like to be able to track homework and other tasks by Nextcloud Decks.
We have shared it with the parents and we would like to have the recurring boards.

**Describe the solution you'd like**
We would like to have the recurring boards, for example we have daily tasks that we would like to be checked after completion.
The same tasks should be re-activated next day.
There should be possible to have a report for tasks missed per day, week or month.
The schedule should be possible like a cron, to be able to select variable patterns for repetition.

**Describe alternatives you've considered**
we were looking at Trello, but we like the privacy of nextcloud

**Additional context**
Willing to provide testing and more ideas.

Many thanks!

**Comment by jakobroehrl** [comment] 2020-04-29 09:00
Hi, 
in the 1.0 version you can clone boards. Does this help you out?
But unfortunately the containing cards aren't cloned.

**Comment by mihai-satmarean** [comment] 2020-05-06 08:27
Hi, thanks for looking into it.
The board cloning does not help much.
The desired functionality, would be to be able to create "templates" that can be cloned on demand, or by cron job.
The deck would be displayed on some tablet screen, waiting for the things to be dragged kanban style to finished.
The same deck content would be cloned next day and so on.
Please let me know if this helps.

**Comment by jakobroehrl** [comment] 2020-05-06 08:31
OK, would functions on clone boards are missing? 
Cloning cards, too?

**Comment by mihai-satmarean** [comment] 2020-05-06 08:53
I think the simplest iteration so far would be:
After creating a board with cards and all content should be possible to clone that either to 
- a "Board template" that can be used to clone new boards from it.
- just a new board

**Comment by juliushaertl** [comment] 2020-05-15 19:48
Let me close this as a duplicate of #154 which is currently not on our roadmap, but as described the board cloning should already help to cover the use case as far as i can see.

**Closed by juliushaertl** 2020-05-15 19:48 UTC
