### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by flogee** [nextcloud/deck#2151] opened 2020-07-29 13:06 UTC
It would be very helpful to boost our productivity if it was possible to add custom attributes, for instance a dropdown with set options or custom textfields to all cards within a board.

**Comment by stefan-niedermann** [comment] 2020-07-29 13:12
Dear @flogee,

this is a duplicate of #1833. Please use the search function first, before opening new issues and also please use the issue template next time :slightly_smiling_face: 

Regards

**Closed by stefan-niedermann** 2020-07-29 13:12 UTC
