### ISSUE TITLE
Attached file from NC storage deleting when removing sharing from card

### ISSUE THREAD

**Issue by LazyGatto** [nextcloud/deck#3222] opened 2021-08-02 20:19 UTC
### Steps to reproduce
1. Attach file from NC storage.
2. Reopen Deck to see that file successfully attached to card.
3. Remove attachment from card
Result - File moved to Trash bin from its original location.
--
PS If you try to remove sharing from file itself in Files app - then in card no file attached - but card shows attachment icon on board view.

### Expected behaviour
As result it supposed to be just removing sharing for this file. And not deleting the attached file itself from its original location.

### Actual behaviour
Attached file removed from card and actually moved to Trash bin from its original location.

## Server configuration detail

**Operating system:** Linux 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64

**Webserver:** nginx/1.14.2 (fpm-fcgi)

**Database:** mysql 10.3.29

**PHP version:** 

7.3.29-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 22.0.0 - 22.0.0.11

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** tar.gz

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.15.0
 - admin_audit: 1.11.0
 - apporder: 0.13.0
 - approval: 1.0.4
 - breezedark: 22.0.0
 - bruteforcesettings: 2.2.0
 - calendar: 2.3.1
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 4.0.1
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.18.0
 - deck: 1.5.0
 - drawio: 1.0.1
 - external: 3.9.0
 - extract: 1.3.2
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_accesscontrol: 1.12.0
 - files_automatedtagging: 1.12.0
 - files_fulltextsearch: 22.0.0
 - files_pdfviewer: 2.3.0
 - files_retention: 1.11.0
 - files_rightclick: 1.1.0
 - files_sharing: 1.13.2
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.11.0
 - flow_notifications: 1.2.0
 - fulltextsearch: 22.0.0
 - fulltextsearch_elasticsearch: 22.0.0
 - groupfolders: 9.0.2
 - impersonate: 1.9.0
 - issuetemplate: 0.7.0
 - logreader: 2.7.0
 - lookup_server_connector: 1.9.0
 - mail: 1.10.2
 - maps: 0.1.9
 - metadata: 0.14.0
 - nextcloud_announcements: 1.11.0
 - notifications: 2.10.1
 - oauth2: 1.9.0
 - onlyoffice: 7.1.0
 - password_policy: 1.12.0
 - photos: 1.4.0
 - privacy: 1.6.0
 - provisioning_api: 1.11.0
 - quota_warning: 1.11.0
 - recommendations: 1.1.0
 - serverinfo: 1.12.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - side_menu: 1.25.2
 - spreed: 12.0.1
 - systemtags: 1.11.0
 - tasks: 0.14.0
 - text: 3.3.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.1
 - twofactor_totp: 6.1.0
 - unsplash: 1.2.3
 - updatenotification: 1.11.0
 - user_ldap: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.6.0
 - weather_status: 1.1.0
 - whiteboard: 0.0.3
 - workflow_ocr: 1.22.1
 - workflow_script: 1.7.0
 - workflowengine: 2.3.0
Disabled:
 - circles
 - encryption
 - files_external
 - firstrunwizard
 - support
 - survey_client

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "trusted_domains": [
        "*****",
        "10.1.20.72",
        "10.1.20.73"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "objectstore": {
        "class": "\\OC\\Files\\ObjectStore\\S3",
        "arguments": {
            "bucket": "*****",
            "autocreate": true,
            "key": "***REMOVED SENSITIVE VALUE***",
            "secret": "***REMOVED SENSITIVE VALUE***",
            "hostname": "*****",
            "port": 9000,
            "use_ssl": true,
            "region": "optional",
            "use_path_style": true
        }
    },
    "log_type": "file",
    "logfile": "\/var\/www\/nextcloud\/data\/nextcloud.log",
    "logfilemode": 432,
    "loglevel": 3,
    "logdateformat": "F d, Y H:i:s",
    "dbtype": "mysql",
    "version": "22.0.0.11",
    "overwrite.cli.url": "https:\/\/*****\/",
    "overwriteprotocol": "https",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED_FOR",
        "HTTP_X_REAL_IP"
    ],
    "htaccess.RewriteBase": "\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "skeletondirectory": "",
    "allow_local_remote_servers": true,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "app_install_overwrite": [
        "fulltextsearch",
        "fulltextsearch_elasticsearch",
        "files_fulltextsearch",
        "groupfolders",
        "whiteboard",
        "radio",
        "forms",
        "files_fulltextsearch_tesseract",
        "camerarawpreviews",
        "ldapcontacts",
        "issuetemplate"
    ],
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\HEIC",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\Krita",
        "OC\\Preview\\TIFF"
    ]
}
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15

**Comment by stefan-niedermann** [comment] 2021-08-02 20:22
Duplicate of https://github.com/nextcloud/deck/issues/2877

Please use the 🔍  search function before opening new issues 🙂

**Closed by stefan-niedermann** 2021-08-02 20:22 UTC
