### ISSUE TITLE
Add the ability to sort lists similar to how they can be filtered.

### ISSUE THREAD

**Issue by 31337-4554551n** [nextcloud/deck#5484] opened 2024-01-16 06:30 UTC
**Is your feature request related to a problem? Please describe.**
When using long and complex boards, it can be difficult to look through for certain cards. Filtering and searching isn't appropriate in all situations. It would be easier to have the cards sorted so simple scrolling and eyeballing could easily find what is needed.

**Describe the solution you'd like**
The ability to sort lists-alphabetically (and reverse alphabetically if it's a simple addon) by clicking an option instead of manually dragging around dozens of cards. This also lets users drag cards around freely-then order it again.

**Describe alternatives you've considered**
Manually dragging cards around to arrange lists.

**Comment by stefan-niedermann** [comment] 2024-01-16 09:27
Possible pitfalls which came to my mind while thinking about it:
- Drag and Drop must at least be disabled when dragging within the same list (or alternatively completely like in Upcoming cards view)
- The behaviour when dragging a card to another list must be specified (should the list scroll to the (according to the sorting) correct position or no animation at all? How to visually indicate that it actually works in the latter case?
- Which actual real world scenario makes sense to sort a list reverse alphabetically? No offence, but *if* further sorting options are implemented, then they should be useful (like due date ascending) and not any random inverse sorts just because it might be technically easy. Each further sort option clutters the UI and hides more important stuff.

**Comment by stefan-niedermann** [comment] 2024-01-19 09:44
Closing as duplicate of #2111 where the same issues have been discussed (like dragging behavior, inverse sorts, ...)

**Closed by stefan-niedermann** 2024-01-19 09:44 UTC
