### ISSUE TITLE
Card detail view limited to the Description field

### ISSUE THREAD

**Issue by Th3Ph4nt0m** [nextcloud/deck#2808] opened 2021-02-16 14:46 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
The "Set a due date" dialog opens correctly. The size of the card view seems to be limited to the "Description" field. If you click in the Description field, everything works correctly, otherwise the due-date-dialog is only half-displayed and you need to scroll down to see the whole dialog.
-> This only happens in the "Card details PopUp" and not in the sidebar!

**To Reproduce**
1. Go to a card detail view.
2. Click on 'Set a due date'.
5. Click in the "Description" field
6. See the expected behavior

**Expected behavior**
The card detail view should not be limited to the "collapsed" Description field. See points 5-6 above.

**Screenshots**
<img src="https://user-images.githubusercontent.com/44142235/108075246-71061380-706a-11eb-836b-1cd01197dd00.png" width=600>

**Client details:**
 - OS: Ubuntu 20.4 as well as Windows 10
 - Browser `Firefox Developer Edition 86.0b9` as well as `Chrome 88.0.4324.150`
 - Device: Desktop (25 Inches as well as 14 Inches monitor)

<details>
<summary>Server details</summary>

**Operating system**:
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1028-raspi aarch64)

**Web server:**
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2020-08-12T19:46:17

**Database:**
Default

**PHP version:**
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
**Nextcloud version:** (see Nextcloud admin page)
20.0.7

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/latest.tar.bz2

**Signing status:**
??

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.4
  - drawio: 0.9.8
  - external: 3.7.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - impersonate: 1.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - encryption
  - files_external
  - side_menu
  - tasks
  - timemanager
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.7.1",
        "overwrite.cli.url": "***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
not needed
```

#### Browser log
```
not needed


```

</details>

**Comment by Th3Ph4nt0m** [comment] 2021-02-16 14:48
This may be related to #2617 and can be allocated to #2423

**Comment by dodedodo** [comment] 2021-03-24 18:29
Duplicate of #2704

**Closed** 2021-03-24 18:47 UTC
