### ISSUE TITLE
Bad Update on TAG appearance!!! Please revert back!!!

### ISSUE THREAD

**Issue by rprpx** [nextcloud/deck#1907] opened 2020-05-16 11:42 UTC
I believe the very large tags (huge corner radius, a lot of padding) in the updated design do not look becoming and professional, and do not make economic use of space.  

Additionally, the tags now appear to use only 1 line, rather than multiple lines as in the past, even if there are several tags applied to a card.  So, if several tags are applied to a card, I can no longer read all the tags at a glance, making them less-than-useful.

Please consider refining the tag changes. The way the tags were before the latest overhaul was perfect in my opinion.

**Comment by bpcurse** [comment] 2020-05-16 13:25
This seems to be a duplicate of #1872

**Closed** 2020-05-18 07:21 UTC
