### ISSUE TITLE
Give the user an option to return to board, not default ot upcoming cards

### ISSUE THREAD

**Issue by rightsaidfred99** [nextcloud/deck#4372] opened 2023-01-08 03:14 UTC
I think some users will never use upcoming cards, but individual boards. 
I think it would be great to have a little setting in Deck, whereby a user can choose the default landing page for Deck. 

Upcoming cards
Use last view
Use "x" board

**Comment by stefan-niedermann** [comment] 2023-01-08 09:27
Please use the 🔍 search function before opening new issues.

Closing as duplicate of https://github.com/nextcloud/deck/issues/2590

**Closed by stefan-niedermann** 2023-01-08 09:27 UTC

**Comment by alvarofranz** [comment] 2023-02-13 17:36
The linked issue is not a duplicate. This issue is different.

> Linked is about showing the board list on load.
> This issue is about showing a default board on load.
