### ISSUE TITLE
Can't create new labels

### ISSUE THREAD

**Issue by dtcg** [nextcloud/deck#2930] opened 2021-03-31 22:32 UTC
After selecting a card, when typing a new entry in the label text box, the "+" sign appears but nothing happens when clicking it.

**Client details:**
 - OS: linux
 - Browser firefox 87.0
 - Device: desktop

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

I'm a mere user, not an admin of: 

https://data.tedomum.net AND https://framadrive.org

**Nextcloud version:** 
20.0.8.1 AND 17.0.0.9

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by stefan-niedermann** [comment] 2021-04-01 06:45
Duplicate of https://github.com/nextcloud/deck/issues/1472

**Closed by stefan-niedermann** 2021-04-01 06:45 UTC
