### ISSUE TITLE
Can't see images' preview in attachments of web Deck instance

### ISSUE THREAD

**Issue by neerro** [nextcloud/deck#2645] opened 2020-12-11 12:20 UTC
**Describe the bug**
There are have no possibility to see the preview images when files (for example .jpg) attached to tasks.

**To Reproduce**
I've attached the screenshots is self explanatory the issue.

**Expected behavior**
I suppose that it's necessary feature to get possibility an overview quickly attached files. It will absolutely exclude the operation regarding opening files separately one by one. 

**Screenshots**
![deck](https://user-images.githubusercontent.com/75830569/101902202-53788180-3bc3-11eb-8b2d-511d2b2d8ce6.jpg)

**Client details:**
 - OS: Windows 10 (latest)
 - Browser Firefox (latest)

**Comment by stefan-niedermann** [comment] 2020-12-11 12:40
While it is a confirmed bug in the Android app, it is no bug in the web UI - the feature has just not yet been implemented in the web UI.

Therefore this issue is a duplicate of https://github.com/nextcloud/deck/issues/972

The base work is currently done, so we should track this further in #972 🙂

**Closed by stefan-niedermann** 2020-12-11 12:40 UTC

**Comment by neerro** [comment] 2020-12-11 13:58
Ok. Thanks. Waiting for fixing this issue for Android and I pretty hope we'll see this implementation in web UI in close future.
