### ISSUE TITLE
Lost all data when update to 0.4.0

### ISSUE THREAD

**Issue by jmym** [nextcloud/deck#528] opened 2018-07-12 05:53 UTC
**Describe the bug**
Lost all data when update to 0.4.0, and can't add more items.

**To Reproduce**
1. Go to 'update in application notification'
2. Click on 'update'
3. Goto Deck app.
4. See error, the data it's lost.

**Expected behavior**

**Screenshots**

**Client details:**
 - OS: Windows 10
 - Browser chrome
 - Version 67.0.3396.99
 - Device:  desktop

<details>
<summary>Server details</summary>

**Operating system**:
Raspbian
**Web server:**
apache2
**Database:**
mariadb
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
13
**Where did you install Nextcloud from:**
From raspberry pi
**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - audioplayer: 2.3.1
  - calendar: 1.6.1
  - comments: 1.3.0
  - dav: 1.4.7
  - deck: 0.4.0
  - external: 3.0.3
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_automatedtagging: 1.3.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - flowupload: 0.0.7
  - gallery: 18.0.0
  - keeporsweep: 0.1.6
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - nextant: 1.0.9
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - ocdownloader: 1.5.6
  - ojsxc: 3.4.1
  - password_policy: 1.3.0
  - phonetrack: 0.2.8
  - provisioning_api: 1.3.0
  - qownnotesapi: 17.5.0
  - quicknotes: 0.1.3
  - radio: 0.6.1
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - spreed: 3.2.3
  - spreedme: 0.3.11
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - unsplash: 1.1.1
  - updatenotification: 1.3.0
  - user_external: 0.4
  - weather: 1.5.1
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_inotify
  - user_ldap

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment] 2018-07-12 05:54
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/nextcloud/deck/pull/524 (Prepare 0.4.0 release), https://github.com/nextcloud/deck/issues/231 (The style is broken after update to 0.2.1), https://github.com/nextcloud/deck/issues/502 (line feed in decription of cards after update to deck 0.4.0-beta2), https://github.com/nextcloud/deck/issues/517 (wrong target of link of release 0.4.0-beta4?), and https://github.com/nextcloud/deck/issues/340 (Maintenance mode on Nextcloud 12.0.3 during update).

**Comment by jmym** [comment] 2018-07-12 06:15
The register show me this message:
Level | App | Message | Time
-- | -- | -- | --
Error | PHP | RedisException: read error on connection at /var/www/html/nextcloud/lib/private/Memcache/Redis.php#54 | 2018-07-12T07:40:25+0200

Error | index | Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT `configvalue` FROM `oc_preferences` WHERE `userid` = ? AND `appid`='ojsxc' AND `configkey`='longpolling'' with params ["j"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away | 2018-07-12T07:40:24+0200

Error | PHP | Error while sending QUERY packet. PID=7037 at /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#105 | 2018-07-12T07:40:24+0200

**Comment by juliushaertl** [comment] 2018-07-12 06:35
@jmym First of all there is no indication that the data is lost. I'd assume it just fails to display. Please check the nextcloud log for errors related to the deck app. 

Could you post the full error message including the backtrace for the messages you have posted? You can just go to the data folder of your nextcloud and check the nextcloud.log file for more detailed messages.

**Comment by jmym** [comment] 2018-07-12 07:51
{"reqId":"RTATBKDZaP0LHQ5WIKAV","level":3,"time":"2018-07-12T05:40:24+00:00","remoteAddr":"146.158.241.x","user":"j***","app":"PHP","method":"POST","url":"\/nextcloud\/index.php\/apps\/ojsxc\/http-bind","message":"Error while sending QUERY packet. PID=7037 at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.4.0"}
{"reqId":"RTATBKDZaP0LHQ5WIKAV","level":3,"time":"2018-07-12T05:40:24+00:00","remoteAddr":"146.158.241.x","user":"j***","app":"index","method":"POST","url":"\/nextcloud\/index.php\/apps\/ojsxc\/http-bind","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'SELECT `configvalue` FROM `oc_preferences` WHERE `userid` = ? AND `appid`='ojsxc' AND `configkey`='longpolling'' with params [\\\"jmhome\\\"]:\\n\\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `configv...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/ojsxc\\\/lib\\\/dblock.php(57): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/ojsxc\\\/lib\\\/Controller\\\/HttpBindController.php(240): OCA\\\\OJSXC\\\\DbLock->stillLocked()\\n#4 [internal function]: OCA\\\\OJSXC\\\\Controller\\\\HttpBindController->index()\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\OJSXC\\\\Controller\\\\HttpBindController), 'index')\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\OJSXC\\\\Controller\\\\HttpBindController), 'index')\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('HttpBindControl...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/apps\\\/ojsxc\\\/htt...')\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(42): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.4.0"}
{"reqId":"RTATBKDZaP0LHQ5WIKAV","level":3,"time":"2018-07-12T05:40:25+00:00","remoteAddr":"146.158.241.x","user":"j***","app":"PHP","method":"POST","url":"\/nextcloud\/index.php\/apps\/ojsxc\/http-bind","message":"RedisException: read error on connection at \/var\/www\/html\/nextcloud\/lib\/private\/Memcache\/Redis.php#54","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.4.0"}

**Comment by juliushaertl** [comment] 2018-07-12 07:56
There is still nothing deck related. The last message seems to be caused by an error to the redis cache, which might be a reason why fetching the data with 0.4.0 fails. Can you check your setup and see if redis is setup correctly? You can also try to disable redis temporarily to see if this causes the issue.

Are there any other errors in the Nextcloud log?

**Comment by jmym** [comment] 2018-07-12 10:10
Ok, i disabled the memcache and repair Redis and not show errors, and activate the Redis. But Deck don't show me anything. And can't to create more labels. 
I Disable the Deck, in apps, and activate and nothing, occurs. All it's empty.

**Comment by juliushaertl** [comment] 2018-07-12 10:17
Can you check the browser console log for errors? Should work by pressing F12 before opening the deck app. Please report what is listed there when opening deck and trying to create labels.

**Comment by juliushaertl** [comment] 2018-07-12 12:10
Thanks @jmym, I have an idea where this might come from but I'm still unable to reproduce. Can you check the source code of the deck app page by pressing Ctrl+U in your browser, search for `config="` and paste that line?

**Comment by jmym** [comment] 2018-07-12 13:59
var
oc_config={"session_lifetime":1440,"session_keepalive":true,"version":"13.0.4.0","versionstring":"13.0.4","enable_avatars":true,"lost_password_link":null,"modRewriteWorking":false,"sharing.maxAutocompleteResults":0,"sharing.minSearchStringLength":0,"blacklist_files_regex":"\\.(part|filepart)$"};

var
oc_appconfig={"core":{"defaultExpireDateEnabled":false,"defaultExpireDate":null,"defaultExpireDateEnforced":null,"enforcePasswordForPublicLink":false,"enableLinkPasswordByDefault":false,"sharingDisabledForUser":false,"resharingAllowed":true,"remoteShareAllowed":true,"federatedCloudShareDoc":"https:\/\/
docs.nextcloud.com
\/server\/13\/go.php?to=user-sharing-federated","allowGroupSharing":true},"files":{"max_chunk_size":524288000},"shareByMailEnabled":true,"shareByMail":{"enforcePasswordProtection":false},"comments":{"maxAutoCompleteResults":10}};

var
oc_defaults={"entity":"Nextcloud","name":"Nextcloud","title":"Nextcloud","baseUrl":"https:\/\/
nextcloud.com","syncClientUrl":"https:\/\/nextcloud.com
\/install\/#install-clients","docBaseUrl":"https:\/\/docs.nextcloud.com
","docPlaceholderUrl":"https:\/\/docs.nextcloud.com\/server\/13\/go.php?to=PLACEHOLDER","slogan":"un
hogar seguro para todos tus datos","logoClaim":"","shortFooter":"<a
href=\"https:\/\/nextcloud.com\" target=\"_blank\" rel=\"noreferrer
noopener\">Nextcloud<\/a> \u2013 un hogar seguro para todos tus
datos","longFooter":"<a href=\"https:\/\/nextcloud.com\" target=\"_blank\"
rel=\"noreferrer noopener\">Nextcloud<\/a> \u2013 un hogar seguro para
todos tus datos","folder":""};

var oc_userconfig={"avatar":{"version":1,"generated":false}};

Another Line:
<div id="app" class="app-deck" data-ng-app="Deck" ng-controller="
AppController" ng-cloak config="">

**Comment by juliushaertl** [comment] 2018-07-12 14:07
@jmym https://github.com/nextcloud/deck/pull/529/files should fix the issue. Do you have the chance to test this?

**Comment by jmym** [comment] 2018-07-12 14:20
Yes, now it's working correctly. I recovery my labels.

**Comment by juliushaertl** [comment] 2018-07-12 14:43
Thanks @jmym This will be fixed in the next release.

**Closed by juliushaertl** 2018-07-12 14:43 UTC
Labels: needs info
