### ISSUE TITLE
Optional parameter $userId declared before required parameter $path is implicitly treated as a required parameter at ConfigService.php#234

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/deck#5969] opened 2024-06-07 06:02 UTC
I have got the closed bug https://github.com/nextcloud/deck/pull/5794 in Nextcloud 29.0.2 . If i install the app deck i get directly this log entry:

`Optional parameter $userId declared before required parameter $path is implicitly treated as a required parameter at /var/www/virtual/username/html/cloud/apps/deck/lib/Service/ConfigService.php#234`

**Describe the bug**

**To Reproduce**
1. uninstall app deck
2. install app deck
3. error in logfile see above

**Expected behavior**
No error

**Client details:**
 - OS: not relevant
 - Browser: not relevant
 - Version: not relevant
 - Device: not relevant

<details>
<summary>Server details</summary>

Server infos from phpinfo():

**Operating system**:
Red Hat Enterprise Linux Server release 7.9 (Maipo) 
**Web server:**
Apache/2.4.59 (Unix)
**Database:**
only found: mysqlnd 8.1.29 
**PHP version:**
PHP Version 8.1.29
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 29.0.2
**Where did you install Nextcloud from:**
Nextcloud upgrade from older versions (here Nextcloud 29.0.1)
**Signing status:**

`

</details>

**Comment by RainerEmrich** [comment] 2024-06-07 13:53
Same as #5938

**Comment by joshtrichards** [comment] 2024-06-08 19:28
Duplicate of #5793 

The fix is merged but we need to roll a new release with it still.

**Closed** 2024-06-08 19:34 UTC

**Comment by Githopp192** [comment] 2024-07-14 20:21
[PHP] Error: Optional parameter $userId declared before required parameter $path is implicitly treated as a required parameter at /var/www/html/nextcloud/apps/deck/lib/Service/ConfigService.php#234

at 2024-07-14T22:10:03+02:00

Nextcloud version:27.1.11.3
Red Hat Enterprise Linux release 8.10 (Ootpa)
10.6.18-MariaDB,
Apache/2.4.37
PHP 8.2.20
