### ISSUE TITLE
Image on Card ? a picture is worth a thousand words! 🖼

### ISSUE THREAD

**Issue by dualizeo** [nextcloud/deck#4723] opened 2023-05-22 19:21 UTC
Setting an Image on a card communicates the project instantly instead of reading, is this feature a work in progress ? Sorry to ask but I couldn't find anything when I searched for image.

a picture is worth a thousand words! 🖼
Thanks for your time!

**Comment by juliushaertl** [comment] 2023-05-22 20:29
Closing as a duplicate of #1635

**Closed by juliushaertl** 2023-05-22 20:29 UTC
