### ISSUE TITLE
Unable to save changes after typing a card with more than 851 words, 4956 chars

### ISSUE THREAD

**Issue by llzzrrdd** [nextcloud/deck#4803] opened 2023-06-11 19:56 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Unable to save changes after typing a card with more than 851 words, 4956 chars

**To Reproduce**
1. Go to 'Deck'
2. Click on 'New Card'
3. Type more than 851 words, 4956 chars
4. See error in logs: "[deck] Error: OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[54000]: Program limit exceeded: 7 ERROR:  index row size 2712 exceeds btree version 4 maximum 2704 for index "idx_last_editor""

**Expected behavior**
To continue being able to type more in the card.

**Screenshots**
N/A

**Client details:**
 - OS: [Windows 11 Pro / 22H2 / 22621.1778]
 - Browser [Firefox]
 - Version [114.0.1]
 - Device: [desktop]

<details>
<summary>Server details</summary>

**Operating system**: Ubuntu 22.04.2 LTS / 5.15.0-73-generic

**Web server:** Apache/2.4.52 (Ubuntu)

**Database:** psql (PostgreSQL) 14.8 

**PHP version:** PHP 8.1.2-1ubuntu2.11 

**Nextcloud version:** [Nextcloud Hub 4] (26.0.2)

**Where did you install Nextcloud from:** Hansson IT   https://docs.hanssonit.se/s/bj0vl1ihv0jgrmfm08j0/build-your-own/d/bj0vl4ahv0jgrmfm0950/nextcloud-vm

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.


No errors have been found.

```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder




root@nextcloud01:~# sudo -u www-data php --define apc.enable_cli=1 /var/www/nextcloud/occ app:list
Enabled:
  - activity: 2.18.0
  - admin_audit: 1.16.0
  - calendar: 4.4.1
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - collectives: 2.5.0
  - comments: 1.16.0
  - contacts: 5.3.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - deck: 1.9.2
  - external: 5.1.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_external: 1.18.0
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - mail: 3.2.0
  - nextcloud_announcements: 1.15.0
  - notes: 4.7.2
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recognize: 4.1.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - spreed: 16.0.4
  - support: 1.9.0
  - survey_client: 1.14.0
  - systemtags: 1.16.0
  - tasks: 0.15.0
  - text: 3.7.2
  - theming: 2.1.1
  - timemanager: 0.3.7
  - twofactor_backupcodes: 1.15.0
  - twofactor_totp: 8.0.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - bruteforcesettings: 2.6.0
  - encryption: 2.14.0
  - extract: 1.3.5
  - pdfannotate: 0.0.11
  - suspicious_login: 4.4.0
  - user_ldap: 1.16.0




```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder



root@nextcloud01:~# sudo -u www-data php --define apc.enable_cli=1 /var/www/nextcloud/occ config:list
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "IPADDRESS",
            "FQDN",
            "FQDN"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "26.0.2.1",
        "overwrite.cli.url": "https:\/\/FQDN\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "upgrade.disable-web": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": "1800",
        "log_rotate_size": "0",
        "trashbin_retention_obligation": "auto, 60",
        "versions_retention_obligation": "auto, 180",
        "activity_expire_days": "120",
        "simpleSignUpLink.shown": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "default_phone_region": "us",
        "logtimezone": "Europe\/Athens",
        "htaccess.RewriteBase": "\/",
        "preview_concurrency_new": "8",
        "preview_concurrency_all": "16",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    },
    "apps": {
        "activity": {
            "installed_version": "2.18.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "admin_audit": {
            "installed_version": "1.16.0",
            "types": "logging",
            "enabled": "yes",
            "logfile": "\/var\/log\/nextcloud\/audit.log"
        },
        "backgroundjob": {
            "lastjob": "1"
        },
        "calendar": {
            "installed_version": "4.4.1",
            "types": "",
            "enabled": "yes"
        },
        "circles": {
            "installed_version": "26.0.0",
            "types": "filesystem,dav",
            "enabled": "yes",
            "loopback_tmp_scheme": "https",
            "loopback_tmp_path": "\/",
            "migration_22": "1",
            "migration_run": "0",
            "maintenance_run": "0",
            "maintenance_update": "{\"3\":1686513003,\"2\":1686512703,\"1\":1686513003}"
        },
        "cloud_federation_api": {
            "installed_version": "1.9.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "collectives": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "2.5.0"
        },
        "comments": {
            "installed_version": "1.16.0",
            "types": "logging",
            "enabled": "yes"
        },
        "contacts": {
            "types": "dav",
            "enabled": "yes",
            "installed_version": "5.3.0"
        },
        "contactsinteraction": {
            "installed_version": "1.7.0",
            "types": "dav",
            "enabled": "yes"
        },
        "core": {
            "installedat": "1681402965.0868",
            "oc.integritycheck.checker": "[]",
            "vendor": "nextcloud",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "backgroundjobs_mode": "cron",
            "lastupdatedat": "1686511520",
            "lastupdateResult": "[]",
            "moveavatarsdone": "yes",
            "previewsCleanedUp": "1",
            "emailTestSuccessful": "1",
            "lastcron": "1686513003"
        },
        "dashboard": {
            "installed_version": "7.6.0",
            "types": "",
            "enabled": "yes"
        },
        "dav": {
            "installed_version": "1.25.0",
            "types": "filesystem",
            "enabled": "yes",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "buildCalendarSearchIndex": "yes",
            "buildCalendarReminderIndex": "yes"
        },
        "deck": {
            "types": "dav",
            "enabled": "yes",
            "installed_version": "1.9.2"
        },
        "external": {
            "jwt_token_privkey_es256": "-----BEGIN PRIVATE KEY----------END PRIVATE KEY-----\n",
            "jwt_token_pubkey_es256": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDGkqoq+vwMcnmLRNW\/QUnofLnB8k\nkrdCelDt4pFo5Fn8zk+3bpGYIkbRD2I0YG7Bds6elatD8dFnG4CZyLKJjQ==\n-----END PUBLIC KEY-----\n",
            "installed_version": "5.1.0",
            "types": "",
            "enabled": "yes"
        },
        "federatedfilesharing": {
            "installed_version": "1.16.0",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "1.16.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.21.1",
            "types": "filesystem",
            "enabled": "yes",
            "max_chunk_size": "104857600"
        },
        "files_external": {
            "installed_version": "1.18.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_pdfviewer": {
            "installed_version": "2.7.0",
            "types": "",
            "enabled": "yes"
        },
        "files_rightclick": {
            "installed_version": "1.5.0",
            "types": "",
            "enabled": "yes"
        },
        "files_sharing": {
            "installed_version": "1.18.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_trashbin": {
            "installed_version": "1.16.0",
            "types": "filesystem,dav",
            "enabled": "yes"
        },
        "files_versions": {
            "installed_version": "1.19.1",
            "types": "filesystem,dav",
            "enabled": "yes"
        },
        "firstrunwizard": {
            "installed_version": "2.15.0",
            "types": "logging",
            "enabled": "yes"
        },
        "logreader": {
            "installed_version": "2.11.0",
            "types": "",
            "enabled": "yes"
        },
        "lookup_server_connector": {
            "installed_version": "1.14.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "mail": {
            "installed_version": "3.2.0",
            "types": "",
            "enabled": "yes"
        },
        "nextcloud_announcements": {
            "installed_version": "1.15.0",
            "types": "logging",
            "enabled": "yes",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200"
        },
        "notes": {
            "installed_version": "4.7.2",
            "types": "",
            "enabled": "yes"
        },
        "notifications": {
            "installed_version": "2.14.0",
            "types": "logging",
            "enabled": "yes"
        },
        "oauth2": {
            "installed_version": "1.14.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "password_policy": {
            "installed_version": "1.16.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "photos": {
            "installed_version": "2.2.0",
            "types": "dav,authentication",
            "enabled": "yes",
            "lastPlaceMappedUser": "ncadm",
            "lastPlaceMappingDone": "true"
        },
        "privacy": {
            "installed_version": "1.10.0",
            "types": "",
            "enabled": "yes",
            "readableLocation": "gr"
        },
        "provisioning_api": {
            "installed_version": "1.16.0",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "recognize": {
            "installed_version": "4.1.0",
            "node_binary": "\/var\/www\/nextcloud\/apps\/recognize\/bin\/node",
            "types": "filesystem,dav",
            "enabled": "yes"
        },
        "recommendations": {
            "installed_version": "1.5.0",
            "types": "",
            "enabled": "yes"
        },
        "related_resources": {
            "installed_version": "1.1.0-alpha1",
            "types": "",
            "enabled": "yes"
        },
        "serverinfo": {
            "installed_version": "1.16.0",
            "types": "",
            "enabled": "yes",
            "cached_count_filecache": "82365",
            "cached_count_storages": "5"
        },
        "settings": {
            "installed_version": "1.8.0",
            "types": "",
            "enabled": "yes"
        },
        "sharebymail": {
            "installed_version": "1.16.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "spreed": {
            "installed_version": "16.0.4",
            "signaling_token_privkey_es256": "***REMOVED SENSITIVE VALUE***",
            "has_reference_id": "yes",
            "signaling_token_pubkey_es256": "***REMOVED SENSITIVE VALUE***",
            "signaling_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "dav,prevent_group_restriction",
            "project_access_invalidated": "1",
            "enabled": "yes",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "turn_servers": "***REMOVED SENSITIVE VALUE***"
        },
        "support": {
            "installed_version": "1.9.0",
            "types": "session",
            "enabled": "yes",
            "SwitchUpdaterServerHasRun": "yes"
        },
        "survey_client": {
            "installed_version": "1.14.0",
            "types": "",
            "enabled": "yes"
        },
        "systemtags": {
            "installed_version": "1.16.0",
            "types": "logging",
            "enabled": "yes"
        },
        "tasks": {
            "installed_version": "0.15.0",
            "types": "",
            "enabled": "yes"
        },
        "text": {
            "installed_version": "3.7.2",
            "types": "dav",
            "enabled": "yes"
        },
        "theming": {
            "installed_version": "2.1.1",
            "types": "logging",
            "enabled": "yes",
            "productName": "Nextcloud HanssonIT VM"
        },
        "timemanager": {
            "installed_version": "0.3.7",
            "types": "",
            "enabled": "yes"
        },
        "twofactor_backupcodes": {
            "installed_version": "1.15.0",
            "types": "",
            "enabled": "yes"
        },
        "twofactor_totp": {
            "installed_version": "8.0.0",
            "types": "",
            "enabled": "yes"
        },
        "updatenotification": {
            "installed_version": "1.16.0",
            "types": "",
            "enabled": "yes",
            "notify_groups": "[\"admin\"]",
            "tasks": "0.15.0",
            "calendar": "4.4.1",
            "recognize": "4.1.0",
            "core": "26.0.2.1",
            "contacts": "5.3.0",
            "mail": "3.2.0",
            "update_check_errors": "0",
            "collectives": "2.5.0",
            "deck": "1.9.2"
        },
        "user_status": {
            "installed_version": "1.6.0",
            "types": "",
            "enabled": "yes"
        },
        "viewer": {
            "installed_version": "1.10.0",
            "types": "",
            "enabled": "yes"
        },
        "weather_status": {
            "installed_version": "1.6.0",
            "types": "",
            "enabled": "yes"
        },
        "workflowengine": {
            "installed_version": "2.8.0",
            "types": "filesystem",
            "enabled": "yes"
        }
    }
}


or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
[deck] Error: OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[54000]: Program limit exceeded: 7 ERROR:  index row size 2712 exceeds btree version 4 maximum 2704 for index "idx_last_editor"
DETAIL:  Index row references tuple (4,47) in relation "oc_deck_cards".
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing. at <<closure>>

 0. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 328
    OC\DB\Exceptions\DbalException::wrap()
 1. /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 220
    OC\DB\QueryBuilder\QueryBuilder->executeStatement()
 2. /var/www/nextcloud/apps/deck/lib/Db/CardMapper.php line 123
    OCP\AppFramework\Db\QBMapper->update("*** sensitive parameters replaced ***")
 3. /var/www/nextcloud/apps/deck/lib/Service/CardService.php line 350
    OCA\Deck\Db\CardMapper->update("*** sensitive parameters replaced ***")
 4. /var/www/nextcloud/apps/deck/lib/Controller/CardController.php line 98
    OCA\Deck\Service\CardService->update("*** sensitive parameters replaced ***")
 5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Deck\Controller\CardController->update("*** sensitive parameters replaced ***")
 6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
 7. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
 8. /var/www/nextcloud/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
 9. /var/www/nextcloud/lib/base.php line 1058
    OC\Route\Router->match()
10. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

Caused by:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[54000]: Program limit exceeded: 7 ERROR:  index row size 2712 exceeds btree version 4 maximum 2704 for index "idx_last_editor"
DETAIL:  Index row references tuple (4,47) in relation "oc_deck_cards".
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing. at <<closure>>

 0. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1814
    Doctrine\DBAL\Driver\API\PostgreSQL\ExceptionConverter->convert()
 1. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1749
    Doctrine\DBAL\Connection->handleDriverException()
 2. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1163
    Doctrine\DBAL\Connection->convertExceptionDuringQuery()
 3. /var/www/nextcloud/lib/private/DB/Connection.php line 295
    Doctrine\DBAL\Connection->executeStatement()
 4. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 354
    OC\DB\Connection->executeStatement()
 5. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 280
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 326
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 220
    OC\DB\QueryBuilder\QueryBuilder->executeStatement()
 8. /var/www/nextcloud/apps/deck/lib/Db/CardMapper.php line 123
    OCP\AppFramework\Db\QBMapper->update("*** sensitive parameters replaced ***")
 9. /var/www/nextcloud/apps/deck/lib/Service/CardService.php line 350
    OCA\Deck\Db\CardMapper->update("*** sensitive parameters replaced ***")
10. /var/www/nextcloud/apps/deck/lib/Controller/CardController.php line 98
    OCA\Deck\Service\CardService->update("*** sensitive parameters replaced ***")
11. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Deck\Controller\CardController->update("*** sensitive parameters replaced ***")
12. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
13. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
14. /var/www/nextcloud/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
15. /var/www/nextcloud/lib/base.php line 1058
    OC\Route\Router->match()
16. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

Caused by:

Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[54000]: Program limit exceeded: 7 ERROR:  index row size 2712 exceeds btree version 4 maximum 2704 for index "idx_last_editor"
DETAIL:  Index row references tuple (4,47) in relation "oc_deck_cards".
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing. at <<closure>>

 0. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php line 103
    Doctrine\DBAL\Driver\PDO\Exception::new()
 1. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1153
    Doctrine\DBAL\Driver\PDO\Statement->execute()
 2. /var/www/nextcloud/lib/private/DB/Connection.php line 295
    Doctrine\DBAL\Connection->executeStatement()
 3. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 354
    OC\DB\Connection->executeStatement()
 4. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 280
    Doctrine\DBAL\Query\QueryBuilder->execute()
 5. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 326
    OC\DB\QueryBuilder\QueryBuilder->execute()
 6. /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 220
    OC\DB\QueryBuilder\QueryBuilder->executeStatement()
 7. /var/www/nextcloud/apps/deck/lib/Db/CardMapper.php line 123
    OCP\AppFramework\Db\QBMapper->update("*** sensitive parameters replaced ***")
 8. /var/www/nextcloud/apps/deck/lib/Service/CardService.php line 350
    OCA\Deck\Db\CardMapper->update("*** sensitive parameters replaced ***")
 9. /var/www/nextcloud/apps/deck/lib/Controller/CardController.php line 98
    OCA\Deck\Service\CardService->update("*** sensitive parameters replaced ***")
10. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Deck\Controller\CardController->update("*** sensitive parameters replaced ***")
11. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
12. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
13. /var/www/nextcloud/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
14. /var/www/nextcloud/lib/base.php line 1058
    OC\Route\Router->match()
15. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

Caused by:

PDOException: SQLSTATE[54000]: Program limit exceeded: 7 ERROR:  index row size 2712 exceeds btree version 4 maximum 2704 for index "idx_last_editor"
DETAIL:  Index row references tuple (4,47) in relation "oc_deck_cards".
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing. at <<closure>>

 0. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php line 101
    PDOStatement->execute()
 1. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1153
    Doctrine\DBAL\Driver\PDO\Statement->execute()
 2. /var/www/nextcloud/lib/private/DB/Connection.php line 295
    Doctrine\DBAL\Connection->executeStatement()
 3. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 354
    OC\DB\Connection->executeStatement()
 4. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 280
    Doctrine\DBAL\Query\QueryBuilder->execute()
 5. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 326
    OC\DB\QueryBuilder\QueryBuilder->execute()
 6. /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 220
    OC\DB\QueryBuilder\QueryBuilder->executeStatement()
 7. /var/www/nextcloud/apps/deck/lib/Db/CardMapper.php line 123
    OCP\AppFramework\Db\QBMapper->update("*** sensitive parameters replaced ***")
 8. /var/www/nextcloud/apps/deck/lib/Service/CardService.php line 350
    OCA\Deck\Db\CardMapper->update("*** sensitive parameters replaced ***")
 9. /var/www/nextcloud/apps/deck/lib/Controller/CardController.php line 98
    OCA\Deck\Service\CardService->update("*** sensitive parameters replaced ***")
10. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Deck\Controller\CardController->update("*** sensitive parameters replaced ***")
11. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
12. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
13. /var/www/nextcloud/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
14. /var/www/nextcloud/lib/base.php line 1058
    OC\Route\Router->match()
15. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

PUT /apps/deck/cards/66
from IPADDRESS by USERNAME at 2023-06-11T22:30:01+03:00
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by joshtrichards** [comment] 2024-10-02 15:25
Duplicate of #4015
Fixed in #5260

**Closed by joshtrichards** 2024-10-02 15:25 UTC
Labels: bug, feature: modal
