### ISSUE TITLE
Date picker and content underflowing in popover editor

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/deck#3172] opened 2021-07-07 11:13 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

**To Reproduce**
1. Go to a board
2. Click on a card
3. Editor opens
4. Click on the due date so the datepicker opens

**Expected behavior**
Everything is visible

**Screenshots**
![Bildschirmfoto von 2021-07-07 13-10-00](https://user-images.githubusercontent.com/213943/124749732-e5135c00-df24-11eb-8823-461e707ac26b.png)

**Client details:**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 89
 - Device: Desktop

**Server details**

Company instance

**Comment by stefan-niedermann** [comment] 2021-07-07 11:57
Duplicate of #2704

**Closed by stefan-niedermann** 2021-07-07 11:57 UTC
Labels: 1. to develop, bug, feature: modal
