### ISSUE TITLE
Share with group ist kaput

### ISSUE THREAD

**Issue by 9662** [nextcloud/deck#218] opened 2017-06-27 08:34 UTC
### Steps to reproduce
1. Create a deck
2. Click on details → share
3. From the share list, select a group (*not* a user)

### Expected behaviour
The deck should be shared with all members of the selected group, a group icon should be shown.

### Actual behaviour
I have not checked if the other members of the group do have access, but no group icon is shown (broken image link).

This refers to Deck version 0.2.0 on Nextcloud 11.0.3.

**Comment by juliushaertl** [comment] 2017-06-27 11:41
Can you post a screenshot of where the image is not loaded? I cannot reproduce any issue with group sharing using Nextcloud 12 and Deck 0.2.0. I'll try this later on Nc11.

**Comment by 9662** [comment] 2017-07-05 14:21
> Can you post a screenshot of where the image is not loaded?

Yup.

From `/apps/deck/#!/board/:board_id//detail/`

![screenshot_20170705_155355](https://user-images.githubusercontent.com/13080040/27867942-68e7656e-619b-11e7-8267-919921b34b5c.png)

The second user with the broken icon is a group. Note that neither an icon nor the group's name appear.

Likewise, from `/apps/deck/#!/`

![screenshot_20170705_155328](https://user-images.githubusercontent.com/13080040/27868029-be13f43a-619b-11e7-98f1-54f00cb51182.png)

The middle one is the board in the previous screenshot. The bottom one is another board which has been shared with an individual user as opposed to a group.

These screenshots were just taken on NC11 using Deck 0.2.1 (just [upgraded](https://github.com/nextcloud/deck/issues/227)).

**Comment by 9662** [comment] 2017-07-05 14:24
> I'll try this later on Nc11.

Personally, if the problem is confined to NC11, I'm not sure if it's worth fixing. Just my opinion.

**Comment by juliushaertl** [comment] 2017-07-06 11:24
@9662 I cannot reproduce this on NC11 here. Are you using any custom user backend? Is it possible that the group that the board is assigned to doesn't exist anymore?

**Comment by 9662** [comment] 2017-07-06 13:46
@juliushaertl No, just the standard backend. The group does exist, with both me and other active users being members of it.

I will upgrade to NC12 in the next few days/weeks and report back. I guess this issue may be closed as a “can't reproduce” in the meanwhile, if it makes your life easier?

**Comment by juliushaertl** [comment] 2017-07-06 13:54
Ok, feel free to reopen then. :wink:

**Closed by juliushaertl** 2017-07-06 13:54 UTC
Labels: 0. Needs triage
