### ISSUE TITLE
Template for cards on each board

### ISSUE THREAD

**Issue by ZamanOof** [nextcloud/deck#3242] opened 2021-08-09 19:54 UTC
Hello,
It would be nice to have a standard template  for hole group or each board.

> why?

**because it make it easier to direct the work or task in one path or direction, or some time need to pin check list as standard to look at issue ,feature or idea etc..
mean as when open github post..**

Best Regards

**Comment by stefan-niedermann** [comment] 2021-08-10 07:10
Closing as duplicate of https://github.com/nextcloud/deck/issues/1556 - please use the 🔍 search function before opening new issues 🙂

**Closed** 2021-08-10 07:11 UTC
