### ISSUE TITLE
Well integration of Deck with Task app 

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/deck#2820] opened 2021-02-21 12:53 UTC
**Is your feature request related to a problem? Please describe.**
I liked Deck very much and I and my friends are using it very well. But one feature am requesting here is that, Whenever someone assigns some task to some other guy it just appears on tasks app without bein editable. What I was thinking in mind is that if it is possible to edit tasks that have been assigned to me, that way a person gave me the task see my progressions while I update the task which then directly synced to Deck to change the statuses.

**Comment by stefan-niedermann** [comment] 2021-02-21 13:00
Might be related (or even a duplicate of) https://github.com/nextcloud/deck/issues/2399

**Comment by juliushaertl** [comment] 2021-04-14 16:21
Yes, is a duplicate of #2399

**Closed by juliushaertl** 2021-04-14 16:21 UTC
