### ISSUE TITLE
Nextcloud 23 not showing Shares - Shared by me

### ISSUE THREAD

**Issue by apg1980** [nextcloud/deck#3464] opened 2021-11-30 14:32 UTC
mariadb 10.5.13
php8.0.13
Apache
ubuntu 20.04 lts

![grafik](https://user-images.githubusercontent.com/9514965/144066397-2652dae9-41c0-4311-9ebb-bed860b39d90.png)
....with a tons of shares

**Comment by juliushaertl** [comment] 2021-11-30 15:56
FYI @mejo- @azul For the collectives exception trace. Though it then looks unrelated to the issue that is disappearing when deck is disabled. Could you see if there is any other error message when loading the Shared with me page?

**Comment by juliushaertl** [comment] 2021-11-30 15:57
Also please report which version of deck you are using and maybe check the just release 1.6.0 to see if this also shows up the issue.

**Comment by azul** [comment] 2021-11-30 16:07
Let's format the trace a bit:
```json
{
   "app" : "no app in context",
   "exception" : {
      "Code" : 0,
      "CustomMessage" : "--",
      "Exception" : "Exception",
      "File" : "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
      "Line" : 158,
      "Message" : "OCA\\Collectives\\Db\\CollectiveShareMapper::deleteByToken(): Argument nextcloud/server#1 ($token) must be of type string, null given, called in /var/www/nextcloud/apps/collectives/lib/Listeners/ShareDeletedListener.php on line 30 in file '/var/www/nextcloud/apps/collectives/lib/Db/CollectiveShareMapper.php' line 125",
      "Previous" : {
         "Code" : 0,
         "Exception" : "TypeError",
         "File" : "/var/www/nextcloud/apps/collectives/lib/Db/CollectiveShareMapper.php",
         "Line" : 125,
         "Message" : "OCA\\Collectives\\Db\\CollectiveShareMapper::deleteByToken(): Argument nextcloud/server#1 ($token) must be of type string, null given, called in /var/www/nextcloud/apps/collectives/lib/Listeners/ShareDeletedListener.php on line 30",
         "Trace" : [
            {
               "class" : "OCA\\Collectives\\Db\\CollectiveShareMapper",
               "file" : "/var/www/nextcloud/apps/collectives/lib/Listeners/ShareDeletedListener.php",
               "function" : "deleteByToken",
               "line" : 30,
               "type" : "->"
            },
            {
               "class" : "OCA\\Collectives\\Listeners\\ShareDeletedListener",
               "file" : "/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php",
               "function" : "handle",
               "line" : 87,
               "type" : "->"
            },
            {
               "class" : "OC\\EventDispatcher\\ServiceEventListener",
               "file" : "/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
               "function" : "__invoke",
               "line" : 251,
               "type" : "->"
            },
            {
               "class" : "Symfony\\Component\\EventDispatcher\\EventDispatcher",
               "file" : "/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
               "function" : "callListeners",
               "line" : 73,
               "type" : "->"
            },
            {
               "class" : "Symfony\\Component\\EventDispatcher\\EventDispatcher",
               "file" : "/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php",
               "function" : "dispatch",
               "line" : 88,
               "type" : "->"
            },
            {
               "class" : "OC\\EventDispatcher\\EventDispatcher",
               "file" : "/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php",
               "function" : "dispatch",
               "line" : 100,
               "type" : "->"
            },
            {
               "class" : "OC\\EventDispatcher\\EventDispatcher",
               "file" : "/var/www/nextcloud/lib/private/Share20/Manager.php",
               "function" : "dispatchTyped",
               "line" : 1210,
               "type" : "->"
            },
            {
               "class" : "OC\\Share20\\Manager",
               "file" : "/var/www/nextcloud/apps/files_sharing/lib/Controller/ShareAPIController.php",
               "function" : "deleteShare",
               "line" : 415,
               "type" : "->"
            },
            {
               "class" : "OCA\\Files_Sharing\\Controller\\ShareAPIController",
               "file" : "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
               "function" : "deleteShare",
               "line" : 217,
               "type" : "->"
            },
            {
               "class" : "OC\\AppFramework\\Http\\Dispatcher",
               "file" : "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
               "function" : "executeController",
               "line" : 126,
               "type" : "->"
            },
            {
               "class" : "OC\\AppFramework\\Http\\Dispatcher",
               "file" : "/var/www/nextcloud/lib/private/AppFramework/App.php",
               "function" : "dispatch",
               "line" : 157,
               "type" : "->"
            },
            {
               "class" : "OC\\AppFramework\\App",
               "file" : "/var/www/nextcloud/lib/private/Route/Router.php",
               "function" : "main",
               "line" : 302,
               "type" : "::"
            },
            {
               "class" : "OC\\Route\\Router",
               "file" : "/var/www/nextcloud/ocs/v1.php",
               "function" : "match",
               "line" : 62,
               "type" : "->"
            },
            {
               "args" : [
                  "/var/www/nextcloud/ocs/v1.php"
               ],
               "file" : "/var/www/nextcloud/ocs/v2.php",
               "function" : "require_once",
               "line" : 23
            }
         ]
      },
      "Trace" : [
         {
            "class" : "OC\\AppFramework\\Http\\Dispatcher",
            "file" : "/var/www/nextcloud/lib/private/AppFramework/App.php",
            "function" : "dispatch",
            "line" : 157,
            "type" : "->"
         },
         {
            "class" : "OC\\AppFramework\\App",
            "file" : "/var/www/nextcloud/lib/private/Route/Router.php",
            "function" : "main",
            "line" : 302,
            "type" : "::"
         },
         {
            "class" : "OC\\Route\\Router",
            "file" : "/var/www/nextcloud/ocs/v1.php",
            "function" : "match",
            "line" : 62,
            "type" : "->"
         },
         {
            "args" : [
               "/var/www/nextcloud/ocs/v1.php"
            ],
            "file" : "/var/www/nextcloud/ocs/v2.php",
            "function" : "require_once",
            "line" : 23
         }
      ]
   },
   "id" : "61a639834a059",
   "level" : 3,
   "message" : "OCA\\Collectives\\Db\\CollectiveShareMapper::deleteByToken(): Argument nextcloud/server#1 ($token) must be of type string, null given, called in /var/www/nextcloud/apps/collectives/lib/Listeners/ShareDeletedListener.php on line 30 in file '/var/www/nextcloud/apps/collectives/lib/Db/CollectiveShareMapper.php' line 125",
   "method" : "DELETE",
   "remoteAddr" : "---",
   "reqId" : "9CwZYoHmz2hzfQF4Njh5",
   "time" : "2021-11-30T15:47:24+01:00",
   "url" : "/ocs/v2.php/apps/files_sharing/api/v1/shares/2168",
   "user" : "---",
   "userAgent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0",
   "version" : "23.0.0.10"
}

```

**Comment by azul** [comment] 2021-11-30 16:16
Tracking the collectives issue here: https://gitlab.com/collectivecloud/collectives/-/issues/265

**Comment by mejo-** [comment] 2021-12-01 11:56
I wonder how the described issue and the posted error backtrace belong to each other.

@apg1980 the error suggests that you tried to *delete* a share, right? During this operation, for some reason the error that you posted above happened. We're working on a fix for this in the Collectives app: https://gitlab.com/collectivecloud/collectives/-/merge_requests/431

@apg1980 could you please try to reproduce the error with empty share list one more time? First re-enable the deck app, then go to the shares list and if it's still empty, look again whether a new error got logged to the Nextcloud logs?

For discovering the correct log entries, it helps to first open the log file and watch it live while doing the action that is supposed to trigger the error. In the terminal this can be done with `tail -f <path-to-logfile>`.

**Comment by apg1980** [comment] 2021-12-02 06:36
Hi i can confirm, my shares disappear after enabling latest deck app 1.6

`{"reqId":"d0tZn90bSLCyhmyVyNHG","level":3,"time":"2021-12-02T07:34:54+01:00","remoteAddr":"---","user":"---","app":"no app in context","method":"GET","url":"/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json&shared_with_me=false&include_tags=true","message":"Did expect one result but found none when executing: query \"SELECT * FROM `*PREFIX*deck_cards` WHERE `id` = :dcValue1 ORDER BY `order` ASC, `id` ASC\"; ","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0","version":"23.0.0.10","exception":{"Exception":"OCP\\AppFramework\\Db\\DoesNotExistException","Message":"Did expect one result but found none when executing: query \"SELECT * FROM `*PREFIX*deck_cards` WHERE `id` = :dcValue1 ORDER BY `order` ASC, `id` ASC\"; ","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php","line":361,"function":"findOneQuery","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/nextcloud/apps/deck/lib/Db/CardMapper.php","line":140,"function":"findEntity","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/nextcloud/apps/deck/lib/Sharing/ShareAPIHelper.php","line":56,"function":"find","class":"OCA\\Deck\\Db\\CardMapper","type":"->"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/Controller/ShareAPIController.php","line":316,"function":"formatShare","class":"OCA\\Deck\\Sharing\\ShareAPIHelper","type":"->"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/Controller/ShareAPIController.php","line":873,"function":"formatShare","class":"OCA\\Files_Sharing\\Controller\\ShareAPIController","type":"->"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/Controller/ShareAPIController.php","line":815,"function":"getFormattedShares","class":"OCA\\Files_Sharing\\Controller\\ShareAPIController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"getShares","class":"OCA\\Files_Sharing\\Controller\\ShareAPIController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->"}],"File":"/var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php","Line":283,"CustomMessage":"--"},"id":"61a86940e6678"}`

**Comment by juliushaertl** [comment] 2021-12-02 08:29
Thanks for that, I edited your post to make it more readable for later reference.

**Comment by apg1980** [comment] 2022-03-24 06:33
Hello the issue is still present in nc 23.0.3 with latest app version of deck.

**Comment by fmakira** [comment] 2022-08-22 12:21
hi,  issue  still present in nc 24.0.4 with deck 1.7.1.

**Comment by tjareson** [comment] 2022-09-18 09:59
I'm not sure if that is directly related: the nextcloud iPhone app shows me a "Share 500 internal server error" everytime I open the nextcloud app. But all folders are visible. 
In the log I see combined with this error message:
OCP\AppFramework\Db\DoesNotExistException: Did expect one result but found none when executing: query "SELECT * FROM `*PREFIX*deck_cards` WHERE `id` = :dcValue1 ORDER BY `order` ASC, `id` ASC"; 

If I disable the deck app, the error msg disappears.  
Deck version 1.7.1 on nextcloud 24.0.5

**Comment by fmakira** [comment] 2022-09-18 13:18
Exactly this

Il Dom 18 Set 2022, 11:59 tjareson ***@***.***> ha scritto:

**Comment by apg1980** [comment] 2022-10-27 12:41
Hi, any updates here? issue still exists on nc 25 with Deck 1.8.1

**Comment by fmakira** [comment] 2022-10-27 15:51
Same for me, but I noticed that it happened only for few users. Perhaps
something in the db is the cause,  like invalid mountpoints... need further
investigation.

Il Gio 27 Ott 2022, 14:41 apg1980 ***@***.***> ha scritto:

**Comment by mtalmont** [comment] 2022-12-01 15:48
I have got the same issue : Did expect one result but found none when executing: query \"SELECT * FROM `*PREFIX*deck_cards` WHERE `id` = :dcValue1 ORDER BY `order` ASC, `id` ASC\"; "

NC 24.0.7 DECK version : 1.7.3

**Comment by kdoteu** [comment] 2023-01-04 07:39
Same error still appears on NC 25.0.2 Deck Version: 1.8.3

```
OCP\AppFramework\Db\DoesNotExistException: Did expect one result but found none when executing: query "SELECT * FROM `*PREFIX*deck_cards` WHERE `id` = :dcValue1 ORDER BY `order` ASC, `id` ASC"; 
```

Found the error in combination with my QOwnNotes Sync. The sync stopped working quite a while ago and I wanted to give an other shot. So I tackeled the problem down to this error message and disabled Deck. Now my sync is working again ...

**Comment by juliushaertl** [comment] 2023-01-04 08:12
Can you share the full log line as json? That should give better hints on where the error actually happens

**Comment by ptandler** [comment] 2023-01-05 17:28
I also came accross this via QOwnNotes Sync, NC 24.0.8, Deck 1.7.3

**Comment by ptandler** [comment] 2023-01-05 17:31
> Same for me, but I noticed that it happened only for few users. Perhaps something in the db is the cause, like invalid mountpoints... need further investigation.

Anything I can assist in debugging?

**Comment by roo-punch** [comment] 2023-02-14 14:03
I arrived here via issues with QOwnNotes, am seeing this same error, on Nextcloud 25, Deck version 1.8.3

**Closed** 2023-03-29 09:00 UTC
Labels: bug, 1. to develop, bug: regression
