### ISSUE TITLE
Deck, board templates, or clone board with cards.

### ISSUE THREAD

**Issue by rwslippey** [nextcloud/deck#5042] opened 2023-08-20 18:03 UTC
Small workflow improvement request/idea.

In  my case I use decks to track tasks for projects. These projects are repetitive in nature. Meaning they are the same process every time.

Ideally, I'd like to be able to create a board as a template and clone this board every time I need to create a new project that runs through the same workflow. However, I've noticed that doing so does not copy the cards, just the board/lists.

Alternatively, export/import could work as well, however I'm not seeing import functionality in the UI yet.

**Comment by juliushaertl** [comment] 2023-08-21 09:01
Thanks for the suggestion. Please check existing tickets next time, as this is actually a duplicate of https://github.com/nextcloud/deck/issues/2797

**Closed by juliushaertl** 2023-08-21 09:01 UTC
