### ISSUE TITLE
Timeline incomplete since last update

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/deck#5261] opened 2023-11-06 20:47 UTC
**Describe the bug**
If I open a card and switch to timeline not all entries are loaded. Sometimes two entries, sometimes 6 entries but not all.

**To Reproduce**
1. Go to Deck
2. Click on a card
3. Click on timeline
4. Not all timeline entries are loaded, loading circle are everytime visible but nothing happens

**Expected behavior**
All entries are visible

**Screenshots**
![image](https://github.com/nextcloud/deck/assets/1473674/7a6ce05e-39b4-411c-9f03-cac30bb6b763)

**Client details:**
 - OS: Windows 10 and Windows 11
 - Browser: Microsoft Edge
 - Version 119
 - Device: DELL Notebook

**Operating system**:
Ubuntu 20.04

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
8.2

**Nextcloud version:** (see Nextcloud admin page)
27.1.3

**Comment by juliushaertl** [comment] 2023-11-07 20:38
Duplicate of https://github.com/nextcloud/deck/issues/3395 looks like fetching is not working as expected there

**Closed by juliushaertl** 2023-11-07 20:38 UTC
