### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by TheACF** [nextcloud/deck#3647] opened 2022-03-17 08:23 UTC
I am using deck very much and the overview is already overloaded, i want to request if it is (or would be) possible to group the Boards with Categories or something to get only the "categorie" in view i need at the moment.

**Comment by stefan-niedermann** [comment] 2022-03-17 09:07
Duplicate of https://github.com/nextcloud/deck/issues/2006

**Closed by stefan-niedermann** 2022-03-17 09:07 UTC
