### ISSUE TITLE
Enhancement: Add options to copy a board

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/deck#767] opened 2018-12-06 13:39 UTC
I'd like to propose a feature that allows you to copy an entire board. This would be quite helpful in cases where you want to have something like a "template board" that models a certain type of project. If you have a new project of the same kind, just copy the template, give it a new name and start your work...

**Comment by juliushaertl** [comment] 2018-12-07 09:01
Thans for your feature request. This is somehow a duplicate of #154 so I'm closing this one.

**Closed by juliushaertl** 2018-12-07 09:01 UTC
