### ISSUE TITLE
Caldav board sabre 404

### ISSUE THREAD

**Issue by mebitek** [nextcloud/deck#4724] opened 2023-05-23 12:49 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
I'm writing a client to integrate with nextcloud deck app. I'm able to get all VTODO into my app but when I try to update one of them I get this error 

<error xmlns="DAV:">
                             │                  <exception xmlns="http://sabredav.org/ns">Sabre\DAV\Exception\NotFound</exception>
                             │                  <message xmlns="http://sabredav.org/ns">Node with name &#39;card-58.ics&#39; could not be found</message>
                             │               </error>

I can see this error also if I use curl:
curl -v --user "*****:******" https://nextcloud.mebitek.com/remote.php/dav/calendars/mebitek/app-generated--deck--board-1/card-58.ics -T ~/Scaricati/card-58.ics

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Node with name 'card-58.ics' could not be found</s:message>
</d:error>

if I try to edit something form another calendar that supports VTODO all works fine.
it seems that it is the "app-generated--deck--board-1" that is causing the problem

**To Reproduce**
1. make a PUT call to an existing vtodo card

**Expected behavior**
I can edit the VTODO

**Screenshots**

**Client details:**
 - OS: Linux
 - Browser curl/go webdav client
 - Version deck version 1.9
 - Device: laptop

```

</details>

**Comment by stefan-niedermann** [comment] 2023-05-23 13:54
Please note that DAV support is not complete for the Deck app.

See also: https://github.com/nextcloud/deck/issues/2399 and https://github.com/nextcloud/deck/issues/2355

**Comment by mebitek** [comment] 2023-05-23 14:05
thx for the answer. so how is it possiible to achive an edit command? via some api?

**Comment by stefan-niedermann** [comment] 2023-05-23 14:29
Deck has a REST API: https://deck.readthedocs.io/en/latest/API/

It works reasonable, but it also has quite a few long standing bugs, especially deleting attachments doesn't work and `ETag`s make trouble here and there (in case you want to use them).

**Comment by mebitek** [comment] 2023-05-24 11:22
thx @stefan-niedermann I'm using the rest api and it is working well. just a question, where can I find the api to move a card to another stack?

**Comment by stefan-niedermann** [comment] 2023-05-24 12:48
Its not a separate endpoint, just update the property of the card

**Comment by mebitek** [comment] 2023-05-24 12:55
I'm sending a stackId json field but I'm getting bad request error

**Comment by mebitek** [comment] 2023-05-25 14:11
@stefan-niedermann thx so much, I just released the first version of the TUI frontend

**Comment by juliushaertl** [comment] 2023-11-11 21:02
Closing as a duplicate of https://github.com/nextcloud/deck/issues/2399 and https://github.com/nextcloud/deck/issues/2355

**Closed by juliushaertl** 2023-11-11 21:02 UTC
