### ISSUE TITLE
Weird Tag Behaviour when moving card to another deck

### ISSUE THREAD

**Issue by yellelieder** [nextcloud/deck#2497] opened 2020-11-03 17:51 UTC
**Describe the bug**
Tag/Label can´t be removed after moving the card.

**To Reproduce**
1. Creat individual tag for cards on deck A
2. assign it to a card
3. move the card to another deck B
4. Tag now cant be removed since it´s not available in B.

**Expected behavior**
Eighter remove tag form card or add the tag to the new deck.

**Client details:**
 - OS: Winows 10
 - Browser Chrome
 - Device: desktop

**Comment by stefan-niedermann** [comment] 2020-11-03 18:11
Duplicate of https://github.com/nextcloud/deck/issues/1832 which describes this and more issues with the *move* feature.

**Closed by stefan-niedermann** 2020-11-03 18:11 UTC
