### ISSUE TITLE
Task completion mark

### ISSUE THREAD

**Issue by sibergad** [nextcloud/deck#3083] opened 2021-05-23 08:11 UTC
![Без имени-2](https://user-images.githubusercontent.com/64952550/119252971-fe07be00-bbbf-11eb-8729-087f82edb62f.jpg)

Please add the task completion feature to the app. Because the tasks in the Pending Items that have a deadline still remain.

**Comment by stefan-niedermann** [comment] 2021-05-23 08:40
Please use the 🔍  search function before opening new issues.

Duplicate of #534

**Closed by stefan-niedermann** 2021-05-23 08:40 UTC
