### ISSUE TITLE
Users should be able to edit but not to delete

### ISSUE THREAD

**Issue by tschombes** [nextcloud/deck#3651] opened 2022-03-17 14:52 UTC
When i share a board with a group of users i have to give them "edit" rights to allow them to pick tasks or move tasks between lists.

It happens from time to time a user deletes a task and then everything related with that task is gone.

It would be great if there was an option to allow editing and moving tasks but prevent deletion.

**Comment by stefan-niedermann** [comment] 2022-08-08 06:36
I vote against this issue because:
1. Distinguishing between `edit` and `delete` permissions is **not a well known concept**. This is valid for file systems, but also for other software like Confluence wiki or (I believe) Jira
2. It makes no sense because **`edit`ing basically includes `delete`ing**. If an user "edits" all fields to blank, there is nothing more but an empty card, which is quite the same as if it ain't there at all in my opinion. One could argue, that the history is kept in the activities, but this is also valid for deleted cards.
3. It is a **technical solution for an organizational problem**: Either you trust someone or you don't 🤷 


The only "pro" argument I could imagine is **consistency** with Nextcloud Files (where this separation of permissions is also a mistake in my opinion).

**Comment by juliushaertl** [comment] 2023-11-11 21:50
Thanks for your feature request. I can see this is a valid use case however we currently consider deck more as a simple tool that is easy to use and want to keep the complexity low. We target common use cases but don’t necessarily want to extend to a fully fledged project management tool. There are lots of good open source tools out there already for more complex use cases. Therefore I’d consider this out of scope.

It might be worth to have a look at the tables app  which would allow separate views with different permissions on a shared dataset.

**Closed by juliushaertl** 2023-11-11 21:50 UTC

**Comment by a6datta** [comment] 2024-10-14 15:26
The issue is if we don't allow someone to edit (or delete), that person is unable to add note and report progress. So from an organizational point of view this app is of no use.
