### ISSUE TITLE
Put the comments under the description

### ISSUE THREAD

**Issue by Aviortheking** [nextcloud/deck#1284] opened 2019-10-11 07:41 UTC
**Is your feature request related to a problem? Please describe.**
I just discovered that comments existed, and I think it would be way better if they were placed under the description box

**Describe the solution you'd like**
allow to send and see comments in the first pane

**Comment by juliushaertl** [comment] 2019-10-11 08:34
Duplicate of https://github.com/nextcloud/deck/issues/1073

**Closed by juliushaertl** 2019-10-11 08:34 UTC
