### ISSUE TITLE
Multi-Line comments are not shown/accessible

### ISSUE THREAD

**Issue by wdata68** [nextcloud/deck#2585] opened 2020-11-19 06:24 UTC
Deck V1.2.0/V1.2.1
When the comment contains newline character (multiline), empty comment is shown. All previously created multline comments are also shown as empty and not accessible. No errors in the log are found.
![Create](https://user-images.githubusercontent.com/74700302/99629399-fcaadc80-2a48-11eb-9f74-29adf170c430.JPG)
![shown](https://user-images.githubusercontent.com/74700302/99629404-fd437300-2a48-11eb-8fcb-845a954a34e8.JPG)

**Comment by juliushaertl** [comment] 2020-11-19 08:09
Ah closing as a duplicate of https://github.com/nextcloud/deck/issues/2066 which also mentions the disappearing comment now

**Closed** 2020-11-19 08:09 UTC
Labels: 1. to develop, bug
