### ISSUE TITLE
Drag and drop Re-order boards

### ISSUE THREAD

**Issue by ashgoodman** [nextcloud/deck#585] opened 2018-08-13 01:58 UTC
It would be nice if the order boards are listed in the left pane could be controlled by either a drag and drop option or a "up/down" arrow tool.

**Comment by juliushaertl** [comment] 2018-10-09 13:02
CLosing as a duplicate of #601 since it contains a bit more reasoning on the use case and options.

**Closed by juliushaertl** 2018-10-09 13:02 UTC
Labels: 0. Needs triage, enhancement

**Comment by compumatter** [comment] 2019-02-14 14:33
Hello Julius,

I see this issue is marked closed. I am once again coming back to Deck and hoping this issue was implemented.  Projects are never truly prioritized based on their alphabetical structure but either by date or sense of priority.  

I feel this is a large missing behavior and am commenting here in hopes you will see it and move to include it.

Sincerely,

Jay
CompuMatter

**Comment by putt1ck** [comment] 2019-02-14 14:39
@compumatter have you looked at #601?

**Comment by compumatter** [comment] 2019-02-14 14:41
Yes I did.

It has been recorded as closed...

But this is truly a valuable addition and I do not think too complicated 
to implement.

So I am tabling it again.

Jay

**Comment by putt1ck** [comment] 2019-02-14 14:42
Stale bot closed from lack of activity - that's the one to re-open
