### ISSUE TITLE
[feature request] Quick Add for cards

### ISSUE THREAD

**Issue by gittynick** [nextcloud/deck#4769] opened 2023-06-08 07:38 UTC
I would much like to have some kind of "Quick Add" function for adding cards - like todoist or vikunja
for example if i type "nameofcard @user1 @tomorrow #urgent" the card would be added with the title "nameofcard", assigned to user1, due tomorrow and have a label "urgent"
wouldn't that be cool !? :-)

**Comment by juliushaertl** [comment] 2023-11-12 10:10
duplicate of #2777

**Closed by juliushaertl** 2023-11-12 10:11 UTC
