### ISSUE TITLE
filter on multiple tags not working

### ISSUE THREAD

**Issue by alexbijma** [nextcloud/deck#2171] opened 2020-08-06 08:24 UTC
using Nextcloud version 18.0.7
Deck version 1.0.5

When check multiple labels in filter **nothing** is displayed. If you select only one label in the filter it works like expected and all cards with the selected label is displayed.

Expected behaviour:
when you select multiple labels in the filter. All cards of the (multiple) selected labels are shown.

**Comment by kbeerepoot** [comment] 2020-08-06 14:22
> using Nextcloud version 18.0.7
> Deck version 1.0.5
> 
> When check multiple labels in filter **nothing** is displayed. If you select only one label in the filter it works like expected and all cards with the selected label is displayed.
> 
> Expected behaviour:
> when you select multiple labels in the filter. All cards of the (multiple) selected labels are shown.

Are you sure you are using the correct logic here? When you are selecting multiple labels, the applied filter should show all cards to which ALL the selected labels are assigned, not all cards to which ANY of the selected labels are assigned ...

**Comment by alexbijma** [comment] 2020-08-06 14:38
ah ok, yes than it works as expected.
I assumed ANY instead of AND. It would be nice to have the choice AND or OR.

**Comment by kbeerepoot** [comment] 2020-08-06 14:43
> ah ok, yes than it works as expected.
> I assumed ANY instead of AND. It would be nice to have the choice AND or OR.

This issue is actually referred to in #2149

**Comment by stefan-niedermann** [comment] 2020-08-07 13:04
Yep, closing this as duplicate of #2149

**Closed by stefan-niedermann** 2020-08-07 13:04 UTC
