### ISSUE TITLE
Description unable to saved if add Due Date

### ISSUE THREAD

**Issue by flycrshish** [nextcloud/deck#324] opened 2017-10-09 09:57 UTC
### Steps to reproduce
1.Add a Description in card ,type "TEST_LINE_1" ,click other card and back to this card, Description show "TEST_LINE_1" ,it's saved correct.
2.add a Due date in this card ,modify Description to "TEST_LINE_1_add",
3.click other card and back this card, Description show "TEST_LINE_1" ,not saved ,and Due date is not saved too.

**Comment by juliushaertl** [comment] 2017-10-09 10:12
Looks like a duplicate of #321, can you check your error logs if that is the same issue?

Also, if you'd like to help testing, #322 might fix the issue.

**Comment by flycrshish** [comment] 2017-10-09 10:33
yes ,error log is the same as #321

**Closed** 2017-10-09 10:44 UTC
Labels: 0. Needs triage, bug
