### ISSUE TITLE
Done tasks keep firing notifications

### ISSUE THREAD

**Issue by devlich** [nextcloud/deck#4550] opened 2023-03-18 08:14 UTC
**Describe the bug**
There is no way to mark a card as complete after adding a due date (neither in the deck nor in the tasks), so nextcloud keeps annoying the whole team with notifications of tasks already done. This also makes the "overdue cards" filter unusable by the way.

**To Reproduce**
Add a due date to a card

**Expected behavior**
Not notifying tasks tagged as done or a way to mark a task as done.

> I've read previous issues on this topic, but couldn't find an answer that work for me. I understand that this feature has been implemented in the past, but I don't know if it was removed, if it will come in a future release, or if it was simply abandoned. Please enlighten me if possible.

**Comment by stefan-niedermann** [comment] 2023-03-18 15:54
Duplicate of https://github.com/nextcloud/deck/issues/534

**Closed by stefan-niedermann** 2023-03-18 15:54 UTC
