### ISSUE TITLE
Show new comments as they happen

### ISSUE THREAD

**Issue by LostinSpacetime** [nextcloud/deck#2713] opened 2021-01-08 09:22 UTC
**Situation now:**  
If a new comment is added to a card, one gets a notification, but the new message is not shown, unless one refreshes the website. This makes collaboration very hard and unintuitive.

**Improvement:**  
New comments and changes should be shown as they happen.

**Comment by juliushaertl** [comment] 2021-01-08 12:38
Duplicate of #256

**Closed by juliushaertl** 2021-01-08 12:38 UTC
