### ISSUE TITLE
Dynamic resizing has bugs with Nextcloud JSXC chat plugin in 0.3 

### ISSUE THREAD

**Issue by poVoq** [nextcloud/deck#390] opened 2018-01-13 08:02 UTC
### Steps to reproduce
1. Enable both Deck and JSXC chat
2. Open deck and toggle the chat side bar in a desktop browser (firefox)
3. notice the extra blank space created and that the "add new stack" are not moving back to the right completely

### Expected behaviour
Dynamic resizing should be effected by this (as it was in previous versions of Deck)

### Actual behaviour
see above

I am pretty sure this is new to 0.3, but I might have missed it before as I was not using it extensively.

**Comment by juliushaertl** [comment] 2018-01-13 09:05
Seems to be a duplicate of https://github.com/nextcloud/deck/issues/279 to me. Feel free to reopen if it is a different issue.

**Closed by juliushaertl** 2018-01-13 09:05 UTC

**Comment by poVoq** [comment] 2018-01-13 10:08
Hmm yes maybe related, but functionality of Deck seem unaffected, just the layout is somewhat broken.
