### ISSUE TITLE
Card overflow scrolling for action menu

### ISSUE THREAD

**Issue by Jab2870** [nextcloud/deck#317] opened 2017-10-03 20:58 UTC
### Steps to reproduce
1. Create a board and add a card
2. click on the three dots to open the action menu

### Expected behaviour
The menu should not be constrained by the cards outline

### Actual behaviour
Scrollbars are added to the card

![screenshot_2017-10-03_21-53-08](https://user-images.githubusercontent.com/1909202/31148764-a5d00266-a885-11e7-8594-6d62cd46a1b7.png)

### General server configuration

**Operating system:** Linux jabserver 4.12.13-1-ARCH #1 SMP PREEMPT Fri Sep 15 06:36:43 UTC 2017 x86_64

**Web server:** Apache/2.4.27 (Unix) OpenSSL/1.1.0f PHP/7.1.10 (apache2handler)

**Database:** mysql 10.1.26

**PHP version:** 7.1.10
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - ctype
 - dom
 - fileinfo
 - filter
 - hash
 - json
 - mbstring
 - SPL
 - PDO
 - bz2
 - posix
 - Reflection
 - session
 - SimpleXML
 - standard
 - tokenizer
 - xml
 - xmlreader
 - xmlwriter
 - mysqlnd
 - apache2handler
 - Phar
 - curl
 - exif
 - ftp
 - gd
 - gmp
 - iconv
 - imap
 - intl
 - ldap
 - mcrypt
 - mysqli
 - pdo_mysql
 - zip
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:**  ARCH Repositories

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - apporder: 0.4.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.5
 - checksum: 0.3.5
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - deck: 0.2.3
 - drawio: 0.8.8
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_clipboard: 0.6.4
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.1.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - metadata: 0.5.0
 - music: 0.5.2
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ocdownloader: 1.5.4
 - passman: 2.1.4
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - audioplayer
 - encryption
 - files_external
 - previewgenerator
 - richdocuments
 - sensorlogger
 - user_external
 - user_ldap
 - zenodo
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocmmhe4ow3jv",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.local",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "\/mnt\/server-data\/nextcloud\/data",
    "overwrite.cli.url": "http:\/\/nextcloud.local",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "loglevel": 2
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Operating system:** Arch Linux

**Comment by juliushaertl** [comment] 2017-10-03 21:01
Duplicate of #311 A bugfix release will be out at the end of the week. 😉

**Closed by juliushaertl** 2017-10-03 21:01 UTC

**Comment by Jab2870** [comment] 2017-10-03 21:03
@juliushaertl Thanks,
My mistake for only searching open issues

**Comment by juliushaertl** [comment] 2017-10-03 21:11
No problem. Thanks for reporting anyway. :+1:
