### ISSUE TITLE
Mail-Reminder for "Due Date"

### ISSUE THREAD

**Issue by mcteefax** [nextcloud/deck#1548] opened 2020-02-21 09:05 UTC
In Nextcloud "activities" it is possible to activate Mail-Reminders for several DecK-activities. But I didn't find a possibility to get an Mail-Reminder, when a "Due-Date" is reached or when a card is assigned to me. So i have also look via browser in Deck.

For me it doesn't matter, if I would have to activate it in "activities" or anywhere in Deck.

**Comment by juliushaertl** [comment] 2020-02-21 11:59
Duplicate of https://github.com/nextcloud/deck/issues/1202

**Closed by juliushaertl** 2020-02-21 11:59 UTC
