### ISSUE TITLE
A way to hide or delete shared boards

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/deck#3475] opened 2021-12-06 11:05 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
There is no way to delete a board that have been shared to me, that's causing bulk board list in my deck app. 

**Describe the solution you'd like**
I think it would be great if shared boards can be deleted by a user that the board have been shared but not from the owner of the board. 

**Describe alternatives you've considered**
The other way is to be able to hide boards or archive shared boards. 

**Additional context**

**Comment by stefan-niedermann** [comment] 2021-12-06 11:07
Duplicate of https://github.com/nextcloud/deck/issues/955

**Closed by stefan-niedermann** 2021-12-06 11:07 UTC
