### ISSUE TITLE
Attaching files when editing description can be perceived as broken.

### ISSUE THREAD

**Issue by GeorgiosG** [nextcloud/deck#2186] opened 2020-08-09 22:10 UTC
Hi,

We are using Deck to manage internal projects. It works great so far, however there was an instance where a couple of people involved in a project got confused when they tried to add attachments to a card.

They tried to add the attachment via the clip icon that appears when editing the detail description of the card.

That normally responds with a list of available attachments to select from.

When there are no attachments, the user is faced with an empty "Select Attachment" dialog, which can give the impression that something is broken.

I can think of two ways to eliminate that confusion, when there are no attachments to select from:
1. Prompt the user to add one or more attachments, and then prompt the select dialog
2. When the user edits the detail description, hide the clip icon (next to the "eye" / preview icon) as long as there are no files attached to the card.

As mentioned, any of the two solutions would eliminate the confusion.

Regards,
Georgios

**Comment by juliushaertl** [comment] 2020-08-19 20:30
Duplicate of https://github.com/nextcloud/deck/issues/1139 Fixed by https://github.com/nextcloud/deck/pull/2035

**Closed by juliushaertl** 2020-08-19 20:30 UTC
