### ISSUE TITLE
Colorize text in cards

### ISSUE THREAD

**Issue by Gobytego** [nextcloud/deck#5032] opened 2023-08-17 19:06 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Color text in cards

**Describe the solution you'd like**
Would love to see an option to color the text in the cards description.

**Describe alternatives you've considered**

**Additional context**

**Comment by juliushaertl** [comment] 2023-08-18 04:58
Please search for existing issues before opening new ones. This is a duplicate of https://github.com/nextcloud/deck/issues/3592

**Closed by juliushaertl** 2023-08-18 04:58 UTC

**Comment by Gobytego** [comment] 2023-08-18 12:51
that's a completely different request. that's for different colored cards. not what we want. we want as i stated different colored text for the cards description text.

**Comment by juliushaertl** [comment] 2023-08-18 13:27
Sorry, then I mixed this up, however since the editor and stored formatting is based on markdown I don't see any chance to implement this as there is no standard for colorizing text in markdown.

**Comment by Gobytego** [comment] 2023-08-18 14:21
got ya... thank you @juliushaertl
