### ISSUE TITLE
Modal design - div id="tab-details" is too small

### ISSUE THREAD

**Issue by rscata** [nextcloud/deck#2831] opened 2021-02-26 09:09 UTC
**Describe the bug**
On modal details, the `div id=tab-details` is to small. To select the due date, you must scroll to the entire div.

**To Reproduce**
1. Go to 'a board'
2. Click on 'card'
3. Select Due Date

**Screenshots**
![image](https://user-images.githubusercontent.com/2580211/109279915-018ae380-7823-11eb-8cbe-02488df8c8d0.png)

**Client details:**
 - OS: [Linux]
 - Browser [Firefox]
 - Version [86.0 (64-bit)]
 - Device: [desktop]

<details>
<summary>Server details</summary>

**Operating system**:
Ubuntu 

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
PHP Version 7.4.8

**Nextcloud version:** (see Nextcloud admin page)
20.0.8

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by stefan-niedermann** [comment] 2021-02-26 09:15
Duplicate of #2830

Please use the **:mag: search function** before opening new issues (in this case the other issue was at the very first position and opened only one hour earlier!)

**Closed by stefan-niedermann** 2021-02-26 09:15 UTC
