### ISSUE TITLE
board details stopped working: /apps/deck/boards/NaN

### ISSUE THREAD

**Issue by grinapo** [nextcloud/deck#2969] opened 2021-04-13 10:07 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

All boards » Board … » `Board details` does not work anymore, infinite "Loading board".
Web console shows a `/apps/deck/boards/NaN` call (along with error 400).

This worked a few versions before.

**Client details:**
 - Browser firefox
 - Version 1.3.2
 - Device: desktop

<details>
<summary>Server details</summary>

**Operating system**:
Linux 5.3.10-1 x86_64

**Web server:**
nginx/1.14.2 (fpm-fcgi)

**Database:**
mysql 10.3.27

**PHP version:**
7.3.27-1~deb10u1

**Nextcloud version:**  
21.0.1 - 21.0.1.1

**Where did you install Nextcloud from:** 
direct

**List of activated apps:** 
``` Enabled: - accessibility: 1.7.0 - activity: 2.14.3 - admin_audit: 1.11.0 - analytics: 3.4.1 - announcementcenter: 5.0.0 - bbb: 1.3.0 - calendar: 2.2.0 - cloud_federation_api: 1.4.0 - comments: 1.11.0 - contacts: 3.5.1 - contactsinteraction: 1.2.0 - dashboard: 7.1.0 - dav: 1.17.1 - deck: 1.3.2 - drawio: 1.0.0 - duplicatefinder: 0.0.6 - event_update_notification: 1.2.0 - federatedfilesharing: 1.11.0 - federation: 1.11.0 - files: 1.16.0 - files_accesscontrol: 1.11.0 - files_antivirus: 3.2.0 - files_automatedtagging: 1.11.0 - files_downloadactivity: 1.10.0 - files_mindmap: 0.0.24 - files_pdfviewer: 2.1.0 - files_rightclick: 1.0.0 - files_sharing: 1.13.1 - files_trashbin: 1.11.0 - files_versions: 1.14.0 - files_videoplayer: 1.10.0 - firstrunwizard: 2.10.0 - forms: 2.2.4 - group_default_quota: 0.1.1 - groupfolders: 9.0.0 - groupquota: 0.1.5 - integration_google: 1.0.0 - issuetemplate: 0.7.0 - logreader: 2.6.0 - lookup_server_connector: 1.9.0 - mail: 1.9.5 - nextcloud_announcements: 1.10.0 - notifications: 2.9.0 - notify_push: 0.1.6 - oauth2: 1.9.0 - onlyoffice: 6.3.0 - password_policy: 1.11.0 - photos: 1.3.0 - polls: 1.8.1 - privacy: 1.5.0 - provisioning_api: 1.11.0 - quota_warning: 1.10.0 - recommendations: 1.0.0 - registration: 1.1.2 - serverinfo: 1.11.0 - settings: 1.3.0 - sharebymail: 1.11.0 - sharepermissions: 1.0.1 - spreed: 11.1.2 - support: 1.4.0 - survey_client: 1.9.0 - systemtags: 1.11.0 - tasks: 0.13.6 - text: 3.2.0 - theming: 1.12.0 - twofactor_backupcodes: 1.10.0 - twofactor_totp: 6.0.0 - updatenotification: 1.11.0 - user_saml: 4.1.0 - user_status: 1.1.1 - user_usage_report: 1.5.0 - viewer: 1.5.0 - weather_status: 1.1.0 - whiteboard: 0.0.3 - workflow_script: 1.6.0 - workflowengine: 2.3.0 Disabled: - bruteforcesettings - encryption - files_external - ldap_contacts_backend - maps - rainloop - riotchat - user_ldap ``` 

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"dUOX4abJCv3DjRI968Yu","level":2,"time":"2021-04-13T10:04:34+00:00","remoteAddr":"10.*","user":"*","app":"filesystem","method":"GET","url":"/apps/deck/boards/NaN","message":"Storage wrapper 'sharepermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","userAgent":"Mozilla/5.0 (X11
; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0","version":"21.0.1.1"}
```

#### Browser log
```
400 Bad Request
```
</details>

**Comment by stefan-niedermann** [comment] 2021-04-13 10:16
Duplicate of https://github.com/nextcloud/deck/issues/2951

Will be fixed in the next release.

**Closed by stefan-niedermann** 2021-04-13 10:16 UTC

**Comment by stefan-niedermann** [comment] 2021-04-13 12:00
no problem, i guess you didn't find it because it is closed and the search function only shows open issues by default.

I will fix the typo in the other issue... 😉
