### ISSUE TITLE
In Activity stream, Deck entries display <pre class="visualdiff"></pre>

### ISSUE THREAD

**Issue by stevecopeza** [nextcloud/deck#2052] opened 2020-06-20 08:37 UTC
![Activity_-_Orca_Intranet](https://user-images.githubusercontent.com/19606448/85197485-80696d00-b2e1-11ea-8ce4-d28feeb2a4aa.jpg)

**Describe the bug**
Tech entries in the Activity stream have -

<pre class="visualdiff"></pre>

around the content.
This happens in every case, the attached screenshot shows how it appears.

**To Reproduce**
1. Make a change on a Deck card
2. View Activity stream
**Expected behavior**
For the relevant information displayed with out any code being visible

**Screenshots**

**Client details:**
 - all web client
![Activity_-_Orca_Intranet](https://user-images.githubusercontent.com/19606448/85197555-fa015b00-b2e1-11ea-9457-461b879b73c3.jpg)

**Comment by juliushaertl** [comment] 2020-06-22 09:37
Duplicate of https://github.com/nextcloud/deck/issues/1557

**Closed by juliushaertl** 2020-06-22 09:37 UTC
