### ISSUE TITLE
Fix margin in header bar

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/deck#194] opened 2017-06-19 20:50 UTC
Files:
![margin-files](https://user-images.githubusercontent.com/16517095/27305347-9258e1ea-5541-11e7-9cd0-cbd4718f1e94.png)

Deck:
![margin-deck](https://user-images.githubusercontent.com/16517095/27305361-9c30dcd6-5541-11e7-9d25-1598cd5639c0.png)

**Comment by juliushaertl** [comment] 2017-06-20 08:45
@artemanufrij So this was the issue caused by the audioplayer?

**Comment by artemanufrij** [comment] 2017-06-20 10:20
No, it's our issue :)

**Comment by juliushaertl** [comment] 2017-06-20 10:23
Ah you mean the space between the togge button and the home icon :+1:

**Comment by artemanufrij** [comment] 2017-06-20 11:35
yes

**Comment by pixelipo** [comment] 2017-06-20 13:23
wait a bit on this. I have an open PR that makes some changes to the breadcrumbs in Files.

**Comment by artemanufrij** [comment] 2017-06-20 14:10
OK, I will wait for your feedback

**Comment by artemanufrij** [comment] 2017-06-22 18:01
@pixelipo hey Marin had you time to open a PR?

**Comment by pixelipo** [comment] 2017-06-22 18:54
I did, long time ago, but it hasn't been merged yet. See nextcloud/server#5229

**Comment by artemanufrij** [comment] 2017-06-22 19:04
ah... ok... I see. Thank you for your feedback!

**Comment by juliushaertl** [comment] 2017-12-08 15:24
Actually fixed with the new breadcumbs in 13 and adapted in #350

**Closed** 2017-12-08 19:14 UTC
Labels: 2. developing
