### ISSUE TITLE
Move comments to separate sidebar tab

### ISSUE THREAD

**Issue by natrius** [nextcloud/deck#1073] opened 2019-05-30 13:58 UTC
**Is your feature request related to a problem? Please describe.**

I'm always frustrated i have to search comments. I introduced a friend to deck for marriage planning and he wrote some comments in the description because he did not actually thought that comments are 1, possible at all and 2, they are found in the timeline.The timeshould not contain anything active. It should just be a passive timeline in case i want to check something. How it was moved and so on. 

**Describe the solution you'd like**

Move the comments itself in the Description at the bottom in an extra section.
In the timeline there still should be a "x wrote a comment." or "x deleted a comment". 

**Describe alternatives you've considered**

Alternatively introduce a new tab, so its Description, Comments, Attachment, Timeline.

**Additional context**

![dock_comments_v1](https://user-images.githubusercontent.com/7243447/58637815-a5182e80-82f3-11e9-8254-27d2399ba023.png)

or 

![dock_comments_v2](https://user-images.githubusercontent.com/7243447/58637827-ab0e0f80-82f3-11e9-90ec-bff436108645.png)

**Comment by juliushaertl** [comment] 2019-06-21 07:45
This was implemented after the general discussion of merging activity/comments into one timeline in https://github.com/nextcloud/server/issues/658. 

Moving them to the description tab seems wrong to me, as it is clearly something different. The main issue seems to be that the comments are distributed between all the activity entries. What do you think about allowing to filter the timeline view to just show comments? That should solve the usability issue you have.

**Comment by natrius** [comment] 2019-06-21 09:53
No, the main issue is that we did not even know comments are possible. Just after i was just clicking around because of something else i discovered this. Together with https://github.com/nextcloud/deck/issues/730 it would be easier to start with, but now. Discover by accident. 

My suggestions would be:

- Add new tab "Comments"
- Change "Description" to "General" and divide into sections "Description" and "Comments" for example. 

I would never actively search in a timeline for a new comment. As said, i expect there things like "New comment", "Comment edited", "Comment deleted" and stuff like that, but not the comment itself. 

Your suggested solution is not bad but just in this case at least add under "Description" a Info in italic or something like this "Comments can be found in the timeline". As said, we did not even know comments are possible. After discovering it once, everything is fine. But the path to discovering the comments...

**Comment by juliushaertl** [comment] 2019-06-22 08:17
I see your point, maybe @jancborchardt has an idea since the discoverability of of comments will be a general issue with the unified timeline.

**Comment by bpcurse** [comment] 2019-06-22 13:54
Same issue described here #728.

The problem is, that displaying comments in the timeline may have some logic in it, but it definitively is **not** intuitive. No one will search there for comments.
@natrius The same happens in our setup. People do not use comments and instead put them in the description.

> Change "Description" to "General" and divide into sections "Description" and "Comments" for example.

I would love to see a solution, where the comments simply are shown under the description text (if there is any). This seems to be intuitive to me.

![deck_comments_mockup](https://user-images.githubusercontent.com/29312856/59964784-a52bd880-9505-11e9-841d-f1e739b1f754.png)

**Comment by jancborchardt** [comment] 2019-06-22 23:35
An essential part of having the comments discoverable is that the "Activity" tab should be the first, leftmost tab and thus active by default. The middle tab is "Sharing" and the last tab is for "Details" (which also contains description etc.)

This is how we specified it in **Sidebar standardization https://github.com/nextcloud/server/issues/10289**
If it is not per specification then comments are less discoverable. If we add the comments tab back again then it’s more cumbersome to do everything else (»if everything is important, nothing is«).

**Comment by putt1ck** [comment] 2019-06-23 04:05
The comments need to be readable as a stream without regard to who moved a card to a difference stack (list), modified the description in some way, added or removed an attachment etc.. Comments are the discussion of the item as described - so as @bpcurse suggests, having comments below the description is probably both the most intuitive and makes them most useful - and the description (details) should be the default view for a selected card because it's likely essential reading for anyone new to the  card.

**Comment by jancborchardt** [comment] 2019-06-23 09:17
Alright, let’s go for an exception here then. @juliushaertl what do you think?

**Comment by natrius** [comment] 2019-06-23 09:37
Please, do not put the activity-tab in as the first tab, thats a bad idea. At first i want to see the description of the tab. Most of the time i don't care about the activity at all. That is just for special occasions i have to check something. 

So, the suggested solution would be the first i mentioned, divide the "Description" tab into "Description" and "Comments". Renaming the Tab into "General" would also be possible, so its, well, more general.

**Comment by jancborchardt** [comment] 2019-06-24 15:44
@natrius I already agreed to doing that. :)

**Comment by juliushaertl** [comment] 2019-08-12 11:10
> Alright, let’s go for an exception here then. @juliushaertl what do you think?

Fine by me. Lets do this in the vue rewrite then :+1:

**Comment by putt1ck** [comment] 2019-10-22 09:52
@juliushaertl is there anything we can do to help (test or dev)?

**Comment by juliushaertl** [comment] 2019-10-22 10:10
Feel free to checkout the vue branch if you want to do some early testing. Regarding comments @jakobroehrl is working hard on finishing the vue implementation and the only big issue to complete feature parity is file attachments as far as I can see. We will do some beta releases for the new version in a couple of weeks as well i think.

If you want to help with development you can have a look at our vue migration project at https://github.com/nextcloud/deck/projects/1 Any contribution is welcome :wink:

**Comment by putt1ck** [comment] 2019-10-23 04:45
@juliushaertl will see what can be done. Will certainly be up for "live testing" beta releases - is there somewhere we can subscribe to learn when betas are available?

**Comment by juliushaertl** [comment] 2019-10-23 05:51
I'll publish it as a release to github so if you want to subscribe to it, there is an RSS feed: https://github.com/nextcloud/deck/releases.atom

**Comment by juliushaertl** [comment] 2020-01-29 17:09
We have fresh nightly builds available at https://github.com/nextcloud/deck/releases/tag/nightly for early testing if you want, but there is still a lot of things missing (see https://github.com/nextcloud/deck/projects/1 for details)

While activity and comments are only partly working atm, the tabs are already separated so let's close this.

**Closed by juliushaertl** 2020-01-29 17:09 UTC
Labels: 2. developing, design

**Comment by putt1ck** [comment] 2020-04-23 08:15
@juliushaertl  Activity and comments appear to be merged back in v1b2?

**Comment by juliushaertl** [comment] 2020-04-23 08:17
No, nothing should have changed in that regard

**Comment by putt1ck** [comment] 2020-04-23 13:49
Ok, looks like our test server is reverting beta 2 to current release (but didn't do that to beta 1 - odd)
