### ISSUE TITLE
Change boards order

### ISSUE THREAD

**Issue by fastcat001** [nextcloud/deck#4038] opened 2022-09-07 16:18 UTC
Please, make it possible to change boards order
by moving them up and down

**Comment by stefan-niedermann** [comment] 2022-09-07 16:49
Please, search for existing issues *before* open new ones.

Closing as duplicate of https://github.com/nextcloud/deck/issues/601#issuecomment-644698298

**Closed by stefan-niedermann** 2022-09-07 16:49 UTC
