### ISSUE TITLE
Feature Request: Automation

### ISSUE THREAD

**Issue by abacao** [nextcloud/deck#3964] opened 2022-08-10 06:17 UTC
Hello all,

First of all, thank you for the app.
My feature request/suggestion is on Automation in stacks that will solve some other requests made here.

What I imagine is a configuration per stack that would allow the setup of some fields, such as:

- add a tag / remove a tag / remove all tags when the card is moved to that stack
- add a assign user / removes / remove all (this can almost solve and issue of vertical swimlanes per assignee)
- adds / remove a card color background giving the visual help of priority (red, yellow, green)
- adds some relative time to the cards due date (+3d / +1w / +1m....)

With this sort of automation, I believe it is possible to do and use Deck in a more productive way.

**Comment by stefan-niedermann** [comment] 2022-08-10 06:57
From my point of view this is a duplicate of https://github.com/nextcloud/deck/issues/1722 🤷

**Comment by abacao** [comment] 2022-08-10 07:18
Details were left on the Feature Request Above.

**Closed** 2022-08-10 07:17 UTC
