### ISSUE TITLE
Public Share Link

### ISSUE THREAD

**Issue by dacoex** [nextcloud/deck#3842] opened 2022-05-28 17:58 UTC
**Is your feature request related to a problem? Please describe.**
Currently, I can only share a board with internal users or assign it to a project.
However, I would like to share it with external users to track joint work with people who are not on my Nextcloud instance.

**Describe the solution you'd like**
Add a share button in the right-handed board property / configuration menu similar as for files or polls app.

**Describe alternatives you've considered**
Adding the external contributors to the nextcloud instance could be an option.
If it is for a single project, this is rather a huge overhead.
Thus, an optional external link would be very helpful.

**Additional context**
Adding external users also as responsible person would open the door for external collaborators even further.
One could add to each board: Contributor name & contributor email for sending reminders.

**Comment by stefan-niedermann** [comment] 2022-05-28 18:17
Please use the 🔍  **search function** before opening new issues.

Closing as duplicate of https://github.com/nextcloud/deck/issues/14

**Closed by stefan-niedermann** 2022-05-28 18:17 UTC
