### ISSUE TITLE
Make Attachments accessible via Files

### ISSUE THREAD

**Issue by rponline** [nextcloud/deck#982] opened 2019-04-09 20:36 UTC
**Is your feature request related to a problem? Please describe.**  
So, i introduced a new nextcloud instance with deck for collaborating to my team ... and my colleges added spreadsheets, Word-Documents and so to the cards. But it's super-annoying to edit such an attachment: you have to download, edit and upload it again manually.  
Yes, we could just paste a share URL of a File to a Card but this would be still hacky. 

**Describe the solution you'd like**  
Add Attachment -> Web-File-Picker Dialog (as an overlay) with following features:
* Navigate threw files
* options for read/write access
* Button to upload a file in current directory. (optional)
* Multiselect (optional)

After selecting a File, Nextcloud shares the files with the Deck (i don't know if this kind of abstraction exists yet).

Then, list the attachments. 

The ocdialog looks already promising, but it doesn't have all the features :/ [`core/src/jquery/ocdialog.js`](https://github.com/nextcloud/server/blob/6b653635a771a0707bae3b6afb89f760faaab8b6/core/src/jquery/ocdialog.js)

**Describe alternatives you've considered**  
Maintain a directory/file structure along the Decks and use that for storing files. Hmm. Not really.

**Comment by juliushaertl** [comment] 2019-04-10 14:07
Thanks for your feature request. This is actually a duplicate of https://github.com/nextcloud/deck/issues/564 :wink:

**Closed by juliushaertl** 2019-04-10 14:07 UTC
