### ISSUE TITLE
Save is too slow

### ISSUE THREAD

**Issue by oparoz** [nextcloud/deck#147] opened 2017-05-22 15:14 UTC
### Steps to reproduce

1. Click on a task
1. Assign a tag
1. Click on another task
1. Assign a tag
1. Click on the previous task

### Expected behaviour

Tags never disappear

### Actual behaviour

Tag on the 1st tag vaporises.

The tags are actually never saved on the server

Saving is too slow or requires some specific combo to be activated.

Per example, if I click on description and then back on the tag field, I see the "Saved" notification and only then are tags properly saved

**Comment by juliushaertl** [comment] 2017-05-22 17:30
@oparoz Assigning tags should be saved instanly. Can you check the browsers network console if there is a POST request when assigning a new tag?

**Comment by oparoz** [comment] 2017-05-22 17:44
So, I've checked and I do see POST requests if I wait long enough. The problem is that you sometimes want to assign tags quickly and it doesn't work.
Would be good to queue those requests so that they don't get forgotten when the detailed view loads the new card.

**Comment by juliushaertl** [comment] 2017-05-22 17:51
@oparoz Ok, guess queuing would be really nice to have.

**Comment by juliushaertl** [comment] 2017-05-24 17:43
I did some testing, the problem seems to be that in step 5 the card loads the labels without the one started saving in the background (2). So tags are saved even if i change between multiple cards but they are not displayed correctly when reentering.

**Comment by oparoz** [comment] 2017-05-24 17:44
That sounds easier to solve :)

**Comment by oparoz** [comment] 2017-06-26 11:44
I seem to have the most problems with card which already have a tag. It's then very difficult to add additional ones as the UI is inconsistent with the last actions taken.

**Comment by artemanufrij** [comment] 2017-06-26 12:06
I have polished it a little bit: #207

**Comment by oparoz** [comment] 2017-06-26 12:40
This is related to applying the tags, not modifying them ;)

Seems it's really broken in 0.2.0

`angular.min.js:122 Possibly unhandled rejection: Updating cards failed`

**Comment by artemanufrij** [comment] 2017-06-26 19:35
hey @oparoz I can't reproduce this issue...

Tested on NC12 and Deck last master version on Chromium

**Comment by juliushaertl** [comment] 2017-10-08 11:01
@oparoz Would be nice if you could check if #320 fixes the issue for you as well.

**Comment by juliushaertl** [comment] 2017-12-17 17:28
That should actually be fixed now by 95f4e4b0149866cb71876e5860ba7549ec3bd155 since we propagate changes correctly between the stack and card data representations.

**Closed by juliushaertl** 2017-12-17 17:28 UTC
Labels: 1. to develop, bug, frontend
