### ISSUE TITLE
Activating Deck leads to impossible Login in Nextcloud - internal Server Error

### ISSUE THREAD

**Issue by martin-77** [nextcloud/deck#3194] opened 2021-07-15 12:52 UTC
### Steps to reproduce
Did update from Nextcloud 21 -> 22
Deck was preinstalled in 21, worked without problems, had certain Decks running

### Expected behaviour
No Internal Server Error

### Actual behaviour
only with deactivated deck prossible to log in

## Server configuration detail

**Operating system:** Linux 5.11.22-1-pve #1 SMP PVE 5.11.22-2 (Fri, 02 Jul 2021 16:22:45 +0200) x86_64

**Webserver:** nginx/1.20.1 (fpm-fcgi)

**Database:** mysql 10.3.29

**PHP version:** 

7.4.21
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** 22.0.0 - 22.0.0.11

**Updated from an older Nextcloud/ownCloud or fresh install:** 21

**Where did you install Nextcloud from:** nextcloud.com

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.15.0
 - admin_audit: 1.11.0
 - analytics: 3.5.1
 - announcementcenter: 6.0.0-alpha.1
 - apporder: 0.13.0
 - approval: 1.0.3
 - calendar: 2.3.1
 - circles: 22.0.0
 - cloud_federation_api: 1.4.0
 - cms_pico: 1.0.15
 - comments: 1.11.0
 - contacts: 4.0.0
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.18.0
 - deck: 1.5.0
 - dicomviewer: 1.2.2
 - event_update_notification: 1.3.0
 - external: 3.9.0
 - federatedfilesharing: 1.11.0
 - files: 1.16.0
 - files_automatedtagging: 1.12.0
 - files_external: 1.12.1
 - files_markdown: 2.3.4
 - files_rightclick: 1.1.0
 - files_sharing: 1.13.2
 - files_trackdownloads: 1.10.0
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.11.0
 - fileslibreofficeedit: 1.0.2
 - firstrunwizard: 2.11.0
 - impersonate: 1.9.0
 - integration_moodle: 1.0.1
 - integration_whiteboard: 0.0.14
 - issuetemplate: 0.7.0
 - logreader: 2.7.0
 - lookup_server_connector: 1.9.0
 - mail: 1.10.1
 - metadata: 0.14.0
 - news: 16.0.0
 - nextcloud_announcements: 1.11.0
 - notes: 4.1.0
 - notifications: 2.10.1
 - oauth2: 1.9.0
 - password_policy: 1.12.0
 - photos: 1.4.0
 - polls: 3.0.0
 - privacy: 1.6.0
 - provisioning_api: 1.11.0
 - rainloop: 7.1.2
 - recommendations: 1.1.0
 - richdocuments: 4.2.0
 - serverinfo: 1.12.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - side_menu: 1.25.2
 - spreed: 12.0.0
 - support: 1.5.0
 - survey_client: 1.10.0
 - systemtags: 1.11.0
 - talk_matterbridge: 1.22.4
 - tasks: 0.13.6
 - text: 3.3.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.1
 - updatenotification: 1.11.0
 - uploaddetails: 0.1.3
 - user_ldap: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.6.0
 - weather_status: 1.1.0
 - workflow_ocr: 1.22.0
 - workflow_script: 1.7.0
 - workflowengine: 2.3.0
Disabled:
 - appointments
 - bbb
 - bookmarks
 - bruteforcesettings
 - customproperties
 - eidlogin
 - encryption
 - federation
 - files_downloadactivity
 - files_fulltextsearch
 - files_fulltextsearch_tesseract
 - files_pdfviewer
 - fulltextsearch
 - fulltextsearch_elasticsearch
 - integration_openproject
 - ldap_write_support
 - pdfannotate
 - piwik
 - suspicious_login
 - workflow_pdf_converter

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "10.0.0.202",
        "xxx",
        "xxx",
        "localhost"
    ],
    "auto_mail_accounts": {
        "imap_host": "imap.xxx.de",
        "imap_port": "993",
        "imap_ssl_mode": "ssl",
        "smtp_host": "smtp.xxx.de",
        "smtp_port": "465",
        "smtp_ssl_mode": "ssl",
        "email_address_suffix": ""
    },
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/xxxxxx",
    "dbtype": "mysql",
    "version": "22.0.0.11",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "default_language": "de",
    "appstore.experimental.enabled": false,
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "knowledgebaseenabled": true,
    "auth.bruteforce.protection.enabled": false,
    "defaultapp": "mail",
    "updater.release.channel": "stable",
    "theme": "",
    "loglevel": "2",
    "mysql.utf8mb4": true,
    "app_install_overwrite": [
        "apporder",
        "files_trackdownloads",
        "activitylog",
        "auto_mail_accounts",
        "recommendation_assistant",
        "ocsms",
        "polls",
        "spreed",
        "uploaddetails",
        "twainwebscan",
        "occweb",
        "contacts",
        "piwik",
        "fulltextsearch_elasticsearch",
        "fulltextsearch",
        "files_fulltextsearch",
        "files_fulltextsearch_tesseract",
        "side_menu",
        "rainloop",
        "appointments",
        "pdfdraw",
        "dicomviewer",
        "tasks",
        "issuetemplate"
    ],
    "check_for_working_htaccess": true,
    "check_for_working_wellknown_setup": true,
    "check_data_directory_permissions": true,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "allow_local_remote_servers": true,
    "data-fingerprint": "7205fabd0999856d36274bc28cc4dcba",
    "default_phone_region": "DE"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
sesitive Data included - LDAP is used, works without any problem if deck is deaktivated
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
TypeError: Argument 1 passed to OC\Group\Manager::getUserIdGroupIds() must be of the type string, null given, called in /var/www/nextcloud/lib/private/Group/Manager.php on line 316

    /var/www/nextcloud/lib/private/Group/Manager.php - line 316:

    OC\Group\Manager->getUserIdGroupIds()

    /var/www/nextcloud/apps/deck/lib/Service/PermissionService.php - line 316:

    OC\Group\Manager->isInGroup()

    /var/www/nextcloud/apps/deck/lib/Capabilities.php - line 53:

    OCA\Deck\Service\PermissionService->canCreate()

    /var/www/nextcloud/lib/private/CapabilitiesManager.php - line 69:

    OCA\Deck\Capabilities->getCapabilities()

    /var/www/nextcloud/lib/private/Template/JSConfigHelper.php - line 190:

    OC\CapabilitiesManager->getCapabilities()

    /var/www/nextcloud/lib/private/TemplateLayout.php - line 220:

    OC\Template\JSConfigHelper->getConfig()

    /var/www/nextcloud/lib/private/legacy/OC_Template.php - line 182:

    OC\TemplateLayout->__construct()

    /var/www/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php - line 204:

    OC_Template->fetchPage()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 171:

    OCP\AppFramework\Http\TemplateResponse->render()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 156:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 301:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1000:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()
```

**Comment by guste-github** [comment] 2021-07-16 15:00
I have the [same behaviour/issue](https://github.com/nextcloud/docker/issues/1535) after updating from 21.0.2 to 22.0.0.

**Comment by a4bits** [comment] 2021-07-24 09:48
I do have same issue. Now it even gives Internal Server error with log:


`{
    "reqId": "UiG1XuG6NWWwDazrBxfW",
    "level": 3,
    "time": "2021-07-24T09:19:31+00:00",
    "remoteAddr": "78.xx.xx.xx",
    "user": "--",
    "app": "index",
    "method": "GET",
    "url": "/index.php/login",
    "message": "Argument 1 passed to OC\\Group\\Manager::getUserIdGroupIds() must be of the type string, null given, called in /public_html/lib/private/Group/Manager.php on line 316",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) xx xx",
    "version": "22.0.0.11",
    "exception": {
        "Exception": "TypeError",
        "Message": "Argument 1 passed to OC\\Group\\Manager::getUserIdGroupIds() must be of the type string, null given, called in /public_html/lib/private/Group/Manager.php on line 316",
        "Code": 0,
        "Trace": [
            {
                "file": "/public_html/lib/private/Group/Manager.php",
                "line": 316,
                "function": "getUserIdGroupIds",
                "class": "OC\\Group\\Manager",
                "type": "->",
                "args": [
                    null
                ]
            },
            {
                "file": "/public_html/apps/deck/lib/Service/PermissionService.php",
                "line": 316,
                "function": "isInGroup",
                "class": "OC\\Group\\Manager",
                "type": "->",
                "args": [
                    null,
                    "Przedstawiciel Handlowy"
                ]
            },
            {
                "file": "/public_html/apps/deck/lib/Capabilities.php",
                "line": 53,
                "function": "canCreate",
                "class": "OCA\\Deck\\Service\\PermissionService",
                "type": "->",
                "args": []
            },
            {
                "file": "/public_html/lib/private/CapabilitiesManager.php",
                "line": 69,
                "function": "getCapabilities",
                "class": "OCA\\Deck\\Capabilities",
                "type": "->",
                "args": []
            },
            {
                "file": "/public_html/lib/private/Template/JSConfigHelper.php",
                "line": 190,
                "function": "getCapabilities",
                "class": "OC\\CapabilitiesManager",
                "type": "->",
                "args": []
            },
            {
                "file": "/public_html/lib/private/TemplateLayout.php",
                "line": 220,
                "function": "getConfig",
                "class": "OC\\Template\\JSConfigHelper",
                "type": "->",
                "args": []
            },
            {
                "file": "/public_html/lib/private/legacy/OC_Template.php",
                "line": 182,
                "function": "__construct",
                "class": "OC\\TemplateLayout",
                "type": "->",
                "args": [
                    "guest",
                    "core"
                ]
            },
            {
                "file": "/public_html/lib/public/AppFramework/Http/TemplateResponse.php",
                "line": 204,
                "function": "fetchPage",
                "class": "OC_Template",
                "type": "->",
                "args": [
                    {
                        "alt_login": [
                            {
                                "href": "https://praca.pankurak.pl/index.php/apps/sociallogin/oauth/facebook",
                                "name": "Log in with Facebook"
                            }
                        ]
                    }
                ]
            },
            {
                "file": "/public_html/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 171,
                "function": "render",
                "class": "OCP\\AppFramework\\Http\\TemplateResponse",
                "type": "->",
                "args": []
            },
            {
                "file": "/public_html/lib/private/AppFramework/App.php",
                "line": 156,
                "function": "dispatch",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    {
                        "__class__": "OC\\Core\\Controller\\LoginController"
                    },
                    "showLoginForm"
                ]
            },
            {
                "file": "/public_html/lib/private/Route/Router.php",
                "line": 301,
                "function": "main",
                "class": "OC\\AppFramework\\App",
                "type": "::",
                "args": [
                    "OC\\Core\\Controller\\LoginController",
                    "showLoginForm",
                    {
                        "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
                    },
                    {
                        "_route": "core.login.showLoginForm"
                    }
                ]
            },
            {
                "file": "/public_html/lib/base.php",
                "line": 1000,
                "function": "match",
                "class": "OC\\Route\\Router",
                "type": "->",
                "args": [
                    "/login"
                ]
            },
            {
                "file": "/public_html/index.php",
                "line": 36,
                "function": "handleRequest",
                "class": "OC",
                "type": "::",
                "args": []
            }
        ],
        "File": "/public_html/lib/private/Group/Manager.php",
        "Line": 333,
        "CustomMessage": "--"
    }
}`

**Comment by sephentos** [comment] 2021-07-29 03:31
I also can confirm that. Having Decks active results in not being able to sign in.

```
[index] Error: Argument 1 passed to OC\Group\Manager::getUserIdGroupIds() must be of the type string, null given, called in /var/www/nextcloud/htdocs/lib/private/Group/Manager.php on line 316

GET /login/flow?clientIdentifier=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

Disabling Decks results in working logins again.

**Comment by martin-77** [comment] 2021-07-29 07:13
I think it must be related to LDAP...
https://github.com/nextcloud/server/pull/23508/files

I remember, that I had problems to login into Nextcloud and manually edited the file in a previous version. (this nextcloud is a fresh install without modified files)

**Comment by Chartman123** [comment] 2021-07-29 12:57
> I think it must be related to LDAP...

We don't use LDAP and face the same problem...

**Comment by martin-77** [comment] 2021-07-29 16:30
> > I think it must be related to LDAP...
> 
> We don't use LDAP and face the same problem...

Do you use the Usermanagement from nextcloud? I have a second instance with nearly the same plugins on the same server (i use proxmox lxc) which updated wirhout any issues. The difference is, that the second instance is wirhout groups and Others Users than me.

Maybe i'll Test this in the next few days, If I can provoke this bug.

**Comment by guste-github** [comment] 2021-07-29 18:56
I can confirm: No LDAP but one group defined in nextcloud.

OC\Group\Manager::getUserIdGroupIds() is called against this group with null as UserId => Exception

The check is called before login. At that time there isn't a "real" user, only Guest?

**Comment by Chartman123** [comment] 2021-07-29 19:01
> Do you use the Usermanagement from nextcloud?

Yes, we use the Database user backend with some groups.

**Comment by martin-77** [comment] 2021-07-30 07:19
Bug persists in the latest beta 22.1.0 RC1

**Comment by Henk57** [comment] 2021-08-02 23:04
The strange thing is that this does not happen on all NC installations. I have one.
I run all relevant occ commands to repair and correct the database.
I also disabled addons, but this had no effect.
Other NC that work use the same apps.
I'm pretty sure that something in the database is causing the issue. But I can not find out what.
The error is since the update from latest 21 release to 22.
And my users are desperate waiting for a solution ...

**Comment by juliushaertl** [comment] 2021-08-03 07:53
If anyone wants to help testing a possible fix is in https://github.com/nextcloud/deck/pull/3225

**Comment by Chartman123** [comment] 2021-08-03 08:05
> If anyone wants to help testing a possible fix is in #3225

Works for me, thank you very much!

**Comment by martin-77** [comment] 2021-08-03 09:27
Yeah - works as far as I could evaluate.

Thanks!

**Comment by juliushaertl** [comment] 2021-08-03 10:00
The userId will always be null if the user is not fully logged in yet and the code in question gets executed through the capabilities fetching also for unauthenticated requests. Now the issue seems to come from Nextcloud 22 where type hints were introduced for the method in the server https://github.com/nextcloud/server/commit/68ec18323d07e7293fd59c82d51300a6d9d68176 but that would only get called if there is a group limit configured in Nextcloud.

In the end it was a valid bug in deck which unfortunately did only show up after introducing type hints on the server side.

**Comment by Henk57** [comment] 2021-08-03 13:37
I can confirm that this works !! Excellent job !
I added those 4 lines to the code.

**Closed** 2021-08-04 16:41 UTC
Labels: bug

**Comment by martin-77** [comment] 2021-08-05 04:29
Again big thanks to @juliushaertl for the solution and explanation
