### ISSUE TITLE
Unable to Mark List Item As Complete within Tasks App 

### ISSUE THREAD

**Issue by paulcalabro** [nextcloud/deck#2621] opened 2020-11-26 19:54 UTC
### Steps to reproduce
1. Create a board
2. Add a list to the board
3. Add a card to the list
4. Navigate to the Tasks app
5. Try to mark the list item as complete. Notice that you are unable to do so. Also, note that the input is disabled within the HTML.

### Expected behaviour
You can check off the associated task item within the Tasks app.

### Actual behaviour
You're unable to check off the associated task item within the Tasks app.

## Server configuration detail

**Operating system:** Linux 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64

**Webserver:** nginx/1.19.4 (fpm-fcgi)

**Database:** mysql 10.5.8

**PHP version:** 

7.4.12
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, session, posix, readline, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 20.0.2 - 20.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.3
 - admin_audit: 1.10.0
 - blockscores: 0.0.2
 - bookmarks: 4.0.5
 - breezedark: 20.0.1
 - calendar: 2.1.2
 - circles: 0.20.4
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.1
 - deck: 1.2.2
 - encryption: 2.8.1
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_antivirus: 3.0.0
 - files_external: 1.11.1
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - group_everyone: 0.1.6
 - groupfolders: 8.1.1
 - groupquota: 0.1.4
 - integration_discourse: 0.0.5
 - integration_github: 0.0.12
 - integration_gitlab: 0.0.8
 - integration_mastodon: 0.0.10
 - integration_reddit: 0.0.5
 - integration_twitter: 0.0.5
 - issuetemplate: 0.7.0
 - keeporsweep: 0.2.1
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - news: 15.0.6
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - passman: 2.3.6
 - password_policy: 1.10.1
 - photos: 1.2.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - social: 0.4.1
 - socialsharing_diaspora: 2.1.0
 - socialsharing_email: 2.1.0
 - socialsharing_facebook: 2.1.0
 - socialsharing_twitter: 2.1.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_admin: 3.0.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_gateway: 0.17.0
 - twofactor_nextcloud_notification: 3.0.0
 - twofactor_totp: 5.0.0
 - twofactor_u2f: 6.0.0
 - updatenotification: 1.10.0
 - user_ldap: 1.10.2
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - twofactor_email

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.paulcalabro.com",
        "172.31.46.200"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbtype": "mysql",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "log_type": "file",
    "loglevel": 0,
    "maintenance": false,
    "mysql.utf8mb4": true,
    "overwrite.cli.url": "http:\/\/nextcloud.paulcalabro.com",
    "overwriteprotocol": "https",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable",
    "version": "20.0.2.2",
    "app_install_overwrite": [
        "folderplayer",
        "passman",
        "drawio",
        "spreedme",
        "files_external_dropbox",
        "files_readmemd",
        "keeporsweep",
        "blockscores"
    ],
    "activity_expire_days": "7",
    "app.mail.imap.timeout": 60,
    "app.mail.imaplog.enabled": true,
    "app.mail.smtp.timeout": 60,
    "app.mail.smtplog.enabled": true,
    "debug": false,
    "defaultapp": "activity",
    "enable_previews": true,
    "jpeg_quality": "100",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "smtp",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpsecure": "tls",
    "theme": "",
    "data-fingerprint": "62091c29b16ac995688f46ef2b3ea408"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
background_sync_interval: 1800enabled: yesinstalled_version: 1.10.2s01_lastChange: 1582149020s01has_memberof_filter_support: 0s01home_folder_naming_rule: s01last_jpegPhoto_lookup: 0s01ldap_agent_password: s01ldap_attributes_for_group_search: s01ldap_attributes_for_user_search: s01ldap_backup_host: s01ldap_backup_port: s01ldap_base: s01ldap_base_groups: s01ldap_base_users: s01ldap_cache_ttl: 600s01ldap_configuration_active: 0s01ldap_default_ppolicy_dn: s01ldap_display_name: displayNames01ldap_dn: s01ldap_dynamic_group_member_url: s01ldap_email_attr: s01ldap_experienced_admin: 0s01ldap_expert_username_attr: s01ldap_expert_uuid_group_attr: s01ldap_expert_uuid_user_attr: s01ldap_ext_storage_home_attribute: s01ldap_gid_number: gidNumbers01ldap_group_display_name: cns01ldap_group_filter: s01ldap_group_filter_mode: 0s01ldap_group_member_assoc_attribute: s01ldap_groupfilter_groups: s01ldap_groupfilter_objectclass: s01ldap_host: s01ldap_login_filter: s01ldap_login_filter_mode: 0s01ldap_loginfilter_attributes: s01ldap_loginfilter_email: 0s01ldap_loginfilter_username: 1s01ldap_nested_groups: 0s01ldap_override_main_server: s01ldap_paging_size: 500s01ldap_port: s01ldap_quota_attr: s01ldap_quota_def: s01ldap_tls: 0s01ldap_turn_off_cert_check: 0s01ldap_turn_on_pwd_change: 0s01ldap_user_avatar_rule: defaults01ldap_user_display_name_2: s01ldap_user_filter_mode: 0s01ldap_userfilter_groups: s01ldap_userfilter_objectclass: s01ldap_userlist_filter: s01use_memberof_to_detect_membership: 1types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by stefan-niedermann** [comment] 2020-11-26 20:39
AFAIK the integration into the Tasks app as well as the Cale dars are currently only readonly.

**Comment by aleadco** [comment] 2020-11-27 01:23
Hello @stefan-niedermann , do you plan to incorporate more functionality with the task application? Coincidentally today we discussed that issue in my workplace.

**Comment by stefan-niedermann** [comment] 2020-11-27 05:35
I am the developer of the Dech Android App and have no plans to personally implement features for the Deck Server App or the Task Server Apo so no - but i know there happens very active development for both server apps and they will be continuously improved. 🙂

**Comment by tensau** [comment] 2020-12-02 19:10
Would be great to have a bidirectional integration between both of the apps, as there are some great Task apps for Android.

**Comment by juliushaertl** [comment] 2020-12-29 19:42
closing as a duplicate of #2399

**Closed by juliushaertl** 2020-12-29 19:42 UTC
