### ISSUE TITLE
Open card in Upcoming cards not working

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/deck#2541] opened 2020-11-13 15:52 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Open card in Upcoming cards not working

**To Reproduce**
1. Open deck
2. Click on a card to open the bigger detail view 
3. Bigger detail view  is opened. 
4. Close cards detail view and you see the board of the card
5. Click on "Upcoming cards" (left side)
6. Click on a card to open the bigger detail view  (same as 2.)
7. See: nothing happens (not sure: perhaps everything is frozen)

**Expected behavior**
 Click on a card will open the bigger detail view  (same as 3.)

**browser console**
DOMException: Node.insertBefore: Child to insert before is not a child of this node main.js:63:9
    errorHandler main.js:63

Versions
Deck 1.2.0-beta1
Nextcloud 20.0.0

**Comment by HonkXL** [comment] 2022-02-01 09:10
problem still exists in Nextcloud 23.0.1 and Deck 1.6.0

**Comment by eliasp** [comment] 2022-03-14 22:04
Problem still exists in Nextcloud 3.0.2.1 and Deck 1.6.1

**Comment by lu-krin** [comment] 2022-09-18 09:46
Problem still exists in NC 24.0.4 and Deck 1.7.1

See https://github.com/nextcloud/deck/issues/3837

**Comment by mvvvmd** [comment] 2023-04-21 08:00
Problem still exists in NC 26.0.1 and Deck 1.9.0

**Comment by ghmrj** [comment] 2023-08-12 10:30
Same here: Still exists in NC26.0.5 and Deck 1.9.2

**Comment by juliushaertl** [comment] 2023-11-11 22:50
I also cannot reproduce this. Since the version reported is quite old, please try if this is still an issue on the latest and don't hesitate to reopen if it is still an issue.

**Comment by ghmrj** [comment] 2023-11-14 07:32
Disagree :)
Nextcloud 27.1.3 with Deck 1.11.0 - open any card, go to "upcoming cards" (German "anstehende Karten"), then open anothe card and URL will show the card URL, nothing will happen and Firefox console brings this:
`DOMException: Node.insertBefore: Child to insert before is not a child of this node
    VueJS 17
    init vue-router.esm.js:3005
    init vue-router.esm.js:3004
    updateRoute vue-router.esm.js:2414
    transitionTo vue-router.esm.js:2263
    confirmTransition vue-router.esm.js:2402
    r vue-router.esm.js:2084
    r vue-router.esm.js:2091
    r vue-router.esm.js:2091
    r vue-router.esm.js:2091
    Ia vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2396
    r vue-router.esm.js:2084
    r vue-router.esm.js:2088
    m vue-router.esm.js:2384
    Ya vue-router.esm.js:2162
    m vue-router.esm.js:2362
    r vue-router.esm.js:2087
    r vue-router.esm.js:2091
    r vue-router.esm.js:2091
    r vue-router.esm.js:2091
    Ia vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2392
    transitionTo vue-router.esm.js:2260
    push vue-router.esm.js:2715
    push vue-router.esm.js:3036
    push vue-router.esm.js:3035
    openCard CardItem.vue:174
    VueJS 3
main.js:58:9
`

**Comment by nrgeen** [comment] 2023-11-14 09:46
Hello,
I am still experiencing the same problem.

It occurs under the following conditions:
Browser: Firefox 119.0
Nextcloud: 27.1.3
Deck: 1.11.0

For demonstration purposes, I have created a short video that hopefully shows the problem. 
I hope it helps: https://zuhause.mueller-post.de/s/DFAJRA6kzpPBBtR

**Comment by juliushaertl** [comment] 2023-11-14 14:49
Thanks for sharing that, can reproduce but only on stable27 not the main branch, I'll check for the difference

**Comment by juliushaertl** [comment] 2023-11-14 14:54
Fixed by https://github.com/nextcloud/deck/pull/4817 will backport this

**Closed by juliushaertl** 2023-11-14 14:54 UTC
Labels: bug, 1. to develop, feature: modal
