### ISSUE TITLE
"view description" button jumps around

### ISSUE THREAD

**Issue by fm-sys** [nextcloud/deck#1931] opened 2020-05-19 18:02 UTC
**Describe the bug**
The button "view description" jumps down, if there are unsafed changes (so the text field gets to long).

**Expected behavior**
The buttons should stay in a line.

**Screenshot**
![2020-05-19 19_53_58-Deck - Nextcloud](https://user-images.githubusercontent.com/64581222/82361130-bda0bd80-9a0a-11ea-8a1d-c600b53791a2.png)

**Client details:**
 - OS: Windows
 - Browser Firefox
 - Version 76.0.1 (64-Bit)
 - Device: desktop

**Comment by juliushaertl** [comment] 2020-05-19 18:22
Duplicate of https://github.com/nextcloud/deck/issues/1812

**Comment by juliushaertl** [comment] 2020-05-19 18:22
Ah sorry, to fast, it is not about the order.

**Comment by juliushaertl** [comment] 2020-05-19 18:25
I can reproduce this on small window sizes. We should make sure the text is shortened then with ...

**Closed** 2020-06-16 07:59 UTC
Labels: 1. to develop, bug, design: papercut
