### ISSUE TITLE
Allow external access?

### ISSUE THREAD

**Issue by Quin452** [nextcloud/deck#2007] opened 2020-06-09 15:14 UTC
Just wondering if there is a way to allow external access to Deck, similar to Trello.

Ideally, I'd like to invite people outside of my organisation (because it is literally just me) to comment on my boards.
I work with freelancers, so enabling them to create cards on boards for their projects would be handy, and give the opportunity for my clients to comment and ask questions on the tasks.

Sorry if this has been asked before.  I know there are Circles and Groups, but I couldn't find the information I needed on there (especially since Circles has only just been updated to work with the latest version of NextCloud).

**Comment by stefan-niedermann** [comment] 2020-06-09 15:24
Duplicate of https://github.com/nextcloud/deck/issues/14

**Closed by stefan-niedermann** 2020-06-09 15:24 UTC
