### ISSUE TITLE
Lost all information in description window and not working checkboxes

### ISSUE THREAD

**Issue by 4tler** [nextcloud/deck#2591] opened 2020-11-19 20:31 UTC
**Describe the bug**
If I activate checkboxes in the description, the entire content is deleted. After creating new boxes, they will not be able to be selected at the same time. When I select a box, another is deactivated.

**To Reproduce**
1. Go to 'Deck' and a card with checkboxes
2. Click on a checkbox

<details>
<summary>Server details</summary>

**Operating system**: ubuntu server 20.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.4

**Nextcloud version:** 19.0.4/20.0.2

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here. No errors have been found.
```

**List of activated apps:**
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.3
  - admin_audit: 1.10.0
  - apporder: 0.11.0
  - breezedark: 20.0.1
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.1
  **- deck: 1.2.1**
  - encryption: 2.8.1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.0
  - files_automatedtagging: 1.10.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trackdownloads: 1.9.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - flow_notifications: 1.0.2
  - forms: 2.0.4
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.3
  - support: 1.3.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - files_external
  - firstrunwizard
  - groupfolders
  - survey_client
  - user_ldap
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by stefan-niedermann** [comment] 2020-11-19 20:38
Duplicate of https://github.com/nextcloud/deck/issues/2580

A fix is already in the pipeline.

You should be able to [restore the description content from the timeline tab](https://github.com/nextcloud/deck/issues/2580#issuecomment-730319105).

**Closed by stefan-niedermann** 2020-11-19 20:38 UTC
