### ISSUE TITLE
Incorrect calendar view in increased card mode

### ISSUE THREAD

**Issue by neerro** [nextcloud/deck#3104] opened 2021-06-03 13:00 UTC
**Describe the bug**
When I opened empty card in increased card mode and tried to put any date inside the pop-up calendar, I've seen the next picture. Calendar doesn't show all its board and I have to scroll down to find the necessary date to mark it (as it shown on the picture below).

![Снимок](https://user-images.githubusercontent.com/75830569/120646830-96d0f000-c482-11eb-8081-ac8fa0bec5d7.PNG)

**Expected behavior**
It would be great if calendar board shown its board on top of all cards layers (shown with red line and dots in the picture above) 
**!** I assume that another two fields above, has the same issue, that should be improved too.

**By the way:** What about the translation. Some words have an English version. If it needed I would help you with translation in Russian.

**Client details:**
 - OS: Win10
 - Browser Firefox 
 - Version v90.0
 - Device: Desktop

<details>
<summary>Server details</summary>

**Operating system**: Linux Ubuntu

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** 22.0.2

**Where did you install Nextcloud from:** Nextcloud official repository

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by stefan-niedermann** [comment] 2021-06-03 14:46
Duplicate of https://github.com/nextcloud/deck/issues/2704 - please use the :mag: search function before opening new issues.

**Closed by stefan-niedermann** 2021-06-03 14:46 UTC

**Comment by neerro** [comment] 2021-06-03 19:41
Yes, you are right, but it was impossible for me to find the issue with mentioned theme description in issue #2704 as the theme name don't mirror an actual issue. And since the issue #2704 was posted some changes has done, and now we have no see the problems as calendar window moving to top or something like that. At present time we may observe only necessity to put the pop-up calendar window on the top layer.
