### ISSUE TITLE
Custom Tags

### ISSUE THREAD

**Issue by HumanG33k** [nextcloud/deck#2821] opened 2021-02-22 17:05 UTC
Hello sry if it's the wrong place but currently i can't add custom tags.
Their is a special menu entry somewhere ? I try the little + in the (right panel) form but not working. 

I use the last sable version of nextcloud.

**Comment by stefan-niedermann** [comment] 2021-02-22 17:13
Left sidebar, choose the 3-dots menu, board details. A sidebar opens at the right side, there you can manage your tags.

This is the correct place to report bugs and request features.

For help use help.nextcloud.com and if you think this is a bug please fill in the complete issue template - it's there for a reason 😉

**Comment by HumanG33k** [comment] 2021-02-22 17:19
No not working the + is when i type something in the tags form.

**Comment by stefan-niedermann** [comment] 2021-02-22 17:21
> if you think this is a bug please fill in the complete issue template - it's there for a reason 😉

We can not help without any logs from your browser and details of your environment.

**Comment by HumanG33k** [comment] 2021-02-22 17:29
ok i found the good view but it can be improve i guess. 

throught the boards option i can add  
![Capture d’écran_2021-02-22_18-24-34](https://user-images.githubusercontent.com/1794193/108745493-72887d80-753b-11eb-8932-f7c41a57cb6a.png)

but from the card details panel i can't the + do not work or the "enter" key. I use Linux with the dev version of firefox but but the "issue" was reported by one user of the instance.

![Capture d’écran_2021-02-22_18-25-22](https://user-images.githubusercontent.com/1794193/108745485-70262380-753b-11eb-99bc-7921c4e318dc.png)

There is somewhere a wiki or some of documentation ?

**Comment by stefan-niedermann** [comment] 2021-02-22 17:36
This should work, but again: **Please fill in the [issue template](https://github.com/nextcloud/deck/issues/new?assignees=&labels=&template=Bug_report.md)** and provide the requested information.

**Comment by mwunderling** [comment] 2021-03-22 01:40
I have the same issue on Deck 1.3.1 and NC 21 while using chrome. 

Per my image, I have only 4 usable tags. I can't even edit/remove them unlike in the image above. Typing in the input field and clicking the '+' icon does nothing for me.  
![chrome_MJTZHEOuLT](https://user-images.githubusercontent.com/22336325/111929661-3ed64000-8a74-11eb-973a-954048f75056.png)

**Comment by juliushaertl** [comment] 2021-04-14 16:20
Closing as a duplicate of #1472

**Closed by juliushaertl** 2021-04-14 16:20 UTC
