### ISSUE TITLE
Swimlanes

### ISSUE THREAD

**Issue by preske87** [nextcloud/deck#5539] opened 2024-02-01 09:51 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
- It's a feature request.
- I understood from another issue #32 that there was a discussion on swimlanes, which somehow ended.
- I would like to bring up the idea of swimlanes again, or however you want to call them

_What are the use cases_
- for a project team using a single kanban board, swimlines could be used to raise very important/critical issues to the top, i.e. having a swimlane "critical" at the top which holds e.g. tasks with close due date or high priority
- swimlanes allow to model a kanban-version of the Eisenhower-matrix by having a seggregation by urgency and importance
- swimlanes also allow to have "clusters" of task (typically by Epic). This then e.g. allows to have all tasks related for a given event in one cluster and not scattered all around the board

**Describe the solution you'd like**
- Swimlines, i.e. horizontal sections in the kanban board where tasks sharing the same attribute are located
- Allocation of tasks into a lane is distinct, i.e. one task is only allocated into one lane

**Describe alternatives you've considered**
- Taking the recommendation froms #32 different boards becomes messy

**Additional context**

**Comment by joshtrichards** [comment] 2024-10-02 14:59
Duplicate of #32

**Closed by joshtrichards** 2024-10-02 14:59 UTC
Labels: enhancement
