### ISSUE TITLE
Register Activity events to get Email notifications

### ISSUE THREAD

**Issue by UrienRakarth** [nextcloud/deck#563] opened 2018-07-31 17:48 UTC
**Is your feature request related to a problem? Please describe.**
The problem is that we cannot have email notifications when a card or stack are created.

**Describe the solution you'd like**
I think the integration with Activity app will be great (also with Notifications too).

**Describe alternatives you've considered**
I tried hard-codding it but we don't want that method since Activity has a true potential for it.

**Additional context**
Since Comments and File has the Activity working fine on it... I tried to do a version of it for Deck. But since I'm new to this I don't understand how to properly do it. 
I might find a solution to this but nothing fancy, just copying from here to there.

Thank you so much!

**Comment by juliushaertl** [comment] 2018-08-02 17:37
This is a duplicate of #211

**Closed by juliushaertl** 2018-08-02 17:37 UTC

**Comment by UrienRakarth** [comment] 2018-08-02 17:40
Lol sorry, thx :)
