### ISSUE TITLE
Ticket id for project items

### ISSUE THREAD

**Issue by ultrasites** [nextcloud/deck#3844] opened 2022-05-30 08:17 UTC
I need a (incremental) ticket id per project and it shoud be searchable. 
It's better to refollow it with the git log for example.

**Example:**
Board: Project A
Ticket: FooBar
TicketId: #ProjectA0001 

Best regards,
a beautiful deck user

**Comment by stefan-niedermann** [comment] 2022-05-30 08:39
Duplicate of https://github.com/nextcloud/deck/issues/2906

**Closed by stefan-niedermann** 2022-05-30 08:39 UTC
