### ISSUE TITLE
Paste in the description closes edition mode without the pasted content

### ISSUE THREAD

**Issue by callmemagnus** [nextcloud/deck#302] opened 2017-09-14 08:29 UTC
### Steps to reproduce
1. Create a task
2. open it on the right side panel
3. click to edit the description
4. Type something and then try to paste with Ctrl-v

### Expected behaviour
I should be able to continue editing the description.
I expect the Ctrl-v to work as the right-click->paste menu in my browser.

### Actual behaviour
The description field is not editable anymore and the content of the paste is not in the description.

### General server configuration

**Operating system:** Linux my,domain.com 3.14.32-xxxx-grs-ipv6-64 #9 SMP Thu Oct 20 14:53:52 CEST 2016 x86_64

**Web server:** nginx/1.10.3 (fpm-fcgi)

**Database:** mysql 5.5.57

**PHP version:** 5.6.30-0+deb8u1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - ereg
 - libxml
 - openssl
 - pcre
 - zlib
 - bcmath
 - bz2
 - calendar
 - ctype
 - dba
 - dom
 - hash
 - fileinfo
 - filter
 - ftp
 - gettext
 - SPL
 - iconv
 - mbstring
 - session
 - posix
 - Reflection
 - standard
 - shmop
 - SimpleXML
 - soap
 - sockets
 - Phar
 - exif
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xml
 - xmlreader
 - xmlwriter
 - zip
 - cgi-fcgi
 - PDO
 - apcu
 - curl
 - gd
 - gmp
 - imagick
 - imap
 - json
 - mcrypt
 - mysql
 - mysqli
 - pdo_mysql
 - pdo_sqlite
 - readline
 - recode
 - sqlite3
 - tidy
 - xmlrpc
 - xsl
 - mhash
 - apc
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** upgrade

**Where did you install Nextcloud from:**  tar.gz

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - apporder: 0.4.0
 - calendar: 1.5.4
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.2.2
 - federatedfilesharing: 1.2.0
 - files: 1.7.2
 - files_markdown: 2.0.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - passman: 2.1.4
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - encryption
 - federation
 - files_external
 - firstrunwizard
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocb8e977a2dd",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "...\/cloud\/nextcloud-data",
    "dbtype": "mysql",
    "version": "12.0.2.0",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "forcessl": true,
    "loglevel": 0,
    "theme": "",
    "maintenance": false,
    "trusted_domains": [
        "my.domain.com"
    ],
    "mail_from_address": "cloud",
    "mail_smtpmode": "php",
    "mail_domain": "domain.com",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "appstoreenabled": true,
    "appstoreurl": "https:\/\/api.nextcloud.com\/v1",
    "appstore.experimental.enabled": true,
    "trashbin_retention_obligation": "auto",
    "asset-pipeline.enabled": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "htaccess.RewriteBase": "\/",
    "updater.release.channel": "stable",
    "appcodechecker": false,
    "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
    "has_internet_connection": true<!--

**Operating system**: linux

**Web server:** nginx + php fpm

**Database:** mysql

**Signing status:**,
    "check_for_working_webdav": true,
    "check_for_working_wellknown_setup": true,
    "config_is_read_only": false,
    "remember_login_cookie_lifetime": 1296000,
    "session_lifetime": 86400,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "apps_paths": [
        {
            "path": "...\/cloud\/nextcloud\/apps",
            "url": "\/apps",
            "writable": true
        },
        {
            "path": "...\/cloud\/nextcloud\/apps2",
            "url": "\/apps2",
            "writable": true
        }
    ],
    "overwrite.cli.url": "https:\/\/my.domain.com"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0

**Operating system:** Linux

### Logs

<details>
        <summary>Browser log</summary>
When the edition starts, console only write:

```
edit
undefined
```

</details>

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**Comment by juliushaertl** [comment] 2017-09-15 06:44
@callmemagnus Thanks for your bug report. I currently cannot reproduce this issue on FF55 here.

> When the edition starts, console only write:
> edit
> undefined

That is not happening on my instance. Are you running  the latest version of deck?

**Comment by callmemagnus** [comment] 2017-09-21 09:14
Tested again with the following setup:
FF 55.0.2 on linux
nextcloud: 12.0.2
deck: 0.2.2

Still unable to paste with Ctrl-V in the description field.

![image](https://user-images.githubusercontent.com/232478/30688261-f33b3ccc-9ebd-11e7-86ee-ec4d8ca1c0d2.png)

**Comment by juliushaertl** [comment] 2017-10-08 12:39
Hm, are you using any browser extensions or maybe a clipboard manager that might cause this? Works fine here with firefox/gnome both using ctrl-v and middle-mouse-button.

**Comment by callmemagnus** [comment] 2017-10-09 19:39
Hello again... I restarted in safe-mode to disable all my extension on firefox.

With sadly the same result, I Ctrl-v and the focus leave the field.

I did a video but it seems that github does not support that file type in issues.

-> https://youtu.be/YntkdJ0cajY

**Comment by juliushaertl** [comment] 2017-10-10 11:11
@callmemagnus Can you check if pasting works in the following jsfiddle: https://jsfiddle.net/juliushaertl/bfqu5sck/3/

The field should keep focus and 'blur: false' should still be set.

**Comment by juliushaertl** [comment] 2018-01-13 09:24
Closing since I'm unable to reproduce and no further answer since some time. Feel free to reopen if there is new information.

**Closed by juliushaertl** 2018-01-13 09:24 UTC
Labels: 0. Needs triage, bug

**Comment by callmemagnus** [comment] 2018-01-14 10:51
Oups, I forgot to follow up on this issue.

I tested the jsfiddle.

I tried to investigate a little. Can it be that typing Ctrl blurs the field ? In your fiddle, when I focus on the textarea I get (obviously):

```
focus: true
blur: false
```
 
But when I press Ctrl down, I get, while keeping the finger on the key:

```
focus: false
blur: true
```

As soon as I press the V, it changes back to the "normal" one.

Can this be the issue? I wonder if the edit mode is closed as soon a the blur event is triggered.

If yes, the guilty chain:

- angular
- firefox
- gnome 3
- ubuntu

And guess what... I am only able to reproduce this with firefox. Tried Chromium and Chrome, both of them do not blur on pressing Ctrl.

**Comment by juliushaertl** [comment] 2018-01-15 14:15
> But when I press Ctrl down, I get, while keeping the finger on the key:
Hm, that seems to be the reason why the focus is lost on your setup.

> If yes, the guilty chain:
I'm actually running all the same, except that i run arch linux instead of ubuntu. 

> And guess what... I am only able to reproduce this with firefox. Tried Chromium and Chrome, both of them do not blur on pressing Ctrl.

My intention is, that this might be a firefox bug, since it works fine with my FF57 and you are using FF55.

**Comment by callmemagnus** [comment] 2018-03-01 09:58
Hello again,

OK  I finally found the reason of the misbehaving Ctrl key.

In gnome there was a configuration that enabled you to "highlight" the position of the mouse when you click "Ctrl". It does not work anymore, don't know why.

The configuration was still there. So it was interfering with ALL operations using Ctrl.

Sorry for the noise!

The said configuration:

```
gsettings set org.gnome.settings-daemon.peripherals.mouse locate-pointer false
```

**Comment by juliushaertl** [comment] 2018-03-01 11:42
@callmemagnus Great that you found a solution.
