### ISSUE TITLE
Save attachments to Files

### ISSUE THREAD

**Issue by metbril** [nextcloud/deck#2003] opened 2020-06-08 18:19 UTC
**Is your feature request related to a problem? Please describe.**

... attachments I add to cards are only available through the card and cannot be found in the Files app.

**Describe the solution you'd like**

Any file uploaded to a card is (also) stored in a location in the Files app. For example in a `/Deck` folder. 

**Describe alternatives you've considered**

I currently add files from the files app as a "linked" file, but a simple direct "upload and link" would be awesome.

**Additional context**

**Comment by juliushaertl** [comment] 2020-06-08 18:26
Duplicate of #564

**Comment by metbril** [comment] 2020-06-09 04:05
This is not a duplicate. It is the other way around. The other request let's a user attach an already uploaded file. My request let's a user upload a file in Deck but SAVE it to Files.

**Comment by juliushaertl** [comment] 2020-06-09 06:49
It is, just the title is not updated to the full flow we decided on:

> Files uploaded from local storage will be stored in a default folder, pre-defined by the user.

**Closed by juliushaertl** 2020-06-09 06:49 UTC
