### ISSUE TITLE
Restricted boards for only users' cards.

### ISSUE THREAD

**Issue by emirefek** [nextcloud/deck#2606] opened 2020-11-23 10:16 UTC
[Feature Request]

Hi. Everyone thanks for this awesome opensource product. But I think there should be a feature like which I'll describe. 

We don't want to hide boards from specific users but sometimes we don't want to all users see all board. Is there a chance to create permission hierarchy like this?

**More clearly definition :
Assume 4 different groups: (Team Admin), (Team Manager), (Employees1), (Employees2)
Assume we have just 1 board: (Active Jobs)
Assume We have 3 different cards in our board: (Job1), (Job2), (Job3).

** Scenario:
Team Manager added Card(Job1), assigned to (Employee1) = Result: (Team Admin), (Team Manager), (Employees1) can see it in board.
Team Manager added Card(Job2), assigned nobody = Result: (Team Admin), (Team Manager) can see it in board.
Team Admin added Card(Job3), assigned to (Employee2) = Result: (Team Admin), (Team Manager), (Employees2) can see it in board.

I think I clearly explained everything. If you have questions about feature request, I can explain more. Thanks.

**Comment by juliushaertl** [comment] 2020-12-29 20:00
Could you check https://github.com/nextcloud/deck/issues/663 maybe? I think having an option to limit access to only assigned cards should cover your use case so I'd close this as a duplicate of the other feature request.

**Closed by juliushaertl** 2020-12-29 20:00 UTC
