### ISSUE TITLE
NC 25.0.5 - Card: month and year cannot be selected!

### ISSUE THREAD

**Issue by Nick-Git2** [nextcloud/deck#4564] opened 2023-03-27 19:23 UTC
only days can be selected but no month & no year

![grafik](https://user-images.githubusercontent.com/65270786/228044674-e6560f25-8970-4a9e-a6f2-76caf43dcaca.png)

**Comment by reox** [comment] 2023-03-28 11:11
Duplicate of #4296 and others...

edit the text, so the modal container gets larger and the full calender is displayed.

**Comment by juliushaertl** [comment] 2023-05-03 10:53
Fixed in #4643

**Closed by juliushaertl** 2023-05-03 10:53 UTC
