### ISSUE TITLE
Deck 1.2.8 is broken on NC 18

### ISSUE THREAD

**Issue by liejuntao001** [nextcloud/deck#3197] opened 2021-07-16 15:11 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Upgrade Deck from 1.2.7 to 1.2.8, the plugin is broken on NC 18

**To Reproduce**
Right after the upgrade, there are continuous error logs from various "other" app, like "notification", "core", "index".
The "Deck" app is not usable. An "internal server error" is returned from UI.

Disable "Deck" app, no more error logs

Downgrade Deck to 1.2.7, things back to normal.

**Expected behavior**
It should work

**Screenshots**

**Client details:**
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]  90.0.4430.212
 - Device: [e.g. iPhone6, desktop] Desktop

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Example one from "notification"

{"reqId":"0L7H4hTAiFsP0xKLVtHD","level":3,"time":"2021-07-16T02:16:58+00:00","remoteAddr":"14.140.93.241","user":"488cdd74-158b-1038-973f-a769092e89b8","app":"notifications","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve boardMapper! Class boardMapper does not exist","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":115,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["boardMapper"]},{"file":"/var/www/html/lib/private/ServerContainer.php","line":150,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["boardMapper",true]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":77,"function":"query","class":"OC\\ServerContainer","type":"->","args":["boardMapper"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":100,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Deck\\Notification\\Notifier","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":115,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Deck\\Notification\\Notifier"]},{"file":"/var/www/html/lib/private/ServerContainer.php","line":150,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Deck\\Notification\\Notifier",true]},{"file":"/var/www/html/lib/private/Notification/Manager.php","line":147,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Deck\\Notification\\Notifier"]},{"file":"/var/www/html/lib/private/Notification/Manager.php","line":252,"function":"getNotifiers","class":"OC\\Notification\\Manager","type":"->","args":[]},{"file":"/var/www/html/apps/notifications/lib/Controller/EndpointController.php","line":102,"function":"prepare","class":"OC\\Notification\\Manager","type":"->","args":[{"__class__":"OC\\Notification\\Notification"},"en"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"listNotifications","class":"OCA\\Notifications\\Controller\\EndpointController","type":"->","args":["v2"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Notifications\\Controller\\EndpointController"},"listNotifications"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Notifications\\Controller\\EndpointController"},"listNotifications"]},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Notifications\\Controller\\EndpointController","listNotifications",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"apiVersion":"v2","_route":"ocs.notifications.Endpoint.listNotifications"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"apiVersion":"v2","_route":"ocs.notifications.Endpoint.listNotifications"}]},{"file":"/var/www/html/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"apiVersion":"v2","_route":"ocs.notifications.Endpoint.listNotifications"}]},{"file":"/var/www/html/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/notifications/api/v2/notifications"]},{"file":"/var/www/html/ocs/v2.php","line":24,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","Line":106,"CustomMessage":"Failed to load notification notifier class: OCA\\Deck\\Notification\\Notifier"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0","version":"18.0.14.1","id":"60f0ec32e2ede"}


Another one from "index"

{"reqId":"eGchUzZqfjSDkRgFmzJ4","level":3,"time":"2021-07-16T02:16:52+00:00","remoteAddr":"23.28.233.78","user":"99ee83ec-494f-1037-90b1-e18fef703928","app":"index","method":"GET","url":"/apps/deck/","message":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve permissionService! Class permissionService does not exist","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":115,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["permissionService"]},{"file":"/var/www/html/lib/private/ServerContainer.php","line":150,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["permissionService",true]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":389,"function":"query","class":"OC\\ServerContainer","type":"->","args":["permissionService",true]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":77,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["permissionService"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":100,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Deck\\Controller\\PageController","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":115,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Deck\\Controller\\PageController"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":415,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Deck\\Controller\\PageController"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":386,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Deck\\Controller\\PageController"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":112,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Deck\\Controller\\PageController"]},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Deck\\Controller\\PageController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"deck.page.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"deck.page.index"}]},{"file":"/var/www/html/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"deck.page.index"}]},{"file":"/var/www/html/lib/base.php","line":1011,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/deck/"]},{"file":"/var/www/html/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","Line":106,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36","version":"18.0.14.1","id":"60f19fbcf2056"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by stefan-niedermann** [comment] 2021-07-16 15:12
@liejuntao001 can you please verify that this issue is not a duplicate of https://github.com/nextcloud/deck/issues/3194?

**Closed** 2023-08-22 16:44 UTC
