### ISSUE TITLE
Deadline

### ISSUE THREAD

**Issue by JeremyCrealead** [nextcloud/deck#4671] opened 2023-05-12 09:41 UTC
Hi,
since the last update, you can no pick the due date of a calendar in the cards. 

Thanks in advance.

**Comment by stefan-niedermann** [comment] 2023-05-12 09:48
Duplicate of https://github.com/nextcloud/deck/issues/4663

**Closed by stefan-niedermann** 2023-05-12 09:48 UTC

**Comment by juliushaertl** [comment] 2023-05-12 09:53
Also please don't ignore the issue template next time, there are reasons for asking additional information like the version
