### ISSUE TITLE
Board - Clone

### ISSUE THREAD

**Issue by mattheskay** [nextcloud/deck#6497] opened 2024-11-14 13:31 UTC
Hello,
first i would like to thank you for this fantastic application.

For our use (and i read it some month ago, that there were also other users asking for this) it would be very important, that if you want to copy/clone a board, that the cards within the lists (cards without content) would be copied too. And, that the order of the lists stays the same. (Now order changes "randomly")

Also an option to choose what components to clone would be perfect.

These improvements would really help a lot and bring it to a higher level.

**Comment by grnd-alt** [comment] 2024-11-14 14:27
Thanks for your feedback, we really appreciate it. Such a feature has already been requested, and is even somewhat in development. We hope to see some improvements on the cloning functionality in the future.

**Comment by grnd-alt** [comment] 2024-11-14 14:27
duplicate of #2797

**Closed by grnd-alt** 2024-11-14 14:27 UTC
