### ISSUE TITLE
 Impossible to drop the card in an empty column

### ISSUE THREAD

**Issue by oparoz** [nextcloud/deck#235] opened 2017-07-06 12:11 UTC
### Steps to reproduce

1. Move a card from its current location to and empty column

### Expected behaviour

The dotted drop zone should show up

### Actual behaviour

Impossible to drop the card

On 0.2.1

**Comment by juliushaertl** [comment] 2017-07-06 13:43
@pixelipo Can you have a look, this might be caused by the migration to SCSS.

**Comment by juliushaertl** [comment] 2017-08-08 10:37
Fixed with #238

**Closed by juliushaertl** 2017-08-08 10:37 UTC
Labels: 2. developing, bug, design, frontend, high
