### ISSUE TITLE
Board Templates and/or Board Cloning

### ISSUE THREAD

**Issue by bobrocksgithub** [nextcloud/deck#347] opened 2017-11-25 15:34 UTC
### Steps to invoke:
1. Click on existing board
2. Select "Clone"
3. New Board is created as clone

OR

### Steps to invoke:
1. Select dropdown next to +
2. Select "New from Template"
3. Creates new Board from seleted template

### Purpose
Many Projects share similar structures and/or Stack
Enabling Board Templates and/or cloning enables rapid setup of new Boards from predefined Boards (templates)
This saves a lot of time by preventing creation of similar Boards/Stacks

**Comment by juliushaertl** [comment] 2017-11-25 20:26
duplicate of https://github.com/nextcloud/deck/issues/154

**Closed by juliushaertl** 2017-11-25 20:26 UTC

**Comment by bobrocksgithub** [comment] 2017-11-26 08:11
Sorry, looked through the list and missed it.
thanks
