### ISSUE TITLE
Deleted deck cards are being kept in deleted items forever

### ISSUE THREAD

**Issue by 31337-4554551n** [nextcloud/deck#2927] opened 2021-03-31 09:51 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

**To Reproduce**
1. Go to a board
2. Click on deleted items
3. Scroll down to the bottom of the list
4. See that the earliest cards are still sitting in deleted, and haven't been cleaned up. This includes any attachments which remain on the file system

**Expected behavior**
For there to only be deleted items from a short period leading up.

**Screenshots**
![image](https://user-images.githubusercontent.com/26422914/113125490-00056e80-925a-11eb-86e6-44d0131f42fd.png)

**Client details:**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Desktop

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 20.0.8

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by stefan-niedermann** [comment] 2021-05-21 15:24
@jakobroehrl or @juliushaertl are you able to reproduce this issue? I have been asked a couple of times now on various channels, but i can't really figure out what might be wrong here...

It seems to be a blocking issue for at least one organisation as far as i can tell...

**Comment by jakobroehrl** [comment] 2021-05-30 12:33
So the problem is, that deleted cards are never completly deleted?
I can reproduce this. On my system are deleted cards from 9 month ago

**Comment by 31337-4554551n** [comment] 2021-06-10 08:18
Yes, that's my issue.
Server is getting clogged with image attachments etc for cards that should be long gone.
I don't suppose you know a fix? Are other people having this?

**Comment by 31337-4554551n** [comment] 2021-07-08 07:38
I am sorry, I do not know well enough how to use github and track changes of things-so I apologise if this is being worked on, I wouldn't know.

Just wanted to make sure I'm not the only one still experiencing this on the latest version of deck? @jakobroehrl are you still seeing this
Is there some unofficial/manual fix I can implement to temporarily alleviate the problem?

**Comment by jakobroehrl** [comment] 2021-07-08 14:01
Currently there is no fix.

**Comment by 31337-4554551n** [comment] 2021-07-08 14:05
> Currently there is no fix.

Is this an issue affecting everyone, or just under certain conditions?
Also, is there some form of manual cleanup/work around available?

It's got to be only certain people, right? Seems like a problem that would be getting attention if it was impossible to delete cards for everyone

**Comment by matejak** [comment] 2021-08-03 16:59
It is interesting that deleted items are hanging there while #133 seemingly implements deleting after five minutes: https://github.com/nextcloud/deck/pull/133/commits/2c63bfb4b8a7d5b0c22dc1d753e56d1dd08b61a9 @jakobroehrl could you please clarify this?

**Comment by 3on108** [comment] 2021-08-22 20:03
Looking into the solution from #133, I propose to implement similar solution as in this commit for deleted boards, i.e. to permanently erase deleted deck cards every 5 min via a cron job - https://github.com/nextcloud/deck/pull/133/commits/2c63bfb4b8a7d5b0c22dc1d753e56d1dd08b61a9 

1. extend CardMapper.php with findToDelete() similar to BoardMapper.php
3. extend DeleteCron.php to initiate cardMapper and call cardMapper->findToDelete() and ->delete()

**Comment by 31337-4554551n** [comment] 2021-09-29 07:00
I am sorry I'm not terribly familiar with github, but just seeing the year old cards still exist on my system after updating deck a couple of times since starting this issue. is it a known issue, or something funky with my particular setup?

**Comment by 3on108** [comment] 2021-09-29 18:29
> I am sorry I'm not terribly familiar with github, but just seeing the year old cards still exist on my system after updating deck a couple of times since starting this issue. is it a known issue, or something funky with my particular setup?

Hi, this is a know issue, I've already implemented a fix and it's currently in the code review process. Once my changes are approved, they will be included in the following release of the deck application or that's at least how I understand the process :-)

**Comment by 31337-4554551n** [comment] 2021-09-30 04:01
> > I am sorry I'm not terribly familiar with github, but just seeing the year old cards still exist on my system after updating deck a couple of times since starting this issue. is it a known issue, or something funky with my particular setup?
> 
> Hi, this is a know issue, I've already implemented a fix and it's currently in the code review process. Once my changes are approved, they will be included in the following release of the deck application or that's at least how I understand the process :-)

You're a champion. Thank you so much for your hard work!

**Comment by 31337-4554551n** [comment] 2021-11-26 14:06
> > I am sorry I'm not terribly familiar with github, but just seeing the year old cards still exist on my system after updating deck a couple of times since starting this issue. is it a known issue, or something funky with my particular setup?
> 
> Hi, this is a know issue, I've already implemented a fix and it's currently in the code review process. Once my changes are approved, they will be included in the following release of the deck application or that's at least how I understand the process :-)

So it looks like there have been some deck version updates since, but deleted items persist?

**Comment by 3on108** [comment] 2021-11-27 13:29
> So it looks like there have been some deck version updates since, but deleted items persist?

Unfortunately we found a bug in my implementation, so I will have to fix it first for the change to be included in the deck release.

**Comment by 31337-4554551n** [comment] 2022-11-07 08:25
This is still ongoing, I was wondering if there was any progress on this?

**Closed** 2022-11-07 17:26 UTC
