### ISSUE TITLE
Filter view: only see cards by person x or tag y

### ISSUE THREAD

**Issue by dosch** [nextcloud/deck#670] opened 2018-11-02 14:37 UTC
I'd like to have filtered views

When viewing a deck full of cards I'd like to filter to see only cards assigned to me, or with a certain tag on them.

This would allow me to quickly see what is relevant to me.

**Comment by juliushaertl** [comment] 2018-11-06 18:51
Seems to be a duplicate of #414

**Closed by juliushaertl** 2018-11-06 18:51 UTC
