### ISSUE TITLE
Losing all the description if I click on a checkbox.

### ISSUE THREAD

**Issue by Byter3** [nextcloud/deck#2612] opened 2020-11-24 11:28 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Losing all the description if I click on a checkbox.

**To Reproduce**
1. Select a card with check list on it
2. Click on a checkbox
4. disapears the description

**Expected behavior**
Not disapearing, but marking it checked

**Client details:**
 - Browser Edge(chromium)
 - Version 87.0.664.41
 - Device: Windows 10

**Operating system**: Linux 4.9.0-13

**Database:** PostgreSQL 9.6.17

**PHP version:** 7.4.3

**Nextcloud version:** 19.0.4

**Where did you install Nextcloud from:**
Univention appliance  (uptodate)

</details>

**Comment by stefan-niedermann** [comment] 2020-11-24 12:52
Duplicate of https://github.com/nextcloud/deck/issues/2580, https://github.com/nextcloud/deck/issues/2591, #2595 #2603, #2610 and #2592 

[A fix](https://github.com/nextcloud/deck/pull/2584) is already in the pipeline.

You should be able to [restore the description content from the timeline tab](https://github.com/nextcloud/deck/issues/2580#issuecomment-730319105).

Please use the search function next time before open a new issue, thank you 🙂.

**Closed by stefan-niedermann** 2020-11-24 12:52 UTC
