### ISSUE TITLE
Ability to move the Deck folder

### ISSUE THREAD

**Issue by newhinton** [nextcloud/deck#3751] opened 2022-04-24 14:48 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when nextcloud apps create their datafolder in my nextcloud root folder

**Describe the solution you'd like**
Like other apps do it, provide a setting that allows the user to set a custom folder for that data.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by stefan-niedermann** [comment] 2022-04-24 15:33
Duplicate of https://github.com/nextcloud/deck/issues/3176

Please use the 🔍  **search function** before opening new issues.

**Closed by stefan-niedermann** 2022-04-24 15:33 UTC
