### ISSUE TITLE
List of boards broken after update to 0.4 

### ISSUE THREAD

**Issue by wiertz** [nextcloud/deck#530] opened 2018-07-12 15:05 UTC
I just updated to Deck v0.4 (on Nextcloud 13.04) and the menu to the left does not list any existing board. All it shows are the general menu items (All boards, Archived boards...) and the java script placeholder {{ b.title }}. I tried on my iPad and on my Mac using Firefox.

**Comment by juliushaertl** [comment] 2018-07-12 15:07
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/nextcloud/deck/issues/528 (Lost all data when update to 0.4.0), https://github.com/nextcloud/deck/pull/524 (Prepare 0.4.0 release), https://github.com/nextcloud/deck/issues/502 (line feed in decription of cards after update to deck 0.4.0-beta2), https://github.com/nextcloud/deck/issues/78 (Avatars broken on 0.1.2), and https://github.com/nextcloud/deck/issues/231 (The style is broken after update to 0.2.1).

**Comment by juliushaertl** [comment] 2018-07-12 15:38
@wiertz Thanks for reporting. I cannot reproduce that, but can you check the browser error console for possible javascript error messages?

Maybe related to #528 so maybe you can try if #529 fixes the issue for you?

**Comment by wiertz** [comment] 2018-07-12 15:56
@juliushaertl Thanks for the very fast response. #529 does fix the issue (modifying lib/Controller/PageController.php as in https://github.com/nextcloud/deck/pull/529/files).

I found an unrelated (possible) issue with colours while checking the js console: "The specified value "#{{b.color}}" does not conform to the required format. The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers." Possibly because of the changes to the colour selection for boards. Also the new colour picker does not show in Safari (Chrome and Firefox work fine though).

Thanks for your work – I really enjoy Deck a lot!

**Comment by juliushaertl** [comment] 2018-07-15 09:43
Closing as a duplicate of #528 

@wiertz Please open separate issues for the color picker bugs. :wink:

**Closed by juliushaertl** 2018-07-15 09:43 UTC
Labels: bug, needs info
