### ISSUE TITLE
Markdown in comments

### ISSUE THREAD

**Issue by Dunrar** [nextcloud/deck#4097] opened 2022-10-03 10:18 UTC
### Feature Request
I would like to see markdown support for comments. 

There was an issue for this already, but it has been closed due to comments being something that should be changed in Nextcloud core. While that is undoubtedly true, it seems more relevant to Deck than to any other app or function of Nextcloud. There is an issue in the core repository (https://github.com/nextcloud/server/issues/17375) but that has been open since 2019 and I don't think this will be worked on in the foreseeable future, if ever. 

**Is your feature request related to a problem? Please describe.**
I switched over from Trello, and the comments there are way more powerful due to markdown formatting support. 

**Describe alternatives you've considered**
Someone from Deck implementing it in Nextcloud core.

**Comment by dodedodo** [comment] 2022-10-04 10:32
This is a duplicate to #2905 and #2143.

**Comment by juliushaertl** [comment] 2022-10-04 12:35
Closing as a duplicate of https://github.com/nextcloud/deck/issues/2143#issuecomment-676662256

**Closed by juliushaertl** 2022-10-04 12:35 UTC

**Comment by stefan-niedermann** [comment] 2023-06-07 09:12
> Please just do it!

Looking forward to your contribution in https://github.com/nextcloud/server/issues/17375 :slightly_smiling_face: :rocket:
