### ISSUE TITLE
Group Cards

### ISSUE THREAD

**Issue by beccon4** [nextcloud/deck#1818] opened 2020-05-07 07:59 UTC
To manage projects one often divides tasks into subtasks which are handled together.

For that reason it would be very helpful to be able to group cards in a hierarchical manner like Trello does i.e. attach a card to the one above - and ident it accordingly.

**Comment by jakobroehrl** [comment] 2020-05-12 09:38
Could you provide some screenshots?

**Comment by beccon4** [comment] 2020-05-12 10:53
![grafik](https://user-images.githubusercontent.com/12436716/81675825-9b79cf00-944f-11ea-8935-8f9dd2eb0d53.png)

**Comment by juliushaertl** [comment] 2020-05-15 15:01
Duplicate of #272

**Closed by juliushaertl** 2020-05-15 15:01 UTC
Labels: 1. to develop, enhancement
