### ISSUE TITLE
Can't drag and drop card to empty stack

### ISSUE THREAD

**Issue by swalladge** [nextcloud/deck#266] opened 2017-07-20 08:01 UTC
### Steps to reproduce
1. create a new deck
2. create two new stacks
3. create a new card on one stack
4. attempt to drag and drop the card to the other stack

### Expected behaviour

The card should move from the original stack to the other stack when dropped.

### Actual behaviour

Nothing. The card returns to the original stack. Impossible to drag it across.

Note that it works fine for me when the stack that you are dragging it to has at least one card on it.

### Server configuration

Nextcloud 12.0.0
Deck 0.2.1

**Comment by arendtio** [comment] 2017-07-20 13:20
I can confirm the bug. I think this is a regression introduced with the 0.2.1 update.

**Comment by juliushaertl** [comment] 2017-07-20 17:41
Duplicate of #257 
I'll try to release a new bugfix release over the weekend. Thanks for reporting anyways @swalladge

**Closed by juliushaertl** 2017-07-20 17:41 UTC
