### ISSUE TITLE
display of task title is not correct/description of a task doesn't work

### ISSUE THREAD

**Issue by SvenSonnadara** [nextcloud/deck#2000] opened 2020-06-08 12:09 UTC
1. If I click on a Task, the title in the right frame is shown very strange.

2. It is not possible to write a task comment. If I click on the edit button, the textfield is not editable.

This happens after the latest update to 1.0.2

 - OS: macOS Mojave
 - Browser Chrome
 - Version 83.0.4103.97
 - Device: Macbook pro

**Comment by stefan-niedermann** [comment] 2020-06-08 12:31
Dear @SvenSonnadara 

can you please check whether

- "title is shown very strange" is a duplicate of https://github.com/nextcloud/deck/issues/1980
- "textfield is not editable" is a duplicate of https://github.com/nextcloud/deck/issues/1999

?

**Comment by SvenSonnadara** [comment] 2020-06-08 13:23
Dear @stefan-niedermann,
yes, both are duplicates. Sorry.

**Comment by SvenSonnadara** [comment] 2020-06-08 13:26
When do you expect an update? We use Deck for protocol and task purposes in a public school.

**Comment by stefan-niedermann** [comment] 2020-06-08 13:54
I'm not a developer of the server app, i am just the maintainer of the Android app.

But i am pretty sure that @juliushaertl is working on this topics as soon and hard as he can. Maybe you already have a solution in mind? A pull request with a poc for a fix would speed up the process for sure 🚀  😉 

Let's close this issue and track the problems in the mentioned and linked issues.

**Closed by stefan-niedermann** 2020-06-08 13:54 UTC
