### ISSUE TITLE
Integrate with Tasks

### ISSUE THREAD

**Issue by iGadget** [nextcloud/deck#2254] opened 2020-09-01 17:12 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Currently Deck and Tasks are two completely(?) separate apps with somewhat overlapping functionality.
It would be really helpful if the two had some level of integration to prevent duplicate work and to complement each other's missing functionality.

**Describe the solution you'd like**
Just being able to link Deck projects / cards to specific tasks easily and vice-versa would already help a lot as a 'quick win'.
Deeper integration could then be considered for the longer term, i.e. displaying / embedding specific items from Tasks *inside* Deck.

**Describe alternatives you've considered**
Having worked with Trello, it's pretty obvious that checklists can come in pretty handy in projects. Since Tasks already provides this, it might be preferable to re-use this functionality instead of re-inventing the wheel.

**Additional context**
Will add upon request.

**Comment by ecc86** [comment] 2020-09-02 09:46
This issue seems to be related to or could be a duplicate of #15 I think..?

**Closed** 2020-09-03 06:23 UTC
