### ISSUE TITLE
Deck sharing by link

### ISSUE THREAD

**Issue by thoys1** [nextcloud/deck#4058] opened 2022-09-13 12:21 UTC
Hello Together, 

_Is your feature request related to a problem? Please describe._
I wanna share a board (in Decks) to People, who are not user in any cloud. Share means in read or read/write mode. 
E.g. a teacher sends a link to the pupils an says "look at my baord, there you can find your homework".

_Describe the solution you'd like_
I can share a file or a folder with many options with a link. I like to do the same with a Board. 

Thanks a lot
Thoys

**Comment by stefan-niedermann** [comment] 2022-09-13 13:29
Please use the 🔍  **search function** before opening new issues.

Closing as duplicate of https://github.com/nextcloud/deck/issues/14

**Closed by stefan-niedermann** 2022-09-13 13:29 UTC
