### ISSUE TITLE
Extend the action menu of a card with a "Move" action.

### ISSUE THREAD

**Issue by RobertZenz** [nextcloud/deck#797] opened 2018-12-16 10:30 UTC
The actions menu of cards should be extended with a "Move" action which allows you to move the card to a different stack. Ideally this would be a submenu with the name of all stacks in the current board.

This is (kinda) required if you're on a device on which dragging does not work very well, or if dragging is not possible for other reasons (accessibility issues for example).

**Comment by juliushaertl** [comment] 2018-12-20 07:37
Thanks for your bug report. This is a duplicate of https://github.com/nextcloud/deck/issues/249 which should also support moving between stacks of the current board.

**Closed by juliushaertl** 2018-12-20 07:37 UTC
