### ISSUE TITLE
Use mouse wheel to horizontally scroll across cards

### ISSUE THREAD

**Issue by severin-lemaignan** [nextcloud/deck#525] opened 2018-07-11 08:31 UTC
With more than a few cards, you end up scrolling horizontally quite a lot.

Using the mouse wheel to scroll left and right would provide a smoother interaction.

**Comment by juliushaertl** [comment] 2018-07-11 08:32
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/nextcloud/deck/issues/317 (Card overflow scrolling for action menu), https://github.com/nextcloud/deck/issues/39 (Card should stick with the mouse while moving it around), https://github.com/nextcloud/deck/issues/480 (Recurrently cards), https://github.com/nextcloud/deck/issues/466 (Board doesn't scroll to right side, when moving a card to right side), and https://github.com/nextcloud/deck/issues/138 (Card redesign).

**Comment by juliushaertl** [comment] 2018-07-11 08:33
It should already work that way. It works well for me with Chrome on Linux. Can you provide some details about your browser?

**Comment by severin-lemaignan** [comment] 2018-07-11 08:39
THanks for the super quick response!
I'm on Firefox 60 on Linux.
That said, I've tried with Chromium 67, and it does not work either for me.

**Comment by juliushaertl** [comment] 2018-07-11 08:44
Hm, strange. I cannot reproduce this with Firefox/Chome and both scrolling with the mouse wheel as well as with my trackpad works fine. Just to be sure, horizontal scrolling works on other webpages for you, right?

**Comment by severin-lemaignan** [comment] 2018-07-11 10:10
Horizontal scrolling works on all webpages -- including Deck -- if I press shift while scrolling.

It is not immediately intuitive to me, because in my use case, I've a lot of cards, and few tasks per card -> my layout is mostly horizontal, and I do not often need to scroll vertically. As such, using the mouse wheel (without pressing shift) to scroll horizontally by default would make more sense to me.

**Comment by juliushaertl** [comment] 2018-07-11 10:23
> As such, using the mouse wheel (without pressing shift) to scroll horizontally by default would make more sense to me.

I got your request wrong then. So you propose to scroll horizontally by default when the user scrolls the mouse wheel vertically.

> It is not immediately intuitive to me, because in my use case, I've a lot of cards, and few tasks per card -> my layout is mostly horizontal, and I do not often need to scroll vertically. 

That is a rather use case specific issue. I don't feel comfortable with overwriting browser defaults that would then confuse users who might have decks the other way round with lots of cards on one stack. But thank you very much for your idea @severin-lemaignan, highly appreciated.

**Closed by juliushaertl** 2018-07-11 10:23 UTC
Labels: needs info

**Comment by severin-lemaignan** [comment] 2018-07-11 10:28
@juliushaertl thanks for your responsiveness! and I agree, changing the default browser behaviour is probably not a good idea.
