### ISSUE TITLE
Comment function for cards

### ISSUE THREAD

**Issue by hx187** [nextcloud/deck#640] opened 2018-10-09 22:30 UTC
**Is your feature request related to a problem? Please describe.**
If I am editing a card together with another person, I would like to write comments for that card. So that my colleague, among others, knows why there are current problems, etc.

**Describe the solution you'd like**
A comment function for each map. Best with the editor and the time stamp.

**Describe alternatives you've considered**
Alternatively, you could do it via the description field. However, this is very unattractive and makes no sense.

**Additional context**
-

**Comment by juliushaertl** [comment] 2018-10-10 05:31
This is a duplicate of #10 We just released a first beta of the new version 0.5 which includes this feature. Feel free to test it: https://help.nextcloud.com/t/call-for-testing-deck-0-5-beta/38749

**Closed by juliushaertl** 2018-10-10 05:31 UTC
