### ISSUE TITLE
Extending sidebar content / container (Board menu dialog cut out)

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/deck#2106] opened 2020-07-06 09:04 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
Board menu dialog seems to be cut out by constrains of sidebar container size (see screenshots)

**To Reproduce**
1 open deck, create new board if you havent already
2 on left sidebar, click "menu" (three dots)
3 notice the dialog is cut out and scrolling is required in order to see it full

**Expected behavior**
dialog should be visible in its entirety without the need of scrolling

**Screenshots**

![Screenshot_3](https://user-images.githubusercontent.com/36133540/86575964-62099f80-bf78-11ea-883f-fd40108254da.png)

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by stefan-niedermann** [comment] 2020-07-06 09:15
Duplicate of https://github.com/nextcloud/deck/issues/2050. Please use the search function before opening new issues.

There is already a fix in work: https://github.com/nextcloud/nextcloud-vue/pull/1184 which will probably be shipped in one of the next versions.

**Closed by stefan-niedermann** 2020-07-06 09:15 UTC
