### ISSUE TITLE
Context menu dropdown on card opens 'behind' card 

### ISSUE THREAD

**Issue by MikeDabrowski** [nextcloud/deck#319] opened 2017-10-07 12:10 UTC
### Steps to reproduce
1. Create deck, add at least one card
2. Click 3 dots on card
3. Dropdown (archive,delete) appears hidden an have to scroll to see it 

### Expected behaviour
Tell us what should happen
Use something like appendTo="body" so that dropdown would appear on top of eveerything or at least card.

### Actual behaviour
Dropdown appears hidden belowe card an have to scroll to see it 

### Server configuration
Brand new installation on nextcloud.

**Operating system**:
Browser chrome on win10
**Web server:**
Ubuntu server 17
**Database:**
mariadb
**PHP version:**
7.0.22
**Nextcloud version:** (see Nextcloud admin page)
12

**Where did you install Nextcloud from:**
Nextcloud site
**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.5.2
  - audioplayer: 2.1.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.5
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - deck: 0.2.3
  - documents: 0.16.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_reader: 1.0.4
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - music: 0.5.2
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.1.4
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - radio: 0.6.0
  - richdocuments: 1.12.35
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - theming_customcss: 1.0.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration
**Browser:**
latest chrome 

**Operating system:**
win10pro

I skipped few points of template because this is more html/css problem than network or php conf.

**Comment by juliushaertl** [comment] 2017-10-08 10:11
Duplicate of #311 

I've just released 0.2.4 which should fix the issue.

**Closed by juliushaertl** 2017-10-08 10:11 UTC
