### ISSUE TITLE
Add name of day into calendar and possibility to change first day of week

### ISSUE THREAD

**Issue by vix95** [nextcloud/deck#1947] opened 2020-05-23 20:21 UTC
I caught myself on the fact that I've don't know which day is represented by calendar. I think it would be nice if on the calendar will be shown the little note about days, please refer to the below mockup.
![image](https://user-images.githubusercontent.com/38139321/82739837-7c2e4c00-9d43-11ea-9666-6d6c2d6f040d.png)

And my secondary thing, it would be nice if I could set the first day of week, because in my country monday as first day of week is standard.

Btw. I saw that there is a pull request which fixes the datetime issue.

**Comment by juliushaertl** [comment] 2020-05-25 10:34
Makes sense. We basically need to pass the proper firstDate parameter to the datepicker: https://github.com/nextcloud/calendar/blob/cd4d4f4607025771ab5408d5b458e98f6dd810d0/src/components/Shared/TimePicker.vue#L69

**Comment by juliushaertl** [comment] 2020-05-25 10:35
Ah let's actually close this as a duplicate of https://github.com/nextcloud/deck/issues/1506

**Closed by juliushaertl** 2020-05-25 10:35 UTC
Labels: 1. to develop, bug, good first issue

**Comment by vix95** [comment] 2020-05-25 14:17
Hi @juliushaertl , but in mentioned issue I can't find any information about label on the calendar: Mo, Tu, etc.

I mentioned on add the lables on calendar (marked in red).
![image](https://user-images.githubusercontent.com/38139321/82820723-fcb78e80-9ea2-11ea-87ee-66127082ab93.png)

And select first day of month is a second thing which I've mentioned additionaly.

**Comment by juliushaertl** [comment] 2020-05-25 16:13
Sorry I forgot to send my reply on the other ticket: https://github.com/nextcloud/deck/issues/1506#issuecomment-633638330

I've now included both names of weekdays and months in there as well.
