### ISSUE TITLE
Deleted boards still show up on the main panel and accessible

### ISSUE THREAD

**Issue by m4c7jahhmq** [nextcloud/deck#1874] opened 2020-05-13 07:47 UTC
**Describe the bug**
Deleted boards still show up on the main panel and accessible. I am not sure whether this issue is 1.0.0 specific since I don't have the old version to test.

**To Reproduce**
1. Go to 'Deck' at the top menu.
2. Click on 'Create new board' at the left side-bar
3. Enter "Test 1". This new board is shown both in the left side-bar and the main panel.
4. Click on "..." next to "Test 1" in the left side-bar.
5. Click on "Delete board" in the pop-up menu.
6. Wait for while until "Test 1" disappeared in both the left side-bar and main panel.
7. Click "Deck" at the top menu.
8. "Test 1" re-appears in the main panel, but no longer in the left side-bar.

**Expected behavior**
"Test 1" should disappear in both main panel and left side-bar.

**Screenshots**
<img width="640" alt="Screenshot 2020-05-13 at 3 34 21 PM" src="https://user-images.githubusercontent.com/65154594/81785114-7446fe80-9530-11ea-8636-667dc84327f7.png">

**Client details:**
 - OS: macOS 10.15.4 (Catalina)
 - Browser: Firefox 
 - Version: 76.0.1 (64-bit)
 - Device: Desktop

**Comment by jakobroehrl** [comment] 2020-05-13 07:54
Can confirm it

**Comment by jakobroehrl** [comment] 2020-05-13 07:58
duplicate of #1806

**Closed by jakobroehrl** 2020-05-13 07:58 UTC
Labels: 1. to develop, bug
