### ISSUE TITLE
Deck Board ist empty and causes big Trouble (with "Calendar" and "Tasks")

### ISSUE THREAD

**Issue by configonfi** [nextcloud/deck#3029] opened 2021-04-29 22:48 UTC
Since a few days these three Apps (Deck, Calendar, Tasks) do not work any more.
The Boards of Deck & Tasks are empty (!) and the Calendar-App is loading and loading … nothing.
When I deactivate Deck then Calendar and Tasks work pretty fine.

My Deck-Version is 1.4.1, NC is 21.0.0
NC is rented as a Service (from Hetzner), I got no root-Password.

Thanks for your work and greetings, configonfi

**Comment by stefan-niedermann** [comment] 2021-04-30 05:04
Looks like a duplicate of #3024 and #3027. Can you p)ease try to temporarily disab)e the Circles app?

If this doesn't solve the issue, fill in the complete issue template.

**Comment by configonfi** [comment] 2021-05-01 16:09
> Looks like a duplicate of #3024 and #3027. Can you p)ease try to temporarily disab)e the Circles app?

OK, that was the crucial hint - I was able to solve the Problem. 

In case of this Problem …

1. deactivate Circles (=> Deck is loading the boards!)
2. analyse which board is **shared with circles**
3. unshare the boards or tell the owner of the boards to unshare it 
4. activate Circles.

Hope that will help! :o)

Thanks for your help and work, 
configonfi

**Comment by juliushaertl** [comment] 2021-05-03 06:17
A fix for the deck part to avoid the whole app is not working is in #3037, the circles issue is addressed in https://github.com/nextcloud/circles/pull/577

**Closed** 2021-05-03 07:28 UTC
