### ISSUE TITLE
Attacments disappear on card change

### ISSUE THREAD

**Issue by olegbolden** [nextcloud/deck#2450] opened 2020-10-15 19:02 UTC
This is an old bug persisted for a long time in 1.0.x versions of the app.
After opening deck app you can see attachments only for the first selected card. They disappear for all subsequently selected cards unless page is refreshed.

**Client details:**
 - OS: Debian 9
 - Browser Chrome latest
 - Device: Desktop
 - NC 18.0.10
 - Deck 1.1.2

**Comment by juliushaertl** [comment] 2020-10-16 06:26
Duplicate of https://github.com/nextcloud/deck/issues/1957

**Closed by juliushaertl** 2020-10-16 06:26 UTC
