### ISSUE TITLE
Backup and restore

### ISSUE THREAD

**Issue by ChameleonScales** [nextcloud/deck#2922] opened 2021-03-28 14:11 UTC
Just like the calendar has download and upload features for backup, restore and other purposes, it would be great if Deck had the same.
Although one can download a Deck board through the calendar, it's not possible to upload the deck back since it is then only a calendar and doesn't contain the data that is proper to the deck board.

This has also been asked in this topic: https://help.nextcloud.com/t/import-export-or-backup-restore/85714

**Comment by stefan-niedermann** [comment] 2021-03-28 14:12
Duplicate of https://github.com/nextcloud/deck/issues/87 - please use the 🔍  search function before opening new issues.

**Closed by stefan-niedermann** 2021-03-28 14:12 UTC

**Comment by ChameleonScales** [comment] 2021-03-28 14:14
I did. But I used backup or restore in:title
Sorry I missed it

**Comment by rhinozeross** [comment] 2021-03-31 08:12
Issue #87 is still not solved though and it doesn't seems like it will in the near future:/

**Comment by stefan-niedermann** [comment] 2021-03-31 08:22
> Issue #87 is still not solved though and it doesn't seems like it will in the near future:/

And you believe the issue will be solved earlier if multiple issues to the same topic are open, parallel discussions are happening and the devs spend their time answering the exact same questions over and over again instead of coding? 😉  
(and let me make it clear: This was a purely rhethorical question)

Quoting the maintainer:

> if someone is willing to contribute, I'd be happy to integrate that.

([Source](https://github.com/nextcloud/deck/issues/87#issuecomment-598696004))
