### ISSUE TITLE
additional slash in notifications

### ISSUE THREAD

**Issue by mokkin** [nextcloud/deck#2253] opened 2020-09-01 16:55 UTC
### Steps to reproduce
receive notifications of watched boards

### Expected behaviour
receive notifications without additional slashes leading to the correct card

### Actual behaviour
notifications with additional slashes leading to nowhere

## Server configuration detail

**Operating system:** Linux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 5.7.28

**PHP version:** 

7.4.8
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, gmp, SPL, iconv, session, json, mbstring, pcntl, standard, Phar, posix, Reflection, imap, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, mysqlnd, cgi-fcgi, imagick, curl, gd, mysqli, PDO, pdo_mysql, xsl, sqlite3, intl, sodium, ldap, tidy, pdo_pgsql, pdo_sqlite, igbinary, redis, ionCube Loader, Zend OPcache

**Nextcloud version:** 19.0.2 - 19.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.0
 - admin_audit: 1.9.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.0.4
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.3.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - deck: 1.0.5
 - documentserver_community: 0.1.7
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_external: 1.10.0
 - files_markdown: 2.3.0
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - groupfolders: 7.0.0
 - issuetemplate: 0.6.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - nextcloud_announcements: 1.8.0
 - notes: 3.6.4
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - occweb: 0.0.7
 - onlyoffice: 4.3.0
 - password_policy: 1.9.1
 - passwords: 2020.8.0
 - photos: 1.1.0
 - previewgenerator: 2.3.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - qownnotesapi: 20.1.0
 - recommendations: 0.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - spreed: 9.0.3
 - support: 1.2.1
 - survey_client: 1.7.0
 - systemtags: 1.9.0
 - tasks: 0.13.3
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - encryption
 - files_readmemd
 - mail
 - maps
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
       
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.example.de",
    "dbtype": "mysql",
    "version": "19.0.2.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "default_language": "de",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "app.mail.server-side-cache.enabled": true,
    "theme": "",
    "loglevel": 2,
    "trashbin_retention_obligation": "auto",
    "updatechecker": false,
    "mysql.utf8mb4": true,
    "htaccess.IgnoreFrontController": true,
    "htaccess.RewriteBase": "\/",
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "occweb",
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

![grafik](https://user-images.githubusercontent.com/2938748/91883242-74f0d580-ec84-11ea-85f6-45263c3a7e9a.png)
![grafik](https://user-images.githubusercontent.com/2938748/91883387-a23d8380-ec84-11ea-9017-c133ee931fdc.png)

URL: https://cloud.example.de/apps/deck/#/board/19//card/95

Maybe linked to https://github.com/nextcloud/deck/issues/1698 ?

**Comment by putt1ck** [comment] 2020-09-02 04:26
Closing as duplicate of #2185 (which now has a PR to fix)

**Closed by putt1ck** 2020-09-02 04:26 UTC
