### ISSUE TITLE
many interactions need browser reload to become visible

### ISSUE THREAD

**Issue by mrmuehle** [nextcloud/deck#2347] opened 2020-10-04 20:01 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

user want to change a card. the change is not 
reflected as usual. The card looks like not changed. 

( after browser reload the change has happend) 

![19 0 3-Error-Deck-JS](https://user-images.githubusercontent.com/816161/95025674-d218e600-068b-11eb-8540-e8f7b6facf41.png)

**To Reproduce**
1. Go to any card
2. Click on any function, like assign to some one, delete, 
3. reload the browser too see that it happend, but was not shown.
4. check error in console (screen shot )

**Expected behavior**
the change should be shown immediately

**Client details:**
 - OS:  Win10
 - BrowserFF, Chrome, Edge Chromium 
 - Version stable release, 19.0.3
 - Device: Win 10 desktop

<details>
<summary>Server details</summary>

**Operating system**:
 Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-101-generic x86_64)

**Web server:**
Apache, NGINX proxy, also NGINX FPM

**Database:**
mysql  mariadb 
**PHP version:**
7.3.22
**Nextcloud version:** (see Nextcloud admin page)
19.0.3
**Where did you install Nextcloud from:**
githib 
**Signing status:**
?
```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**
Accessibility	1.5.0	Offiziell	
Activity	2.12.0	Offiziell	
Audio Player	2.12.0		
BigBlueButton Integration	1.1.0		
Calendar	2.0.4	Offiziell	
Collaborative tags	1.9.0	Offiziell	
Comments	1.9.0	Offiziell	
Contacts	3.4.0	Offiziell	
Contacts Interaction	1.0.0	Offiziell	
Deck	1.1.0	Offiziell	
Deleted files	1.9.0	Offiziell	
External storage support	1.10.0	Offiziell	
Federation	1.9.0	Offiziell	
File sharing	1.11.0	Offiziell	
First run wizard	2.8.0	Offiziell	
Full text search	1.4.2		
Full text search - Elasticsearch Platform	1.5.2		
Full text search - Files	1.4.3		
Group folders	7.0.0	Offiziell	
Impersonate	1.6.1	Offiziell	
Log Reader	2.4.0	Offiziell	
Monitoring	1.9.0	Offiziell	
Nextcloud announcements	1.8.0	Offiziell	
Notifications	2.7.0	Offiziell	
ONLYOFFICE	6.0.2	Offiziell	
Password policy	1.9.1	Offiziell	
Photos	1.1.0	Offiziell	
Plain text editor	2.11.0		
Polls	1.4.3		
Privacy	1.3.0	Offiziell	
Reader (ebook reader)	1.4.2		
Recommendations	0.7.0	Offiziell	
Right click	0.16.0	Offiziell	
Share by mail	1.9.0	Offiziell	
Social Login	3.3.0		
Social sharing via email	2.1.0	Offiziell	
Splash	1.1.6		
Support	1.2.1	Offiziell	
Tasks	0.13.3	Offiziell	
Text	3.0.1	Offiziell	
Theming	1.10.0	Offiziell	
Two-Factor Admin Support	3.0.0		
Two-Factor Authentication via Nextcloud notification	2.3.0		
Two-Factor Gateway	0.17.0		
Two-Factor TOTP Provider	5.0.0	Offiziell	
Update notification	1.9.0	Offiziell	
Versions	1.12.0	Offiziell	
Video player	1.8.0	Offiziell
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by marc-romu** [comment] 2020-10-05 06:49
I manage some instances of Nextcloud and I can see that those which are public and its connection is secured with a LetsEncrypt certificate are working fine. But, in one instance which is only available in local intranet and secured with a self-signed certificate, the mentioned problem occurs.

**Comment by juliushaertl** [comment] 2020-10-05 06:54
> Insert your Nextcloud log here

Please provide those, since there is an internal server error there is something going wrong in the backend.

**Comment by mrmuehle** [comment] 2020-10-05 06:57
the above problem is with a fully A+ secure server (let's encrypt, aber keine self signed certificates)
@juliushaertl I can provide any level of detail, if needed to solve this.

**Comment by juliushaertl** [comment] 2020-10-05 07:06
The A+ level tells nothing about the possible cause of the issue, so please check your server logs when the error occurs :wink:

**Comment by mrmuehle** [comment] 2020-10-05 07:10
Exception: Call to undefined method OCA\Deck\Event\FTSEvent::hasArgument()

    /var/www/vhosts/theserver/nextcloud-prod/lib/private/AppFramework/App.php - line 137:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Deck\Con ... {}, "assignUser")

    /var/www/vhosts/theserver/nextcloud-prod/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Deck\\ ... r", "assignUser", OC\AppFramew ... {}, { cardId: "2 ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ cardId: "2 ... "})

    /var/www/vhosts/theserver/nextcloud-prod/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { cardId: "2 ... "})

    /var/www/vhosts/theserver/nextcloud-prod/lib/base.php - line 1012:

    OC\Route\Router->match("/apps/deck/cards/230/assign")

    /var/www/vhosts/theserver/nextcloud-prod/index.php - line 37:

    OC::handleRequest()

Verursacht durchError: Call to undefined method OCA\Deck\Event\FTSEvent::hasArgument()

    /var/www/vhosts/theserver/nextcloud-prod/apps/deck/lib/Service/FullTextSearchService.php - line 111:

    OCA\Deck\Event\FTSEvent->getArgument("id")

    /var/www/vhosts/theserver/nextcloud-prod/apps/deck/lib/AppInfo/ApplicationLegacy.php - line 226:

    OCA\Deck\Service\FullTextSearchService->onCardUpdated("*** sensiti ... *")

    /var/www/vhosts/theserver/nextcloud-prod/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 251:

    OCA\Deck\AppInfo\ApplicationLegacy->OCA\Deck\AppInfo\{closure}("*** sensiti ... *")

    /var/www/vhosts/theserver/nextcloud-prod/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 73:

    Symfony\Component\EventDispatcher\EventDispatcher->callListeners([ Closure {}], "*** sensiti ... *", "*** sensiti ... *")

    /var/www/vhosts/theserver/nextcloud-prod/lib/private/EventDispatcher/EventDispatcher.php - line 86:

    Symfony\Component\EventDispatcher\EventDispatcher->dispatch("*** sensiti ... *", "*** sensiti ... *")

    /var/www/vhosts/theserver/nextcloud-prod/apps/deck/lib/Service/AssignmentService.php - line 155:

    OC\EventDispatcher\EventDispatcher->dispatch("*** sensiti ... *", "*** sensiti ... *")

    /var/www/vhosts/theserver/nextcloud-prod/apps/deck/lib/Controller/CardController.php - line 159:

    OCA\Deck\Service\AssignmentService->assignUser("230", "guido", 0)

    /var/www/vhosts/theserver/nextcloud-prod/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\Deck\Controller\CardController->assignUser("230", "guido", 0)

    /var/www/vhosts/theserver/nextcloud-prod/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Deck\Con ... {}, "assignUser")

    /var/www/vhosts/theserver/nextcloud-prod/lib/private/AppFramework/App.php - line 137:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Deck\Con ... {}, "assignUser")

    /var/www/vhosts/theserver/nextcloud-prod/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Deck\\ ... r", "assignUser", OC\AppFramew ... {}, { cardId: "2 ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ cardId: "2 ... "})

    /var/www/vhosts/theserver/nextcloud-prod/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { cardId: "2 ... "})

    /var/www/vhosts/theserver/nextcloud-prod/lib/base.php - line 1012:

    OC\Route\Router->match("/apps/deck/cards/230/assign")

    /var/www/vhosts/theserver/nextcloud-prod/index.php - line 37:

    OC::handleRequest()

**Comment by mrmuehle** [comment] 2020-10-05 14:39
can I provide anything else?

**Comment by mrmuehle** [comment] 2020-10-05 14:45
before we used deck a lot with nc 18.x, no problems. but this update was not very successful.

**Comment by juliushaertl** [comment] 2020-10-06 06:22
Closing as duplicate of #2344 - a fix is in https://github.com/nextcloud/deck/pull/2358

**Closed by juliushaertl** 2020-10-06 06:22 UTC

**Comment by mrmuehle** [comment] 2020-10-07 07:23
Worked for me.
Thank you!
