### ISSUE TITLE
Request: Add Duplicate Card / Child Card

### ISSUE THREAD

**Issue by Solar-Simon** [nextcloud/deck#4968] opened 2023-08-03 09:32 UTC
**Is your feature request related to a problem? Please describe.**
There is no way to copy a card? If I only copy description, the formatation is corrupted (task lists become bulleted lists)

**Describe the solution you'd like**
Change the Option "Move Card" to "Move/Copy Card", add a checkbox to the selection menu. Check Copy, otherwise move.

**Describe alternatives you've considered**
Add the Option "Copy Card" to the menu, if same board/list is choosen, duplicate.

**Additional context**
We want to run the same process again and again. So we have a template card and want to copy it again and again.
It would be good, if the template card even could have attachements.

It would be even more advanced, if the copies / duplicates are a child of the template. When editing the templates it effects the copies / duplicates. Therefor it should not be possible to edit the child cards. This should only be an option.

**Requests**

- [ ] Fix task lists become bulleted lists (https://github.com/nextcloud/deck/issues/4964)
- [ ] add copy / duplicate option
- [ ] add child option

**Tribut**
Thank you for the great app

**Comment by juliushaertl** [comment] 2023-08-21 09:02
Duplicate of https://github.com/nextcloud/deck/issues/1813 #2848

**Closed by juliushaertl** 2023-08-21 09:02 UTC
