### ISSUE TITLE
Status in card an link to Plugin Bookmark 

### ISSUE THREAD

**Issue by Peachy74** [nextcloud/deck#2941] opened 2021-04-04 21:20 UTC
I think it would be good if a card could get a status. one catchphrase is actually not enough for me. If the status goes to closed, for example, the card could also be moved to another list (done).
I also think it would be great if you could connect a map with links from the Bookmark plugin.
Could something like that be implemented?

**Comment by stefan-niedermann** [comment] 2021-04-04 21:41
> I think it would be good if a card could get a status. one catchphrase is actually not enough for me. If the status goes to closed, for example, the card could also be moved to another list (done).

Duplicate of https://github.com/nextcloud/deck/issues/534

> I also think it would be great if you could connect a map with links from the Bookmark plugin.
Could something like that be implemented?

Opening an issue multiple times will not speed up the development. Deck supports "projects" to connect entities between different apps like Deck cards, Deck boards, Files files, Files folders and Talk rooms with each other. The correct approach for an integration is to implement support for projects also in the Bookmarks app (i will comment it in your issue there). Duplicate of https://github.com/nextcloud/bookmarks/issues/1492

**Closed by stefan-niedermann** 2021-04-04 21:41 UTC

**Comment by stefan-niedermann** [comment] 2021-04-04 21:44
> a map

I have no idea what a "map" is. We have boards, lists and cards in the Deck app. To avoid confusion i recommend to use those terms 🙂
