### ISSUE TITLE
Checkboxes are not saved in enlarged view

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#2351] opened 2020-10-05 09:49 UTC
The bug #2061 re-appeared in 1.1.0 when the enlarged view is used instead of the sidebar.
See description of the bug in the other ticket, it behaves exactly the same.

**Comment by juliushaertl** [comment] 2020-11-19 18:28
Duplicate of #2580, fixed with #2584

**Closed** 2020-11-19 18:28 UTC
Labels: 1. to develop, bug
