### ISSUE TITLE
Can not edit description in Firefox

### ISSUE THREAD

**Issue by reox** [nextcloud/deck#1910] opened 2020-05-16 17:58 UTC
**Describe the bug**
Since v1.0.1 I can no longer edit the description of a card in Firefox.
Chromium however works.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to details of a card
2. Click on edit icon
3. description will get empty (if already exists for example), no cursor will appear

**Client details:**
 - OS: Debian
 - Browser Firefox
 - Version: 76.0.1
 - Device: Desktop

**Comment by trdsr** [comment] 2020-05-16 21:41
same here
Firefox 68.8.0esr on Debian 10

**Comment by putt1ck** [comment] 2020-05-17 04:12
I saw the same issue, but with a full reload (Ctrl-Shift-R) it cleared it and I can edit descriptions in FF (v75).

**Comment by reox** [comment] 2020-05-17 09:02
> I saw the same issue, but with a full reload (Ctrl-Shift-R) it cleared it and I can edit descriptions in FF (v75).

I already tried that and it does not work for me. Also restarting the browser / closing the tab seems to have no effect for me :(

**Comment by juliushaertl** [comment] 2020-05-17 11:11
Please check the browser console for errors as it is requested in the issue template.

**Comment by reox** [comment] 2020-05-17 11:44
All I see is
```
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Notifications permissions denied App.vue:248
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. addStylesClient.js:220:17
New search handler registered search.js:67:12
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 3 globals.js:66:15
```

But that is all when the page loads. If I click the edit button, no new error/warning/message appears.

**Comment by reox** [comment] 2020-05-17 11:55
I do not know what happened, but it came good again.
Closed/Reloaded tabs and browser like crazy. Cleaned Cookies and Browser cache. Each step individually did not had an effect. However, after several reloads it worked finally.

I also created a new firefox profile and checked there, the switch between edit and view takes a few seconds there for the first entry. After that it is much more smoothly.

**Comment by olegchensky** [comment] 2020-05-17 14:27
FF not works

**Comment by lmf-ggal** [comment] 2020-05-17 19:04
Same in Chrome, can't edit description !

**Comment by TheACBH** [comment] 2020-05-18 04:25
Same problem here, but was solved for me by clearing the cache and afterwards doing a reload of the page.

**Comment by olegchensky** [comment] 2020-05-18 04:37
Yes, after clearing FF works.

**Comment by juliushaertl** [comment] 2020-05-18 11:14
That error from #1917 might be a hint:

```
TypeError: "e is null"
    De codemirror.js:681
    splitLines codemirror.js:6460
    setValue codemirror.js:6114
    ni codemirror.js:3942
    value easymde.js:2488
    value VueEasyMDE.common.js:2773
    VueJS 4
```


Still strange I can not reproduce this and you don't see an error.

**Comment by reox** [comment] 2020-05-18 11:25
The only thing I see is when creating a new card:
```
TypeError: "t.t0.response is undefined"
    t Stack.vue:211
    c runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    Qt deck.js:1305
    i deck.js:1305
main.js:65:9
    errorHandler main.js:65
    VueJS 3
```

**Comment by jim3ma** [comment] 2020-05-19 09:37
main.js:65 TypeError: Cannot read property 'data' of undefined
    at Stack.vue:211
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
    at Qt (deck.js?v=733c3399-30:1305)
    at i (deck.js?v=733c3399-30:1305)

**Comment by fm-sys** [comment] 2020-05-19 17:43
Same issue on WindowsPC with Firefox, can not edit description - it's just getting empty! But clearing the browser cache helps...

**Comment by khassad** [comment] 2020-05-20 09:58
Hi, same error here.
Client details:
    OS: Linux Mint 19.3
    Browser Firefox
    Version: 77.0b7
    Device: Desktop

Clearing the cache does help but now I can't attache a file to a card anymore (blank attach popup) but this will be another bug report.

**Comment by juliushaertl** [comment] 2020-05-20 10:05
Ok, I think I have a hint why browser caching does not get invalid during the update. It seems that the webpack chunks (2.js which contains the markdown editor) doesn't get the cachebump ?v=... parameter appended since it is dynamically loaded.

**Comment by reox** [comment] 2020-06-05 06:47
Re-appeared in 1.0.2, however clearing browser data cache worked immediately.

**Comment by juliushaertl** [comment] 2020-06-16 10:24
Should now be fixed by https://github.com/nextcloud/deck/pull/2021

**Closed by juliushaertl** 2020-06-16 10:24 UTC
Labels: 1. to develop, bug
