### ISSUE TITLE
selecting text in card not possible when "Use bigger card view" is active

### ISSUE THREAD

**Issue by joergsch** [nextcloud/deck#3595] opened 2022-02-20 18:57 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

When opening a card, having "Use bigger card view" active, I can create/update/... the text in the description field. Select/copy/past of text works fine.
If I'm no longer in "edit mode", then it's not possible to select any text in the description field.
If the "Use bigger card view" is __not__ active, then it's possible to select the text in the description field.

**To Reproduce**
1. Create card, enter text to description
2. switch from "edit description" (pencil) to "view description" (eye)
3. if the card is only shown on the right side, you need to click on "open in bigger view"
4. select text from the description field

**Expected behavior**
Expectation is that it's possible to select the text in "view description" mode, regardless of "bigger view" or "default view"

**Comment by reox** [comment] 2022-03-08 09:57
I can confirm this with NC 23.0.2 / Deck 1.6.0 / Firefox 97.0.2

**Comment by q-wertz** [comment] 2022-03-14 16:35
Same for the behavior of the text in the Timeline column (also see https://github.com/nextcloud/deck/issues/3584).

**Comment by reox** [comment] 2022-05-06 07:20
Seems to be fixed in NC 24.0.0 / Deck 1.7.0? At least I'm now able to select text again!

**Comment by juliushaertl** [comment] 2022-05-06 07:23
Yes, this was addressed with #3761

**Closed by juliushaertl** 2022-05-06 07:23 UTC
