### ISSUE TITLE
Overview-board: Dublets

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/deck#2483] opened 2020-10-28 13:38 UTC
1. Going to overview board.

Expected:
1. Don't have any dublets.

Instead:
![overview_dublets](https://user-images.githubusercontent.com/34820982/97443290-27fb4980-192b-11eb-8aa8-494fcf2dd435.png)

NC: 20.0.1
Deck:  1.1.2

**Comment by stefan-niedermann** [comment] 2020-10-28 13:56
I see what you did here :laughing: 

Duplicate of #2482

**Closed by stefan-niedermann** 2020-10-28 13:56 UTC
