### ISSUE TITLE
Decks/Tasks integration

### ISSUE THREAD

**Issue by MiroMynttinen** [nextcloud/deck#2631] opened 2020-12-02 14:22 UTC
Hello,

I hope that you could help me with my problems since we want to keep using NextCloud in our company.

I am glad to see the connection between decks and tasks, but I noticed some missing things—both application pros and cons. For example, with Decks, signing "cards" to different people and connecting "cards" to other folders is possible, but it not possible to split this card into "sub-cards". With Tasks, splitting "tasks" to sub-tasks" is possible, but I cannot sign this specific task to someone or connect it to a folder. Task also have a great function of "checking," which indicates task or a subtask is done. This function can be done with tags in Decks.

My problem: The update enables me to view Decs with the Task application but not modifying them. Following functions would be essential for us to have while monitoring Decs with Task-application:

- To see whom the task is appointed to
- To see to which folders the deck is connected to, or attaching a file to the task
- Star the tasks as important
- Pin the tasks
- Check the tasks 

![2020-12-02_14-57-08](https://user-images.githubusercontent.com/75375069/100882061-03a50680-34af-11eb-9b0c-c598fb329b61.png)

Thank you in advance! I hope that this report explained my problem suffieciently enough :)

Cheers,
Miro Mynttinen

**Comment by tensau** [comment] 2020-12-02 19:13
I really would appreciate a bidirectional integration for checking cards in Tasks, too. And also a possibility to move a card to a different task list.

**Comment by juliushaertl** [comment] 2020-12-29 19:50
Duplicate of #2399

**Closed by juliushaertl** 2020-12-29 19:50 UTC
