### ISSUE TITLE
Effort scales on cards

### ISSUE THREAD

**Issue by daudtivan** [nextcloud/deck#3661] opened 2022-03-21 18:26 UTC
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the solution you'd like**
A way to define a "weight" to a given card, representing the effort necessary to conclude it.
It should allow different units of measurements like: hours, decimal points, lists {S, M, L, XL,...}, Fibonacci {1, 3, 5, 8,...}
The author or the person assigned to the card should be able to modify its scale value (so people can discuss it somewhere else and update the card).

**Describe alternatives you've considered**
I could get close to it using tags, but only simple "size" lists would work like S, M, L...
Anything else becomes confuse and requires maintaining both lists of tags + cards.

**Additional context**
I'm not suggesting a full collaborative card scale definition tool here (but you hv my vote if you decide so). All I'm proposing is a placeholder (field or attribute) where the estimated workload of a card is registered by its author or the person it's assigned to.
I've made a sketch of what I believe represents my idea (in addition to #3660 )
![card-scale](https://user-images.githubusercontent.com/91741832/159339237-c2c9249c-f0ee-4d81-a732-9d9ad846e0f7.png)

**Comment by dodedodo** [comment] 2022-03-22 11:59
This issue and the other issue mentioned are both subsets of #1833

**Comment by daudtivan** [comment] 2022-03-22 12:16
Ok. Tks for the feedback.
Glad to know there's something already in the pipeline for that matter.
If NC/Deck wants to compare with Trello, this is coming late to the discussion.
Just voted in favor of that then. Hope it helps.

**Comment by juliushaertl** [comment] 2023-11-11 22:38
Will close this as a duplicate of #1833 then

**Closed** 2023-11-11 22:38 UTC
