### ISSUE TITLE
How to duplicate a card (if there is a model).

### ISSUE THREAD

**Issue by GuillermoAnkh** [nextcloud/deck#3265] opened 2021-08-20 16:16 UTC
Hi,

Thank for the work on Deck it's very a wonderfull tools. I use it to track task and share it for family or association. And there is most of task are same step.
I was wondering if there is a possibility to made a model card and then have an option to duplicate like in the tab ou can move the card can it be possible to offer the possibility like in files from nextcloud. When you want to move a files you could choose betwenn move or copy
Or there is a way to do it actually ?

Thanks a lot and sorry if it's no made properly first time write here.
And please apologize, english is not my mother language.
Thanks a lot for reading.

**Comment by dodedodo** [comment] 2021-08-20 17:58
Seems to be a duplicate of #1813.

**Comment by stefan-niedermann** [comment] 2021-08-21 07:26
yep :)

**Closed by stefan-niedermann** 2021-08-21 07:26 UTC
