### ISSUE TITLE
v1 beta 2: Some noise in activity emails ref deck

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/deck#1755] opened 2020-04-24 06:27 UTC
Activity emails with deck content have first line similar to:

Rich subject or a parameter for "{user} has updated the description of the card {card} in stack {stack} on board {board}" is malformed

These are are followed by actual activity lines for Deck in the more expected form.

NC 18.0.4

**Comment by putt1ck** [comment] 2020-06-03 15:54
We're still seeing this in v1.02; wondering whether the more complete activity stream messages are a clue - specifically I think the malformed ones are related to changes to the description, both initial creation and edits thereof. Comments and card creation activities all appear to be reproduced in the emails, and the malformed email content all seems to match activity stream entries for description activity.

**Comment by mokkin** [comment] 2020-06-22 16:11
I can confirm this in v1.0.3:
![DeepinBildschirmfoto_Bereich auswählen_20200622181031](https://user-images.githubusercontent.com/2938748/85310015-c24a0d00-b4b3-11ea-991c-684f58dc1387.png)

**Comment by juliushaertl** [comment] 2020-06-24 18:58
Is this also the case in the activity stream in the web UI? Any change that one of you could get me either the failing entries of the oc_activity table or after generating and before the mail is sent the contents of the oc_activity_mq table?

**Comment by juliushaertl** [comment] 2020-06-24 18:58
Also is this only related to some cards or to all of them?

**Comment by putt1ck** [comment] 2020-06-25 04:29
It's not consistent (I can see no pattern), not sure where the fail is - but now see that it's different fails in the stream and the email.

An example:

Entries in email:
`Today at 14:51
John User has created card Scratchpad/To Do List in stack Thoughts on board Contract edit & review
	
Today at 14:52
John User has created card Hidden Definitions in stack Thoughts on board Contract edit & review

Today at 14:55
Rich subject or a parameter for "{user} has updated the description of the card {card} in stack {stack} on board {board}" is malformed

Today at 14:55
Rich subject or a parameter for "{user} has updated the description of the card {card} in stack {stack} on board {board}" is malformed

Today at 14:55
John User has created card Figures and Words in stack Treated on board Contract edit & review

Today at 14:58
John User has created card Figures and Money definition in stack Thoughts on board Contract edit & review
	
Today at 14:58
John User has renamed the card Figures and Money definition to Figures and Money format
	
Today at 14:58
John User has renamed the card Figures and Money format to Figures and Money definition
	
Today at 15:00
Rich subject or a parameter for "{user} has updated the description of the card {card} in stack {stack} on board {board}" is malformed
	
Today at 15:00
Rich subject or a parameter for "{user} has updated the description of the card {card} in stack {stack} on board {board}" is malformed
	
Today at 15:00
Rich subject or a parameter for "{user} has updated the description of the card {card} in stack {stack} on board {board}" is malformed`

Equivalent entries from activity stream (same day, entire set from both):
`
  John User has updated the description of the card Figures and Money definition in stack Thoughts on board Contract edit & review
  20 days ago
  <pre class="visualdiff"><ins>[redacted]</ins></pre>
  John User has updated the description of the card Figures and Words in stack Treated on board Contract edit & review
  20 days ago
  <pre class="visualdiff"><ins>[redacted]<ins></pre>
  John User has updated the description of the card Hidden Definitions in stack Thoughts on board Contract edit & review
  20 days ago
  <pre class="visualdiff">Let's say you're drafting {redacted]has stuff like &quot;A phrase&quot; and like &quot;<del>mon</del><ins>figur</ins>e<del>y</del> and words&quot; data type.<ins> </ins></pre>
  John User has renamed the card Figures and Money format to Figures and Money definition
  20 days ago
  John User has renamed the card Figures and Money definition to Figures and Money format
  20 days ago
  John User has created card Figures and Money definition in stack Thoughts on board Contract edit & review
  20 days ago
  John User has created card Figures and Words in stack Treated on board Contract edit & review
  20 days ago
  John User has updated the description of the card Hidden Definitions in stack Thoughts on board Contract edit & review
  20 days ago
  <pre class="visualdiff"><ins> [redacted] again contains stuff like help with the &quot;money and words&quot; data type.</ins></pre>
  John User has updated the description of the card Scratchpad/To Do List in stack Thoughts on board Contract edit & review
  20 days ago
  <pre class="visualdiff"><ins>[redacted] </ins></pre>
  John User has created card Hidden Definitions in stack Thoughts on board Contract edit & review
  20 days ago
  John User has created card Scratchpad/To Do List in stack Thoughts on board Contract edit & review
  20 days ago`

**Comment by mokkin** [comment] 2020-06-28 19:48
In my case the message appears in the activity stream
![DeepinBildschirmfoto_Bereich auswählen_20200628213942](https://user-images.githubusercontent.com/2938748/85956769-6803ed00-b988-11ea-90c8-b08e82803abc.png)

but not in the mail
![DeepinBildschirmfoto_Bereich auswählen_20200628214030](https://user-images.githubusercontent.com/2938748/85956771-6b977400-b988-11ea-8206-64eb5671710d.png)

This is only for some messages, most of them are working correctly. After all the appearance of the class "visualdiff" in the stream is kind of suspicious.

btw: there might be a "sub issue".
In the email the link of the card is published as
`https://cloud.example.de/apps/deck/#/board/16//card/63`
but leads to a blank page caused by an additional `/` The real working URL is
`https://cloud.example.de/apps/deck/#/board/16/card/63`

**Comment by rubo77** [comment] 2020-07-08 05:30
see https://github.com/nextcloud/deck/issues/1254#issuecomment-594555122

> This is definitely a activity issue !
> See :
> https://github.com/nextcloud/activity/blob/2c6ec88c465ff79342b6c5ffbce03625f10f08e4/lib/Data.php#L124
> 
> There is no check when doing the insert into activity_mq

**Comment by rubo77** [comment] 2020-07-08 05:30
can we close this as duplicate?

**Closed** 2020-10-02 15:34 UTC
Labels: bug, feature: activity, needs info
