### ISSUE TITLE
Real-time updates

### ISSUE THREAD

**Issue by AuspeXeu** [nextcloud/deck#3596] opened 2022-02-24 08:27 UTC
Thanks for this awesome app. I was just trying it out today with a coworker but it didn't seem like he was seeing the changes I made to the board without refreshing the page. Is there a way to enable real-time updates?

**Comment by stefan-niedermann** [comment] 2022-02-24 09:01
Duplicate of https://github.com/nextcloud/deck/issues/256

**Closed by stefan-niedermann** 2022-02-24 09:01 UTC
