### ISSUE TITLE
Add markdown menu in Description

### ISSUE THREAD

**Issue by sibergad** [nextcloud/deck#2903] opened 2021-03-20 11:05 UTC
Please add the markdown menu function to the item for description.

**Comment by stefan-niedermann** [comment] 2021-03-20 11:14
Might be a duplicate of https://github.com/nextcloud/deck/issues/1561#issuecomment-641501177

**Comment by juliushaertl** [comment] 2021-04-08 07:48
Yes, this will be done once we have the text editor integrated.

**Closed by juliushaertl** 2021-04-08 07:48 UTC
Labels: design, enhancement, feature: description, frontend
