### ISSUE TITLE
Expose "due to date" in calendar of the user who takes the task

### ISSUE THREAD

**Issue by ratzdi** [nextcloud/deck#1772] opened 2020-04-27 12:38 UTC
When I want to set the achievement date for a task, it should be exposed in my calendar automatic. 

**Describe the solution you'd like**
This feature provides me better and easier overview because calender is synced with my smartphone.

**Comment by juliushaertl** [comment] 2020-04-27 12:46
Duplicate of #15

**Closed by juliushaertl** 2020-04-27 12:46 UTC
