### ISSUE TITLE
allow moving a card to another board by drag & drop

### ISSUE THREAD

**Issue by ilippert** [nextcloud/deck#3597] opened 2022-02-24 08:28 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I am always frustrated when I want to move a card to a different board and have to click several times (using the already existing card menu)

**Describe the solution you'd like**
I want to be able to drag and drop a card to any other board.

**Comment by joshtrichards** [comment] 2024-10-03 22:16
Duplicate of #2209

**Closed** 2024-10-03 22:16 UTC
Labels: enhancement, frontend, 0. Needs triage
