### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by grandmastermoo** [nextcloud/deck#269] opened 2017-07-26 08:08 UTC
### Steps to reproduce
1. Change system date format to European

### Expected behaviour
Deck displays correct date on preview tiles no matter what regional settings are used.

### Actual behaviour
Tiles display "Invalid date"

**Comment by juliushaertl** [comment] 2017-07-26 11:35
duplicate of #240

**Closed by juliushaertl** 2017-07-26 11:35 UTC
