### ISSUE TITLE
Labels sometimes don’t get saved

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/deck#252] opened 2017-07-11 11:49 UTC
### Steps to reproduce
1. Create a card
2. Add a label to it
3. Sometimes it vanishes

Either directly after closing the sidebar, or for example after adding a date, or removing a date again. Not entirely sure why that is.

**Comment by juliushaertl** [comment] 2017-07-11 13:23
Can you check if the label is there after reloading the page? Then this might be a duplicate of https://github.com/nextcloud/deck/issues/147

**Comment by 9662** [comment] 2017-07-11 13:40
> Can you check if the label is there after reloading the page?

Sometimes it is there. Sometimes, the opposite happens: the tag shows as having been applied but disappears on reload. I'll add more details to this issue if/when I have them.

**Comment by rallek** [comment] 2017-10-07 19:20
I have to confirm this issue.
I do have 0.2.3 on NC12.03 installed.
After creating some cards with lables the own defined lables are disappearing after reloading browser page.

First I thought this happens only with the own created lables. But after a while of trying this and that suddenly the own created lables are not disappearing anymore.

Now I know how to reproduce:
* create a new card at the board ``bar``
* create a new label ``foo``
* add the label foo to your new card
* reload the browser page
* bang, the label disappered. You can try it again with another label plus foo. foo will disappear again but the other one not!
* open another board and go back to bar.
* add the label foo to your card
* reload the browser page, and tadda! the label is still there

I bet, the new labels are not stored correctly.

**Comment by juliushaertl** [comment] 2017-10-08 10:45
@rallek Thanks for figuring out how to reproduce. I'll have a look at this.

**Closed** 2017-10-19 09:46 UTC
Labels: 1. to develop, bug, high
