### ISSUE TITLE
Paste a picture in the markdown

### ISSUE THREAD

**Issue by trvrcr** [nextcloud/deck#5233] opened 2023-10-23 11:52 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I would like to be able to insert a picture in the card, I create screenshots that i want to paste inside the card.
It is possible to first save the picture to a file and then link the card to the picture.
yet it is not possible to make it visible inside the details. 

And it is not visible on the card in the overview 

**Describe the solution you'd like**
Make it possible to see the picture in the detailed view (not just the link)
and make the picture visible on the card as well in the overview

**Describe alternatives you've considered**
Alternative exists, but is not visually appealing

**Additional context**
No additional contect

**Comment by juliushaertl** [comment] 2023-11-08 23:46
Duplicate of https://github.com/nextcloud/deck/issues/533

**Closed by juliushaertl** 2023-11-08 23:46 UTC
