### ISSUE TITLE
Card description overwrites wrong/other cards description

### ISSUE THREAD

**Issue by markuman** [nextcloud/deck#2578] opened 2020-11-18 13:04 UTC
**Describe the bug**

When editing a cards description and click to another card, the description overwrites the wrong card.

**To Reproduce**
1. edit one card
2. click directly to another card

**Expected behavior**
The card description is saved and the existing description from the next card is loaded.

**Screenshots**

![deck_card_bug](https://user-images.githubusercontent.com/3920157/99533713-9ec5b880-29a6-11eb-8cd3-963aec78afe2.gif)

**Client details:**
 - OS: Linux
 - Browser firefox
 - Version 82.0.2
 - Device: Desktop

Deck 1.2.0  
Nextcloud 20.0.1.1  
7.4.11

**Comment by stefan-niedermann** [comment] 2020-11-18 13:28
This has been fixed in Deck 1.2.1 which is already available, please update to the latest app version :slightly_smiling_face: 

Duplicate of https://github.com/nextcloud/deck/issues/2568 and https://github.com/nextcloud/deck/issues/2579 (fixed by https://github.com/nextcloud/deck/issues/2568)

**Closed by stefan-niedermann** 2020-11-18 13:28 UTC
