### ISSUE TITLE
OCP\RichObjectStrings\InvalidObjectExeption: Parameter is undefined

### ISSUE THREAD

**Issue by LeoCaplin** [nextcloud/deck#1056] opened 2019-05-20 13:13 UTC
**Describe the bug**
I got this error in my log, which seems relative to deck app

**To Reproduce**
I dont really know why it happens, and it dont really cause working problem, but it flood my log hard.

**Expected behavior**
Dont see this error message

<details>
<summary>Server details</summary>

**Operating system**:  Debian 8.11

**Web server:** Apache 2.0

**Database:** MariaDB 10.0.38

**PHP version:** 7.0.33

**Nextcloud version:** 15.0.8

**Where did you install Nextcloud from:** The official website

**Signing status:**  No errors have been found.

**Deck Version:** 0.6.2

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
[activity] Error: OCP\RichObjectStrings\InvalidObjectExeption: Parameter is undefined at <<closure>>

 0. /var/www/vhosts/bron.fr/drive.bron.fr/apps/activity/lib/GroupHelper.php line 111
    validate("{user} has shar ... }", {user: {type: "u ... }})
 1. /var/www/vhosts/bron.fr/drive.bron.fr/apps/activity/lib/Data.php line 258
    addActivity({activity_id: "6 ... "})
 2. /var/www/vhosts/bron.fr/drive.bron.fr/apps/activity/lib/Controller/APIv2.php line 273
    get(OCA\Activity\GroupHelper {}, OCA\Activity\UserSettings {}, "admnxtcld", 6237, 20, "asc", "deck", "", 0)
 3. /var/www/vhosts/bron.fr/drive.bron.fr/apps/activity/lib/Controller/APIv2.php line 209
    get("deck", 6237, 50, false, "", 0, "asc")
 4. /var/www/vhosts/bron.fr/drive.bron.fr/lib/private/AppFramework/Http/Dispatcher.php line 166
    getFilter("deck", 6237, 50, false, "", 0, "asc")
 5. /var/www/vhosts/bron.fr/drive.bron.fr/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OCA\Activity\Controller\APIv2 {}, "getFilter")
 6. /var/www/vhosts/bron.fr/drive.bron.fr/lib/private/AppFramework/App.php line 118
    dispatch(OCA\Activity\Controller\APIv2 {}, "getFilter")
 7. /var/www/vhosts/bron.fr/drive.bron.fr/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("APIv2Controller", "getFilter", OC\AppFramework\ ... {}, {filter: "deck", ... "})
 8. <<closure>>
    __invoke({filter: "deck", ... "})
 9. /var/www/vhosts/bron.fr/drive.bron.fr/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {filter: "deck", ... "})
10. /var/www/vhosts/bron.fr/drive.bron.fr/ocs/v1.php line 82
    match("/ocsapp/apps/ac ... k")
11. /var/www/vhosts/bron.fr/drive.bron.fr/ocs/v2.php line 24
    require_once("/var/www/vhosts ... p")

GET /ocs/v2.php/apps/activity/api/v2/activity/deck?format=json&limit=50&since=6237&sort=asc
from 90.85.198.49 by admnxtcld at 2019-05-21T06:52:26+00:00
```

</details>

![Nextcloud deck error](https://user-images.githubusercontent.com/37334671/58024412-6673be80-7b12-11e9-9bc8-b31e45a6bcec.PNG)
![Nextcloud deck error 2](https://user-images.githubusercontent.com/37334671/58024453-83a88d00-7b12-11e9-8d42-4eb4c5988c88.PNG)

**Comment by LeoCaplin** [comment] 2019-05-27 06:51
No one can help me ?

**Comment by sundowndev** [comment] 2019-06-14 19:57
Duplicate of #869

**Comment by juliushaertl** [comment] 2019-06-18 19:51
Agreed, I'll close this as a duplicate of #869 

I'll look into this once I find some time to work on deck again.

**Closed by juliushaertl** 2019-06-18 19:51 UTC
Labels: 0. Needs triage
