### ISSUE TITLE
Error 500 when assigning cards to users

### ISSUE THREAD

**Issue by treuss** [nextcloud/deck#2083] opened 2020-06-29 08:36 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

Assigning a card to a user not stored.

**To Reproduce**
1. Go to *deck*
2. Create a new Card and add a title
3. Open developer tools in browser and switch to network
3. Assign that new card to a user
4. See error 500:

**Expected behavior**

Column `type` should be present so the card can be saved.

**Client details:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.116
 - Device: Desktop

<details>
<summary>Server details</summary>

**Operating system**: 

Raspbian GNU/Linux 10 (buster)

**Web server:**

nginx

**Database:**

MariaDB 15.1

**PHP version:**

7.3.14

**Nextcloud version:** (see Nextcloud admin page)

18.0.6

**Where did you install Nextcloud from:**

Tarball

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - apporder: 0.10.0
  - audioplayer: 2.10.1
  - audioplayer_editor: 0.2.2
  - bookmarks: 3.2.2
  - breezedark: 18.0.20
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - carnet: 0.22.1
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - cookbook: 0.7.6
  - dav: 1.14.0
  - deck: 1.0.4
  - drawio: 0.9.6
  - dropit: 0.4.0
  - epubreader: 1.4.2
  - external: 3.5.0
  - extract: 1.2.4
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_antivirus: 2.4.1
  - files_automatedtagging: 1.8.3
  - files_downloadactivity: 1.7.0
  - files_ebookreader: 0.0.1
  - files_external: 1.9.0
  - files_mindmap: 0.0.22
  - files_pdfviewer: 1.7.0
  - files_retention: 1.7.1
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - forms: 1.1.1
  - geoblocker: 0.3.1
  - groupfolders: 6.0.6
  - guests: 1.4.6
  - impersonate: 1.5.2
  - issuetemplate: 0.6.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.4.0
  - maps: 0.1.6
  - news: 14.1.11
  - nextcloud_announcements: 1.7.0
  - notes: 3.6.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocdownloader: 1.7.8
  - ocr: 6.0.43
  - password_policy: 1.8.0
  - passwords: 2020.6.0
  - photos: 1.0.0
  - polls: 1.4.3
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - qownnotesapi: 20.1.0
  - quota_warning: 1.7.0
  - radio: 0.6.6
  - ransomware_protection: 1.6.1
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - socialsharing_email: 2.0.0
  - socialsharing_facebook: 2.0.0
  - spreed: 8.0.9
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.13.1
  - text: 2.0.0
  - theming: 1.9.0
  - theming_customcss: 1.6.0
  - timetracker: 0.0.42
  - twofactor_backupcodes: 1.7.0
  - twofactor_nextcloud_notification: 2.3.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflow_script: 1.3.2
  - workflowengine: 2.0.0
Disabled:
  - accessibility
  - encryption
  - quicknotes
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "****************"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/****************",
        "dbtype": "mysql",
        "version": "18.0.6.0",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "loglevel": 0,
        "logfile": "\/var\/log\/nextcloud.log",
        "session_lifetime": 624960,
        "session_keepalive": true,
        "remember_login_cookie_lifetime": 1296000,
        "theme": "",
        "default_language": "de",
        "maintenance": false,
        "singleuser": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "overwritehost": "****************",
        "htaccess.RewriteBase": "\/",
        "mysql.utf8mb4": true,
        "mail_smtpsecure": "tls",
        "updater.release.channel": "stable",
        "has_rebuilt_cache": true,
        "app_install_overwrite": [
            "radio",
            "files_ebookreader",
            "drawio",
            "files_mindmap"
        ],
        "mail_sendmailmode": "smtp"
    }
}
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

</details>

<details>

<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)

```
[deck] Error: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO `oc_deck_assigned_users`(`card_id`,`participant`,`type`) VALUES(?,?,?)' with params [271, "*******", 0]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'field list' at <<closure>>

 0. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... '", Doctrine\DBAL\Dr ... ]})
 1. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 145
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... '")
 2. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php line 162
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "INSERT INTO `oc ... )", {1: 271,2: "*******",3: 0})
 3. /var/www/nextcloud/lib/public/AppFramework/Db/Mapper.php line 255
    Doctrine\DBAL\Statement->execute()
 4. /var/www/nextcloud/apps/deck/lib/Db/DeckMapper.php line 49
    OCP\AppFramework\Db\Mapper->execute("INSERT INTO `*P ... )", [271,"*******",0], null, null)
 5. /var/www/nextcloud/lib/public/AppFramework/Db/Mapper.php line 129
    OCA\Deck\Db\DeckMapper->execute("INSERT INTO `*P ... )", [271,"*******",0])
 6. /var/www/nextcloud/apps/deck/lib/Db/AssignedUsersMapper.php line 88
    OCP\AppFramework\Db\Mapper->insert(OCA\Deck\Db\AssignedUsers {id: null})
 7. /var/www/nextcloud/apps/deck/lib/Service/AssignmentService.php line 150
    OCA\Deck\Db\AssignedUsersMapper->insert(OCA\Deck\Db\AssignedUsers {id: null})
 8. /var/www/nextcloud/apps/deck/lib/Controller/CardController.php line 159
    OCA\Deck\Service\AssignmentService->assignUser("271", "*******", 0)
 9. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Deck\Controller\CardController->assignUser("271", "*******", 0)
10. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Deck\Controller\CardController {}, "assignUser")
11. /var/www/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Deck\Controller\CardController {}, "assignUser")
12. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Deck\\Controller\\CardController", "assignUser", OC\AppFramework\ ... {}, {cardId: "271",_ ... "})
13. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({cardId: "271",_ ... "})
14. /var/www/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {cardId: "271",_ ... "})
15. /var/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/deck/cards/271/assign")
16. /var/www/nextcloud/index.php line 38
    OC::handleRequest()

POST /apps/deck/cards/271/assign
from ***.***.***.*** by ****** at 2020-06-29T10:19:38+02:00
```

#### Browser log

```
{"status":500,"message":"An exception occurred while executing 'INSERT INTO `oc_deck_assigned_users`(`card_id`,`participant`,`type`) VALUES(?,?,?)' with params [271, \"********\", 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'field list'","exception":{"\u0000Doctrine\\DBAL\\Exception\\DriverException\u0000driverException":{"errorInfo":["42S22",1054,"Unknown column 'type' in 'field list'"]},"\u0000*\u0000message":"An exception occurred while executing 'INSERT INTO `oc_deck_assigned_users`(`card_id`,`participant`,`type`) VALUES(?,?,?)' with params [271, \"********\", 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'field list'","\u0000Exception\u0000string":"","\u0000*\u0000code":0,"\u0000*\u0000file":"\/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","\u0000*\u0000line":60,"\u0000Exception\u0000trace":[{"file":"\/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"-\u003E","args":["An exception occurred while executing 'INSERT INTO `oc_deck_assigned_users`(`card_id`,`participant`,`type`) VALUES(?,?,?)' with params [271, \"********\", 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'field list'",{"errorInfo":["42S22",1054,"Unknown column 'type' in 'field list'"]}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":145,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{},{"errorInfo":["42S22",1054,"Unknown column 'type' in 'field list'"]},"An exception occurred while executing 'INSERT INTO `oc_deck_assigned_users`(`card_id`,`participant`,`type`) VALUES(?,?,?)' with params [271, \"********\", 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'field list'"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php","line":162,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{},{"errorInfo":["42S22",1054,"Unknown column 'type' in 'field list'"]},"INSERT INTO `oc_deck_assigned_users`(`card_id`,`participant`,`type`) VALUES(?,?,?)",{"1":271,"2":"********","3":0}]},{"file":"\/var\/www\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","line":255,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"-\u003E","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/deck\/lib\/Db\/DeckMapper.php","line":49,"function":"execute","class":"OCP\\AppFramework\\Db\\Mapper","type":"-\u003E","args":["INSERT INTO `*PREFIX*deck_assigned_users`(`card_id`,`participant`,`type`) VALUES(?,?,?)",[271,"********",0],null,null]},{"file":"\/var\/www\/nextcloud\/lib\/public\/AppFramework\/Db\/Mapper.php","line":129,"function":"execute","class":"OCA\\Deck\\Db\\DeckMapper","type":"-\u003E","args":["INSERT INTO `*PREFIX*deck_assigned_users`(`card_id`,`participant`,`type`) VALUES(?,?,?)",[271,"********",0]]},{"file":"\/var\/www\/nextcloud\/apps\/deck\/lib\/Db\/AssignedUsersMapper.php","line":88,"function":"insert","class":"OCP\\AppFramework\\Db\\Mapper","type":"-\u003E","args":[{"id":null,"participant":"********","cardId":271,"type":0}]},{"file":"\/var\/www\/nextcloud\/apps\/deck\/lib\/Service\/AssignmentService.php","line":150,"function":"insert","class":"OCA\\Deck\\Db\\AssignedUsersMapper","type":"-\u003E","args":[{"id":null,"participant":"********","cardId":271,"type":0}]},{"file":"\/var\/www\/nextcloud\/apps\/deck\/lib\/Controller\/CardController.php","line":159,"function":"assignUser","class":"OCA\\Deck\\Service\\AssignmentService","type":"-\u003E","args":["271","********",0]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":170,"function":"assignUser","class":"OCA\\Deck\\Controller\\CardController","type":"-\u003E","args":["271","********",0]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"-\u003E","args":[{},"assignUser"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"-\u003E","args":[{},"assignUser"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Deck\\Controller\\CardController","assignUser",{},{"cardId":"271","_route":"deck.card.assignUser"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"-\u003E","args":[{"cardId":"271","_route":"deck.card.assignUser"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":299,"function":"call_user_func","args":[{},{"cardId":"271","_route":"deck.card.assignUser"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"-\u003E","args":["\/apps\/deck\/cards\/271\/assign"]},{"file":"\/var\/www\/nextcloud\/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"\u0000Exception\u0000previous":{"errorInfo":["42S22",1054,"Unknown column 'type' in 'field list'"]}}}
```

</details>

**Comment by treuss** [comment] 2020-06-29 15:09
Solved it myself:

```
ALTER TABLE oc_deck_assigned_users ADD COLUMN type INT;
```

**Comment by juliushaertl** [comment] 2020-07-09 19:04
Duplicate of #2040

**Closed by juliushaertl** 2020-07-09 19:04 UTC
