### ISSUE TITLE
Mark cards as done without archiving them

### ISSUE THREAD

**Issue by jurgenhaas** [nextcloud/deck#3490] opened 2021-12-17 16:37 UTC
When using a board just like the deck app shows on the project page with the last list labelled as "Done", we move completed cards into that column, and they should be treated as done then. In particular, that means:

- do not show the due date as being overdue any more
- do not send reminders about the card being overdue
- do not show the task in the task app any more

I know, the same result can be achieved by archiving the card. But that is different from what the board shows with the "Done" column and it comes with the downside, that we can't have an overview with open and done cards at once.

**Comment by stefan-niedermann** [comment] 2021-12-17 19:22
Duplicate of https://github.com/nextcloud/deck/issues/534

**Closed by stefan-niedermann** 2021-12-17 19:22 UTC
