### ISSUE TITLE
Due Date cannot be set for future month

### ISSUE THREAD

**Issue by JoergPalmer** [nextcloud/deck#1968] opened 2020-05-30 21:05 UTC
**Describe the bug**
When the date/time picker dialog is opened, the right part of the screen is missing. The current date/time is shown, but cut at the "minutes" part. The single and double arrow forward does not show because the dialog is too small

**To Reproduce**
1. Go to card details
2. Click on date picker for due date
3. Single and Double Arrow to forward to future date is missing

**Expected behavior**
The right arrows (single and double) should show, just as the ones on the left hand side.

**Screenshots**
![Screenshot-20200530225413-377x367](https://user-images.githubusercontent.com/24966707/83338859-8d89d200-a2c8-11ea-8802-6f942d33486e.png)

**Client details:**
 - OS: Linux openSUSE Tumbleweed
 - Browser Firefox 76.0.1 (64-Bit)

**Operating system**:
Debian GNU/Linux 10 (buster)

**Web server:**
Apache/2.4.38 (Debian)

**Database:**
mysqld 10.3.22-MariaDB-0+deb10u1

**PHP version:**
PHP 7.4.6

**Nextcloud version:** (see Nextcloud admin page)
18.0.4

**Comment by juliushaertl** [comment] 2020-06-03 10:30
Duplicate of https://github.com/nextcloud/deck/issues/1826

Should be fixed with the just released 1.0.2

**Closed by juliushaertl** 2020-06-03 10:30 UTC
