### ISSUE TITLE
Long card description --> Indexing fails

### ISSUE THREAD

**Issue by besca-red** [nextcloud/deck#5323] opened 2023-11-24 01:55 UTC
**Describe the bug**
After creating a card with a long description an error occurs in the log. After creating this card, no changes (title, description) to this card can be made. Every change attempt fails and produces an error in the log.

**To Reproduce**
1. Go to Deck
2. Create a card
3. Write a long description (in my case: ~3.900 letters)

**Expected behavior**
Should work.

<details>
<summary>Server details</summary>

**Database:**
PostgreSQL 14.10

**PHP version:**
8.1.25

**Nextcloud version:**
26.0.8 / 26.0.9

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
[deck] Error: OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[54000]: Program limit exceeded: 7 ERROR:  index row size 2800 exceeds btree version 4 maximum 2704 for index "idx_last_editor"
DETAIL:  Index row references tuple (16,58) in relation "oc_deck_cards".
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.

```
</details>

**Comment by joshtrichards** [comment] 2024-10-02 15:23
Duplicate of #4015
Fixed in #5260

**Closed by joshtrichards** 2024-10-02 15:23 UTC
Labels: bug
