### ISSUE TITLE
default board setting 

### ISSUE THREAD

**Issue by CaptainPackers** [nextcloud/deck#3640] opened 2022-03-14 06:43 UTC
I would like to set the default board to something other than "Upcoming cards" when I open the Deck app on NextCloud. Is it possible to do that now or is that an enhancement you would need to add. Right now I don't see a lot of configuration options in the app.

Thanks

**Comment by magikmw** [comment] 2022-03-14 10:03
This is a duplicate of https://github.com/nextcloud/deck/issues/2840  
There is a workaround inside though.

**Closed** 2022-03-14 11:14 UTC
