### ISSUE TITLE
Setting a card as "Finished" should automatically handle any due date, somehow.

### ISSUE THREAD

**Issue by dmbreakey** [nextcloud/deck#2446] opened 2020-10-14 15:03 UTC
There should probably be an explicit "Completed" or "Finished" button, rather than relying on recognizing a specific tag.

I think the **best** option would be if there's an explicit "Finished" date as well; any card where a Finished date is present, the "Due date" is ignored. It should be possible to edit the "Finished" date as well, but perhaps only for the board owner.

A simpler option would be to just clear the Due date, instead, but then it's harder to track if a task was completed on schedule or not.

**Comment by juliushaertl** [comment] 2020-10-15 11:59
Closing as a duplicate of https://github.com/nextcloud/deck/issues/534

**Closed by juliushaertl** 2020-10-15 11:59 UTC
