### ISSUE TITLE
Allow attachment of files from Files App to card

### ISSUE THREAD

**Issue by beccon4** [nextcloud/deck#1060] opened 2019-05-22 10:23 UTC
For the time being we can attach files to a card by uploading them from the client's file system.

It would be really nice to be able to attach them from NC's File Application too i.e. attach files already on the cloud.

A current workaround is to share them via link and put it in the  description - but for  that we have to share the file first which is not always appropriate. 

Downloading the file and attach then is problematic as it a) leaves traces on the client side b) is redundant. Linking would allow us to use e.g. Libre Office Online files directly.

**Comment by Aquariu** [comment] 2019-05-22 13:45
Dear all, I have created the corresponding Issue on [the very aplha Deck Android app](https://github.com/stefan-niedermann/nextcloud-deck/issues/83). The level of integration we could get by having this looks fantastic!

**Comment by juliushaertl** [comment] 2019-07-01 09:56
Duplicate of https://github.com/nextcloud/deck/issues/564

**Closed by juliushaertl** 2019-07-01 09:56 UTC
Labels: enhancement
