### ISSUE TITLE
Screen too wide for widdescreen

### ISSUE THREAD

**Issue by stone212** [nextcloud/deck#850] opened 2019-01-17 12:51 UTC
**Describe the bug**
Even on a wide monitor (1200x900) the kanban board makes me scroll left and right.  

**To Reproduce**
1. Go to Deck
2. Click on a board
3. See that you have to scroll left and right

**Expected behavior**
A user should never have to scroll left and right is the usual UI rule.  In Deck it isn't necessary. If you click "settings" it all fits back very nicely.

**Screenshots**
Attached

**Client details:**
1200x900
![toowideforwidescreen](https://user-images.githubusercontent.com/26020999/51316676-45f50400-1a4d-11e9-91c7-9c53e87dc9e1.png)

**Comment by juliushaertl** [comment] 2019-01-18 15:17
Closing as a duplicate of #434. See my answer from there:

> We experimented with a dynamic stack width in the past but didn't came to a satisfying solution, that allowed to keep all information rendered on the cards. See #82 for reference. To get an overview of all cards you might use the browser zoom functionality, but I see no reasonable solution to show all stacks by default, as there could be an infinite number of those.

**Closed by juliushaertl** 2019-01-18 15:17 UTC
