### ISSUE TITLE
Error when getting shares in background job

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/deck#3002] opened 2021-04-19 06:02 UTC
```
{"reqId":"MZIYcJgnbNGth5cOsMIv","level":3,"time":"2021-04-19T06:00:02+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Group\\Manager::getUserIdGroupIds() must be of the type string, null given, called in /var/www/html/lib/private/Group/Manager.php on line 317","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Group/Manager.php","line":317,"function":"getUserIdGroupIds","class":"OC\\Group\\Manager","type":"->","args":[null]},{"file":"/var/www/html/apps-extra/deck/lib/Service/PermissionService.php","line":207,"function":"isInGroup","class":"OC\\Group\\Manager","type":"->","args":[null,"group1"]},{"file":"/var/www/html/apps-extra/deck/lib/Service/PermissionService.php","line":153,"function":"userCan","class":"OCA\\Deck\\Service\\PermissionService","type":"->","args":[[{"id":3,"__class__":"OCA\\Deck\\Db\\Acl"}],1,null]},{"file":"/var/www/html/apps-extra/deck/lib/Sharing/DeckShareProvider.php","line":276,"function":"checkPermission","class":"OCA\\Deck\\Service\\PermissionService","type":"->","args":[{"__class__":"OCA\\Deck\\Db\\CardMapper"},"1",1]},{"file":"/var/www/html/apps-extra/deck/lib/Sharing/DeckShareProvider.php","line":649,"function":"applyBoardPermission","class":"OCA\\Deck\\Sharing\\DeckShareProvider","type":"->","args":[{"__class__":"OC\\Share20\\Share"},1]},{"file":"/var/www/html/apps-extra/deck/lib/Sharing/DeckShareProvider.php","line":765,"function":"resolveSharesForRecipient","class":"OCA\\Deck\\Sharing\\DeckShareProvider","type":"->","args":[[{"__class__":"OC\\Share20\\Share"}],"user1"]},{"file":"/var/www/html/lib/private/Share20/Manager.php","line":1350,"function":"getSharedWith","class":"OCA\\Deck\\Sharing\\DeckShareProvider","type":"->","args":["user1",12,null,-1,0]},{"file":"/var/www/html/apps/files_sharing/lib/MountProvider.php","line":82,"function":"getSharedWith","class":"OC\\Share20\\Manager","type":"->","args":["user1",12,null,-1]},{"file":"/var/www/html/lib/private/Files/Config/MountProviderCollection.php","line":119,"function":"getMountsForUser","class":"OCA\\Files_Sharing\\MountProvider","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Storage\\StorageFactory"}]},{"file":"/var/www/html/lib/private/Files/Filesystem.php","line":452,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Mount\\Manager"}]},{"file":"/var/www/html/lib/private/Files/Filesystem.php","line":377,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::","args":["user1"]},{"file":"/var/www/html/lib/private/legacy/OC_Util.php","line":324,"function":"init","class":"OC\\Files\\Filesystem","type":"::","args":["user1","/user1/files"]},{"file":"/var/www/html/lib/private/Files/Utils/Scanner.php","line":116,"function":"setupFS","class":"OC_Util","type":"::","args":["user1"]},{"file":"/var/www/html/lib/private/Files/Utils/Scanner.php","line":155,"function":"getMounts","class":"OC\\Files\\Utils\\Scanner","type":"->","args":[""]},{"file":"/var/www/html/apps/files/lib/BackgroundJob/ScanFiles.php","line":90,"function":"backgroundScan","class":"OC\\Files\\Utils\\Scanner","type":"->","args":[""]},{"file":"/var/www/html/apps/files/lib/BackgroundJob/ScanFiles.php","line":126,"function":"runScanner","class":"OCA\\Files\\BackgroundJob\\ScanFiles","type":"->","args":["user1"]},{"file":"/var/www/html/lib/private/BackgroundJob/Job.php","line":52,"function":"run","class":"OCA\\Files\\BackgroundJob\\ScanFiles","type":"->","args":[null]},{"file":"/var/www/html/lib/private/BackgroundJob/TimedJob.php","line":59,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/html/cron.php","line":128,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/html/lib/private/Group/Manager.php","Line":334,"CustomMessage":"Error while running background job (class: OCA\\Files\\BackgroundJob\\ScanFiles, arguments: )"},"userAgent":"--","version":"22.0.0.2"}
```

**Comment by joshtrichards** [comment] 2024-10-01 18:47
Duplicate of #3140

**Closed by joshtrichards** 2024-10-01 18:47 UTC
Labels: bug, 1. to develop
