### ISSUE TITLE
PUBLIC SHARE

### ISSUE THREAD

**Issue by punkyard** [nextcloud/deck#4942] opened 2023-07-18 09:43 UTC
A public view of a deck could be very useful to us.
We are non-profit and work with volunteers that won't create an account on NC.
But it would be very handy if could share a public view of a deck with them of the status of our projects.

Thanks ✌️

**Comment by juliushaertl** [comment] 2023-07-18 09:44
Duplicate of #14 

Please use the search before opening new issues to see if there are already existing ones.

**Closed by juliushaertl** 2023-07-18 09:44 UTC

**Comment by punkyard** [comment] 2023-07-18 12:54
ok @juliushaertl 
sorry then
As it's a 2017 thread, I thought I'd update the subject
Thanks for your response!

**Comment by cyberstrawberry101** [comment] 2023-07-18 16:21
I also would like to see this functionality if anyone else is to task to get it implemented.  Last I recall, there were underlying structural reasons in the sharing system that made sharing decks publicly difficult to implement.
