### ISSUE TITLE
Please help - Add A project/board/card button - missing

### ISSUE THREAD

**Issue by digitalteamgkdi** [nextcloud/deck#4374] opened 2023-01-10 04:01 UTC
![missing add](https://user-images.githubusercontent.com/122334644/211458788-abe54ce8-6b9e-4f0a-90b6-88201eacbdc6.png)

Hello I just update Nextcloud to 23.0.5. but for my deck apps, it missing the "add to a project" menu ini sidebar view details.

Can anyone help me how to find the menu. thanks.

**Comment by stefan-niedermann** [comment] 2023-01-10 07:36
Please use the 🔍 search function before opening new issues.

Closing as duplicate of https://github.com/nextcloud/deck/issues/4213

**Closed by stefan-niedermann** 2023-01-10 07:36 UTC
